### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1]
Add a good Contact Page.

**Comment by vishal0316** [comment]
assign me

**Comment by prem-prasad1710** [comment]
Hi @Rakesh9100 @vishal0316 ! I'm interested in fixing this issue.
Please assign this issue to me.

**Comment by sidhigrover** [comment]
"Embarking on the Contact Page enhancement journey:

Crafting a clean and user-friendly layout for seamless communication.
Implementing clear calls-to-action to guide visitors effectively.
Ensuring responsiveness for accessibility on all devices. Ready to revamp the Contact Page for an improved user experience!"

Please assign me this issue to me

**Comment by pankhuri92** [comment]
Hi @Rakesh9100 I would like to add a responsive and friendly contact page to it. Kindly assign me the issue.

**Comment by Shivangi015** [comment]
Hey @Rakesh9100 , I am good with page making task and i can make an attractive contact page for this site. Please assign this task to me.

**Comment by Yatin12527** [comment]
I'd love to update the contact section.

**Comment by rishicds** [comment]
Hi @Rakesh9100 , I believe I can work on this task so if you'd like it please assign the task to me

**Comment by yaten2302** [comment]
Hi @Rakesh9100, could you please assign this issue to me under SWOC24.

**Comment by Rakesh9100** [comment]
@vishal0316 Assigned, Proceed!!

**Comment by vishal0316** [comment]
> @vishal0316 Assigned, Proceed!!

done and i created PR
