### ISSUE TITLE
[Feature]: Suitable background color needs to be added on each card

### ISSUE THREAD

**Issue by Yatin12527** [Rakesh9100/Beautiify#10]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As we scroll down to components and open each component we get plain white background which obviously can be changed with more suitable background color.

**Feature requested**

Background would look much better with different background color

**screenrecording**

https://github.com/Rakesh9100/Beautiify/assets/134225415/e0d654e0-f4c8-4d03-8fe5-59d26e3a22a1

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by vishal0316** [comment]
Hey please assign me I can do this

**Comment by Rakesh9100** [comment]
@Yatin12527 Pls work on the previously assigned issue first

**Comment by sanketshinde3001** [comment]
@Rakesh9100  Can u assign me this task .

**Comment by Aryankarma** [comment]
Hey @Rakesh9100  can i work on this issue?

**Comment by Yatin12527** [comment]
> @Yatin12527 Pls work on the previously assigned issue first

Hey, wanted to let you know i created the PR for previous issue and its completed.

**Comment by KanwalpreetSingh1823** [comment]
Hii @Rakesh9100  I'm Interested in fixing this issue. I have added some CSS on the Cards. I have attached the screenshot of the work below. Please check it. I will also add more CSS for this.
Please assign this issue to me.

![beautiify](https://github.com/Rakesh9100/Beautiify/assets/147548295/a2e5ac51-6f35-4cfd-97b4-d4f36109fcc5)

**Comment by Rakesh9100** [comment]
@Yatin12527 Go ahead
