### ISSUE TITLE
Adding a Preloader to the main website

### ISSUE THREAD

**Issue by Vikranthraosb** [Rakesh9100/Beautiify#100]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Using a loading animation can make the website look nicer and improve how people enjoy using it.

Can do it using simple javascript and GASP 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Are you talking about adding any coponent or implement Preloader in the main website? @Vikranthraosb

**Comment by Vikranthraosb** [comment]
> Are you talking about adding any coponent or implement Preloader in the main website? @Vikranthraosb

Adding a Preloader in the website.

**Comment by Rakesh9100** [comment]
Okay go ahead and implement the eye catching preloader @Vikranthraosb

**Comment by Vikranthraosb** [comment]
Thanx bro

**Comment by Vedika-Agrawal** [comment]
Hey, I also want to contribute to this issue using GSAP under JWOC.

**Comment by Paarisha1** [comment]
can i contribute in this

**Comment by Rakesh9100** [comment]
@Paarisha1 Share your ideas with proper screenshots on the working of this issue

**Comment by Paarisha1** [comment]
![IMG_20240114_163540.jpg](https://github.com/Rakesh9100/Beautiify/assets/147527266/b1d45df5-c808-4217-abf3-896c8e73eed1)

Sir I have already added this preloader to website

**Comment by Rakesh9100** [comment]
Okay go ahead @Paarisha1

**Comment by Rakesh9100** [comment]
Are you working under SWOC @Paarisha1

**Comment by Paarisha1** [comment]
Yes sir
