### ISSUE TITLE
[Feature] Add Draggable Card

### ISSUE THREAD

**Issue by MadhurimaNayak** [Rakesh9100/Beautiify#1003]
### Description

This card can be dragged and placed anywhere on the screen based on user preference.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New card addition

**Comment by Rakesh9100** [comment]
Go ahead @MadhurimaNayak

**Comment by MadhurimaNayak** [comment]
okayy will you add the label after a open a pull request?

**Comment by Rakesh9100** [comment]
Yes @MadhurimaNayak

**Comment by Anupama-du** [comment]
Hi, I would like to solve this issue, please assign me
