### ISSUE TITLE
[Feature] Add Product Details Card

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1007]
### Description

The product card features a sleek, minimalistic design, showcasing a product image with a smooth hover animation that enlarges the image slightly. A "Shop" button also has a hover effect, changing color to draw attention. The design emphasizes simplicity and elegance, enhancing user interaction and visual appeal.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/a0faa106-f2df-4957-86ee-307d2a27da2c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new card addition

**Comment by Praneeth-2602** [comment]
@Rakesh9100 please assign me this issue
