### ISSUE TITLE
[Feature] Add Sliding Sticky Notes Card

### ISSUE THREAD

**Issue by Anshika-17** [Rakesh9100/Beautiify#1010]
### Description

###Implement Sliding Sticky Notes Design Card
##Description
- As a user, I want to have a visually appealing and efficient way to manage my notes and tasks within the application. I would like to see a sliding sticky notes design card that allows me to quickly access and organize my information.

#User Stories
- As a user, I want to be able to create, edit, and delete sticky notes within the card.
- As a user, I want to be able to add tags to my sticky notes to categorize them.
- As a user, I want the sticky notes card to have a clean and modern design that aligns with the application's branding.
- As a user, I want to be able to smoothly slide through multiple sticky notes within the card.
- As a user, I want the layout of the sticky notes card to be responsive and adapt to different screen sizes.
- As a user, I want the sticky notes feature to be well-integrated with the application's existing note-taking and task management functionalities.
- As a user with disabilities, I want the sticky notes feature to be accessible and usable by users with various abilities, including those using assistive technologies.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/144370954/dfaaa30d-9619-42fa-9199-f7dcaaeae867)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new card addition

**Comment by Rakesh9100** [comment]
Go ahead @Anshika-17
