### ISSUE TITLE
[Feature] Add Bubbles Text Animation

### ISSUE THREAD

**Issue by Skb08** [Rakesh9100/Beautiify#1011]
### Description

We aim to enhance the user interface by adding text that is composed of particles. When a user hovers over this text, the particles should scatter, creating a visually engaging effect. This feature will add an interactive and dynamic element to our page.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/113046759/4de6f156-f63d-4b57-8f16-921289c366aa

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new text animation addition

**Comment by Rakesh9100** [comment]
Do you want to add this as a component in Text Animations category @Skb08

**Comment by Skb08** [comment]
@Rakesh9100 yes

**Comment by Skb08** [comment]
@Rakesh9100 can you assign this to me?

**Comment by Rakesh9100** [comment]
What would be the name of your component @Skb08

**Comment by Skb08** [comment]
Bubble Animation Text

**Comment by Rakesh9100** [comment]
Go ahead, you can name it `Bubbles-Text-Animation`
