### ISSUE TITLE
[Feature] Add Theme Toggle Dropdown

### ISSUE THREAD

**Issue by hars-21** [Rakesh9100/Beautiify#1014]
### Description

I want to add a new dropdown component for theme selection. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hars-21** [comment]
@Rakesh9100 Please assign me

**Comment by laxmi09-walker** [comment]
please assigned me this issue.

**Comment by Rakesh9100** [comment]
What will be the name of your component @hars-21

**Comment by Rakesh9100** [comment]
Proceed @hars-21
