### ISSUE TITLE
[Feature] Add 3D Animated Breadcrumb

### ISSUE THREAD

**Issue by hars-21** [Rakesh9100/Beautiify#1015]
### Description

Adding a new breadcrumb component that is 3D and bends to the mouse pointer on hover.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hars-21** [comment]
@Rakesh9100 Please assign me

**Comment by saurabhsingh720** [comment]
@hars-21 
Can u give the overview?

**Comment by hars-21** [comment]
![Screen Shot 2024-06-19 at 10 39 47 PM](https://github.com/Rakesh9100/Beautiify/assets/144909381/e669fe02-368f-4e8d-ac70-c74a5cb4722f)
![Screen Shot 2024-06-19 at 10 39 55 PM](https://github.com/Rakesh9100/Beautiify/assets/144909381/0a7a8cae-3618-464f-a023-c93ac51b4a97)
Somewhat like this. I will add this component.

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new addition

**Comment by Rakesh9100** [comment]
What will be the name of your component @hars-21

**Comment by hars-21** [comment]
3D-animated breadcrumb @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @hars-21
