### ISSUE TITLE
[Feature] Add Tooltips Category and several Components

### ISSUE THREAD

**Issue by hars-21** [Rakesh9100/Beautiify#1016]
### Description

Adding a new section under components for adding tooltips this will increase number of UI elements and also help users to get ui elements for tooltips. Also, along with new section, I'll be adding 3-4 tooltip components to get started.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by laxmi09-walker** [comment]
please assigned me this issue.
Thanks.

**Comment by Rakesh9100** [comment]
What all tooltips components will you add, provide me the name and some supporting screenshots @hars-21

**Comment by hars-21** [comment]
I'll be adding 4 tooltip components: Shopping cart tooltip, linked apps tooltip, animated tooltip and count tooltip.


![Screen Shot 2024-07-08 at 12 01 23 PM](https://github.com/Rakesh9100/Beautiify/assets/144909381/57f8b2ce-7720-412e-b308-842630082856)


![Screen Shot 2024-07-08 at 11 53 13 AM](https://github.com/Rakesh9100/Beautiify/assets/144909381/0f72d20a-0d94-4471-b843-be31fd7f5c26)

![Screen Shot 2024-07-08 at 11 53 35 AM](https://github.com/Rakesh9100/Beautiify/assets/144909381/82a718e9-ba0d-46ee-8212-6582374af70f)

![Screen Shot 2024-07-08 at 11 51 00 AM](https://github.com/Rakesh9100/Beautiify/assets/144909381/fb652965-ce8f-4945-887f-a42c409181d5)

**Comment by Rakesh9100** [comment]
Okay, go ahead @hars-21
