### ISSUE TITLE
[Feature] Add Ghost Text Animation 

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/Beautiify#1019]
### Description

Want to add the  new ghost text animation as it look so crazy and awesome 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/70de1094-0169-4f73-a7b8-107a3e40aa1d)
![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/351eeada-b9c5-491a-8a70-bbc655b52b2b)
![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/aab51e65-17d7-4e4e-95e2-1dbc91b46f95)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new text animation addition

**Comment by Rakesh9100** [comment]
Pls work on your assigned issue first and don't open too many issues at once @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
okk i am working on it and submitting the PR today

**Comment by Rakesh9100** [comment]
Go ahead @SaiyamTuteja
