### ISSUE TITLE
[Feature] Add Swipe Right Button-2

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/Beautiify#1020]
### Description

I want to add the new Beautiify  button in the button section which looks so awesome  and attractive with neon color 

Assign me this issue under **GSSOC24**

### Screenshots

**Before Hover** 
![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/47ee0b96-49e7-4c65-81d4-bdff4fe02947)
**After Hover** 
![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/5d4e81c7-84fd-4113-8a0f-6a392a1b5791)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@SaiyamTuteja 
What is the name of the button that u want to add?

**Comment by SaiyamTuteja** [comment]
Beautiify

**Comment by saurabhsingh720** [comment]
@SaiyamTuteja 
I am asking what type of button u want to add?
Yyour button have some specific name.

**Comment by SaiyamTuteja** [comment]
button name is **beautiify** we can also change the name of the button

**Comment by Rakesh9100** [comment]
Beautiify is the name of the project, provide the proper name for the button based on what effect that button has @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
SWIPE Button When we click on it then it will move towards the right and click to swipe to right

**Comment by Rakesh9100** [comment]
Go ahead, keep the name as `Swipe-Right-Button-2` @SaiyamTuteja
