### ISSUE TITLE
[Feature] Add Teddy Button

### ISSUE THREAD

**Issue by Archiesachin** [Rakesh9100/Beautiify#1024]
### Description

When clicked on the button a teddy bear with parachute will be ejected, notifying the work done.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/103347688/898d9e8c-cfd6-44e3-b421-853dae4c3281

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Archiesachin
