### ISSUE TITLE
[Feature] Add Floating Action Button (FAB) Navigation Bar

### ISSUE THREAD

**Issue by sanayamahajan-23** [Rakesh9100/Beautiify#1029]
### Description

A navigation bar inspired by mobile design, featuring a floating action button that expands into a radial menu when clicked. This is particularly useful for mobile-first designs.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@sanayamahajan-23 
Can u give a preview of it?

**Comment by sanayamahajan-23** [comment]
Really sorry but I need to create a code for it

**Comment by sanayamahajan-23** [comment]
Can you give me some time forit

**Comment by sanayamahajan-23** [comment]
![image](https://github.com/Rakesh9100/Beautiify/assets/112759683/18a19689-6567-40dd-a5be-08052065e422)


here is its preview i took the image from internet but it would be something like that

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new addition

**Comment by Rakesh9100** [comment]
Go ahead @sanayamahajan-23

**Comment by sanayamahajan-23** [comment]
sir also add level whether 1,2,or 3
