### ISSUE TITLE
[Feature] Implement Dark Theme for the website

### ISSUE THREAD

**Issue by PARKER-X** [Rakesh9100/Beautiify#103]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Enhancement of Homepage of beautiify  by creating Toggle for dark and light mode #Intermediate/Beginner Issue
Any swoc contributor can work!

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by IamSudhir-Kumar** [comment]
Hey @Rakesh9100 I am a contributor in SWOC . I can work on this issue!!!! 
*In the dark mode the Website can be look like this* 
![Screenshot 2024-01-08 161608](https://github.com/Rakesh9100/Beautiify/assets/112376748/b12d59a7-eb30-4aa9-9d0b-aa26b7e5d6d1)
![Screenshot 2024-01-08 161543](https://github.com/Rakesh9100/Beautiify/assets/112376748/26db167b-9598-44f0-bf68-1115242d9ebd)

**Comment by Rakesh9100** [comment]
This is the project `Beautiify` not `CalcDiverse`. Pls work accordingly if you want to @IamSudhir-Kumar

**Comment by IamSudhir-Kumar** [comment]
Sorry for that mistake please assign this issue to me !!! I want to work on this @Rakesh9100

**Comment by IamSudhir-Kumar** [comment]
It can be look like these But I can make more changes on navbar section
![Uploading Screenshot 2024-01-08 172030.png…]()

**Comment by Rakesh9100** [comment]
Okay, start working!! Give your best, will see how it goes @IamSudhir-Kumar

**Comment by IamSudhir-Kumar** [comment]
Is it okay? Or should I make some changes 
![Beautiify-GoogleChrome2024-01-0821-25-12-ezgif com-video-to-gif-converter](https://github.com/Rakesh9100/Beautiify/assets/112376748/5886b60f-c6b8-4095-84cb-08844fd2626c)

**Comment by thatguywhocode** [comment]
hello @Rakesh9100 , I would like to work on this issue under JWOC.

**Comment by Rakesh9100** [comment]
Go ahead @thatguywhocode

**Comment by thatguywhocode** [comment]
Hey @Rakesh9100 , I have solved issue and created pr under JWOC.

**Comment by Parth4git** [comment]
I wanted to work on this issue .Pls assign this issue to me . @Rakesh9100

**Comment by branihat** [comment]
hello @Rakesh9100  , I would like to work on this issue

**Comment by Rakesh9100** [comment]
Go ahead @Parth4git

**Comment by Rakesh9100** [comment]
You want to work for which open source program @Parth4git

**Comment by thatguywhocode** [comment]
Hey @Rakesh9100 , i'll look for the errors and solve it under JWOC.

**Comment by Rakesh9100** [comment]
@Parth4git Do you want to work

**Comment by branihat** [comment]
I wanted to work on this issue .Pls assign this issue to me . @Rakesh9100

**Comment by Parth4git** [comment]
> @Parth4git Do you want to work

yes I want to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
Proceed @Parth4git

**Comment by vishapraj** [comment]
Pls assign me this issue @Rakesh9100 under 'JWOC'

**Comment by Parth4git** [comment]
@Rakesh9100 do you want dark mode toggle button only on home page or at every pages .
Update of work -- All the work is almost done

**Comment by Rakesh9100** [comment]
Each and every page @Parth4git 

Can you show the screenshot at which place are you placing the button?

**Comment by Parth4git** [comment]
![Screenshot 2024-01-26 162602](https://github.com/Rakesh9100/Beautiify/assets/99666524/51b7949b-e064-42e9-b74d-a39d0f8a28cf)

**Comment by Parth4git** [comment]
@Rakesh9100 does it look all right

**Comment by Rakesh9100** [comment]
Make sure to update your forked repo locally and then make your changes and open PR @Parth4git 

Place it down the navbar!!

**Comment by Parth4git** [comment]
where I did not understand . please mark the point @Rakesh9100

**Comment by Rakesh9100** [comment]
![image](https://github.com/Rakesh9100/Beautiify/assets/73993775/672196d6-1134-4296-8988-2db0778442b9)

@Parth4git

**Comment by Rakesh9100** [comment]
PR update @Parth4git

**Comment by Parth4git** [comment]
I am working on things you mention yesterday .updating location of button on every page and updated css accordingly @Rakesh9100

**Comment by Parth4git** [comment]
@Rakesh9100 kindly look through it and tell anything required or not 

https://github.com/Rakesh9100/Beautiify/assets/99666524/2953dbe1-4fc3-4279-a373-a0fb34214ce0
