### ISSUE TITLE
[Feature] Add Pan Flip Loader

### ISSUE THREAD

**Issue by samarsajad** [Rakesh9100/Beautiify#1030]
### Description

A cooking pan preloader that flips a pan cake for the food websites

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by samarsajad** [comment]
Please assign me this issue @Rakesh9100

**Comment by saurabhsingh720** [comment]
@samarsajad 
Attach a clip of it?

**Comment by Rakesh9100** [comment]
Do you have any supporting screenshot @samarsajad

**Comment by samarsajad** [comment]
> Do you have any supporting screenshot @samarsajad
Something like this


https://github.com/Rakesh9100/Beautiify/assets/142666229/5648422b-41e0-4067-85b8-a764a0760402

**Comment by samarsajad** [comment]
Please assign this issue to me @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @samarsajad
