### ISSUE TITLE
[Feature] Add Touch Slider Carousel

### ISSUE THREAD

**Issue by komal-agarwal5** [Rakesh9100/Beautiify#1032]
### Description

I wish to add a touch slider carousal component for card.
It looks good for portfolio websites or showcase websites.

### Screenshots

![IMG_20240615_114451](https://github.com/Rakesh9100/Beautiify/assets/122633300/21531c66-7de5-4579-920c-a8e505b86b1c)
P.s it's a dummy edited version

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @komal-agarwal5

**Comment by Rakesh9100** [comment]
Pls provide your PR @komal-agarwal5

**Comment by komal-agarwal5** [comment]
> Pls provide your PR @komal-agarwal5

Sorry for the delay due to semester exams,I shall complete it by today EOD
