### ISSUE TITLE
[Docs] Fix the typo

### ISSUE THREAD

**Issue by nainika0305** [Rakesh9100/Beautiify#1036]
### What would you like to share?

![image](https://github.com/Rakesh9100/Beautiify/assets/149311472/226bda91-d00f-4b84-8e1e-fdc7f6204447)
Beneath the heading 'Beautifiy' , a tagline reads, 'Every component, on the right place.' However, this phrase is grammatically incorrect and should be revised to 'Every component, in the right place!' or 'Every component in one place!' to better convey the intended meaning.

Please assign me this issue under gssoc  , and let me know which of the two taglines i suggested would be preferred. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 need to bhe change I think

**Comment by Rakesh9100** [comment]
Go ahead @nainika0305
