### ISSUE TITLE
[Feature] Add Gradient Border Button

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1037]
### Description

A button with a dynamic gradient border that changes colors continuously.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
Can u give overview of it?

**Comment by VaishnaviMankala19** [comment]
https://github.com/Rakesh9100/Beautiify/assets/131646799/e6143a63-d440-45c4-8213-4b5306f1b4ef

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new button addition

**Comment by Rakesh9100** [comment]
Go ahead @VaishnaviMankala19
