### ISSUE TITLE
[Feature] Add Pulsing Button

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1038]
### Description

A button that emits a pulsing glow effect, drawing attention to it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@VaishnaviMankala19 
Attach a video of it

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new button addition

**Comment by VaishnaviMankala19** [comment]
@Rakesh9100 can you assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @VaishnaviMankala19
