### ISSUE TITLE
[Feature] Add Color Cycle Text Animation

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1039]
### Description

Text that continuously cycles through different colors, creating a rainbow effect.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by VaishnaviMankala19** [comment]
https://github.com/Rakesh9100/Beautiify/assets/131646799/c84323ea-623a-4cc9-b135-581bed442071

**Comment by VaishnaviMankala19** [comment]
@Rakesh9100 can you assign me this issue

**Comment by Rakesh9100** [comment]
Proceed @VaishnaviMankala19
