### ISSUE TITLE
Redirect to Home Page

### ISSUE THREAD

**Issue by PARKER-X** [Rakesh9100/Beautiify#104]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

It's a good beginner issue.Redirect to home page currently no option available for redirection of home page

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/74282916/e825fda1-bd22-4574-920c-caf9715b788a)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Issue no. 9 already exist for this @PARKER-X
