### ISSUE TITLE
[Feature] Add Flower Effect Button

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Rakesh9100/Beautiify#1042]
### Description

Adding a button when hoverd have a flower effects

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100  please assign me the issue so that i can raise a pull request  and i have made code ready

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100  can you please assign me soon so that i can start working on it

**Comment by Rakesh9100** [comment]
Go ahead @Saipradyumnagoud

**Comment by malvika-sinha** [comment]
Kindly assign me this issue.
