### ISSUE TITLE
[Bug]  FOOTER section is not present in all components

### ISSUE THREAD

**Issue by Husan7** [Rakesh9100/Beautiify#1045]
### Description

Hi sir,
I want to work on this issue 
please assign me this issue

### Screenshots

![Screenshot 2024-06-18 121748](https://github.com/Rakesh9100/Beautiify/assets/162671639/a0173734-e812-47f7-9f7f-b7e30630cd33)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sarthaksharma39** [comment]
I would like to work on this issue. It would be great if you assign this to me.
Thank you
Your sincerely,
Sarthak Sharma

**Comment by laxmi09-walker** [comment]
please , assign me issue .
Thanks.

**Comment by Rakesh9100** [comment]
Issue 638 is already open for this, you can comment there if you want to work @Husan7
