### ISSUE TITLE
[Feature] Add FAQ page to the website

### ISSUE THREAD

**Issue by Husan7** [Rakesh9100/Beautiify#1046]
### Description

by adding this feature beautify looks attractive and user friendly
please assign me this issue i want to work on this issue 

### Screenshots

After

https://github.com/Rakesh9100/Beautiify/assets/162671639/c7e7afe8-7314-430f-9976-7ede13955bc1

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to be assigned @Husan7

**Comment by Husan7** [comment]
Yes @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @Husan7
