### ISSUE TITLE
[Bug] Fix reverse star selection and 0-star rating acceptance in Survey Form

### ISSUE THREAD

**Issue by NidhiTornekar** [Rakesh9100/Beautiify#1047]
### Description

In the components-> forms-> survey form, when user tries to submit (say) a 2-star rating, it is selecting 2 stars from right to left instead of left to right as shown.
![ss16](https://github.com/Rakesh9100/Beautiify/assets/121748841/c3720254-5e79-40fe-8ee3-297c5102dd2d)

Also, a zero star rating is being accepted, which should not be allowed as shown:
![ss15](https://github.com/Rakesh9100/Beautiify/assets/121748841/f71ded44-2b11-462f-9e4d-02c15e04a3fd)

I would like to correct this functionality , please assign me this issue under GSSOC 2024.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by NidhiTornekar** [comment]
@Rakesh9100 Please assign me this issue

**Comment by Rakesh9100** [comment]
Proceed @NidhiTornekar
