### ISSUE TITLE
[Feature] Add Bootstrap Carousel

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/Beautiify#1048]
### Description

Add bootstrap carousel with some background style.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/126322584/6f826792-2f26-4d0a-a978-8257949c64dd)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zalabhavy** [comment]
@Rakesh9100 Please assign me this task !

**Comment by Rakesh9100** [comment]
Proceed @zalabhavy
