### ISSUE TITLE
[Style] Enhance the Event Form UI

### ISSUE THREAD

**Issue by nidhipai78** [Rakesh9100/Beautiify#1049]
### What's the style idea?

We need to improve the font color for the text area,  since it looks very dull. The font color can be a little brighter.
![Screenshot_20240618_224110](https://github.com/Rakesh9100/Beautiify/assets/110184554/7d2c81ee-b4e6-48ec-a061-f62b92db30dd)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sarthaksharma39** [comment]
I would like to work on this issue. It would be great if you assign this to me.
Thank you
Your sincerely,
Sarthak Sharma

**Comment by laxmi09-walker** [comment]
Hi i  would like to work on this issue. I can implement it efficiently. Looking forward to contributing!
Thanks!

**Comment by Rakesh9100** [comment]
Go ahead @nidhipai78
