### ISSUE TITLE
[Docs] Fix the typo in Simple Footer

### ISSUE THREAD

**Issue by nidhipai78** [Rakesh9100/Beautiify#1052]
### Description

There is a typo in the simple footer. The alumni is spelled as "alumini" in the simple footer. I would like to correct this bug.

### Screenshots

<img width="941" alt="image" src="https://github.com/Rakesh9100/Beautiify/assets/110184554/13888abc-d8d6-4e84-be88-39a3a7c2cf01">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @nidhipai78
