### ISSUE TITLE
[Style] Remove unnecessary scrollbar in some components

### ISSUE THREAD

**Issue by SrinivasDevolper** [Rakesh9100/Beautiify#1053]
### Description

I find the unnecessary scrollbar in the project links and remove it

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

### Screenshots

Here are some examples of the actual behavior of the image

![beatiful image 3](https://github.com/Rakesh9100/Beautiify/assets/121508628/c3d2db4f-3d0f-4396-a936-25fdc9dea53c)

![beatiful image 2](https://github.com/Rakesh9100/Beautiify/assets/121508628/a5641e81-37dd-414a-8b65-d5974f45de47)

![beatiful image 1](https://github.com/Rakesh9100/Beautiify/assets/121508628/37a5908b-6f52-40eb-b3a9-0be16a78fb8f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SrinivasDevolper
