### ISSUE TITLE
[Feature] Add Social Hover Tone Button

### ISSUE THREAD

**Issue by ANKeshri** [Rakesh9100/Beautiify#1054]
### Description

in components / button i like to add a new type of button .

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/159682348/e79926ba-1cd8-436c-97e2-a95c1e9237dc

@Rakesh9100 please assign me this issue i want to add social icon button with hovering according to its colour in button section under components . 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the name of your button @ANKeshri

**Comment by ANKeshri** [comment]
> What will be the name of your button @ANKeshri

@Rakesh9100  ""Animated circular button""

**Comment by ANKeshri** [comment]
@Rakesh9100 sir please assign this issue to me i have rechecked that this type of button has not been added .

**Comment by ANKeshri** [comment]
> > What will be the name of your button @ANKeshri
> 
> @Rakesh9100 ""Social Hovertone button""

**Comment by ANKeshri** [comment]
@Rakesh9100 assign me this issue please

**Comment by Rakesh9100** [comment]
Go ahead @ANKeshri
