### ISSUE TITLE
[Feature] Add Download Button

### ISSUE THREAD

**Issue by tanyagupta01** [Rakesh9100/Beautiify#1061]
### Description

 A video of how the button would look like is provided below.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/156044894/7699a5d8-03d7-4b4f-ab63-f924cc86286a

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @tanyagupta01

**Comment by Rakesh9100** [comment]
Provide your PR @tanyagupta01

**Comment by biga-codes** [comment]
please assign me to this issue @Rakesh9100

**Comment by RedWing0021** [comment]
Please assign this to me!!
