### ISSUE TITLE
[Style] Make Feedback Form-2 responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/Beautiify#1063]
### Description

Feedback-Form-2 is not responsive

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124435030/126cee28-d832-4661-8dac-77646df6cc37)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @agastya3636

**Comment by Rakesh9100** [comment]
Provide your PR @agastya3636

**Comment by bharat-c27** [comment]
Hey @Rakesh9100 please assign the issue to me. I can work on it.

**Comment by crazyshrut** [comment]
hey @Rakesh9100 , I am a gssoc contributor
Can you please assign this to me?

**Comment by Rakesh9100** [comment]
Go ahead @bharat-c27

**Comment by SATAYM8540** [comment]
I would like to work on this project . please assign it to me.

**Comment by Rakesh9100** [comment]
Do you currently want to work on this @SATAYM8540

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 Can you kindly help me to locate this page directory on the repository. I could work on this if it's still left uncontributed.

**Comment by Rakesh9100** [comment]
@abhirajadhikary06 

[Repository path](https://github.com/Rakesh9100/Beautiify/tree/main/Components/Forms/Feedback-Form-2)

[Website preview](https://beautiify.netlify.app/components/forms/feedback-form-2/)

**Comment by Rakesh9100** [comment]
Are you contributing for KWOC program @SATAYM8540

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 I went through the Feedback-Form-2 and found out that the form is in working condition only the "Lorem Ipsum" text needs a change

**Comment by Rakesh9100** [comment]
Is it responsive for every screen? If yes, then make the CSS good and whatever responsiveness is required and create the PR to fix this issue @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 Sure will make a PR by tomorrow.
