### ISSUE TITLE
[Feature] Add Go Back Button

### ISSUE THREAD

**Issue by Mubashir2611** [Rakesh9100/Beautiify#1065]
### Description
**I want to add an animated GO BACK Button** 
**Assign me @Rakesh9100** 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/108177382/3bd6b7ed-7365-4bf5-8457-caac0700cb9f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Mubashir2611

**Comment by Rakesh9100** [comment]
Add your component part in `ssets/html_files/buttons.html` file by making the new commit in this same PR to display it on the website @Mubashir2611

**Comment by Rakesh9100** [comment]
Add your component part in `assets/html_files/buttons.html` file by making the new commit in this same PR to display it on the website @Mubashir2611
