### ISSUE TITLE
[Feature] Add Bat Button

### ISSUE THREAD

**Issue by AnshRehan04** [Rakesh9100/Beautiify#1068]
### Description

i want to add a  mesmerizing, bat-styled button that is sure to capture attention and spark intrigue.This button features a sleek and dynamic bat design, perfect for adding a touch of nocturnal elegance and gothic charm to a website.

Please Assign me with this issue
Screenshot is attached below.

![Screenshot 2024-06-20 193438](https://github.com/Rakesh9100/Beautiify/assets/118544177/5567b64c-00f1-4a5d-beb0-92b60b04d817)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AnshRehan04
