### ISSUE TITLE
[Feature] Add Registration Form

### ISSUE THREAD

**Issue by DiwareNamrata23** [Rakesh9100/Beautiify#1076]
### Description

The registration form contains details about the user . It will be developed using html css from scratch.

### Screenshots

<img width="564" alt="Screenshot 2024-06-21 at 11 58 33 AM" src="https://github.com/Rakesh9100/Beautiify/assets/142529986/5b48a4c8-c8e8-4228-9770-610b8a079549">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by malvika-sinha** [comment]
I want to fix this issue. Kindly assign me

**Comment by Mayank-Nema** [comment]
Hi, I'm Mayank Nema a GSSoC '24 participant. I’m interested in contributing to this project. Kindly assign me . I'm eager to start and contribute to the team. Thanks!

**Comment by Rakesh9100** [comment]
Go ahead @DiwareNamrata23

**Comment by Rakesh9100** [comment]
Provide your PR @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
Yes will provide today itself
