### ISSUE TITLE
[Feature] Add Frozen Text Animation

### ISSUE THREAD

**Issue by Dsmita03** [Rakesh9100/Beautiify#1083]
### Description

I want to add a new component under Text animations.

### Screenshots

<img width="784" alt="Screenshot 2024-06-21 at 8 27 19 PM" src="https://github.com/Rakesh9100/Beautiify/assets/123728188/47e05fc0-f9b0-42f0-99ea-f0c93f7f38a2">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Dsmita03
