### ISSUE TITLE
[Feature] Add Scrollbars Category and a Component

### ISSUE THREAD

**Issue by ananya-dhiman** [Rakesh9100/Beautiify#1089]
### Description

Adding a section for different types of scrolls and adding atleast two samples for the same 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/145692647/208b430e-3453-4fcb-ae6f-7e487f917507)
![image](https://github.com/Rakesh9100/Beautiify/assets/145692647/5d8378ae-729d-4e80-aec9-25bbbcf59a68)
For dark and white mode
![image](https://github.com/Rakesh9100/Beautiify/assets/145692647/ab8490c6-f568-46b7-865a-4edc89f7712f)
Scroll with bottom to top button
### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshots of scrolls if you have @ananya-dhiman

**Comment by ananya-dhiman** [comment]
Screenshots are added @Rakesh9100

**Comment by Rakesh9100** [comment]
So you want to add Scrollbars Category and 2-3 components inside that @ananya-dhiman

**Comment by ananya-dhiman** [comment]
Yes

**Comment by Rakesh9100** [comment]
Okay, go ahead @ananya-dhiman
