### ISSUE TITLE
Adding a "Moving Squares" Background 

### ISSUE THREAD

**Issue by NikmanGT** [Rakesh9100/Beautiify#109]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

To add a "Moving Squares" background on the Backgrounds Component section
(The Text is just for reference)

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/140642394/61283738-a1ba-47cb-b449-9934bb9f7305)
https://github.com/Rakesh9100/Beautiify/assets/140642394/80372d20-3b3a-4c50-8f21-5d402c34d382

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @NikmanGT
