### ISSUE TITLE
[Feature] Add Neon Graphics Background

### ISSUE THREAD

**Issue by pankhuri92** [Rakesh9100/Beautiify#1092]
### Description

I would like to add a graphics kind of background animation to the background component. 
Kindly assign me the issue under GSSOC'24.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/138357063/1ee68c3e-43c2-42f0-bef4-88b72f7e0549

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @pankhuri92
