### ISSUE TITLE
[Feature] Add Bouncing Loader

### ISSUE THREAD

**Issue by tanishaprasad** [Rakesh9100/Beautiify#1097]
### Description

A loader that bounces back and forth, often used for loading bars or indicators.

### Screenshots

![bouncingloader](https://github.com/Rakesh9100/Beautiify/assets/145560431/4c767fc0-e60e-4057-a4c1-07512fa3d57e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ShagunSharma17** [comment]
Hi @tanishaprasad can you assign this issue to me?

**Comment by Rakesh9100** [comment]
Go ahead @tanishaprasad
