### ISSUE TITLE
[Feature] Add Autocomplete Search Bar

### ISSUE THREAD

**Issue by tanishaprasad** [Rakesh9100/Beautiify#1098]
### Description

This type of search bar provides suggestions or autocomplete options as users type. It enhances usability by helping users find relevant search terms quickly.

### Screenshots

![Searchbar](https://github.com/Rakesh9100/Beautiify/assets/145560431/becdff7a-1bc2-4b10-b033-daacfd346597)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ShagunSharma17** [comment]
Hi @tanishaprasad can you assign this task to me. I think i can make an attractive search bar

**Comment by Rakesh9100** [comment]
From where you will get the suggestions, will it fetch from the Google @tanishaprasad

**Comment by ShagunSharma17** [comment]
> From where you will get the suggestions, will it fetch from the Google @tanishaprasad

We can use Google places API for location based suggestions or Custom Search JSON API.

**Comment by tanishaprasad** [comment]
> From where you will get the suggestions, will it fetch from the Google @tanishaprasad

The suggestions will be fetched using an array as the data source for suggestions.

**Comment by Rakesh9100** [comment]
Okay, go ahead @tanishaprasad

**Comment by Rakesh9100** [comment]
Pls provide your PR @tanishaprasad

**Comment by tanishaprasad** [comment]
> Pls provide your PR @tanishaprasad

Done !
