### ISSUE TITLE
Add hover shadow button

### ISSUE THREAD

**Issue by pankhuri92** [Rakesh9100/Beautiify#110]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100, I would like to add an extra element of hover effect to button component.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/138357063/26903f61-fd2d-46be-954a-1e1d3137c73f

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Can you pls clarify that you want to add hover effect buttons inside button category? @pankhuri92

**Comment by pankhuri92** [comment]
Yes, under the button category I want to add another element

**Comment by Rakesh9100** [comment]
Okay carry on @pankhuri92
