### ISSUE TITLE
[Feature] Display the name of contributor on hovering

### ISSUE THREAD

**Issue by NidhiTornekar** [Rakesh9100/Beautiify#1102]
### Description

In the contributor page, currently only the images of contributors are being displayed.
It would look better if the contributor's GitHub username is also being displayed on hovering above his/her image.

### Screenshots

This is the current contributors page:
![ss1](https://github.com/Rakesh9100/Beautiify/assets/121748841/117110dc-6fe3-421e-93fa-94ee8ce5543f)

This is with a sample case:
(I wont change other components like background image/colour, below is just an example for displaying name additionally on hovering)
![ss2](https://github.com/Rakesh9100/Beautiify/assets/121748841/a487daaf-d9c5-4899-963a-3f38f3ed5692)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by NidhiTornekar** [comment]
@Rakesh9100 Please assign me this issue under GSSOC 2024

**Comment by Rakesh9100** [comment]
Go ahead @NidhiTornekar
