### ISSUE TITLE
[Feature] Add Like Effect Button

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Rakesh9100/Beautiify#1104]
### Description

Adding like button gets effects on hover

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100  please assign me the issue

**Comment by Aradhyajha** [comment]
@Rakesh9100 .. sir i want to work on this issue please assign this task to me

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot if you have @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
![image](https://github.com/Rakesh9100/Beautiify/assets/143107589/d6d755ff-5fa8-4143-9da6-a3e35a267c59)

Here is the sample @Rakesh9100
