### ISSUE TITLE
[Feature] Add Bookmark Effect Button

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Rakesh9100/Beautiify#1105]
### Description

Book mark effect button on hover

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100  please assign me this issue

**Comment by Rakesh9100** [comment]
Provide the supporting screenshot if you have @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
![image](https://github.com/Rakesh9100/Beautiify/assets/143107589/53c2db3e-b47f-4cb2-b40d-a76128f769e9)

@Rakesh9100 Here is the sample

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 I have Provided supporting Screenshot

**Comment by Rakesh9100** [comment]
Go ahead @Saipradyumnagoud
