### ISSUE TITLE
[Feature] Add Glitch Effect Button

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Rakesh9100/Beautiify#1106]
### Description

On hover of the button we get glitch Effect For the button

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100  Please Asssign me the issue

**Comment by Rakesh9100** [comment]
Pls provide the screenshot in GIF form of your issue @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
![image](https://github.com/Rakesh9100/Beautiify/assets/143107589/a673e957-fd5d-4bba-954d-55afe1cfb672)

here is the screen shot

**Comment by Rakesh9100** [comment]
Provide the recorded video or GIF of how it is working, as it seems like just normal button with GLITCH text on it @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
https://github.com/Rakesh9100/Beautiify/assets/143107589/d6768b9f-87d9-401c-896f-2d1d3b76f947

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 I have added gif for your understanding please assign me so that i can start working

**Comment by Rakesh9100** [comment]
Go ahead @Saipradyumnagoud

**Comment by Rakesh9100** [comment]
Pls provide your PR @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Yes I have Provide my Pull Request
