### ISSUE TITLE
Add a stylist scroll bar to the website

### ISSUE THREAD

**Issue by divyansh2375** [Rakesh9100/Beautiify#111]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

if we make this in another color it will look pretty cool

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/130889408/a29a7d81-5280-441b-aff7-320a7f74d046)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by divyansh2375** [comment]
@Rakesh9100  can i please work on this issue ?

**Comment by Rakesh9100** [comment]
Go ahead @divyansh2375

**Comment by Rakesh9100** [comment]
@divyansh2375 Status of your PR

**Comment by sanskritisahu21** [comment]
I'm eager to contribute to Beautify, and after exploring the issues, I'm interested in working on this issue. Please assign this issue to me.

**Comment by divyansh2375** [comment]
> I'm eager to contribute to Beautify, and after exploring the issues, I'm interested in working on this issue. Please assign this issue to me.

i am already working on this issue sanskiriti
