### ISSUE TITLE
[Feature] Add Bootstrap Navigation Bar

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/Beautiify#1111]
### Description

I want to add bootstrap navigation bar.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/126322584/7a31a1fd-7386-47c0-9f1b-b6b901138cb7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zalabhavy** [comment]
@Rakesh9100 please assign me !

**Comment by Rakesh9100** [comment]
It is just the simple navigation bar either made using Bootstrap or without it @zalabhavy

**Comment by zalabhavy** [comment]
@Rakesh9100 I will use Bootstrap.
It is simple but this type of Navigation bar not present in Beautify so I want to add this !

**Comment by Rakesh9100** [comment]
Okay proceed @zalabhavy
