### ISSUE TITLE
[Feature] Add Chevron Breadcrumb

### ISSUE THREAD

**Issue by AmrutaJayanti** [Rakesh9100/Beautiify#1112]
### Description

Chevron Dropdown

### Screenshots

![Screenshot 2024-06-25 195853](https://github.com/Rakesh9100/Beautiify/assets/142327526/e365007c-03a4-476b-a1d5-1154300edfdd)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AmrutaJayanti
