### ISSUE TITLE
[Feature] Add On/Off Button

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/Beautiify#1115]
### Description

I want to add the new ON/OFF Button which looks more attractive 

please assign me this issue under GSSOC24

### OFF Stage
![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/719c1b99-e475-4198-90bf-befbf873ecad)

### ON Stage
![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/13b90ede-fad0-4c5c-99ba-feb6bdb8929f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SaiyamTuteja
