### ISSUE TITLE
[Feature] Add Multiple Selection Dropdown

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/Beautiify#1116]
### Description

NA

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/139672976/6563464d-8146-4446-b1cc-0c6533916521)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @DharshiBalasubramaniyam
