### ISSUE TITLE
[Feature] Add scroll progress indicator bar

### ISSUE THREAD

**Issue by aslams2020** [Rakesh9100/Beautiify#1119]
### Description

Hey @Rakesh9100 
I want to add a **"Scroll Down Progress Bar"**

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page. 
The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### ScreenShot 

Example Like this - 
As All the "component pages" are Large for scrolling, this Scroll Progress Bar Will Definitely Improve the user's scrolling experience and will also help to know their location on the page -

![image](https://github.com/XceeDesigns/Website/assets/131389695/0f92f30d-9dd7-464f-b1fb-6e854d1fe01c)

**Expected Outcome**
The scroll down progress bar will provide users with a better understanding of their position on the page, enhancing navigation and overall user experience.

@Rakesh9100,
Could you please assign me this issue under GSSOC'24?

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aslams2020** [comment]
@Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @aslams2020

**Comment by aslams2020** [comment]
Thankyou @Rakesh9100!
