### ISSUE TITLE
Add a wavy background

### ISSUE THREAD

**Issue by pankhuri92** [Rakesh9100/Beautiify#112]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100 , I would like to add a background with waves in footer. Kindly assign me the issue.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @pankhuri92
