### ISSUE TITLE
[Feature] Add Application Form

### ISSUE THREAD

**Issue by maradadivyasree020** [Rakesh9100/Beautiify#1120]
### Description

Used for applying for jobs, schools, loans, etc.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by maradadivyasree020** [comment]
plrease review it and assign labels

**Comment by Rakesh9100** [comment]
Hey, please create your PR by forking my repo on your account. You have done it in your account only @maradadivyasree020

**Comment by maradadivyasree020** [comment]
I have done it please assign labels

**Comment by Rakesh9100** [comment]
Provide your PR first @maradadivyasree020

**Comment by maradadivyasree020** [comment]
#1253
