### ISSUE TITLE
[Feature] Add Outer Space Background

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1131]
### Description

I want to add Outer Space Background Under Backgrounds

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/131646799/27adcb81-ca2f-48ec-a9ec-31f79f912b14

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new background addition

**Comment by Rakesh9100** [comment]
Go ahead @VaishnaviMankala19 

You have too many issues opened at once, finish one by one ASAP!!
