### ISSUE TITLE
[Feature] Add Firefly Animation Background

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1132]
### Description

I want to add Animated fireflies glowing and moving around as background

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/131646799/8633f80d-04b5-4125-9d74-8502756fe30b

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new background addition
