### ISSUE TITLE
[Feature] Add Bouncing Text Animation

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1134]
### Description

I want to add Bouncing text animation under Text-Animations

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/131646799/1edee1dd-eb55-4c61-bed6-cda59a49959f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new text animation

**Comment by Rakesh9100** [comment]
Go ahead @VaishnaviMankala19
