### ISSUE TITLE
[Feature] Add 3D Cube Loader

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1135]
### Description

Implement a visually appealing 3D cube cluster loader animation to enhance the user experience during loading times. The animation should consist of multiple smaller cubes joining together to form a larger cube, providing a modern and engaging visual cue to users, indicating that a process is in progress. This loader can be utilized in various parts of the application where loading indicators are required.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/b1b6e66f-aec0-4bcb-9297-8900d17a4591

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New loader addition

**Comment by Rakesh9100** [comment]
Go ahead @Praneeth-2602
