### ISSUE TITLE
[Feature] Add Sliding Text Animation

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1136]
### Description

I want to add Sliding Text animation under Text-Animation

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/131646799/d03736cb-f104-433b-af22-c6276868abbe

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @VaishnaviMankala19
