### ISSUE TITLE
[Feature] Add Expandable Text Animation

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1137]
### Description

I want to add expand text on hover feature under Text-Animations

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/131646799/e03d455b-27c3-4c69-8f71-e604e21cb880

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@VaishnaviMankala19 any proper name for this text animation

**Comment by saurabhsingh720** [comment]
@Rakesh9100  new text animation

**Comment by VaishnaviMankala19** [comment]
@saurabhsingh720 ExpandableText

**Comment by saurabhsingh720** [comment]
@VaishnaviMankala19 ok

**Comment by Rakesh9100** [comment]
Go ahead, keep the name as `Expandable-Text-Animation` @VaishnaviMankala19
