### ISSUE TITLE
[Feature] Add Robo Toggle Switch

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1142]
### Description

A dynamic dark-light mode toggle button featuring a playful animation where a robot rolls over while the sun and moon move up and down, respectively. This engaging animation provides a delightful user experience while switching between light and dark themes. The button is designed for smooth and responsive transitions, adding both functionality and charm to your application.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/78193165-65f6-4411-9f98-38d5d19ea03e

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New button addition

**Comment by Rakesh9100** [comment]
What will be the short and best name of your component @Praneeth-2602

**Comment by Praneeth-2602** [comment]
RoboSwitch or RoboToggleButton

**Comment by Praneeth-2602** [comment]
@Rakesh9100 sir please look into this
