### ISSUE TITLE
[Feature] Add Typewriter Loader

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1143]
### Description

A captivating typewriter animation loader that mimics the appearance of text being typed out on a typewriter. This loader provides an engaging and visually appealing indication of loading processes, enhancing the overall user experience. Ideal for applications that aim for a creative and nostalgic touch, the TypeLoad component is easy to integrate and customize to fit the design aesthetics of your project.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/c915f729-c25b-4a67-8597-c4441ddca05c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New loader addition
