### ISSUE TITLE
[Feature] Add Minimalist Dark Toggle Switch

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1145]
### Description

A minimalist dark theme toggle button designed for a seamless user experience. With a single click, users can switch between light and dark modes, enhancing visual comfort and personalizing their interface. The toggle button is easy to integrate and ensures a smooth transition between themes.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/ec669cb4-4030-4406-a649-ce7e812b193b

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New button addition

**Comment by Praneeth-2602** [comment]
Sir is a toggle-switch component

**Comment by saurabhsingh720** [comment]
@Praneeth-2602 
But it can be added in a button component
