### ISSUE TITLE
[Feature] Add Squid Game Loader

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1146]
### Description

An intriguing loader animation inspired by Squid Game, featuring the iconic triangle, square, and rectangle shapes.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/c9c7abda-dc65-4377-ae1c-43b53610aa9e

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [x] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new loader addition
