### ISSUE TITLE
Adding changing background

### ISSUE THREAD

**Issue by kshitigambhir** [Rakesh9100/Beautiify#115]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

A new image will load everytime the page is loaded.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Do you want to add this as a component under Background category ? @kshitigambhir
