### ISSUE TITLE
[Feature] Add Progress Text Loader

### ISSUE THREAD

**Issue by sandy-queen** [Rakesh9100/Beautiify#1154]
### Description

I want to add a new loader. The loader will consist of a progress bar and a text. The text will change colours with the loading progress, and the bar will show the progress.

I think it can be called the "Loading Bar and Text"?

### Screenshots

![load text and bar](https://github.com/Rakesh9100/Beautiify/assets/147652780/f9cf5b63-93d5-4315-b8d8-0559696faee0)

**Please assign this issue to me under GSSOC'24**

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New loader addition

**Comment by Rakesh9100** [comment]
Loading Bar and Text Loader don't sound a good name, please provide a better name of your loader component @sandy-queen

**Comment by sandy-queen** [comment]
Then can it be called "Progress Bar Loader"?

**Comment by Rakesh9100** [comment]
Okay, keep it as `Progress-Text-Loader` @sandy-queen
