### ISSUE TITLE
[Feature] Add Portfolio Contact Form

### ISSUE THREAD

**Issue by komal-agarwal5** [Rakesh9100/Beautiify#1159]
### Description

I wish to add a 2card themed contact form which is very useful in portfolio or similiar types of websites

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/122633300/7bf1f50c-e68f-4108-858e-d991f004e1b6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new form addition

**Comment by Rakesh9100** [comment]
Go ahead @komal-agarwal5
