### ISSUE TITLE
Add Scroll Reveal effect

### ISSUE THREAD

**Issue by sambitsingha** [Rakesh9100/Beautiify#116]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The scroll reveal effect when appiled to the elements will reveal the elements one by one on scroll. it can customised accordingly to direction , delay , distance , etc.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/110420002/95d61d2f-9078-42ae-8e4a-d60aa9e1bfa3

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Okay, go ahead @sambitsingha

**Comment by sambitsingha** [comment]
@Rakesh9100  Will submit it by today

**Comment by Rakesh9100** [comment]
@sambitsingha Status of your PR

**Comment by sambitsingha** [comment]
Completed. I will submit tomorrow ;)
