### ISSUE TITLE
[Feature] Add Interactive Particle Hero

### ISSUE THREAD

**Issue by ANKeshri** [Rakesh9100/Beautiify#1161]
### Description

I want to add a new type of hero ie "interactive particle hero effect"

### Screenshots

it will look like this 

https://github.com/Rakesh9100/Beautiify/assets/159682348/4f2c1d6c-3aa6-4e7d-bf88-71b23138397c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ANKeshri** [comment]
@Rakesh9100 please assign me this issue i want to work on it

**Comment by ANKeshri** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @ANKeshri
