### ISSUE TITLE
[Feature] Add Neon Glow Hero

### ISSUE THREAD

**Issue by Maana-Ajmera** [Rakesh9100/Beautiify#1162]
### Description

Making a hero section that glows and fades.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/162733812/cb5cf6f6-68a8-4c28-b2f0-326f2ef9c3b8

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maana-Ajmera** [comment]
@Rakesh9100 please assign me this issue i want to work on it

**Comment by Rakesh9100** [comment]
What exactly do you want to add, pls clarify your issue nicely @Maana-Ajmera

**Comment by Maana-Ajmera** [comment]
@Rakesh9100 Creating a hero section with neon glows can be a striking and visually appealing choice for a website.

**Comment by Rakesh9100** [comment]
Okay go ahead @Maana-Ajmera
