### ISSUE TITLE
[Feature] Add Menu Transfer List

### ISSUE THREAD

**Issue by Maana-Ajmera** [Rakesh9100/Beautiify#1164]
### Description

We can add menu transfer list where one or more menu items can be added or removed

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/162733812/8cac36d4-a229-4c87-99eb-f286702184a7

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maana-Ajmera** [comment]
@Rakesh9100 please assign me this issue I want to work on it

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new addition of transfer list

**Comment by Maana-Ajmera** [comment]
@Rakesh9100 please assign me this issue I want to work on it

**Comment by Rakesh9100** [comment]
Go ahead @Maana-Ajmera
