### ISSUE TITLE
[Feature] Add Slide Reveal Popup

### ISSUE THREAD

**Issue by ANKeshri** [Rakesh9100/Beautiify#1165]
### Description

- a new type of pop up in which its appearing something is coming behind from slide 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/159682348/4054bce4-a666-4d9c-8e09-8bc243fb95c5

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ANKeshri** [comment]
@Rakesh9100 please assign me this issue i want to work on it

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new popup addition

**Comment by ANKeshri** [comment]
@Rakesh9100 please assign me this issue under gssoc labels

**Comment by ANKeshri** [comment]
@Rakesh9100 can I work on it ?

**Comment by Rakesh9100** [comment]
Go ahead @ANKeshri
