### ISSUE TITLE
[Feat]: Create a separate contributors page 

### ISSUE THREAD

**Issue by SulagnaKundu** [Rakesh9100/Beautiify#117]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to create a separate contributors page and remove the already existing contributors section from the main page.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by SulagnaKundu** [comment]
I want to work on this issue. Can you please assign me this issue under SWOC S4 ?

**Comment by Rakesh9100** [comment]
Can you show some screenshots or share your ideas about how good you will customise the contributors page @SulagnaKundu

**Comment by SulagnaKundu** [comment]
Like, I can only create a separate page like the contact section, may be add some on click hover effect on them or make some changes in the styling may be.

**Comment by Rakesh9100** [comment]
@SulagnaKundu Update of your PR

**Comment by SulagnaKundu** [comment]
I am working on it. Till now, I have created the page , I am yet to add some css like hover effects and all.
![image](https://github.com/Rakesh9100/Beautiify/assets/103977344/e132c201-574f-4725-9602-7f645880ec28)
Is the background of the page fine?

**Comment by Rakesh9100** [comment]
Yes, fine @SulagnaKundu

**Comment by Rakesh9100** [comment]
@SulagnaKundu Status of your PR

**Comment by SulagnaKundu** [comment]
I am still working on it. Need some time to complete this.

**Comment by Rakesh9100** [comment]
Pls tell me by when will you create a PR as already it's been 5 days you are assigned to this issue @SulagnaKundu

**Comment by sksinha2410** [comment]
@Rakesh9100 I would like to work on this under JWOC

**Comment by Rakesh9100** [comment]
Have you gone through this issue that what you have to do @sksinha2410

**Comment by sksinha2410** [comment]
Yes, I have to create and link a webpage which will show the name of the contributors along with their contribution.

**Comment by sksinha2410** [comment]
Kindly assign me this

**Comment by sksinha2410** [comment]
completed as per instruction.
