### ISSUE TITLE
[Feature] Add Cursors Category and several Components

### ISSUE THREAD

**Issue by Nidhi-Satyapriya** [Rakesh9100/Beautiify#1172]
### Description

Adding animated cursor effects can be yet another striking functionality under Beautify.
I shortlisted two cursor animations that I'd like to build for Beautify.
1) Swirl Cursor Effect
2) Dot Cursor Effect

I will build them purely using HTML, CSS and JS. 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/123321320/832aee53-77ca-4862-af73-6542d6970991

https://github.com/Rakesh9100/Beautiify/assets/123321320/abfee7ab-8388-4329-8fac-e8bf76e2b1fb

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Nidhi-Satyapriya** [comment]
@SrinivasDevolper @Rakesh9100  kindly review this and assign it to me.

**Comment by saurabhsingh720** [comment]
@Nidhi-Satyapriya 
Youu want to add these effect inside background component. Right!!

**Comment by Nidhi-Satyapriya** [comment]
Hey @saurabhsingh720. I plan to introduce a new 'Animated Cursor' component where not just I, but anyone can add engaging cursor effects with a sample background (since animated cursor effect is the aim, not the background).
To start with this idea, I myself would like to add two of my favorite animated cursor effects (as mentioned above).
I hope I made it clear.

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Can it be needed??

**Comment by Nidhi-Satyapriya** [comment]
Hi @SrinivasDevolper @Rakesh9100 ! Did you review this issue?

**Comment by saurabhsingh720** [comment]
@Nidhi-Satyapriya 
Mention the mentor and admin only.
@SrinivasDevolper is a contributor.
Understood!!

**Comment by saurabhsingh720** [comment]
@Nidhi-Satyapriya 
When admin reviews your issue then they will reply u in the comment.

**Comment by Rakesh9100** [comment]
Yes, idea seems good @saurabhsingh720 

Please go ahead @Nidhi-Satyapriya

**Comment by Rakesh9100** [comment]
Pls provide your PR @Nidhi-Satyapriya

**Comment by Nidhi-Satyapriya** [comment]
Yes sir, asap. @Rakesh9100

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100 I made a PR. Kindly review it at your earliest convenience.

**Comment by Nidhi-Satyapriya** [comment]
@Rakesh9100  @saurabhsingh720 It's been over two weeks since I contributed. May I know the status?

**Comment by saurabhsingh720** [comment]
@Rakesh9100
