### ISSUE TITLE
[Feature] Add footer in all the components category page

### ISSUE THREAD

**Issue by kunalmaurya6** [Rakesh9100/Beautiify#1173]
### Description

footer is missing from all pages except home page

https://github.com/Rakesh9100/Beautiify/assets/109097899/d732bd8d-6f26-43fc-84e7-e5371805d546

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@kunalmaurya6 
U have to add footer of all components that matches to those component.
Can u do that?

**Comment by kunalmaurya6** [comment]
definitely i will do if i get assign this to me

**Comment by kunalmaurya6** [comment]
ofcourse it will increase user experience

**Comment by Rakesh9100** [comment]
Issue #638 is already open for this, lmk further @kunalmaurya6
