### ISSUE TITLE
[Feature] Add Animated Progress Loader

### ISSUE THREAD

**Issue by jaydeep099** [Rakesh9100/Beautiify#1174]
### Description

Adding Progress bar as in new component and Adding a animated progress bar.

### Screenshots

![Screenshot 2024-07-01 181505](https://github.com/Rakesh9100/Beautiify/assets/148114163/ee035ffa-ac0f-4fb4-8d39-0ef3ead60513)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to add this component in Loaders Category @jaydeep099

**Comment by jaydeep099** [comment]
@Rakesh9100 I have no problem but if you see as loader perspective but i personally think it should have different component that is progress bar or we can rename to loader and progress bar. At last i don't any problem to add in loader category.

**Comment by jaydeep099** [comment]
@Rakesh9100 assign me I have no problem in adding loader category

**Comment by Rakesh9100** [comment]
Provide me the video of your component for clarity, is this component a loader or not @jaydeep099

**Comment by jaydeep099** [comment]
https://github.com/user-attachments/assets/bc9b149d-805d-4603-bd0d-61b699f7928e

@Rakesh9100 Please Check it

**Comment by Rakesh9100** [comment]
Provide me the proper name of your loader, which includes the suffix Loader @jaydeep099

**Comment by jaydeep099** [comment]
@Rakesh9100 it is progress loader and suffix is Animated progress loader

**Comment by Rakesh9100** [comment]
Go ahead @jaydeep099
