### ISSUE TITLE
[Style] Enhance the home page UI

### ISSUE THREAD

**Issue by mahak0711** [Rakesh9100/Beautiify#1176]
### Description

Enhance UI of Component Cards and Add Animations for Better User Experience

Description:
Enhancing the UI of component cards and integrating animations can significantly improve the user experience. This issue outlines the proposed enhancements and their expected benefits.

Enhancements:

Visual Hierarchy: Use different font sizes and weights to distinguish titles, subtitles, and body text.
Highlight important information with color, bold text, or icons.

Color Scheme: Choose a color palette that aligns with our brand.
Use contrasting colors for text and background to improve readability.

Interactive Elements: Incorporate buttons and links with clear call-to-actions (CTAs).
Ensure buttons are easy to identify and click.
Animations:

Smooth Transitions: Implement animations for transitions between different states (e.g., hover effects, page changes).
Aim for smooth and natural transitions to reduce cognitive load.
Guided Interactions:

Use animations to guide users' attention to important elements or actions.
For example, subtle animations on CTA buttons can draw attention without being intrusive.
Feedback and Affordance:

Provide visual feedback for user interactions, indicating actions have been recognized (e.g., button presses, form submissions).
Enhance the sense of control and satisfaction for users.

Attachments/References:

https://github.com/Rakesh9100/Beautiify/assets/128406559/56acd49e-6175-4989-8639-94730f9e0275

### Screenshots

![Screenshot 2024-07-03 004030](https://github.com/Rakesh9100/Beautiify/assets/128406559/cbe06ab1-4ab9-47bc-a2ff-35d7d3baba6e)
![Screenshot 2024-07-03 004007](https://github.com/Rakesh9100/Beautiify/assets/128406559/81baea5a-986c-4407-a81a-6e8c35a26dc8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by mahak0711** [comment]
Please @Rakesh9100 assign this issue to me!

**Comment by mandeep848** [comment]
Please @Rakesh9100  assign this issue to me, i can add some more UI in this

**Comment by Rakesh9100** [comment]
Pls review this @saurabhsingh720

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
It makes the website looks better.
We can assign her

**Comment by saurabhsingh720** [comment]
@mahak0711 
You have to add icons as well that are used in the recent components

**Comment by mahak0711** [comment]
@saurabhsingh720 okay,i'll add it.

**Comment by mahak0711** [comment]
@saurabhsingh720 Please review it.I added the new components
![image](https://github.com/user-attachments/assets/2f583b29-a078-4439-9e24-a1ed67838875)

**Comment by saurabhsingh720** [comment]
@mahak0711 
Add icons make it look good.
Currently it is looking very empty

**Comment by saurabhsingh720** [comment]
@mahak0711 your img is not opening

**Comment by mahak0711** [comment]
@saurabhsingh720 

![Screenshot 2024-07-20 003430](https://github.com/user-attachments/assets/a8f4df0b-d5b1-41ed-8c8b-f4bcf4822abd)

**Comment by saurabhsingh720** [comment]
@mahak0711 
It is not looking good 
Make the icon centre

**Comment by mahak0711** [comment]
@saurabhsingh720 made the changes
![Screenshot 2024-07-24 110900](https://github.com/user-attachments/assets/6fa568fb-3a6a-48fc-a788-adffb2236006)

**Comment by saurabhsingh720** [comment]
@mahak0711 looks cool.
Make the proper alignment of all the components
