### ISSUE TITLE
[Feature] Add Bar Fill Loader

### ISSUE THREAD

**Issue by debangi29** [Rakesh9100/Beautiify#1177]
### Description

Can add a component bar fill loader in Beautify!! :)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to work on this @debangi29

**Comment by Rakesh9100** [comment]
Go ahead @debangi29

**Comment by Rakesh9100** [comment]
Pls provide your PR @debangi29

**Comment by debangi29** [comment]
Yes sir I'm working on it
Thanks :)
