### ISSUE TITLE
[Feature] Add Subscription Footer

### ISSUE THREAD

**Issue by komal-agarwal5** [Rakesh9100/Beautiify#1178]
### Description

I want to add a new footer component.It has extra placeholder for site links,logo and subscribe button.It will be useful for ecommerce sites or newsletter applications.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/122633300/02da6424-dcdc-42e0-8f7b-53af3ecfe51f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the name of your component @komal-agarwal5

**Comment by komal-agarwal5** [comment]
> What will be the name of your component @komal-agarwal5

@Rakesh9100 It's name will be subscription footer

**Comment by Rakesh9100** [comment]
Go ahead @komal-agarwal5

**Comment by Rakesh9100** [comment]
Pls provide your PR @komal-agarwal5

**Comment by komal-agarwal5** [comment]
> Pls provide your PR @komal-agarwal5

Yes giving by EOD
