### ISSUE TITLE
[Feature] Add Subscribe Popup

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/Beautiify#1179]
### Description

Adding a new popup component would be better for user to have more options

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142779809/cd1d6b47-7539-4082-be79-56065daec877

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @root-0101

**Comment by Rakesh9100** [comment]
Provide your PR @root-0101

**Comment by root-0101** [comment]
I have raised the PR please review it
