### ISSUE TITLE
[Feature] Add Rate us component

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/Beautiify#1182]
### Description

It would be great if we create a "Rate us" category in the components sections which include various rate us card which is helpful for user and then can easily use these rate us features in their webpages

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 could it be needed??

**Comment by Rakesh9100** [comment]
It can come in Cards category only, no need for separate category @root-0101

**Comment by Rakesh9100** [comment]
It can come in the Cards category only, no need for a separate category @root-0101
