### ISSUE TITLE
[Feature] Add Medical Form

### ISSUE THREAD

**Issue by Nayanika1402** [Rakesh9100/Beautiify#1184]
### Description

Used in healthcare settings for patient information, medical history, consent, etc.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Nayanika1402 
Show me how it looks??

**Comment by Rakesh9100** [comment]
Provide the supporting screenshot of your issue @Nayanika1402

**Comment by Nayanika1402** [comment]
Screenshots:
![Screenshot 2024-07-12 000618](https://github.com/Rakesh9100/Beautiify/assets/132455412/8778e0c3-9588-4170-89ec-a0dad58a0eeb)
![Screenshot 2024-07-12 000627](https://github.com/Rakesh9100/Beautiify/assets/132455412/b4d85743-a3d5-4e54-8227-c0ae30dcadd9)
@Rakesh9100 @saurabhsingh720

**Comment by Rakesh9100** [comment]
Okay, go ahead @Nayanika1402

**Comment by Nayanika1402** [comment]
@Rakesh9100 Kindly merge the PRs as the points are valuable and the program is going to end tomorrow.

**Comment by saurabhsingh720** [comment]
@Nayanika1402 it will be merge sooner 
Program end on 10 August
