### ISSUE TITLE
[Feature] Add Wave Text Animation

### ISSUE THREAD

**Issue by MadhurimaNayak** [Rakesh9100/Beautiify#1188]
### Description

Add a option under the text animations component list - waves inside text. The text would be in outline, and there will be a constant wave that is moving inside it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot or GIF of your component @MadhurimaNayak

**Comment by MadhurimaNayak** [comment]
I am talking about something like this but instead of the flat shape inside the text it would be a wave and be moving.
![image](https://github.com/Rakesh9100/Beautiify/assets/124715194/7574a84b-9b93-4bfa-a5d3-54495b2cf54e)

**Comment by Rakesh9100** [comment]
Okay, go ahead and name it `Wave-Text-Animation` @MadhurimaNayak
