### ISSUE TITLE
[Feature] Add Book Card

### ISSUE THREAD

**Issue by AnshRehan04** [Rakesh9100/Beautiify#1189]
### Description

I want to add an eyecatching card which opens like a book like we turn around the pages and our  content inside that page.
Please Assign me under GSSOC '24.

Thank You

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/118544177/d671ba19-7102-4bdf-b830-378b1bcec732)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the name of your component @AnshRehan04

**Comment by AnshRehan04** [comment]
Book Card

**Comment by Rakesh9100** [comment]
Go ahead @AnshRehan04
