### ISSUE TITLE
Adding Search Bar Category and a Component

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#119]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to add a search bar component under the components section.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @saurav2208

**Comment by Rakesh9100** [comment]
@saurav2208 Status of your PR

**Comment by saurav2208** [comment]
> @saurav2208 Status of your PR

Working on it. Will be done by tomorrow.
