### ISSUE TITLE
I added contact page

### ISSUE THREAD

**Issue by vishal0316** [Rakesh9100/Beautiify#12]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I added contact page according to UI and Color Palettes.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/106919588/cc4a2215-0d08-46a2-96e0-0c2c253bdf06)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Issue is already open. Check the comment there @vishal0316
