### ISSUE TITLE
Adding 3d rotating text animation

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#120]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i would like to add a rotating 3d text animation . please assign it to e under swoc'24.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @GhoshAditi
