### ISSUE TITLE
[Style] Enhance the footer socials with actual color

### ISSUE THREAD

**Issue by ANKeshri** [Rakesh9100/Beautiify#1204]
### Description

- at present when we hover over social icons all gets converted to red colour .

- i want that each should convert to its actual colour when we hover on social icons

### Screenshots

Before : 

https://github.com/Rakesh9100/Beautiify/assets/159682348/f1906877-1691-4671-a2a5-2050d811e647

want to make like this :

https://github.com/Rakesh9100/Beautiify/assets/159682348/ad1d6542-928d-4f41-a2f3-76712b690654

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @ANKeshri
