### ISSUE TITLE
[Feature] Add Circular Navigation Bar-2

### ISSUE THREAD

**Issue by Maana-Ajmera** [Rakesh9100/Beautiify#1205]
### Description

I want to add a circular navbar in the navbar section 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/162733812/2f926e84-00c5-4944-a88a-72a0c520c665

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Maana-Ajmera** [comment]
@Rakesh9100 I want to add this feature , please assign it to me

**Comment by prachi0701** [comment]
@Maana-Ajmera , Assign this to me!!

**Comment by Maana-Ajmera** [comment]
@saurabhsingh720 @Rakesh9100 should I work on it ?

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Circular nav bar is already added. But its animation is different.
Can it be added?

**Comment by Rakesh9100** [comment]
Yes, go ahead @Maana-Ajmera
