### ISSUE TITLE
[Style] Implement single page for all the menu items

### ISSUE THREAD

**Issue by siddhant-2002** [Rakesh9100/Beautiify#1206]
### What's the style idea?

i think we should create one single page for home about contributers and contact us and when we click on get components then we will render our components  you can refer below layout to understand changes 

![image](https://github.com/Rakesh9100/Beautiify/assets/112260375/6ac3832a-3759-42d3-95cb-949b4a46b342)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by siddhant-2002** [comment]
Hey please tell me your thoughts or else close the issue

**Comment by Rakesh9100** [comment]
No need of this, separate pages are only fine. Please work on other issues @siddhant-2002
