### ISSUE TITLE
[Style] Enhance the 404 error page

### ISSUE THREAD

**Issue by Damini2004** [Rakesh9100/Beautiify#1208]
### What's the style idea?

We need to improve

![image](https://github.com/Rakesh9100/Beautiify/assets/119414762/52676fac-87e0-479a-8d82-65f65983949c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Damini2004 
What improvement did u want to do?
Can u give any image of that?

**Comment by Damini2004** [comment]
Here i will add the animated video that will depicts that page not found.

**Comment by saurabhsingh720** [comment]
@Damini2004 can u show us?

**Comment by Damini2004** [comment]
![gif1](https://github.com/user-attachments/assets/e1234ef9-8ea0-49c3-b54a-7efe5196ebe1)
![CodePen-404-Page](https://github.com/user-attachments/assets/9f0c0052-9c50-40fe-a83f-7bb24c416a37)
Like this Can you assign this to me with suitable level i will do it within 1 day

**Comment by saurabhsingh720** [comment]
@Rakesh9100 which animation is better wrt u

**Comment by Damini2004** [comment]
2nd one but if necessary i will explore more gif in order to achieve betterment.

**Comment by Rakesh9100** [comment]
Go ahead with the 2nd one, make sure to match the UI @Damini2004

**Comment by aashlesha12** [comment]
I'm interested in working on issue #1208. I've already reviewed the issue description and believe I have the necessary skills to contribute.

Please let me know if you're open to assigning this to me."
