### ISSUE TITLE
[Style] Enhance the About page image with floating animation

### ISSUE THREAD

**Issue by Damini2004** [Rakesh9100/Beautiify#1209]
### What's the style idea?

We need to improve

![Screenshot 2024-07-13 135640](https://github.com/user-attachments/assets/45d5ce17-9ceb-42d8-984c-5e2afc5cc139)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Damini2004 
Attach the image again
Previous one is not visible.

**Comment by Damini2004** [comment]
![Uploading image.png…]()
![Screenshot 2024-07-13 135640](https://github.com/user-attachments/assets/45d5ce17-9ceb-42d8-984c-5e2afc5cc139)

**Comment by Damini2004** [comment]
@saurabhsingh720 assign this to i can do it within one day.

**Comment by saurabhsingh720** [comment]
@Damini2004 your img is not opening

**Comment by Damini2004** [comment]
![image](https://github.com/user-attachments/assets/c77d11ff-9801-4702-ae12-071caeaaa98a)

But it is visible

**Comment by saurabhsingh720** [comment]
@Damini2004 
I asked u to give the animation that u want to add

**Comment by Damini2004** [comment]
Sorry sir for misunderstanding but the floating animation will applied on the given image of about section  that will levitate the image countiniously. @saurabhsingh720

**Comment by saurabhsingh720** [comment]
@Rakesh9100 will it needed

**Comment by Rakesh9100** [comment]
Can you pls provide the demo of the animation that you want to add to that particular image @Damini2004

**Comment by Rakesh9100** [comment]
Can you pls provide the demo of the animation you want to add to that particular image @Damini2004

**Comment by Damini2004** [comment]
https://counsellor.social/  Here you with get demo of floating animation image where the image beside the login credential are levitating.
Kindly assign this to me as soon as possible i wanted to work on it.

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Good to assign her.

**Comment by Rakesh9100** [comment]
Do you want to be work @Damini2004

**Comment by Rakesh9100** [comment]
Do you want to work @Damini2004

**Comment by Damini2004** [comment]
@Rakesh9100  Assign this to me i will create PR with in one day.

**Comment by Rakesh9100** [comment]
Go ahead @Damini2004
