### ISSUE TITLE
[Bug] Website Content is not responsive and perfect aligned

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#121]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

There are a few issues with the content of the website. 
1. The content on the website is not responsive, in mobile and other screens the component section overlaps the button. 
2. There are extra spaces around the content hindering its responsiveness on mobile devices.

### Screenshots

![beautify desktop](https://github.com/Rakesh9100/Beautiify/assets/33122840/1fbd5f5c-4c9e-4f06-8858-cc0329355f87)
![beautify1](https://github.com/Rakesh9100/Beautiify/assets/33122840/6b283bfd-ee1a-4d2a-9da8-3745cb16856e)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @pb0126
