### ISSUE TITLE
[Feature] Add Neon Spectrum Text Animation

### ISSUE THREAD

**Issue by ANKeshri** [Rakesh9100/Beautiify#1211]
### Description

add a new type of text animation in thisch text changes its colour smoothly as shown in attached video

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/159682348/85384a13-d5c0-40bc-8a8c-6fae5ede022c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@ANKeshri 
New text animation

**Comment by ANKeshri** [comment]
@saurabhsingh720 please tag @Rakesh9100  

@Rakesh9100 should I work on it

**Comment by ANKeshri** [comment]
@Rakesh9100 sir I have created pr for my earlier assigned issue Can you please assign me this also I have checked this type animation is not added by anyone .

**Comment by ANKeshri** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
Proceed @ANKeshri
