### ISSUE TITLE
[Style] Enhance the hover effect of navbar

### ISSUE THREAD

**Issue by heli0707** [Rakesh9100/Beautiify#1217]
### Description

Update the footer hover effect by changing the background color to a lighter shade and adding a subtle text shadow. This enhancement provides clear visual feedback, making footer links more engaging and easier to interact with.

### Screenshots

https://github.com/user-attachments/assets/9d60d7ef-833b-45ce-88dd-b2dde5b19b69

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
In title, you have mentioned navbar, but in the description it is footer. So whose hover effect you exactly want to enhance @heli0707

**Comment by heli0707** [comment]
@Rakesh9100 
sorry it's my mistake
I want to change the navbar hover effect and update this 

https://github.com/user-attachments/assets/dc7b8b73-6654-41ee-af0c-4d27c6e30b8a

make something like this

**Comment by Rakesh9100** [comment]
Do you want to work @heli0707

**Comment by Rakesh9100** [comment]
Any update @heli0707

**Comment by aashlesha12** [comment]
I'm interested in working on issue #1217. I've already reviewed the issue description and believe I have the necessary skills to contribute.

Please let me know if you're open to assigning this to me."

**Comment by Aayush316** [comment]
I am interested and capable of providing the solution to the issue. I have read and understood the issue. So please let me know if you can assign this issue to me.

**Comment by RanitDERIA** [comment]
Hi @Rakesh9100 , I'd like to work on this issue! I'll update the footer hover effect by adjusting the background color to a lighter shade and adding a subtle text shadow to enhance user interaction. Could you please assign this issue to me? Thanks!
