### ISSUE TITLE
[Feature] Add Cookie Consent Popup

### ISSUE THREAD

**Issue by anagha-chaudhari** [Rakesh9100/Beautiify#1218]
### Description

In components, I wish to add one more popup type i.e Cookie Consent Popup under the popups section

### Screenshots

Reference:
![popup](https://github.com/user-attachments/assets/6f9975c6-ee5b-436f-a03f-310d3cc70338)
![popup2](https://github.com/user-attachments/assets/d3ca0007-76f0-486a-9de9-c982e5394238)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @anagha-chaudhari
