### ISSUE TITLE
[Feature] Add All In One Form

### ISSUE THREAD

**Issue by zalabhavy** [Rakesh9100/Beautiify#1224]
### Description

**I want to add a form which contains all input fields like** 

**text
password
email
textarea
checkbox
options
file
dropdown menu 
Rang**

**I will use Html , Bootstrap for create this form**

### Screenshots

![image](https://github.com/user-attachments/assets/3af29efd-ee78-4a00-9a93-80427df3ca14)
![image](https://github.com/user-attachments/assets/84eb5ec8-7e88-4a32-92fa-d52585cde59a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zalabhavy** [comment]
@Rakesh9100 Please assign me this task !

Thank You !

**Comment by Rakesh9100** [comment]
What will be the name of your component? Also, will you enhance the UI, or will it be this simple @zalabhavy

**Comment by zalabhavy** [comment]
@Rakesh9100 

I will enhance UI with shadow in form also input focus I can make animated background behind form.

Name of component :- All in one form

**Comment by Rakesh9100** [comment]
Okay, go ahead @zalabhavy
