### ISSUE TITLE
[Feature] Add Gaming Theme Button

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/Beautiify#1227]
### Description

A Button with perfect for gaming theme

### Screenshots

![image](https://github.com/user-attachments/assets/d014e83a-ad8f-4156-9673-f0a4064d7dc7)
on hover:
![image](https://github.com/user-attachments/assets/743f6e5d-0b8d-45c9-936c-e84143859d3b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new button addition
