### ISSUE TITLE
[Feature] Add Dynamic Hover Button

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/Beautiify#1228]
### Description

Button is a styled interactive element made up of five individual boxes, each displaying a letter to form the word "HOVER". When the user hovers over the button, a smooth transition reveals different letters, ultimately spelling out "WORLD". Each box has a background color and text that changes on hover, creating a dynamic and engaging visual effect. The transition animations are carefully timed for a cohesive and fluid appearance.

### Screenshots

https://github.com/user-attachments/assets/ae6938ac-e186-461e-ba7d-41181accda99

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new button addition

**Comment by saurabhsingh720** [comment]
@divyansh-2005   what is your button name?

**Comment by divyansh-2005** [comment]
"Dynamic Hover Button"

**Comment by saurabhsingh720** [comment]
Ok
