### ISSUE TITLE
[Feature] Add Social Hover Animated Button

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/Beautiify#1229]
### Description

A button in circular shape divided into four sections for social media links

### Screenshots

![image](https://github.com/user-attachments/assets/df29a4b0-514f-4e6a-adc0-1c29675026f8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@divyansh-2005 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .
