### ISSUE TITLE
[Feature] Add Play Now Button

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/Beautiify#1230]
### Description

A animated play now button

### Screenshots

![image](https://github.com/user-attachments/assets/e49cce7a-3633-49b3-906d-c9366b908b89)

![image](https://github.com/user-attachments/assets/6a07c633-7be3-4bf7-8d41-f4adb1ac76c8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@divyansh-2005 
I am assigning u this issue.
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .

**Comment by divyansh-2005** [comment]
ok
