### ISSUE TITLE
[Feature]: Add Delete Effect Button

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Rakesh9100/Beautiify#1239]
### Description

Adding Delete Effect Button On Hover

### Screenshots

![image](https://github.com/user-attachments/assets/c45ac918-38f0-40a5-9e13-8fac3e750dc1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Please assign me the issue

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 please assign me the issue
soon..

**Comment by saurabhsingh720** [comment]
@Saipradyumnagoud 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .

**Comment by Saipradyumnagoud** [comment]
@saurabhsingh720 Yes Bro i have Raised My PR

**Comment by Rakesh9100** [comment]
We already have Delete Animation Button added @Saipradyumnagoud
