### ISSUE TITLE
Adding Floating Hearts Background

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#124]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to one more background styles. Plz assign this issue to me under swoc'24.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by GhoshAditi** [comment]
@Rakesh9100 i would like to work on it.

**Comment by Rakesh9100** [comment]
Go ahead @GhoshAditi
