### ISSUE TITLE
README.md File is Looking very bad , i want to made it easy to understand.

### ISSUE THREAD

**Issue by piyushsahujtp** [Rakesh9100/Beautiify#1242]
### Description

Want to add more features by which the readme file become easily undestable and requires all features of the project.

### Screenshots

![Screenshot 2024-07-15 141318](https://github.com/user-attachments/assets/877ca90f-a567-4494-9f81-6aca08f78840)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need of this @piyushsahujtp
