### ISSUE TITLE
[Feature] Add Gradient Tooltip and Mario Themed Tooltip

### ISSUE THREAD

**Issue by hars-21** [Rakesh9100/Beautiify#1248]
### Description

Two new tooltip components in the library
1. Gradient Tooltip
2. Mario themed tooltip

### Screenshots

![Screen Shot 2024-07-15 at 5 06 09 PM](https://github.com/user-attachments/assets/a1c578b2-e1cd-4d27-ac4d-c4a8c4775df9)
![Screen Shot 2024-07-15 at 5 07 12 PM](https://github.com/user-attachments/assets/d0718053-35af-4fd0-8bbd-d0a444667975)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hars-21** [comment]
@Rakesh9100 Please assign me this issue.

**Comment by hars-21** [comment]
@Rakesh9100 Please assign me this issue.

**Comment by saurabhsingh720** [comment]
@hars-21 go forward 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .

**Comment by hars-21** [comment]
@Rakesh9100 Please assign this issue to me! @saurabhsingh720 @

**Comment by saurabhsingh720** [comment]
@hars-21 go ahead bro

**Comment by hars-21** [comment]
Ok

**Comment by Praneeth-2602** [comment]
this is issue is solved right?

**Comment by hars-21** [comment]
No, I am working on it.
