### ISSUE TITLE
[Docs] Add newly added categories in Readme

### ISSUE THREAD

**Issue by hars-21** [Rakesh9100/Beautiify#1250]
### Category of documentation update

New category addition - tooltip 

### Describe the change you think might work

Add a new category - tooltip in readme.md file. tooltip component library has been added but missing in documentation

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hars-21** [comment]
@Rakesh9100 Please assign me this issue.

**Comment by hars-21** [comment]
@Rakesh9100 Please assign me this issue.

**Comment by Rakesh9100** [comment]
You have opened too many issues, complete at a fast pace but with quality work @hars-21

**Comment by Rakesh9100** [comment]
Go ahead @hars-21
