### ISSUE TITLE
[Style] Improve the contact form responsiveness

### ISSUE THREAD

**Issue by sanjaraiy** [Rakesh9100/Beautiify#1257]
### What's the style idea?

We need to improve
![Screenshot 2024-07-16 172617](https://github.com/user-attachments/assets/0f6f9950-b346-4a7c-85c9-78b6f36202b9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@sanjaraiy  go ahead 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .

**Comment by Rakesh9100** [comment]
Can you pls tell for which screen dimension have you faced this issue @sanjaraiy

**Comment by sanjaraiy** [comment]
This issue occurs on screens larger than medium size.

**Comment by Rakesh9100** [comment]
Tell me the width and height of that screen, I need to check @sanjaraiy

**Comment by sanjaraiy** [comment]
approximate screen size - 1280 × 551
