### ISSUE TITLE
[Feature] Add On/Off Toggle Switch

### ISSUE THREAD

**Issue by thevijayshankersharma** [Rakesh9100/Beautiify#1259]
### Description

Create an interactive on/off toggle switch widget using HTML, CSS, and JavaScript. This widget allows users to toggle between two states with a simple click, enhancing user interface (UI) functionality on your website or web application.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by thevijayshankersharma** [comment]
@Rakesh9100 @saurabhsingh720

![image](https://github.com/user-attachments/assets/c29dcb15-c1f3-4f51-afb4-71c9d1d4cea5)

![image](https://github.com/user-attachments/assets/cbde6734-8e91-4f16-87af-f35c3bd49f80)

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new addition

**Comment by saurabhsingh720** [comment]
@thevijayshankersharma go ahead 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .
