### ISSUE TITLE
Add a Flipside button

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#126]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Adding a new button. plz assign it me to underswoc'24 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Which button you want to add? Name/type of that @GhoshAditi

**Comment by GhoshAditi** [comment]
Flipside button

**Comment by GhoshAditi** [comment]
Flipside button @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay, go ahead @GhoshAditi
