### ISSUE TITLE
[Feature] Gradient Card Component

### ISSUE THREAD

**Issue by thevijayshankersharma** [Rakesh9100/Beautiify#1260]
### Description

Implement a stylish and interactive gradient card component using HTML, CSS, and JavaScript. This component showcases structured content with a vibrant gradient background, making it suitable for highlighting featured items or information on your website. Customize the card's appearance and content easily to suit different design requirements and enhance user engagement with intuitive hover effects.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@thevijayshankersharma 
Please attach some img to show what u want to add.

**Comment by thevijayshankersharma** [comment]
@saurabhsingh720 Here is the image 

![image](https://github.com/user-attachments/assets/321ac392-784a-4e0e-ab66-9a1feff9a7c0)

**Comment by saurabhsingh720** [comment]
@thevijayshankersharma go ahead 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .
