### ISSUE TITLE
[Feature] Add Spooky Themed Hero

### ISSUE THREAD

**Issue by samarsajad** [Rakesh9100/Beautiify#1262]
### Description

A halloween themed hero section

### Screenshots

I would like to add a hero section like this 
![image](https://github.com/user-attachments/assets/a549b072-30f5-4b28-859d-8412c967dbef)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by samarsajad** [comment]
Please assign this to me @Rakesh9100

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new addition to hero section

**Comment by samarsajad** [comment]
Please assign this to me @Rakesh9100

**Comment by saurabhsingh720** [comment]
@samarsajad go ahead 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .
