### ISSUE TITLE
[Feature] Add Wavy Footer

### ISSUE THREAD

**Issue by DiwareNamrata23** [Rakesh9100/Beautiify#1266]
### Description

The responsive animated sea footer for a website .. The tech stack used for this website are html and css 

### Screenshots
<img width="1440" alt="Screenshot 2024-07-29 at 3 58 32 PM" src="https://github.com/user-attachments/assets/cb3af5fd-21d5-453c-bc7d-075d5ed679a4">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@DiwareNamrata23 go ahead 
I am assigning u
As admin is busy for some days
Do your task and provide your PR asap.
Then admin merge it with the proper labels .
