### ISSUE TITLE
[Feature] Add Confetti Button

### ISSUE THREAD

**Issue by VaishnaviMankala19** [Rakesh9100/Beautiify#1271]
### Description

A button that triggers a confetti animation when clicked.

### Screenshots

https://github.com/user-attachments/assets/48e3b665-7187-4d81-8d2c-9946c61080c6

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @VaishnaviMankala19

**Comment by Rakesh9100** [comment]
Provide your PR @VaishnaviMankala19

**Comment by Priyanshu-2005** [comment]
Hey @Rakesh9100 I would like to work on this issue kindly assign this issue to me

**Comment by aashlesha12** [comment]
I'm interested in working on issue #1271. I've already reviewed the issue description and believe I have the necessary skills to contribute.

Please let me know if you're open to assigning this to me.

**Comment by aashlesha12** [comment]
https://github.com/user-attachments/assets/92a80e5e-0934-487f-ace7-cb9d7e78df00

 I've created a video demonstrating my solution to the reported issue.
