### ISSUE TITLE
[Feature] Add Book Loader

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Rakesh9100/Beautiify#1282]
### Description

I want to add a book loader under the loader section.

### Screenshots

![Screenshot 2024-07-20 025507](https://github.com/user-attachments/assets/01b6d22a-d526-475c-ba1d-b1fe094b006e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @ParnaRoyChowdhury777

**Comment by Rakesh9100** [comment]
Provide your PR @ParnaRoyChowdhury777

**Comment by ParnaRoyChowdhury777** [comment]
> Provide your PR @ParnaRoyChowdhury777 

I will provide the PR within today night...
