### ISSUE TITLE
[Feature] Add Aurora Borealis Background

### ISSUE THREAD

**Issue by kosuri-indu** [Rakesh9100/Beautiify#1284]
### Description

I want to add Aurora Borealis Background which simulates the colorful, shifting lights of the Northern Lights

### Screenshots

https://github.com/user-attachments/assets/5935ce5b-253b-4d1a-92a4-b0e3922d28c3

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kosuri-indu** [comment]
@Rakesh9100 
Please assign this issue to me :)
Thank you

**Comment by kosuri-indu** [comment]
@Rakesh9100 
Sir could you give update on this issue?

**Comment by Rakesh9100** [comment]
Go ahead @kosuri-indu
