### ISSUE TITLE
[Feature] Add 3D Card Carousel

### ISSUE THREAD

**Issue by Archiesachin** [Rakesh9100/Beautiify#1287]
### Description

I want to add a 3D Card Caraousel in the caraousel section

### Screenshots

![Screenshot (1191)](https://github.com/user-attachments/assets/d5040460-29c9-44dc-a04d-9e225245071e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Archiesachin
