### ISSUE TITLE
[Feature] Add Squares Animation Background

### ISSUE THREAD

**Issue by Ajita369** [Rakesh9100/Beautiify#1289]
### Description

I want to add square animation background . Please assign me this task under GSSOC'24.

### Screenshots

![image](https://github.com/user-attachments/assets/4b86dfa1-6e14-4e1d-b577-fdc9c23ec3a3)
![image](https://github.com/user-attachments/assets/9ef10da1-ee06-49ab-8bac-3e70e1ff3f0f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Ajita369
