### ISSUE TITLE
[Feature] Add Lineup Card

### ISSUE THREAD

**Issue by ShouryaMishra2006** [Rakesh9100/Beautiify#1299]
### Description

professionals concerned about their productive works in their life needs a catchy schedule or time table so that they can take interest in looking and following or considering it . my card will contain the proper layout of their schedules.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the short and proper name of your card component @ShouryaMishra2006

**Comment by ShouryaMishra2006** [comment]
> What will be the short and proper name of your card component @ShouryaMishra2006

Lineup card

**Comment by ShouryaMishra2006** [comment]
please assign

**Comment by Rakesh9100** [comment]
Go ahead @ShouryaMishra2006
