### ISSUE TITLE
Add Open Graph Protocols and twitter tags

### ISSUE THREAD

**Issue by rakesh-vajrapu** [Rakesh9100/Beautiify#13]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add Open Graph Protocols and twitter tags to the website for efficient social media sharing. Please assign this issue to me @Rakesh9100 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Not needed for now. Pls work on other good issues @rakesh-vajrapu
