### ISSUE TITLE
Adding a "Hovering Spaced" Text Animation

### ISSUE THREAD

**Issue by NikmanGT** [Rakesh9100/Beautiify#130]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

To add a "Hovering Spaced" Text on the Text Animation Component section

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140642394/2c680ded-7d46-483b-8d69-9d0338082729

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @NikmanGT

**Comment by NikmanGT** [comment]
> Go ahead @NikmanGT

Thanks ❤️
