### ISSUE TITLE
[Feature] Add Ghost Button

### ISSUE THREAD

**Issue by Nayanika1402** [Rakesh9100/Beautiify#1315]
### Description

A ghost button is a type of button used in web design that is characterized by its minimalist and subtle appearance.

### Screenshots

![Screenshot 2024-08-01 235230](https://github.com/user-attachments/assets/ca28a1b0-1cbe-4152-acc9-5b5e73d606bb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What effect it has, pls show me the screenshot in the form of video/GIF @Nayanika1402

**Comment by Nayanika1402** [comment]
https://github.com/user-attachments/assets/2851b7a5-cb30-42e5-9989-b51bb7992a81

This is the sample video.

**Comment by Rakesh9100** [comment]
This is just the simple hover button, as I can see @Nayanika1402
