### ISSUE TITLE
[Feature] Add User Profile Tooltip

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/Beautiify#1316]
### Description

Display user information when hover the username

### Screenshots

![image](https://github.com/user-attachments/assets/f0a93d91-d826-464d-aa61-060a2e222c4d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DharshiBalasubramaniyam
