### ISSUE TITLE
[Feature] Add Send Message Button

### ISSUE THREAD

**Issue by Saipradyumnagoud** [Rakesh9100/Beautiify#1318]
### Description

Send Message button

### Screenshots

![image](https://github.com/user-attachments/assets/f1ffd08f-9fa2-472b-b9c0-890c9c8a2afb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@Rakesh9100 Can You Please assign me the issue

**Comment by Rakesh9100** [comment]
Pls show the effect of this button in the form of video/GIF @Saipradyumnagoud

**Comment by Saipradyumnagoud** [comment]
https://github.com/user-attachments/assets/18bfb783-4912-41f9-a0d3-62612d266f4b


here is the video

**Comment by Rakesh9100** [comment]
Go ahead @Saipradyumnagoud
