### ISSUE TITLE
[Feature] Add Alexa Styled Loader

### ISSUE THREAD

**Issue by vishanurag** [Rakesh9100/Beautiify#1332]
### Description

- I want to add a loader that looks like Alexa logo.

### Screenshots

Demo:

https://github.com/user-attachments/assets/94590303-6f0f-4cf2-82fa-278b179d2b58

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vishanurag** [comment]
@Rakesh9100 please assign this issue to me under GSSoC'24

**Comment by vishanurag** [comment]
@Rakesh9100 please assign this issue to me under GSSoC'24 🙏

**Comment by Rakesh9100** [comment]
Go ahead @vishanurag
