### ISSUE TITLE
[Feature] Add Zooming Text Animation

### ISSUE THREAD

**Issue by ShouryaMishra2006** [Rakesh9100/Beautiify#1336]
### Description

Text animations part would be incomplete without zooming text animation in which texts will be getting zoomed in and out to catch attention. Some important messages of the website should be written in that animation.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @ShouryaMishra2006
