### ISSUE TITLE
[BUG] : Outdated Twitter icon

### ISSUE THREAD

**Issue by SulagnaKundu** [Rakesh9100/Beautiify#134]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The twitter icon in the contact section is outdated and needs to be changed.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/103977344/4c689e45-a30a-4ac1-9d14-583a52f3b3c9)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @SulagnaKundu

**Comment by Rakesh9100** [comment]
@SulagnaKundu Provide your PR by today else you will be unassigned

**Comment by thatguywhocode** [comment]
Hello @Rakesh9100   , I would like to work on this issue under JWOC.

**Comment by Rakesh9100** [comment]
Go ahead @thatguywhocode

**Comment by thatguywhocode** [comment]
Hey @Rakesh9100 , i solved the bug and created the pr under JWOC.

**Comment by sksinha2410** [comment]
@Rakesh9100 I would like to work on this under JWOC
