### ISSUE TITLE
[Feature] Add Follow Along Cursor

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1341]
### Description

I want to add this minimalist follow along cursor that emphasizes the important contents on the page.

### Screenshots

https://github.com/user-attachments/assets/5bb50580-1f6a-4a8e-8d27-bb84ed308187

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Don't open too many issues at once, max 2 can be opened @Praneeth-2602

**Comment by Rakesh9100** [comment]
Don't open too many issues at once, max 2 can be opened, maintain the decorum of open-source @Praneeth-2602
