### ISSUE TITLE
[Feature] Add Nature Button

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#1343]
### Description

A button on hover the branches wave

### Screenshots

https://github.com/user-attachments/assets/ff121071-64dc-49d1-b3e5-78995c2f93ec

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Hey @Praneeth-2602 

Didn't you read my comment in issue #1341 !!
