### ISSUE TITLE
[Feature] Add 3D Crypto Coin Hero

### ISSUE THREAD

**Issue by Utsavladia** [Rakesh9100/Beautiify#1348]
### What's the style idea?

We need to add the interactive 3d coin hero section 

![image](https://github.com/user-attachments/assets/188401b6-67e0-4d10-a8d3-59df5d0d3219)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Utsavladia

**Comment by Utsavladia** [comment]
@Rakesh9100  Kindly merge this PR before GSSOC ends 😌
