### ISSUE TITLE
Footer Component 

### ISSUE THREAD

**Issue by Vedika-Agrawal** [Rakesh9100/Beautiify#137]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey @Rakesh9100 , I would like to add one more component ie Footer component  under Get Components.
And I also would like to work on this issue under JWoC 24.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Issues for JWoC will be assigned from 15th Jan, 2024 @Vedika-Agrawal 

Till then keep exploring the projects!! ✨

**Comment by Paarisha1** [comment]
can i contribute in this
