### ISSUE TITLE
[Feature Request]: Add Twitter Social Handle to Footer

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Rakesh9100/Beautiify#138]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This feature request is raised to enhance user engagement and connectivity by adding the official Twitter social handle to the footer of our home page. Providing easy access to our Twitter profile Assign me this user JWOC

### Screenshots

![Screenshot from 2024-01-11 01-44-27](https://github.com/Rakesh9100/Beautiify/assets/44281971/4663812d-0ad2-4bea-b1f9-0f8a019699be)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Issues for JWoC will be assigned from 15th Jan, 2024 @Vedika-Agrawal 

Till then keep exploring the projects!! ✨

**Comment by Rakesh9100** [comment]
Issues for JWoC will be assigned from 15th Jan, 2024 @NaveenChandraAdhikari 

Till then keep exploring the projects!! ✨

**Comment by NaveenChandraAdhikari** [comment]
So can you assign me this under SWOC'24

**Comment by Rakesh9100** [comment]
Okay proceed @NaveenChandraAdhikari
