### ISSUE TITLE
[Feature] Enhance the Card-Based Transfer List

### ISSUE THREAD

**Issue by coder2875** [Rakesh9100/Beautiify#1380]
### Description

The current one is very basic. There could be something like a card counter or search functionality.

### Checklist

- [X] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aashlesha12** [comment]
I'm interested in working on issue #1380. I've already reviewed the issue description and believe I have the necessary skills to contribute.

Please let me know if you're open to assigning this to me.

**Comment by aashlesha12** [comment]
I've created a video demonstrating my solution to the reported issue.
https://github.com/user-attachments/assets/a227ef1a-7147-40f1-a604-31a34be2e9b4

**Comment by aashlesha12** [comment]
I've created a video demonstrating my solution to the reported issue.

https://github.com/user-attachments/assets/ea0465c0-1a66-4aec-8b89-89f0a37622af

**Comment by aashlesha12** [comment]
https://github.com/user-attachments/assets/c4fa00c9-f68e-41cf-a8a4-3770d5313825

Here's the solution that I've created for the reported issue.
