### ISSUE TITLE
[Feature] Display contributor name on hover over contributor icons

### ISSUE THREAD

**Issue by saadgibawa** [Rakesh9100/Beautiify#1382]
### Description

 I would like to suggest a simple yet meaningful enhancement for the contributors' page of this project. The current page displays profile icons of all contributors, which works well for those with recognizable avatars. However, contributors who do not have a profile picture or use default avatars might go unnoticed.
I would like to add a tooltip to each contributor’s profile icon that displays the contributor's GitHub username when the user hovers over the icon. This feature would provide a better user experience, ensuring all contributors are properly recognized, and making the contributors' page more informative and complete.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you currently want to work on this and resolve it @saadgibawa

**Comment by saadgibawa** [comment]
@Rakesh9100 Yes, I want to work on this

**Comment by Rakesh9100** [comment]
Go ahead @saadgibawa

**Comment by Rakesh9100** [comment]
Any update of your PR @saadgibawa

**Comment by saadgibawa** [comment]
I'm working on it and will raise a PR when finished

**Comment by abhirajadhikary06** [comment]
@saadgibawa You took up an awesome part of work. I am eager to know if you are writing the contributor's name individually or using Github's API to fetch the usernames ?
