### ISSUE TITLE
[Bug] Gap Between Custom Cursor and Pointer

### ISSUE THREAD

**Issue by coder2875** [Rakesh9100/Beautiify#1384]
### Description

The custom cursor has a noticeable gap from the actual mouse pointer. This gap needs to be fixed so the cursor follows the mouse pointer closely.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aashlesha12** [comment]
I'm interested in working on issue #1384. I've already reviewed the issue description and believe I have the necessary skills to contribute.

Please let me know if you're open to assigning this to me.

**Comment by aashlesha12** [comment]
https://github.com/user-attachments/assets/747744a7-06b7-4c37-8c84-168f28acb423

Here's the solution that I've created for the reported issue.
