### ISSUE TITLE
[Feature] Add Infinite Scroll Emoji Background

### ISSUE THREAD

**Issue by abhirajadhikary06** [Rakesh9100/Beautiify#1388]
### Description

**Add a new theme to the Background category**

Please add KWOC to the checklist

### Screenshots

![image](https://github.com/user-attachments/assets/cd2857e3-d8bd-4070-9294-9ec3f1ce860d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by abhirajadhikary06** [comment]
@Rakesh9100 Please assign the issue to me. and also please fix the checkbox and add KWOC in the options.

**Comment by Rakesh9100** [comment]
What kind of theme do you want to add @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
I want to add a theme of infinitely scrolling emojis. I am attaching a screenshot of the same
![image](https://github.com/user-attachments/assets/bada2cc8-01b6-4e8c-bbb6-d60c81603d65)

**Comment by Rakesh9100** [comment]
Okay, so you want to add a new background component? @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
Yes..you are right

**Comment by Rakesh9100** [comment]
What will be the proper name of this component @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
**Infinite Scroll Emoji Background**
Maybe the above name suits best

**Comment by Rakesh9100** [comment]
Okay, proceed @abhirajadhikary06
