### ISSUE TITLE
[Style] Enhance the footer UI

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Rakesh9100/Beautiify#1389]
### Description

 in your website i want to implement some featurees:
1. added logo to footer
2. added underline animation and hover effect to all nav items
3. justified their aligned give them a proper space
4. make all heading tag more engagging by adding some colorful animation

### Screenshots

![WhatsApp Image 2024-12-08 at 12 48 55_7810b663](https://github.com/user-attachments/assets/b01f1e74-9b25-4f19-a41c-f8338b4c16ce)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Atharvverma1234** [comment]
Hi, I would like to work on this issue. Please assign it to me. Thank you!

**Comment by Rakesh9100** [comment]
Go ahead @biswajit-sarkar-007

**Comment by Rakesh9100** [comment]
Please complete your assigned issue first @biswajit-sarkar-007
