### ISSUE TITLE
[Style] Enhance the contact form

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Rakesh9100/Beautiify#1390]
### Description

in your website at contact from section i have notched some implement should be done like:
1.the contact information are not decorated properly like there is lack of animation 
2. the URL link and website icons are not aligned properly
3. and the social icons are not in the right position 

this features improve the UI of contact section to make more engaging to the users.

### Screenshots

![WhatsApp Image 2024-12-08 at 12 57 22_dd4ef97b](https://github.com/user-attachments/assets/e7b549d1-fe2f-42bb-a9d8-80007fa1f61f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @biswajit-sarkar-007
