### ISSUE TITLE
[Feature] Add Error Pages Category and a Component

### ISSUE THREAD

**Issue by abhirajadhikary06** [Rakesh9100/Beautiify#1398]
### What would you like to share?

It would be great if there were components for different kinds of Error Pages like 404, 500 etc.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you also plan to add any components inside that @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
Yes like different designs of 404 error page.

**Comment by Rakesh9100** [comment]
Okay, the html page just you can copy the other category html page and make the changes accordingly, and also add 2-3 error pages components in this. Make sure no extra functionality changes to be done @abhirajadhikary06
