### ISSUE TITLE
[Bug] Fix the inconsistent text input color in footer

### ISSUE THREAD

**Issue by Atharvverma1234** [Rakesh9100/Beautiify#1400]
### Description

The inputted text color in the message input box differs from the other input fields. Specifically, the text entered into the message box appears yellow, while the text in the other input fields appears black. This inconsistency affects the uniformity of the user experience and might confuse users as the visibility of the inputted text is less.

### Screenshots

![Screenshot 2024-12-10 213521](https://github.com/user-attachments/assets/527a1183-bcae-441d-8a1a-f62b6ec12663)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Atharvverma1234
