### ISSUE TITLE
[Feature] Improve UI 

### ISSUE THREAD

**Issue by Archi-shaw** [Rakesh9100/Beautiify#1401]
### Description

It would look better if Contact Us is in the middle, quick links on the left and the description on the right...

### Screenshots

[
![Screenshot 2024-12-11 025315](https://github.com/user-attachments/assets/7889cdcc-647e-4240-9e3c-ca1b8587d842)
](url)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Archi-shaw** [comment]
@Rakesh9100 Please assign this issue to mee.

**Comment by Rakesh9100** [comment]
Why do you think like this, any reason behind this @Archi-shaw

**Comment by Archi-shaw** [comment]
@Rakesh9100 Thanks for your feedback! I thought centering the 'Contact Us' section would draw more attention to it, as it's a key action for users. Placing the Quick Links on the left aligns with common web design practices, as users often expect navigation elements in this position. The description on the right would help create a balanced and visually appealing layout, keeping functional and informational content distinct. However, I completely understand if the current design works well for you, and I’m open to further adjustments based on your preferences!

**Comment by Rakesh9100** [comment]
I don't think we need this change, please work on other good issues @Archi-shaw
