### ISSUE TITLE
[Bug] Fix the contact form responsiveness

### ISSUE THREAD

**Issue by sammy0318** [Rakesh9100/Beautiify#1406]
### Description

🐞 Bug Report: Text Area Scrollbar on smaller screens

Issue:-
The text area on the form is currently displaying a scrollbar on smaller screens, which makes it look cluttered and affects the user experience. Users may find it difficult to view and edit their message due to limited space within the text area.

Fix:-
Increase the height of the text area to ensure that users can view and edit their entire message without needing to scroll. Additionally, apply appropriate padding within the text area to improve spacing and make the input feel more spacious and user-friendly.

@Rakesh9100 Sir please assign this issue to me ...

### Screenshots

![bug](https://github.com/user-attachments/assets/bc3d13e7-b2d8-4a05-8734-11ee79813ba4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead, you can also increase width and center align the form inputs @sammy0318
