### ISSUE TITLE
Add footer in all the components category page

### ISSUE THREAD

**Issue by sammy0318** [Rakesh9100/Beautiify#1409]
### Description

Their are no footers in any of the components pages , would like to add footer on every component page.
@Rakesh9100 Sir please assign this issue to me .

### Screenshots

![Screenshot (860)](https://github.com/user-attachments/assets/ebba8052-6ede-4ede-9eee-fae9b93a5630)
![Screenshot (861)](https://github.com/user-attachments/assets/744092be-ccbe-4262-8f17-6fa34e562c89)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Why are you creating a new issue again if already an issue is opened for this, and you have commented on that @sammy0318
