### ISSUE TITLE
Adding Customizable Progress Loader

### ISSUE THREAD

**Issue by sanketshinde3001** [Rakesh9100/Beautiify#141]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

*This is Highly Customizable Progress Loader , where user can change both percentage of completion or time of animation as per requirement. Also the inside number is in sync with outer animation so it looks attractive to watch. Also added neomorphism effect to loader.

*where we can use ?
- Sometimes in websites we need to show progress of work or progress of our project.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/126979961/c505a2b7-dac6-4636-b7a7-f0ba5066421f)

https://github.com/Rakesh9100/Beautiify/assets/126979961/542665c4-12be-4653-88ca-0083f31c4e14

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Do you want to add this under Loaders category as one of the component @sanketshinde3001

**Comment by sanketshinde3001** [comment]
Yes. 
Want to add it under loader category as component

**Comment by Rakesh9100** [comment]
Okay go ahead @sanketshinde3001
