### ISSUE TITLE
[Style] Make Neumorphism Accordion component responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1410]
### We need to improve the responsiveness of Neumorphism Accordion. The heading text is not properly fit for small devices.

![image](https://github.com/user-attachments/assets/23dcf997-e614-4361-90b6-5c150becdf7f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ThePhoenix08** [comment]
Hey, could you please assign me this issue, I am student contributor in KWoC, I would like to work on this issue.

**Comment by Rakesh9100** [comment]
Go ahead @ThePhoenix08
