### ISSUE TITLE
[Style] Make Abstract Particle Swarm Background component responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1411]
### We need to improve the responsiveness of Abstract Particle Swarm Background component for small devices.

![image](https://github.com/user-attachments/assets/553fb5f6-74dd-4ad7-90f5-a47c35dabedf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ThePhoenix08** [comment]
Hey, I think I can work on this issue, I did some testing in my local environment, I propose using the getClientBoundingRect() and a window onResize event listerner to make the canvas.width and canvas.height update dynamically everytime window viewport changes, additionally use css to make the width height of the canvas 100vw and 100vh to take the complete viewport, that way it will spread to the complete screen on mobiles aswell. I would request you to assign me this issue aswell if possible.

**Comment by Rakesh9100** [comment]
Please complete your assigned issue first @ThePhoenix08

**Comment by Rakesh9100** [comment]
Go ahead @ThePhoenix08
