### ISSUE TITLE
[Style] Make 404 Error Card component responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1412]
### We need to improve the responsiveness of 404 Error Card component present in Cards category.

![image](https://github.com/user-attachments/assets/136ee461-f93e-41d5-a7d2-fdfd61c41acf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by 712Kunal** [comment]
I am a KWOC'24 contributor, Kindly assign me the issue. I had also made the error card component responsive, with your permission can I make a pull request on the same ?

**Comment by Rakesh9100** [comment]
GO ahead @712Kunal

**Comment by Rakesh9100** [comment]
Go ahead @712Kunal
