### ISSUE TITLE
[Style] Make Animated Login Register Form component responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1418]
### We need to improve the responsiveness of Animated Login Register Form component for every device properly.

![image](https://github.com/user-attachments/assets/271ac29d-a5ee-4989-abf0-8ab6862b9a62)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by jitendrasuthar1998** [comment]
@Rakesh9100 I would like to work on this issue.
Can you please assign this issue to me?
I am participating in KWOC.
