### ISSUE TITLE
[Style] Make Animated Login/Signup Form component responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1419]
### We need to improve the responsiveness of Animated Login/Signup Form component for every device properly.

![image](https://github.com/user-attachments/assets/a2eef151-5e07-4f54-b2d8-124ee1c6e388)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by 712Kunal** [comment]
@Rakesh9100 I am KWOC'24 contributor, Kindly assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @712Kunal
