### ISSUE TITLE
Add 3D Animated Accordion

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#142]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello, I'd like to add a 3d animated accordion please assign it to me under SWOC'24.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @rishicds
