### ISSUE TITLE
[Style] Make Slide Login Register Form component responsive

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#1420]
### We need to improve the responsiveness of `Slide Login Register Form` component for every screen sizes, with centering the content for small devices.

![image](https://github.com/user-attachments/assets/7a495bee-e91e-4a14-8e65-93b4d68abc85)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by 712Kunal** [comment]
I am a KWOC'24 contributor, please kindly assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @712Kunal
