### ISSUE TITLE
[Bug] Fix the rate limit exceed of GitHub API on contributors page

### ISSUE THREAD

**Issue by ThePhoenix08** [Rakesh9100/Beautiify#1423]
### Description

Rate Limit of GitHub API is getting exceeded while loading individual avatars and names of the contributors on the contributors page of the application.
I diagnosed this in my local testing is being caused by following lines
```javascript
...
fetch(contributor.url)
 .then(contributorDetails => contributorDetails.json())
 .then(contributorData => {
     const displayName = contributorData.name || contributor.login;
...
```
As we can see, for each contributor specific contributor data is being fetched and loaded as contributorData but all it is being used as in the document is for the display name of the individual. Large amounts of fetch requests and rate limiting error issue can be avoided by not fetching this contributor.url for just the "name" of the contributor and instead using the already in use as fallback contributor.login that is the username as display name for all users. Either way the rate limit results in most of the contributors display names being fallback to username only.

So I propose the following improvements
- Remove the contributor.url fetch and use contributor.login as username
- Implement lazy loading for avatars of the contributors
- Introduce an avatar fallback icon / svg if avatar fetch fails or is loading
- Implement infinite scroll functionality so that number of queries can be further reduced. Infinite scroll methodology will only fetch further contributors on scroll to fill the viewport.
- Add contributions count bubble on avatars top right corner which show how many contributions they did to the repo, its available in the data we fetch but is not in use.

### Screenshots

Developer tools > Network tab:
![Screenshot 2024-12-23 121801](https://github.com/user-attachments/assets/df4bde62-42f5-4d3f-84a7-7b5d0fb4f0cd)

Developer tools > Console
![Screenshot 2024-12-23 121746](https://github.com/user-attachments/assets/84b35b64-0303-4a93-8dee-b0c77c97b99b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Please go ahead @ThePhoenix08
