### ISSUE TITLE
Addition of colour drop animation background

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#144]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

would like to add a new background.
please assign it to me under swoc'24

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100  thank you 😊
