### ISSUE TITLE
Addition of smooth scrolling transition

### ISSUE THREAD

**Issue by Souvik34** [Rakesh9100/Beautiify#146]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add the smooth scrolling effect

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls describe your issue more and for which program you want to work @Souvik34
