### ISSUE TITLE
Add a Frosted Glass Loader

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/Beautiify#147]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to add a frosted glass loader under the loader components.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by bhavya-anand19** [comment]
@Rakesh9100 Should I provide some demo image?

**Comment by Rakesh9100** [comment]
Proceed @bhavya-anand19 

Will see screenshots in the PR, don't worry.

**Comment by Rakesh9100** [comment]
@bhavya-anand19 Status of your PR

**Comment by bhavya-anand19** [comment]
> @bhavya-anand19 Status of your PR

It will be completed by tomorrow.
