### ISSUE TITLE
Adding a Request Feature Page 

### ISSUE THREAD

**Issue by divyansh2375** [Rakesh9100/Beautiify#149]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a request page where if anyone requests to add any new things related to css so he or she can fill that form and so that we can build the stuff for them also . @Rakesh9100 can i work on this task ?

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
A contact form is already present on the website. And feature opening issue is available on github. So I don't think a seperate request page is required. Pls work on other good issues @divyansh2375 

If you have any further comments, let me know.
