### ISSUE TITLE
Add animated Breadcrumb

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#152]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I wish to add an animated breadcrumb.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/83c37330-ce6c-49a7-a14a-b4d553a4ed96)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead, Use good UI @rishicds

**Comment by Rakesh9100** [comment]
Hey @rishicds Same issue already exist. Pls work on other new issues.

**Comment by rishicds** [comment]
Okay np @Rakesh9100

**Comment by rishicds** [comment]
What if I use a different design? @Rakesh9100

**Comment by Rakesh9100** [comment]
You can edit this issue title and description for adding some other feature if you want to @rishicds

**Comment by rishicds** [comment]
Okay I'll edit this after the loader one @Rakesh9100
