### ISSUE TITLE
Flipping Text Loader

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#154]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hi, I'd like to add a flipping text loader, please assign it to me under SWOC'24.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/6d71b6c2-aaf7-4477-9e77-4ea219acaa53)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Okay proceed @rishicds
