### ISSUE TITLE
Adding a chatbot

### ISSUE THREAD

**Issue by manya975** [Rakesh9100/Beautiify#156]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

This issue is regarding a chatbot that will further explain the components or any doubt regarding the website for making it more user friendly website

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by manya975** [comment]
@Rakesh9100 I would love to work on this issue

**Comment by Rakesh9100** [comment]
Pls describe your idea more precisely about how your work of action would be after getting assigned @manya975 

And you will work for which program?

**Comment by praptisharma28** [comment]
@Rakesh9100 , assign me this under iwoc2024 & hard, I will use TIDIO to add a chatbot to your site. I will add it in the bottom right corner and it will open like a pop up, I have done this earlier.

**Comment by manya975** [comment]
@Rakesh9100 I will add a option an option for chatbot on every page like on the main page,it will help help people to summarise or explain what this website is for and what are it's feature and inside other panels like components it'll explain that what each component is actually for.Can you please elaborate like what do you mean by 'which program '

**Comment by Rakesh9100** [comment]
For which open source program you would like to work for and have created this issue? `SWOC or IWOC or JWOC` @manya975

**Comment by manya975** [comment]
Hi @Rakesh9100 . I would like to work on this for SWOC 24. I'll use botpress for making the chatbot. Using botpress we can add website data to that as well. So can you please assign me this issue?

**Comment by Rakesh9100** [comment]
Okay, go ahead @manya975

**Comment by manya975** [comment]
Thank you @Rakesh9100
