### ISSUE TITLE
Changing background

### ISSUE THREAD

**Issue by kshitigambhir** [Rakesh9100/Beautiify#160]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

each time the page reloads the background will change

### Screenshots

![Screenshot (104)](https://github.com/Rakesh9100/Beautiify/assets/134823553/0d2d2bcf-a5bd-4846-9d6d-2314510fc3b8)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
The current UI is good. Pls work on other issues @kshitigambhir
