### ISSUE TITLE
I want to add a back to top button

### ISSUE THREAD

**Issue by Babunshil** [Rakesh9100/Beautiify#161]
### Description

It has some motion on hover 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/106283743/9500ceb3-110c-4193-af2b-3442eb909d83)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
For which program you want to work @Babunshil

**Comment by rahat2134** [comment]
@Rakesh9100 assign this to me under jwoc

**Comment by rahat2134** [comment]
@Rakesh9100 i want to work on this issue, want to add back to top button

**Comment by Rakesh9100** [comment]
Issues for JWoC will be assigned from 15th Jan, 2024 @rahat2134 

Till then keep exploring the projects!! ✨
