### ISSUE TITLE
[Bug] Card componet causing unresponsiveness on mobile screen

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#163]
### Description

The card component in the website has extra width, which is overflowing content outside the main div, hence causing unresponsiveness on a mobile screen.
The size needs to be fixed in small screen media queries .

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/ce6be610-c31a-4a1e-8b5c-7534a0645ecc)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Assigning but make sure to do responsive changes for the small screens @pb0126
