### ISSUE TITLE
[Feature] Adding neumorphic buttons

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#165]
### Description

In the buttons section under the components, I want to add a new type of button, a neumorphic button. Please assign me this issue under IWOC'24. 

### Screenshots

<img width="1358" alt="Screenshot 2024-01-12 at 9 36 16 PM" src="https://github.com/Rakesh9100/Beautiify/assets/86418216/ccbe7206-6a5a-4f12-90f1-5dbb41afc466">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 made the PR for neumorphic buttons. Please check.
