### ISSUE TITLE
Simple Carousel right button Incorrectly working [BUG]

### ISSUE THREAD

**Issue by dhruvdy** [Rakesh9100/Beautiify#17]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Simple Carousel right button is not working correctly. There is something wrong with the button

### Screenshots

![Bug](https://github.com/Rakesh9100/Beautiify/assets/72575065/5f3b63d0-aaa6-41fd-8e0d-92c4c2d7e996)
When you click a little towards left from the center of the button then only it works.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed!! @dhruvdy
