### ISSUE TITLE
[Feature] Overlay Navigation Bar

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#173]
### Description

I want to add an overlay navigation bar in your navbar collections .!!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Edit your issue description and just tick that program for which you have created this issue for @AbhineshJha

**Comment by AbhineshJha** [comment]
Done sir @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay go ahead @AbhineshJha
