### ISSUE TITLE
[Feature] Add Search Bar for searching components

### ISSUE THREAD

**Issue by divyansh2375** [Rakesh9100/Beautiify#174]
### What would you like to share?

@Rakesh9100  we can add a search bar on the front page of beatify where people can search their css element by their own choice . i haven't done work on this feature before but i can try ? should we do this?

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Okay go ahead and give a try @divyansh2375

**Comment by Rakesh9100** [comment]
Status of your PR @divyansh2375

**Comment by divyansh2375** [comment]
i will be  completing it within next two days

**Comment by divyansh2375** [comment]
![Screenshot (302)](https://github.com/Rakesh9100/Beautiify/assets/130889408/c377d9ad-c6a6-4b40-a15f-8ca3d57ffdcb)
Working on the javascript part where it will filter the components

**Comment by Rakesh9100** [comment]
Provide your PR by today EOD else you will be unassigned @divyansh2375

**Comment by divyansh2375** [comment]
Sir i have college going on so i am not getting so much time give me
atleast 1 week time to build this feature because this search bar feature
is not that easy like html css for me . It requires JS. I have written the
logic code but all i need to work it on home page .

**Comment by Rakesh9100** [comment]
I can't provide you with one week. You will be unassigned!! @divyansh2375

**Comment by divyansh2375** [comment]
Ok then i will try to make it today . Otherwise i can push search bar made
up of html css only and after that i can work with JS . What you say?

**Comment by Rakesh9100** [comment]
No, don't push incomplete work @divyansh2375 

I have to give chance to other contributors.

**Comment by divyansh2375** [comment]
Ok then i will be completing it by today

**Comment by pranjal12-web** [comment]
@Rakesh9100  Can you please assign this issue to me ?

**Comment by Rakesh9100** [comment]
Provide the brief idea of what enhancement and how you will implement this @pranjal12-web

**Comment by pranjal12-web** [comment]
**Case-insensitive search:** Allow users to search regardless of the case. 

**Real-time filtering:** Instead of waiting for the user to finish typing and then triggering the search, we can implement real-time filtering to update the results instantly as the user types.

**Highlight matched text:** Highlight the matched text in the components to make it more visually appealing.

I will implement this using html,css and js

**Comment by Rakesh9100** [comment]
Go ahead @pranjal12-web

**Comment by Rakesh9100** [comment]
You want to work for which open source program @pranjal12-web

**Comment by pranjal12-web** [comment]
JWoC 24

**Comment by Rakesh9100** [comment]
Pls make the proper comment required to work for JWOC @pranjal12-web

**Comment by Rakesh9100** [comment]
Go ahead @pranjal12-web
