### ISSUE TITLE
[Bug] Contact Form component not responsive on small devices

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#175]
### Description

The 1st contact form in the forms section is not responsive below large screens, the content is set aside to one side when seeing the website in smaller screens.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/773da3f3-e464-48ff-8815-df2699404328)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Okay proceed @pb0126

**Comment by Rakesh9100** [comment]
@pb0126 Status of your PR

**Comment by pb0126** [comment]
Hi @Rakesh9100, I'm borrowing some extra time as I have to look into every element for responsiveness. None of the elements is configured according to the mobile screen, so it is taking much longer than expected.
Apologies for the delay. Will get back to you asap.

**Comment by Rakesh9100** [comment]
Alright @pb0126
