### ISSUE TITLE
[Feature] Add a animated searchbar in the search-bar category

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#176]
### Description

I want to add an animated searchbar (which transforms between a search icon and a custom search bar) in the newly added section of Custom Search Bars under Components. Please assign me this issue under @ IWOC 2.0 @ 2k24

### Video Demo

https://github.com/Rakesh9100/Beautiify/assets/86418216/863832e4-03eb-4754-8540-212004b9e147

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 made the PR for the animated searchbar
