### ISSUE TITLE
[Feature] Add Revolving 3D sphere Text animation

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#177]
### Description

I want to add a new text animation Under Components, which includes a revolving 3D sphere containing a list of texts that rotate faster/slower on mouse hover. Please assign me this issue under @ IWOC 2.0 @ 2k24

### Video Demo

https://github.com/Rakesh9100/Beautiify/assets/86418216/78ece031-66e5-4110-8b29-125af92907fc

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
Hi @Rakesh9100 made the PR for adding a Revolving 3D sphere containing a list of texts
