### ISSUE TITLE
Adding a numbered Nav Bar

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#178]
### Description

I have created a numbered Nav Bar in my previous project that I would like to add in this website under the nav bar component.

### Screenshots

![numbered navbar](https://github.com/Rakesh9100/Beautiify/assets/125905089/3b354f3b-20dc-413b-b38d-cb069c70dcdf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Okay go ahead @saurav2208

**Comment by Rakesh9100** [comment]
Status of your PR @saurav2208
