### ISSUE TITLE
Adding a pipeline animation background

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#179]
### Description

I would like to add a pipeline animation background under background component. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @saurav2208

**Comment by Rakesh9100** [comment]
Status of your PR @saurav2208
