### ISSUE TITLE
Adding Hover effect on all boxes

### ISSUE THREAD

**Issue by sanketshinde3001** [Rakesh9100/Beautiify#18]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Currently there is hover effect only in index page which is tilt animation . Instead i'll add zoom in effect which looks better.
Also adding to inside boxes too.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Hover effect is already present. Pls work on other good issues @sanketshinde3001
