### ISSUE TITLE
Adding a 3-D reveal side bar menu

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/Beautiify#180]
### Description

I would like to add a 3-D reveal sidebar Menu under Nav bar component.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @bhavya-anand19
