### ISSUE TITLE
[Feature] Adding an Elastic Side Navigation Bar

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#181]
### Description

I wish to add an elastic side-bar menu inside the nav bar component.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurav2208** [comment]
@Rakesh9100 As I have completed the previous assignments, can I start working?

**Comment by Rakesh9100** [comment]
Sure @saurav2208

**Comment by Rakesh9100** [comment]
Status of your PR @saurav2208

**Comment by Rakesh9100** [comment]
Should I close the issue @saurav2208

**Comment by saurav2208** [comment]
> Should I close the issue @saurav2208

No no.. I'm working on it. Will be done by tomorrow

**Comment by Rakesh9100** [comment]
You will be unassigned if PR is not up by today @saurav2208
