### ISSUE TITLE
[Feature] Adding Animated Infinity Loader

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#182]
### Description

I would like to add an animated infinity loader under the loaders component

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete the assigned issues first @saurav2208

**Comment by saurav2208** [comment]
@Rakesh9100 As my previous assignments are done, should I start working on this issue?

**Comment by Rakesh9100** [comment]
Update of your PR @saurav2208

**Comment by Rakesh9100** [comment]
Should I close the issue @saurav2208

**Comment by saurav2208** [comment]
> Should I close the issue @saurav2208

I'm working on it. Will be completed by tomorrow

**Comment by Rakesh9100** [comment]
You should provide me update atleast if asked for the status 2 days ago @saurav2208

**Comment by saurav2208** [comment]
> You should provide me update atleast if asked for the status 2 days ago @saurav2208

Actually there was some issues with my laptop. Will be active again from now.

**Comment by Rakesh9100** [comment]
You will be unassigned if PR is not up by today @saurav2208
