### ISSUE TITLE
Adding an "Animated Triangles" Background

### ISSUE THREAD

**Issue by NikmanGT** [Rakesh9100/Beautiify#186]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

To add an "Animated Triangles" background on the Backgrounds Component section

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140642394/290f268b-b2a2-4286-a4c5-a0a992d07b17

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @NikmanGT
