### ISSUE TITLE
Making Website Responsive

### ISSUE THREAD

**Issue by sanketshinde3001** [Rakesh9100/Beautiify#19]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I'll make this website responsive which can improve its UI for both PC and Mobile User.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Do you want to work @sanketshinde3001

**Comment by sanketshinde3001** [comment]
Yes sure 😄

**Comment by Rakesh9100** [comment]
Pls wait for sometime as new UI is being ready by other contributor. Once it is ready, will assign you @sanketshinde3001

**Comment by sanketshinde3001** [comment]
Sure

**Comment by Rakesh9100** [comment]
@sanketshinde3001 Status of your work

**Comment by sanketshinde3001** [comment]
ongoing , till tonight i'll make PR.
