### ISSUE TITLE
Adding a Clock Loader

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#191]
### Description

It is a loader designed like a clock, with rotating clock hands indicating the loading progress.
Please assign me this issue under IWOC

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Dhairya1Gupta

**Comment by Sakshamjain98** [comment]
sir please assign this issue to me
