### ISSUE TITLE
[Feature] Horizontal Nav Bar

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#195]
### Description

Placed horizontally across the top of the webpage.
Dropdown menus may be used to organize subcategories.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha

**Comment by Rakesh9100** [comment]
Can you show screenshot of navbar you will add as a component @AbhineshJha

**Comment by Paarisha1** [comment]
can i contribute in this under swoc

**Comment by Rakesh9100** [comment]
You can raise new issues and contribute to this project under SWOC for sure @Paarisha1

**Comment by AbhineshJha** [comment]
here it is ..>>>
![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/3836d37c-a9ed-4a41-a540-dfe66e5ab9d5)

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
