### ISSUE TITLE
[Feature] Adding Mask Hover Animation buttons 

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/Beautiify#196]
### Description
- Adding Mask Hover Animation to Button under the Buttons category , under the IWOC Event.

### Screenshots

[Screencast from 14-01-24 01:17:49 PM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/114584730/b1bc22ea-2ea4-4bf6-b925-0aa86330a10a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Tholkappiar
