### ISSUE TITLE
Adding a new Timeline Card

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#198]
### Description

It will have a Interactive card that displays a timeline of events. Pls assign me this under IWOC @ 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue and fix the error on your PR first @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
Please Assign me this issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Complete you issue #191 first @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
OK  @Rakesh9100 

> Complete you issue #191 first @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
Completed previous PRs .Please assign me this  issue @Rakesh9100

**Comment by Rakesh9100** [comment]
You want to add this component in which category? @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
> You want to add this component in which category? @Dhairya1Gupta

It will be under Cards Category @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
Please add difficulty level medium/hard @Rakesh9100
