### ISSUE TITLE
In Cards section , want to add neumorphism Card type

### ISSUE THREAD

**Issue by sanketshinde3001** [Rakesh9100/Beautiify#20]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add neumorphism card for it..
here is example - 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/126979961/adfe2f83-efae-44fe-be69-711e9f4f2c1f)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed!! @sanketshinde3001

**Comment by sanketshinde3001** [comment]
![image](https://github.com/Rakesh9100/Beautiify/assets/126979961/52276aa5-3ebb-4303-bcc9-ab9cedf42952)

![image](https://github.com/Rakesh9100/Beautiify/assets/126979961/30bb4401-e2af-47d1-94c6-578308ba5718)

* Added Four Types of Neumorphism Card , User can simply can copy style and use it , simple...
* Also made this page responsive.

**Comment by sanketshinde3001** [comment]
In code , I commented it very well so that user don't get confuse to find code.
