### ISSUE TITLE
[Feature] Scroll Triggered Navigation Bar

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#203]
### Description

Similar to fixed, but becomes visible only after the user scrolls down a certain distance.

Maximizes screen real estate when not in use.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142514166/9b28d739-8055-454d-8ba3-ad4845dafa9f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by hemant933** [comment]
i get what u want assign it to me

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
