### ISSUE TITLE
[Feature] : New component For footers

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#207]
### Description

We can create **new section** of **components** for different types of **footers**.

Every Website has a footer in which the give their **social media acounts** , information of website and  other information.

This feature will help users to create their footers and the will get different ideas as new footers will be added to it in future.

I will add a footer of website  i had already made  in that component  its **screenshot is attached**.

While creating it i will follow the structure of files/folders created for website i will not disturbe it.

Kindly assign this issue to me under IWOC2024.

### Screenshots

![Screenshot 2024-01-14 222732](https://github.com/Rakesh9100/Beautiify/assets/149922307/45d77c74-3c85-42a0-8ee3-2d68122dc943)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Good, go ahead @Prince-kushwaha-2004
