### ISSUE TITLE
Adding Payment Form in Forms category

### ISSUE THREAD

**Issue by Prithwi32** [Rakesh9100/Beautiify#209]
### Description

@Rakesh9100  I would like to work on this under JWOC

### Screenshots

![Screenshot 2024-01-15 001043](https://github.com/Rakesh9100/Beautiify/assets/115262737/62298072-7682-42c7-bf40-70010d332581)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
WHere do you want to add this? @Prithwi32

**Comment by Prithwi32** [comment]
> WHere do you want to add this? @Prithwi32

in form section

**Comment by Rakesh9100** [comment]
Okay proceed @Prithwi32

**Comment by sksinha2410** [comment]
@Rakesh9100 I would like to work on this under JWOC

**Comment by Prithwi32** [comment]
@Rakesh9100 please can you review this PR
