### ISSUE TITLE
In Button section want to add one more button: Gradient Button

### ISSUE THREAD

**Issue by sinha-sanchay** [Rakesh9100/Beautiify#21]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add one more button (Gradient button) in button section. 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140732561/52ee1bdc-659d-4f7c-b03f-81f55ceb848a

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed!! @sinha-sanchay
