### ISSUE TITLE
[Feature] Adding Flip Text Animation

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/Beautiify#211]
### Description

Adding Text Flip  Animation to Text under the Text-Animations category , under the IWOC Event.

### Screenshots

[Screencast from 15-01-24 11:08:47 AM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/114584730/55e10c73-34c4-4138-8947-94b5c23c51da)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Tholkappiar 

Name your folder as `Flip-2 Text Animation` @Tholkappiar
