### ISSUE TITLE
[Feature] Addition Of Rotating Squares Loader

### ISSUE THREAD

**Issue by SohanRC** [Rakesh9100/Beautiify#213]
### Description

Want to add a new loader in the loader component section. Assign this issue under JWOC 2024.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
This issue of opening box loader is already open. Pls edit the issue title and open new issues @SohanRC

**Comment by Rakesh9100** [comment]
Describe or mention properly which new components you want to add @SohanRC

**Comment by sksinha2410** [comment]
@Rakesh9100 I would like to work on this under JWOC

**Comment by SohanRC** [comment]
@Rakesh9100 I would like to add a new loader component in the loader section .  I am attaching the image below. Please assign me this issue under JWOC 2024.
![Screenshot 2024-01-15 194653](https://github.com/Rakesh9100/Beautiify/assets/124901633/abc0979a-6440-4bb9-a077-01a48a5c6e78)

**Comment by SohanRC** [comment]
@Rakesh9100 I would like to add a new loader component in the loader component section. I am attaching a preview of the loader. Please assign me this issue under JWOC 2024.
![Untitled design](https://github.com/Rakesh9100/Beautiify/assets/124901633/2800b866-2590-4743-9d80-ec8b8845d617)

**Comment by Rakesh9100** [comment]
What will you name this loader? @SohanRC

**Comment by SohanRC** [comment]
> What will you name this loader? @SohanRC

Rotating Squares Loader

**Comment by Rakesh9100** [comment]
Go ahead @SohanRC

**Comment by SohanRC** [comment]
> Go ahead @SohanRC

I have generated a Pull Request . Kindly review it.

**Comment by SohanRC** [comment]
> Go ahead @SohanRC

I generated a Pull Request. Kindly review it.
