### ISSUE TITLE
[Feature] Add a new type of card [Animated Product Card]

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#216]
### Description

I want to add. new type of card under the components, An animated Product Card, which shall be useful for E-commerce websites and many more. Please assign me this issue under JWOC'24

### Video Demo

https://github.com/Rakesh9100/Beautiify/assets/86418216/a8985b46-a806-4491-a2a2-31df554bb85f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha
