### ISSUE TITLE
GIve it 3D UI Home Page by manipulating Shadows and depths 

### ISSUE THREAD

**Issue by raghav1482** [Rakesh9100/Beautiify#22]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

GIve it 3D UI Home Page by manipulating Shadows and depths .
->Manipulating shadows with minute border and dark background will make it look professional and 3D.

Kindly assign me this issue under SWOC24 @Rakesh9100 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
@raghav1482 Proceed
