### ISSUE TITLE
[Bug] Overlapping of Get Components Button with other sections

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#222]
### Description

There is overlapping of get components button between Accordions and Background div.
Please assign me this issue under IWOC2024 

### Screenshots

<img width="758" alt="issue" src="https://github.com/Rakesh9100/Beautiify/assets/125133940/663df65b-33fe-46a4-9bc4-2a301ba9804b">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Bayyana-kiran** [comment]
Hello @Dhairya1Gupta can u assign me under iwoc24?

**Comment by Bayyana-kiran** [comment]
Approach: I have been checking code,by changing the alignments it could be working ... it's like brute force

**Comment by Rakesh9100** [comment]
It is not overlapping. Work on other issues @Dhairya1Gupta
