### ISSUE TITLE
[Feature] Adding a feedback form under Forms section

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#224]
### Description

It will be used to take feedback from Users  who are consuming their services.
Please assign me this issue under IWOC2024 @Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sksinha2410** [comment]
@Rakesh9100 I would like to work on this under JWOC

**Comment by Rakesh9100** [comment]
You are already assigned to an issue, complete that first @Dhairya1Gupta 

Go ahead @sksinha2410
