### ISSUE TITLE
[Feature] Adding a new Card 

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#229]
### Description

I want to **add** a new **3-D Animated card** in Cards Component.

Card will contain a **image, heading** and **some information.** 
Normally card will show image with heading.
On **hovering** it will display the informations with **beautifull animation.**

I am already working on it i will complete it soon.

Kindly assign this to me under IWOC2024.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Carry on @Prince-kushwaha-2004
