### ISSUE TITLE
[Feature] Adding a Neumorphic Form

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#232]
### Description

I want to add a Neumorphic Form in the form section . Please assign me this issue under IWOC'24

### Screenshots

<img width="457" alt="Screenshot 2024-01-15 at 11 39 37 PM" src="https://github.com/Rakesh9100/Beautiify/assets/86418216/9fcafc9b-1868-49d9-9538-0a72572d0a98">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha
