### ISSUE TITLE
[Feature] Mouse On Wheel Loader

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/Beautiify#233]
### Description

I want to add a " Mouse On Wheel " Loader in the Loaders Section

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140608790/18a61a66-8e44-4c71-a097-692b12df8460

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Please review the PR

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Please reopen it

**Comment by Rakesh9100** [comment]
PR is already open, fix that @JiyaGupta-cs
