### ISSUE TITLE
[FIX]: Component boxes after hover improvement

### ISSUE THREAD

**Issue by Ashutosh104** [Rakesh9100/Beautiify#239]
### What's the style idea?

In the component part after hovering on a component box, the animation should be reversed in a much smoother way.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC

**Comment by Rakesh9100** [comment]
Proceed @Ashutosh104
