### ISSUE TITLE
[Feature] New Voice command search bar component

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#242]
### Description

I will add a new **Voice command search bar** in Search bar component.

I will use **HTML, CSS** and **Javascript** for this.

Feature of voice command will added using **javascript (web speech API).**

Kindly assign this to me under IWOC2024.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 174 is open for adding a search bar. Will assign you this to enhance that search bar after it is added @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 

Sir i want to add a seprate search bar  in search bar component of website that willl take input on voice command as like expandable search bar and icon-to-bar searchbar.

**This feature is not related to issue  174.**

I will also contribute in search bar of website when issue 174 is completed.

Kindly allot this to me to add **seprate section of search bar** which will be available for user to use and see code. like other components.

**Comment by Rakesh9100** [comment]
Okay then go ahead @Prince-kushwaha-2004
