### ISSUE TITLE
Responsiveness of parallax background component 

### ISSUE THREAD

**Issue by pranjal12-web** [Rakesh9100/Beautiify#245]
### Description

I would like to work on making parallax background responsive.

### Screenshots

![Screenshot 2024-01-16 143657](https://github.com/Rakesh9100/Beautiify/assets/67697534/f67ae646-f208-41d7-b969-a092c9d94f43)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by pranjal12-web** [comment]
@Rakesh9100 Please assign me this issue under JWoC24

**Comment by Rakesh9100** [comment]
Go ahead @pranjal12-web

**Comment by Rakesh9100** [comment]
Status of your PR @pranjal12-web

**Comment by pranjal12-web** [comment]
I have raised the PR
