### ISSUE TITLE
Changing colors of component category boxes on hovering

### ISSUE THREAD

**Issue by pranjal12-web** [Rakesh9100/Beautiify#246]
### What's the style idea?

When we hover on the component boxes, we can change the color and background color .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by pranjal12-web** [comment]
@Rakesh9100 Please assign me this issue under JWoC'24

**Comment by Rakesh9100** [comment]
Proceed @pranjal12-web
