### ISSUE TITLE
Facebook and insta links at the bottom of the page directed to linkedin

### ISSUE THREAD

**Issue by pranjal12-web** [Rakesh9100/Beautiify#247]
### Description

Facebook and instagram links at the bottom of the page are getting directed to linkedin page. So either we should add the correct links or remove them.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need. Pls work on the issues assigned to you @pranjal12-web
