### ISSUE TITLE
[Feature] Add a Neumorphic Search bar

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#248]
### Description

Addition of a neumorphic search bar under search bars under components, please assign me this issue under IWOC'24

### Video Demo

https://github.com/Rakesh9100/Beautiify/assets/86418216/6e3a1575-9eb9-4635-9ddb-337143055fb0

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SoumyadevSaha
