### ISSUE TITLE
[Feature] Addition of a Neumorphic Accordion

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#249]
### Description

I want to add a neumorphic accordion to the list of accordions under components. Please assign me this issue under JWOC'24

### Video Demo

https://github.com/Rakesh9100/Beautiify/assets/86418216/25b99d8c-fef5-4993-9fdf-18e723e5647c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SoumyadevSaha
