### ISSUE TITLE
Create a Responsive Footer Including All  types Of Necessary Content

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Beautiify#25]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Here Are Below Some of the Preview Of The Responsive Footer With All Hover Effect

### Screenshots

![Screenshot 2024-01-02 122724](https://github.com/Rakesh9100/Beautiify/assets/129049677/8c8877c2-56ee-4ffa-ae45-acafef0fce9b)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
We don't need this unnecessary big footer for now. Do create good issues @Kapileswar-Moharana
