### ISSUE TITLE
[Feature] Adding a Survey form under forms section

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#253]
### Description

It will contain a survey form to take survey data from user.
Please assign me this issue under IWOC2024 @Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sksinha2410** [comment]
@Rakesh9100 I would like to work on this under JWOC .
Kindly Assign it to me
