### ISSUE TITLE
[Feature] Polaroid Like Photo Carousel

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#255]
### Description

It animates over a stack like structure

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142514166/285682a7-df64-459c-96fd-0b57c4aec3ac

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha
