### ISSUE TITLE
Add a Glassmorphic Navbar

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#258]
### Description

Hi, I'd like to add a glassmorphic navigation bar, please assign it to me under SWOC'24

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/1dd3fac7-05e7-4a11-a64e-4c32a6ee4da5)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @rishicds
