### ISSUE TITLE
Responsive NavBar with better Hover Property and Suitable Color

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Beautiify#26]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me  Under SWOC

**Comment by Rakesh9100** [comment]
Issue already exist for the UI enhancement. Pls create new issues @Kapileswar-Moharana
