### ISSUE TITLE
[Style]: Styling the buttons of the contact page on focus

### ISSUE THREAD

**Issue by yaten2302** [Rakesh9100/Beautiify#261]
### What's the style idea?

Hi @Rakesh9100, I want to style the buttons of the contact page on focus, could you please assign this issue to me under JWoC and SWoC <br>
![image](https://github.com/Rakesh9100/Beautiify/assets/129659514/1b746b4b-2f97-4778-a115-0e5ba85d4bb8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
You want to work for JWOC or SWOC @yaten2302

**Comment by yaten2302** [comment]
I can do it under JWoC?

**Comment by Rakesh9100** [comment]
Okay then, go ahead @yaten2302
