### ISSUE TITLE
[Style] Design of the Payment form

### ISSUE THREAD

**Issue by tarnibalgoher5** [Rakesh9100/Beautiify#267]
### What's the style idea?

Design of the Payment form
https://beautiify.netlify.app/components/forms/payment-form/

The current design of the page does not look visually appealing to the user and instantly withdraws their attention.

Suggestions:
-Change the background color
-Improve the overall design including the typography and color scheme of the form and make it more compact

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @tarnibalgoher5

**Comment by Rakesh9100** [comment]
Status of your PR @tarnibalgoher5

**Comment by tarnibalgoher5** [comment]
yeah working on it, just need to see the make small changes

**Comment by tarnibalgoher5** [comment]
kindly review it

**Comment by Rakesh9100** [comment]
Where is your PR to review @tarnibalgoher5
