### ISSUE TITLE
Increase brightness in hover

### ISSUE THREAD

**Issue by Prachurya-Ray** [Rakesh9100/Beautiify#268]
### What's the style idea?

Increase brightness while somebody hover over the component. It looks dull even though somebody hover over any component to select.

<img width="960" alt="image" src="https://github.com/Rakesh9100/Beautiify/assets/70370699/50426d29-02bf-450c-94e2-29981715640a">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 246 is already opened for this. Pls create new issues @Prachurya-Ray
