### ISSUE TITLE
[Feature] Adding a Spotlight text animation

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#269]
### Description

Hi @Rakesh9100 
This text-animation will glow back and forth as shown in the given attached file
Please assign me this issue under IWOC2024

https://github.com/Rakesh9100/Beautiify/assets/125133940/106bdee1-9f5b-426c-a1df-26a9efb0bdc2

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
You are assigned to an issue, work on that first @Dhairya1Gupta

**Comment by Rakesh9100** [comment]
Go ahead @Dhairya1Gupta

**Comment by Rakesh9100** [comment]
https://beautiify.netlify.app/components/text-animations/spotlight-text-animation/

One spotlight text animation is already present @Dhairya1Gupta

**Comment by Dhairya1Gupta** [comment]
Sorry Sir I didn't noticed 
Please delete or Ignore this issue @Rakesh9100
