### ISSUE TITLE
Adding Favicon Icon To The Website

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [Rakesh9100/Beautiify#27]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I Would Like To Add The Favicon Icon to the Website To Look Better...

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Kapileswar-Moharana** [comment]
@Rakesh9100 Assign This Issue To Me Under SWOC

**Comment by Rakesh9100** [comment]
Favicon is already present @Kapileswar-Moharana Pls do work on other good issues and do not open multiple issues at a time.
