### ISSUE TITLE
[Feature]Add a Greeting-Card

### ISSUE THREAD

**Issue by learnersurajsingh** [Rakesh9100/Beautiify#272]
### Description

Hi
I want to add a card which can be used to wish each other. On hovering over the card, it opens up and shows a beautiful message.

For better understanding, please see the attached video.

Please assign me this under IWOC2024.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/123951068/2dcb7857-5d45-45df-97bf-d618973b66ac

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @learnersurajsingh
