### ISSUE TITLE
[Feature] Adding a Quotes cards under cards section

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#278]
### Description

Hi @Rakesh9100 
Sir this will contain motivation quotes cards in a Carousel form
Please refer to the given video

https://github.com/Rakesh9100/Beautiify/assets/125133940/46a3e07f-aa53-4de3-98bd-3e65343fac03

 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Dhairya1Gupta
