### ISSUE TITLE
[Feature] Add Individual Focus Card

### ISSUE THREAD

**Issue by learnersurajsingh** [Rakesh9100/Beautiify#279]
### Description

Hi
I want to add a set of cards in which on hovering, only one card at a time will be in focus and others will be blurred. 

For better understanding, please see the attached video.

Please assign me this under IWOC2024.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/123951068/ed6150da-63c5-456e-8ac9-fb44042a037a

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @learnersurajsingh
