### ISSUE TITLE
Adding a parallax background under backgrounds component

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/Beautiify#28]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Inside the background component, I want to add more examples by adding a parallax background. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @bhavya-anand19
