### ISSUE TITLE
[Feature] Add a new breadcrumb

### ISSUE THREAD

**Issue by shivam101203** [Rakesh9100/Beautiify#280]
### Description

It is very good breadcrumb and has spherical corners with voilet effect in it.It looks sassy and modern too.

### Screenshots
[Screencast from 17-01-24 05:49:06 PM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/156535575/a8e79b29-662c-45db-bd02-0d497d0487d6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shivam101203** [comment]
please assign this issue to me under iwoc2.0

**Comment by shivam101203** [comment]
@Rakesh9100  please assign it to me

**Comment by Rakesh9100** [comment]
Proceed @shivam101203

**Comment by shivam101203** [comment]
Thanks sir

**Comment by shivam101203** [comment]
Added a new breadcrumb #311 sir

**Comment by shivam101203** [comment]
Please merge the pr

**Comment by shivam101203** [comment]
Please merge this pr #317

**Comment by shivam101203** [comment]
please merge the pr @Rakesh9100  and apology for my mistake
