### ISSUE TITLE
[Feature] Adding 3D Popup Card

### ISSUE THREAD

**Issue by learnersurajsingh** [Rakesh9100/Beautiify#282]
### Description

Hi
I want to add a set of 3D Popup Cards in which on hovering the cards, an image will popup a bit.

For better understanding, please see the attached video.

Please assign me this under IWOC2024.

https://github.com/Rakesh9100/Beautiify/assets/123951068/aaf0f1c7-44b6-4b8c-84f4-84e248466fd1

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @learnersurajsingh

**Comment by Prithwi32** [comment]
@Rakesh9100 I would like to work on this issue under JWOC

**Comment by Rakesh9100** [comment]
Proceed @Prithwi32

**Comment by Prithwi32** [comment]
https://github.com/Rakesh9100/Beautiify/assets/115262737/74c0804a-a39a-4935-a69f-95506bc75bac

@Rakesh9100 Made this 3D-pop animation...let me know feedback about it...and can I proceed to make PR?

@
