### ISSUE TITLE
[Feature] Adding Rounded Square Background Animation

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/Beautiify#284]
### Description

Adding Background Animation under the Backgrounds category , under the IWOC Event.

### Screenshots

[Screencast from 17-01-24 01:28:03 PM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/114584730/8247d9fc-e9b5-443e-8574-46e095dd92e3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What name you will provide to this background @Tholkappiar

**Comment by Tholkappiar** [comment]
It's **Background Rounded Square Animation** !

**Comment by Rakesh9100** [comment]
Go ahead and name your folder as  `Rounded-Square-Animation-Background` @Tholkappiar
