### ISSUE TITLE
[Feature] Animated Breadcrumbs

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#286]
### Description

To add a animated breadcrum which slides like a slider..

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/f17cffa7-ca22-49b5-bcef-3f59c99add79)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
