### ISSUE TITLE
[Bug] Footer overflowing in contributors page on small screen

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#289]
### Description

The footer on the contributor page overlaps the Contributor section making merged visibility of both sections in smaller screens.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/1b6083d2-d0d3-4a33-899e-c28ab1ff6ea0)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @pb0126
