### ISSUE TITLE
Adding Distorted Text Animation

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#29]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Under the text animation component, I want to add a text distorted animation.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by steve2700** [comment]
hello is this issue still available

**Comment by Rakesh9100** [comment]
Proceed @saurav2208
