### ISSUE TITLE
[Bug] Hamburger menu not working in contributors page

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#291]
### Description

On small devices, the hamburger menu is not working on clicking. The menu is not accessible on small devices

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/8ac7203e-b2d7-4eee-b095-35450c61ccaf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete previous issue first @pb0126

**Comment by pb0126** [comment]
Hi @Rakesh9100 , Please assign the following issue so that I can start working on it. I have completed the previous issues.

**Comment by Rakesh9100** [comment]
Go ahead @pb0126
