### ISSUE TITLE
[Feature] Neon Glowing Sign up form

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#294]
### Description

I will add a new **Neon Glowing Sign up form**.
I will create it using **HTML** and **CSS.**

Kindly assign this to me under IWOC2024

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
I had completed this work also kindly assign this to me so that I open PR for this.

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Done sir.

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Sir kindly check my all previous tasks are completed and PR is also merged.
Kindly assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead @Prince-kushwaha-2004
