### ISSUE TITLE
[Feature] Add a new tilted accordion

### ISSUE THREAD

**Issue by shivam101203** [Rakesh9100/Beautiify#296]
### Description

Most websites rarely use horizontal accordions, but this type of accordion makes an effective design component for displaying images, Q&A, and presenting guidelines. Horizontal accordions also function as an onboarding feature or a simple in-page information box.

This animated accordion allows you to get creative with pure CSS3. It uses a rotation transition when clicking on tabs.

### Screenshots

[Screencast from 17-01-24 06:36:09 PM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/156535575/bf2f7bbc-474a-4a77-8983-0f1de861e627)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shivam101203** [comment]
please assign issue to me under iwoc 2024 @Rakesh9100

**Comment by shivam101203** [comment]
Sir please assign this issue to me under iwoc

**Comment by Rakesh9100** [comment]
Go ahead @shivam101203

**Comment by shivam101203** [comment]
Thanks sir

**Comment by shivam101203** [comment]
sir there was issue with fork so i closed the pull request ,please accept #398 as a merge .
