### ISSUE TITLE
Add information about the components instead of Lorem Ipsum 

### ISSUE THREAD

**Issue by Anoushka-Aggarwal** [Rakesh9100/Beautiify#297]
### What would you like to share?

Instead of this 
What is open-source?
Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus nobis ut perspiciatis minima quidem nisi, obcaecati, delectus consequatur fuga nostrum iusto ipsam ducimus quibusdam possimus. Maiores non enim numquam voluptatem?

Write this 
Open source means that the inner workings of a computer program are like an open book – anyone can read, change, and share the code that makes the software run. It's like a collaborative effort where people from all around can contribute to make the program better. The idea is that everyone benefits from the shared knowledge, and the software is often free to use and share. Examples of open-source projects include the Linux operating system and the Firefox web browser. It's a way of working together openly and making technology accessible to everyone.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What exactly you want to do @Anoushka-Aggarwal

**Comment by Anoushka-Aggarwal** [comment]
just add text related to the question .

**Comment by Rakesh9100** [comment]
No need. Pls work on good issues @Anoushka-Aggarwal
