### ISSUE TITLE
[Feature] Adding Tilted Breadcrumb

### ISSUE THREAD

**Issue by yusra05** [Rakesh9100/Beautiify#298]
### Description

I would like to add Tilted Breadcrumb which on hover expands 

### Screenshots
![image](https://github.com/Rakesh9100/Beautiify/assets/112852251/91d6d83d-90c0-441f-9b6e-e6b149c60049)

https://github.com/Rakesh9100/Beautiify/assets/112852251/2c298727-3747-4074-a855-25d468569962

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [x] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls edit the issue description and tick only that open source program for which you have opened the issue @yusra05

**Comment by yusra05** [comment]
done

**Comment by Rakesh9100** [comment]
Go ahead @yusra05
