### ISSUE TITLE
Addition of 3d search bar

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#299]
i would like to add a new search bar.
plz assign it to me under swoc'24.
![Untitled1](https://github.com/Rakesh9100/Beautiify/assets/144611267/39117d6d-f647-4651-ba40-70d5619fea38)

**Comment by GhoshAditi** [comment]
@Rakesh9100 plz assign it to me

**Comment by Rakesh9100** [comment]
Pls follow the issue template and edit the issue description @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 i have put the issue template as you ask and created new issues. i am closing this issue. plz assign those to me. sorry for the inconvinience faced.

**Comment by Rakesh9100** [comment]
You don't need to close the issues. You could have edited just the issue description @GhoshAditi
