### ISSUE TITLE
Spinning Loader

### ISSUE THREAD

**Issue by Rakesh9100** [Rakesh9100/Beautiify#3]
Add a spinning loader inside Loaders component.

**Comment by prem-prasad1710** [comment]
Hi @Rakesh9100  ! I'm interested in fixing this issue.
Please assign this issue to me.

**Comment by Shivangi015** [comment]
@Rakesh9100 I can do this work. Please assign this issue to me.

**Comment by rishicds** [comment]
Hi @Rakesh9100 I'd love to work on this! Please assign this issue to me, thanks :)

**Comment by Rakesh9100** [comment]
@prem-prasad1710 Assigning you!!

**Comment by ayan-joshi** [comment]
@prem-prasad1710 Are u still working on this and have any doubts ?

**Comment by Rakesh9100** [comment]
@rishicds Do you want to work on this?

**Comment by rishicds** [comment]
> @rishicds Do you want to work on this?

sure I'll give it a shot

**Comment by Rakesh9100** [comment]
Proceed @rishicds
