### ISSUE TITLE
Adding Footer 

### ISSUE THREAD

**Issue by vishal0316** [Rakesh9100/Beautiify#30]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Please allow me to add interactive footer.
social medial links , contact us and Site logo or name

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/106919588/3e6b2da9-1175-446d-a9ec-4b5b96150c19)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed!! @vishal0316
