### ISSUE TITLE
Addition of connecting dots background

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#300]
@Rakesh9100 
i would like add connecting the dots background.plz assign it to me under swoc'24.

**Comment by Rakesh9100** [comment]
Pls follow the issue template and edit the issue description @GhoshAditi

**Comment by GhoshAditi** [comment]
@Rakesh9100 i have put the issue template as you ask and created new issues. i am closing this issue. plz assign those to me. sorry for the inconvinience faced.
