### ISSUE TITLE
Contact form validation

### ISSUE THREAD

**Issue by Sanjana787** [Rakesh9100/Beautiify#303]
### Description

if a user enters numeric values at the place of the name it is accepted whereas it should just accept the character value only.

### Screenshots

![1](https://github.com/Rakesh9100/Beautiify/assets/141259407/527a1681-f9d9-4d9e-bc71-a7df32c62289)
![2](https://github.com/Rakesh9100/Beautiify/assets/141259407/f29f58e1-8980-40c5-8607-b420da83a29f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sanjana787** [comment]
@Rakesh9100 please assign this issue to me.

**Comment by ramith-kulal** [comment]
i want to work on this under jwoc'24, can i get asssigned

**Comment by Rakesh9100** [comment]
Go ahead @Sanjana787

**Comment by thatguywhocode** [comment]
Hey @Rakesh9100 , can you assign me under JWOC.

**Comment by Rakesh9100** [comment]
Status of your PR @Sanjana787
