### ISSUE TITLE
[Feature] Bubble Float Animated Background

### ISSUE THREAD

**Issue by Parth4git** [Rakesh9100/Beautiify#304]
### Description

It is a live background play on hover 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/99666524/8adb210a-495e-4ca5-aa4b-b478cae7de70)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Parth4git
