### ISSUE TITLE
[Feature] Add a New Bird Loader

### ISSUE THREAD

**Issue by psykat1116** [Rakesh9100/Beautiify#305]
### Description

I want to add a new Loader. Please Assign me for this.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/95569573/637eca8e-f6e6-481b-bf11-c1f0a8ae593b

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [x] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program for which you have opened the issue @psykat1116

**Comment by Dhairya1Gupta** [comment]
Please assign me this Issue under IWOC 2024 @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @psykat1116
