### ISSUE TITLE
[Bug] Name Validation Issue

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#306]
### Description

when we type numbers in place of name then it is accepting which is a issue and I would like to solve this issue.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/fa2436c2-e255-4e93-87d6-70ed3efa2ace)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open. Pls create new issues @mansi1309
