### ISSUE TITLE
[Feature] Adding Logo in Navbar

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#307]
### Description

I would like to add logo in left side of the web page .Please assign this issue to me

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/b56aa499-1860-4993-878a-ec2e5323c346)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
GO ahead @mansi1309

**Comment by vishapraj** [comment]
Hi @Rakesh9100 please assign me this issue , as I had completed it and I have to pull request only.

**Comment by Rakesh9100** [comment]
@mansi1309 Status of your PR

**Comment by deboneil07** [comment]
Can i work on this issue if it hasn't been solved already?

**Comment by Rakesh9100** [comment]
Proceed @vishapraj

**Comment by Rakesh9100** [comment]
You want to work for which open source program @vishapraj

**Comment by vishapraj** [comment]
Adding logo in nav bar

**Comment by Rakesh9100** [comment]
I am asking for which program SWOC, IWOC or JWOC @vishapraj

**Comment by vishapraj** [comment]
Under "JWOC"

**Comment by Rakesh9100** [comment]
Proceed @vishapraj

**Comment by Divyanshgarg-04** [comment]
@Rakesh9100 I would love to work on this issue under JWOC. Can you please assign this issue to me

**Comment by vishapraj** [comment]
![Screenshot from 2024-01-23 15-01-46](https://github.com/Rakesh9100/Beautiify/assets/126682925/e1a2135e-c4f2-4c04-9b26-6e21f0f3a42e)

**Comment by vishapraj** [comment]
these changes I have done @Rakesh9100

**Comment by Rakesh9100** [comment]
Go to your opened PR and check the comment @vishapraj

**Comment by vishapraj** [comment]
@Rakesh9100 you haven't merged my PR?
