### ISSUE TITLE
[Feature] Toggling Switching Log In / Sign Up Form

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/Beautiify#308]
### Description

I want to add an Animated Toggling Switching Log In / Sign Up Form

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140608790/d8dc7bd1-fee3-43d1-b31d-77db35d647a8

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @JiyaGupta-cs
