### ISSUE TITLE
[Feature] Addition of 3d search bar

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#313]
### Description

@Rakesh9100 i would like to add a 3d search bar . please assign it tome under swoc'24

### Screenshots

![Untitled1](https://github.com/Rakesh9100/Beautiify/assets/144611267/dc295df4-b01e-4280-a2dc-73431bbcc646)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program for which you have opened the issue @GhoshAditi 

Don't close the issue!!

**Comment by GhoshAditi** [comment]
@Rakesh9100 done

**Comment by Rakesh9100** [comment]
Go ahead @GhoshAditi
