### ISSUE TITLE
Addition of connecting dots background

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#314]
### Description

@Rakesh9100 i would like to add connecting dots background. plz assign it to me under swoc'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Edit the issue description and tick only that open source program for which you have opened the issue @GhoshAditi 

Don't close the issue!!

**Comment by GhoshAditi** [comment]
@Rakesh9100 done

**Comment by GhoshAditi** [comment]
@Rakesh9100 i would like to work on it :(

**Comment by Rakesh9100** [comment]
Go ahead now, you were working on one issue so I put this on standyby mode @GhoshAditi
