### ISSUE TITLE
[Feature] Adding a Expandable Breadcrumbs on Hover

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#316]
### Description

I would like to add a expandable breadcrumbs on hover in breadcrumbs section.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/f093cb95-ec20-4a85-8efa-0af88f049561)
I would like to add something like that
![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/54aa5876-893e-401f-9f66-01558a83b420)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issues first @mansi1309

**Comment by Rakesh9100** [comment]
Issue is already open for this @mansi1309
