### ISSUE TITLE
[Feature] Adding a Simple Search Bar

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#318]
### Description

I would like to add simple search bar in search bar section. Please assign this to me.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/2da1e9e9-b539-449b-8578-75c7685bb3d4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issues first @mansi1309

**Comment by kanishka-parmar** [comment]
@Rakesh9100  is this issue open? Can I work on this?

**Comment by Rakesh9100** [comment]
Sure, can you pls tell you want to work for which open source program @kanishka-parmar

**Comment by kanishka-parmar** [comment]
SWOC @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @kanishka-parmar

**Comment by kanishka-parmar** [comment]
Thanks @Rakesh9100
