### ISSUE TITLE
[Feature] Adding Social icons in Footer

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#319]
### Description

I would like to add social media icons footer in footer section. So that user directly follow on it.

### Screenshots

I would like to add something like that.
![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/e70dd4e0-d806-4fa8-a4d1-b8018ad817b8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Social icons is already present in the footer. Pls work on good issues and don't open too many issues at once @mansi1309
