### ISSUE TITLE
[Feature] Adding Pulse animated Search Bar

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/Beautiify#320]
### Description

can add one more search bar in search bars category 

### Screenshots

<https://www.emailonacid.com/blog/article/email-development/pulsing-cta-in-email/>

https://github.com/Rakesh9100/Beautiify/assets/147225647/d378ac99-29c8-436e-b368-975fc1d27f1c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
yes sir i have done this task i will provide you it by tommorow

**Comment by Rakesh9100** [comment]
Status of your PR pls @student-aditipaliwal
