### ISSUE TITLE
[Feature]Parallel Park Breadcrumb

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#324]
### Description

Add a parallel park breadcrumb : A showcase of parking cars using breadcrumb designs

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/2c725dc0-9605-4c5f-b089-d21327276a35)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AbhineshJha** [comment]
Now can i assign with this issue..
I am ready with the pr.. @Rakesh9100

**Comment by Rakesh9100** [comment]
Yes, proceed @AbhineshJha
