### ISSUE TITLE
[Feature] Adding a new particle animation backgound

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#325]
### Description

Hi @Rakesh9100 
I would like to add a new particle animation background under Background section.
For further details please refer to given video

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".
- 

https://github.com/Rakesh9100/Beautiify/assets/125133940/f99554f2-7228-4014-b7fa-af43c6720f28

**Comment by Rakesh9100** [comment]
Go ahead @Dhairya1Gupta

**Comment by Rakesh9100** [comment]
Merged 🥳 @Dhairya1Gupta
