### ISSUE TITLE
[Feature] Shaking Text Animation

### ISSUE THREAD

**Issue by Tholkappiar** [Rakesh9100/Beautiify#330]
### Screenshots

[Screencast from 19-01-24 10:44:33 PM IST.webm](https://github.com/Rakesh9100/Beautiify/assets/114584730/3bc23f0b-75ac-4db0-8fda-f62a37a6580b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to work @Tholkappiar

**Comment by anirbanmajumder0** [comment]
Please assign me this @Rakesh9100  under SWOCS4

**Comment by Rakesh9100** [comment]
Proceed @anirbanmajumder0

**Comment by anirbanmajumder0** [comment]
@Rakesh9100 please check PR #425
