### ISSUE TITLE
[Style] Changing the colours of page and style

### ISSUE THREAD

**Issue by Utkarsht2310** [Rakesh9100/Beautiify#332]
### What's the style idea?

The current colors which are used in the web page are not looking to good like a professional and formal. All the other things are very good and fine so i want to do some changes in the colors so this will look more beautiful and stylish as the name suggest.  
Please assign this issue to me i want to contribute on this under JWOC'2024.
Thank You !

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
The current UI is looking good. What colours enhancement you want to make @Utkarsht2310
