### ISSUE TITLE
[Feature] Adding Transfer List Category and Neuromorphic Transfer List Component

### ISSUE THREAD

**Issue by EAGLEARCHER** [Rakesh9100/Beautiify#333]
### What would you like to share?

This issue is created in order to add a new component which is an item transfer list based on neuromorphic design.
![Screenshot 2024-01-20 ](https://github.com/Rakesh9100/Beautiify/assets/92213232/eed711f8-7bec-4aae-823b-bedec256f51e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by EAGLEARCHER** [comment]
@Rakesh9100 please assign me this under SWOC'24

**Comment by Rakesh9100** [comment]
Under which component category you want to add this @EAGLEARCHER

**Comment by EAGLEARCHER** [comment]
Currently, there is no category for the transfer list, so this will become a new category.

**Comment by EAGLEARCHER** [comment]
@Rakesh9100 this is the final UI of the component transfer list
![transfer-list-final](https://github.com/Rakesh9100/Beautiify/assets/92213232/a9e51fee-753c-4841-a0bb-8aaed8b05b02)

**Comment by Rakesh9100** [comment]
Do you want to create a new category in home page and then add this component under that category @EAGLEARCHER

**Comment by EAGLEARCHER** [comment]
Sorry @Rakesh9100 for the late response.

Yes I want to create a new category on home page

**Comment by Rakesh9100** [comment]
Proceed @EAGLEARCHER

**Comment by Rakesh9100** [comment]
Proceed @EAGLEARCHER
