### ISSUE TITLE
[Feature] Add a Delete Button

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/Beautiify#336]
### Description

 i want to add a delete button having the functionality of on hover it get converted into the delete icon

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sakshamjain98** [comment]
Sir please assign me this issue under iwoc

**Comment by Rakesh9100** [comment]
There are many buttons, not only four!! [Check this](https://beautiify.netlify.app/assets/html_files/buttons) @Sakshamjain98

**Comment by Rakesh9100** [comment]
Don't specify simple like you want to add some more, mention clearly which type of button or any component you want to add @Sakshamjain98

**Comment by Sakshamjain98** [comment]
I want to add a delete button that on click get change to a delete icon

**Comment by Sakshamjain98** [comment]
And also want to add a flower animation button

**Comment by Rakesh9100** [comment]
Do you want to add two types of buttons in this same issue @Sakshamjain98

**Comment by Sakshamjain98** [comment]
No I want to add two buttons in two different issues

**Comment by Rakesh9100** [comment]
Edit this issue title and description for the button you want to add @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Done sir

**Comment by Rakesh9100** [comment]
For delete button, since it is just a component and not functional so what will you add @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Sir functionality is on hover it get converted into delete icon

**Comment by Rakesh9100** [comment]
Okay go ahead @Sakshamjain98

**Comment by Rakesh9100** [comment]
PR status pls @Sakshamjain98

**Comment by Sakshamjain98** [comment]
Sorry sir health issue ka Karan hua nhi sham tk ho jayga
