### ISSUE TITLE
[Feature] Adding a Neumorphic Loader

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#337]
### Description

I want to add a new loader : a neumorphic loader animation. Please assign me this issue under IWOC'24

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/86418216/6a34c401-ed73-41ac-9090-b14b54ad1dd4

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SoumyadevSaha
