### ISSUE TITLE
[Feature] Mouse Responsive tsParticles Background

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#338]
### Description

I want to add a mouse-responsice tsParticle Background under components. Please assign me this issue under IWOC

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/86418216/32556fc4-8f2e-4db4-ad15-8aadbe49aaf9

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SoumyadevSaha
