### ISSUE TITLE
[Feature] New Animated colorful background

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#341]
### Description

I will add a new **Animated colorful background** in backgrounds component.
For this i will use HTML and CSS.

Demo video of this is attached.

Kindly assign this to me under **IWOC024**

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/149922307/5b154ca7-e3a4-4f30-8b82-19b81d29e2ad

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Prince-kushwaha-2004
