### ISSUE TITLE
[Feature] Adding Simple Accordion

### ISSUE THREAD

**Issue by yusra05** [Rakesh9100/Beautiify#347]
### Description

A new Accordion with icons

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/112852251/5fdc0d50-65ec-4d2c-9d56-ca1af7a14a37

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Every accordion expands on click, what is new in your issue @yusra05

**Comment by yusra05** [comment]
It has different style from others

**Comment by Rakesh9100** [comment]
You have to provide me the name of this accordion @yusra05

**Comment by yusra05** [comment]
Iconic Accordition   [ Accordition with icons ]

**Comment by Rakesh9100** [comment]
Are you giving the name or should I close the issue @yusra05

**Comment by yusra05** [comment]
how about simple accordition.

**Comment by Rakesh9100** [comment]
Okay, go ahead @yusra05
