### ISSUE TITLE
[Feature] Add Round Squares Loader

### ISSUE THREAD

**Issue by Nemesis-AS** [Rakesh9100/Beautiify#348]
### Description

Add a square grid loader with round animation

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/56386613/4addd20a-4b4c-4d7e-a43e-dae3acaf3f30

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Nemesis-AS
