### ISSUE TITLE
[Feature] Highlight the active menu item of navbar

### ISSUE THREAD

**Issue by Anoushka-Aggarwal** [Rakesh9100/Beautiify#349]
### Description

When we open contact ,home or any other page it does not highlight which page we are on currently . 

### Screenshots

<img width="1440" alt="Screenshot 2024-01-20 at 9 02 30 PM" src="https://github.com/Rakesh9100/Beautiify/assets/120657205/d645f2e7-ed0a-4d16-a06c-096ed9494dde">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by branihat** [comment]
hello @Rakesh9100  , I would like to work on this issue I am a SWOC contributor

**Comment by Rakesh9100** [comment]
Proceed @Anoushka-Aggarwal

**Comment by Rakesh9100** [comment]
PR status pls @Anoushka-Aggarwal

**Comment by thesri** [comment]
hey, can i please work on this @Rakesh9100 under jwoc 2024?

**Comment by Rakesh9100** [comment]
Proceed @thesri

**Comment by thesri** [comment]
What's the tag for this issue like  how many days will I get for this

**Comment by Rakesh9100** [comment]
Start your work and try to complete ASAP (generally 1-2 days) @thesri

**Comment by AftabMankapure** [comment]
assign me under jwoc

**Comment by Rakesh9100** [comment]
Proceed @AftabMankapure

**Comment by Rakesh9100** [comment]
PR status @AftabMankapure

**Comment by AftabMankapure** [comment]
check the PR
sorry for late 

same issue is occurred @thesri  
not able to change color of home and components  
it take lot of time
but it solved
