### ISSUE TITLE
[SWOC'24] Add contributors section

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/Beautiify#35]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- Enlist all the contributors on the main website
- Showcase them into a hexagonal grid structure of all the contributors

### Screenshots

Solution steps

- Using Javascript, fetching all the data of the contributors
- using css, maintain their styling and giving them a hexagonal grid structure of all the profiles

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please /assign this task to me to contribute in your repo under SWOC'24

**Comment by Rakesh9100** [comment]
Assigning, Go ahead!! @Avdhesh-Varshney

**Comment by Vipul-Harsh** [comment]
hey @Rakesh9100 can you assign me any issue as i was late to start contributiion an now almost all issues are being assigned.
so if you can please help me to find an issue .
thanks

**Comment by Aditi-Dahiya** [comment]
> hey @Rakesh9100 can you assign me any issue as i was late to start contributiion an now almost all issues are being assigned. so if you can please help me to find an issue . thanks

@Vipul-Harsh , You can go through the current website, changes are ongoing in other issues, and you can discuss a new issue if you have any ideas for it with us on Discord.
