### ISSUE TITLE
[Feature] Adding Rotating Circle Loader

### ISSUE THREAD

**Issue by bera474** [Rakesh9100/Beautiify#355]
### Description

Want to add a new Loader into the Loader Section. I am attaching the loader screenshot. Please assign me this issue under JWOC 2024.

### Screenshots

![Screenshot 2024-01-21 030626](https://github.com/Rakesh9100/Beautiify/assets/118124036/41144985-ca69-43f7-a94e-679d9c24d2ff)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What name you will provide to this loader @bera474

**Comment by bera474** [comment]
@Rakesh9100  Rotating Circle Loader.

**Comment by Rakesh9100** [comment]
Go ahead @bera474
