### ISSUE TITLE
[Feature] Adding Perspective Button

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#358]
### Description

I would like to add perspective button in button section.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/133951716/ec0373d4-2324-448d-97a2-6a05d0695a0f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Hey @mansi1309 Pls work on the issues assigned to you and don't open many issues at once without completing the previous ones!!

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
