### ISSUE TITLE
[Feature] Adding Helix Loader

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#359]
### Description

I want to add a new helix loader into the loader components. I am attaching below a recording of helix loader.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/f78cd511-9b79-498f-8897-1e647db6817e

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abidsyed25** [comment]
Please assign me this issue under IWOC label. I am ready to open a Pull Request.

**Comment by Rakesh9100** [comment]
Proceed @Abidsyed25
