### ISSUE TITLE
[SWOC'24] Back to top button

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Rakesh9100/Beautiify#36]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- I would like to create a back to top arrow button for the website.
- Responsive for any type of devices.
- Hovering with neon light effect.
- Best user experience with smooth scroll functioning.
- Helpful for the user to reach out to the top of the website in one click.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/114330097/a2d7fc0c-6922-4dae-817c-0255db043a07)

- No back to top button.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Avdhesh-Varshney** [comment]
@Rakesh9100 please assign this task to me to contribute in your repo under SWOC'24

**Comment by Rakesh9100** [comment]
Proceed @Avdhesh-Varshney
