### ISSUE TITLE
[Feature] Adding a new Square Loader

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#362]
### Description

I would like to add a new square loader.
For further information please refer the following video.

https://github.com/Rakesh9100/Beautiify/assets/125133940/af408263-e1ca-4f44-a353-9b694f1b4483

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by branihat** [comment]
I wanted to work on this issue .Pls assign this issue to me . @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @Dhairya1Gupta
