### ISSUE TITLE
[Style] Make the navbar translucent

### ISSUE THREAD

**Issue by rajpootjyoti700** [Rakesh9100/Beautiify#365]
### What's the style idea?

![WhatsApp Image 2024-01-21 at 18 02 41](https://github.com/Rakesh9100/Beautiify/assets/133164017/87bcab3f-ea09-4221-bf97-4a25759beb3b)
 the background image does not lines up properly with navbar image
this task becomes hectic as we have to configure it for mobile and tablet devices at different widths as well

what i propose is that we can make the navbar translucent giving it a glossy glass pane effect along with little border shadows at the bottom
 and little bit darkened as well to make the navbar contents stand out

### Checklist

- [x] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rajpootjyoti700** [comment]
can u plz assign this issue to me i want to work on it....

**Comment by Syed0206** [comment]
plz assign me this issue under JWOC

**Comment by Rakesh9100** [comment]
Pls edit the issue description and tick only that open source program for which you have opened the issue @rajpootjyoti700

**Comment by Rakesh9100** [comment]
Are you doing the change @rajpootjyoti700

**Comment by rajpootjyoti700** [comment]
> Are you doing the change @rajpootjyoti700

yes i m doing plz assign nd edit done

**Comment by Rakesh9100** [comment]
Proceed @rajpootjyoti700

**Comment by rajpootjyoti700** [comment]
> Proceed @rajpootjyoti700

done my task plz check nd view my PR
