### ISSUE TITLE
[Bug] Social Icons Link in contact page not working

### ISSUE THREAD

**Issue by thatguywhocode** [Rakesh9100/Beautiify#366]
### Description

The social icons in Contact tab does not redirect users to the account profile.

### Screenshots

![Screenshot 2024-01-21 204501](https://github.com/Rakesh9100/Beautiify/assets/138510462/0a63475c-438e-4dd7-9b15-9cab6af255ad)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need. Pls work on other good issues @thatguywhocode

**Comment by Rakesh9100** [comment]
Proceed @thatguywhocode

**Comment by thatguywhocode** [comment]
should i put linkedin links in all three icons or you can provide?

**Comment by thesri** [comment]
can i work on this ? @Rakesh9100 under jwoc 2024

**Comment by Rakesh9100** [comment]
> should i put linkedin links in twitter or you can provide and also can you provide difficulty level too? thanks

Twitter Link: <https://twitter.com/rakeshroshan73>
You can get other links [here](https://rakesh9100.bio.link/)!! @thatguywhocode
