### ISSUE TITLE
[Feature] Add Logo in navbar

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#367]
### Description

I will add the logo of website in nevbar which is missing in every page.
It will look better.

Kindly assign this to me under IWOC2024.

### Screenshots

![Screenshot 2024-01-21 224845](https://github.com/Rakesh9100/Beautiify/assets/149922307/38f2dc4b-3a24-4189-b3c7-f12fdc90638f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by deboneil07** [comment]
Can i please work on this issue?
