### ISSUE TITLE
[Style] Add icon on Navbar for menu items

### ISSUE THREAD

**Issue by Ishita928** [Rakesh9100/Beautiify#370]
### What's the style idea?

We need to improve:
Icons for each button can be added alongside with the text on the Navbar to make it look more appealing
![image](https://github.com/Rakesh9100/Beautiify/assets/146575485/8eccff5f-5eaf-40b7-80f6-82cc84ff2fb7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Ishita928
