### ISSUE TITLE
[Bug] Links are not working correctly

### ISSUE THREAD

**Issue by prakharsingh-74** [Rakesh9100/Beautiify#373]
### Description

In the home page of the website the links are not correctly linked with the profile on clicking the icon of facebook, twitter and instagram they are redirecting to linkedin.
Please Provide the url of your instagram, facebook and twitter accounts kindly. so that i can resolve the issue

https://github.com/Rakesh9100/Beautiify/assets/148339919/feb2c794-f76a-43ac-bdf7-d7f2cce08906

 I would like to work on this issue under JWOC @Rakesh9100 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @prakharsingh-74 

You can get my every profiles [here](https://rakesh9100.bio.link/)

**Comment by prakharsingh-74** [comment]
@Rakesh9100 what is your twitter account

**Comment by Rakesh9100** [comment]
[Twitter](https://twitter.com/rakeshroshan73) @prakharsingh-74
