### ISSUE TITLE
Addition of 3d rotating cylinder text animation

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#375]
### Description

@Rakesh9100  i would like to add a 3d rotating cylindrical text animation . plz assign me this under jwoc'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @GhoshAditi
