### ISSUE TITLE
[Feature] Add a Dynamic Square Grid Loader

### ISSUE THREAD

**Issue by Nemesis-AS** [Rakesh9100/Beautiify#376]
### Description

Add a new square grid animated loader

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/56386613/7d3045d4-651b-4cc0-9598-bc14279ef24f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Nemesis-AS
