### ISSUE TITLE
[Bug] Fixing the contact page

### ISSUE THREAD

**Issue by praptisharma28** [Rakesh9100/Beautiify#378]
### Description

The contact page is not rightly placed it needs to be shifted down.

### Screenshots

![Screenshot (533)](https://github.com/Rakesh9100/Beautiify/assets/123169861/7ee57415-dc5c-483e-87cc-ad820ce18bd4)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by praptisharma28** [comment]
Assign me this @Rakesh9100 , this is a crucial one.

**Comment by Rakesh9100** [comment]
This problem is coming after you have generated PR for one of your issue, pls check that PR @praptisharma28
