### ISSUE TITLE
Add rating page

### ISSUE THREAD

**Issue by shahil-afroz** [Rakesh9100/Beautiify#381]
### Description

Add an rating us page where customers or users rate us in the form of stars. Its connected with the nav bar rate us button.
So I have to make a new navbar button and also a rate us page.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/137023904/d8808ca3-903b-4f82-9c36-08de7931646c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by daksh1210jain** [comment]
![image](https://github.com/Rakesh9100/Beautiify/assets/137384322/a27f7ebb-7006-4d84-8e85-70757b8bc4d9)

I want to add an option at the header of the page

**Comment by Rakesh9100** [comment]
No need of ratings. Pls work on other good issues @daksh1210jain
