### ISSUE TITLE
[Bug] Chatbot button overlapping Scroll to top button in every screen

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#388]
### Description

The chatbot button overlaps the scroll to the top, creating a hindrance in the button's functionality and a design flaw.
The gap between both the buttons should be equal to avoid any click error and need to be aligned with the bellow button to enhance the  look and feel

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/ed2c1115-e241-44c5-a799-b353fe0b4a64)
![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/a366b5d7-8c2f-437e-9a13-2cc9049864f3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by deboneil07** [comment]
@pb0126 can i work on this issue?

**Comment by Rakesh9100** [comment]
Proceed @pb0126

**Comment by deboneil07** [comment]
can i work on this issue if it hasn't been rectified yet> @Rakesh9100

**Comment by pb0126** [comment]
Hi @Rakesh9100 I need access to make changes in the bot styling
Email:- prabhubisht0126@gmail.com
Please give the access to make changes

**Comment by Rakesh9100** [comment]
Do you want to work on this @pb0126

**Comment by pb0126** [comment]
Yes @Rakesh9100 , I need access to the chat bot to implement changes. Can you please assign this issue to me and give me access to chatbot

**Comment by Rakesh9100** [comment]
Pls check your mail to accept the invitation and proceed @pb0126

**Comment by pb0126** [comment]
I have received the invitation, I'll start working on it
