### ISSUE TITLE
[Bug] Chatbot interface overflowing on small devices

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#389]
### Description

The Chatbot interface is overflowing outside the main container on small devices, hiding half of the interface of the chatbot, making it difficult to use and creating a design flaw.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/6925cd2d-82fc-4140-b3cf-7ac97a9a7f4c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Can you pls complete this issue @pb0126
