### ISSUE TITLE
[Feature] Adding Gear Loader

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#390]
### Description

I want to add gear loader in the loader components. I attached a screen recording below. 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/95c7427a-2c99-4578-9901-110439e5ad6f

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Abidsyed25
