### ISSUE TITLE
[Style] Adding hover effects and animations to the components page cards

### ISSUE THREAD

**Issue by SohanRC** [Rakesh9100/Beautiify#393]
### What's the style idea?

We need to improve the hover effects in the Components page. They do not have nice hover effects. Also would like to add scroll animation on the cards. Please assign me under JWOC 2024. I am attaching the ScreenShot here.

![Screenshot 2024-01-23 134317](https://github.com/Rakesh9100/Beautiify/assets/124901633/cc21b0ec-20ed-4e8e-a891-f6437d7c17c9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SohanRC

**Comment by Dky23** [comment]
I can contribute in this issue, assign me for this under SWOC,24
Thank You,

**Comment by SohanRC** [comment]
@Rakesh9100 Please kindly review my PR #452 . Please !!!
