### ISSUE TITLE
[Feature] Add Hexagonal ripple Loader

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#399]
### Description

Hi, I'd like to add a hexagonal ripple loader, please assign it to me under JWOC'24

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/19ede61c-15f9-4a4f-b157-b7ceed7f87c9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @rishicds
