### ISSUE TITLE
Add toggle button

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/Beautiify#40]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Want to add a toggle button in buttons component.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Pls describe your issue more clearly @bhavya-anand19

**Comment by Rakesh9100** [comment]
Okay, go ahead!! @bhavya-anand19
