### ISSUE TITLE
[Feature] Add Light Mode and Dark mode button

### ISSUE THREAD

**Issue by divyansh2375** [Rakesh9100/Beautiify#403]
### Description

want to add a button

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @divyansh2375

**Comment by divyansh2375** [comment]
Progress 60 % . Resolving the confilct error , i mean i cant able to update the latest code of beatifii locally
![image](https://github.com/Rakesh9100/Beautiify/assets/130889408/885cdf84-2f0a-42ab-b94c-45d35ddafe14)

**Comment by Rakesh9100** [comment]
Status of your PR @divyansh2375

**Comment by divyansh2375** [comment]
sir there was a error which is occuring in my local system .i will full try to submitting the pr by today

**Comment by divyansh2375** [comment]
@Rakesh9100 i have successfully added the dark mode feature can you please review it

**Comment by Rakesh9100** [comment]
Hey @divyansh2375 The issue for adding dark mode is already open. This issue is assigned to you considering that you will add a new type of button in Buttons components category!!

**Comment by divyansh2375** [comment]
Don't you want to add Dark mode feature in the website?

**Comment by Rakesh9100** [comment]
Issue already exist for this before @divyansh2375

**Comment by divyansh2375** [comment]
Ok sir then i will be adding a button
