### ISSUE TITLE
[Style] Improve hover effect for the buttons on the navbar

### ISSUE THREAD

**Issue by deboneil07** [Rakesh9100/Beautiify#404]
### What's the style idea?

The current hover effects and animations for the nav-bar do not look complete or proper. I can improve the nav-bar drastically in terms of look and feel.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by deboneil07** [comment]
@Rakesh9100 can you assign me this issue?

**Comment by deboneil07** [comment]
@Rakesh9100  can i work on this?

**Comment by Rakesh9100** [comment]
Proceed @deboneil07

**Comment by Rakesh9100** [comment]
PR status pls @deboneil07

**Comment by AftabMankapure** [comment]
assign me under JWOC

**Comment by Rakesh9100** [comment]
What enhancements will you do @AftabMankapure

**Comment by bhavya-anand19** [comment]
@Rakesh9100 Can you assign me this issue

**Comment by Rakesh9100** [comment]
Proceed @bhavya-anand19

**Comment by Rakesh9100** [comment]
Status of your PR @bhavya-anand19

**Comment by Rakesh9100** [comment]
Provide your PR by today @bhavya-anand19

**Comment by SohanRC** [comment]
@Rakesh9100 Assign me this issue under JWOC 2024

**Comment by bhavya-anand19** [comment]
@Rakesh9100 I'm currently working on the issue. Will create a PR by today

**Comment by AftabMankapure** [comment]
@Rakesh9100  assign me under JWOC

**Comment by Rakesh9100** [comment]
Proceed and implement a good hover effect @AftabMankapure
