### ISSUE TITLE
[Bug] Placeholders doesn't fade on focus in the Contact page

### ISSUE THREAD

**Issue by adi-exe** [Rakesh9100/Beautiify#405]
### Description

When the user starts to fill the contact form , the placeholder for the text boxes should fade a little or be removed while writing.
I guess i could fix this issue .

### Screenshots

![Screenshot (121)](https://github.com/Rakesh9100/Beautiify/assets/134140404/3500db98-8b2c-40c3-b65f-cb357ee9aed2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by adi-exe** [comment]
Can you please assign this to me @Rakesh9100 .

**Comment by Rakesh9100** [comment]
There is no bug, the placeholder disappears as soon as we begin typing @adi-exe

**Comment by Gokilp** [comment]
assign to me
