### ISSUE TITLE
[Feature] Adding Newsletter Subscription Form

### ISSUE THREAD

**Issue by this-is-yaash** [Rakesh9100/Beautiify#406]
### Description

The idea is to create a **Newsletter Subscription Form** for those who want a form pre-build newsletter subscription form.

If this issue is valid then assign me to work on this under **JWOC**

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to add it under the Forms category? @this-is-yaash

**Comment by this-is-yaash** [comment]
Yes, under the **Forms** category.

**Comment by Rakesh9100** [comment]
Proceed @this-is-yaash

**Comment by this-is-yaash** [comment]
Didn't you add the difficulty tag?

**Comment by this-is-yaash** [comment]
@Rakesh9100 May I know the time limit?

**Comment by Rakesh9100** [comment]
Status of your PR @this-is-yaash

**Comment by this-is-yaash** [comment]
I didn't started yet, I'll submit it tomorrow.
Please mention the difficulty tag!

**Comment by this-is-yaash** [comment]
@Rakesh9100 can you please mention the difficulty tag

**Comment by Rakesh9100** [comment]
Difficulty label will be added based on the quality of PR and the work done @this-is-yaash

**Comment by this-is-yaash** [comment]
Alright

**Comment by Rakesh9100** [comment]
PR status @this-is-yaash

**Comment by this-is-yaash** [comment]
Apologies, I have exams scheduled until next week, so I won't be able to work on this issue during that time.
Please un-assign me from this issue.

Thanks!

**Comment by AftabMankapure** [comment]
Assign me under jwoc 

i will add it above the footer 
or any other place you want

**Comment by saurav2208** [comment]
@Rakesh9100 I would like to work on this issue. Please assign me.

**Comment by Rakesh9100** [comment]
Proceed @saurav2208

**Comment by Rakesh9100** [comment]
Status of your PR @saurav2208

**Comment by saurav2208** [comment]
> Status of your PR @saurav2208

Working on it

**Comment by Rakesh9100** [comment]
Provide your PR by today @saurav2208
