### ISSUE TITLE
[Feature] Adding Cyber Radio Button

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/Beautiify#407]
### Description

I want to add a new button i.e. Cyber Radio Button... That on hover Shows the 3d cyber blurring text effect

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Can you show the demo screenshot of this button @Sakshamjain98

**Comment by Sakshamjain98** [comment]
![Screenshot_20240126_194705_Chrome.jpg](https://github.com/Rakesh9100/Beautiify/assets/137368917/6698b70c-fdd8-4008-a9f4-99fdaf6beb6b)

**Comment by Rakesh9100** [comment]
Show the hovering screenshot or demo video @Sakshamjain98

**Comment by Sakshamjain98** [comment]
https://github.com/Rakesh9100/Beautiify/assets/137368917/8eb62eb3-a903-4346-b3f5-c7efa13fbcbf

**Comment by Rakesh9100** [comment]
Proceed @Sakshamjain98

**Comment by Rakesh9100** [comment]
PR status @Sakshamjain98
