### ISSUE TITLE
Add Accordion Component

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#41]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As this website contains a list many useful website components, I want to add an Accordion component in the list along with an example accordion inside it. 

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @saurav2208
