### ISSUE TITLE
Adding icon on nav bar

### ISSUE THREAD

**Issue by Vishalkr10** [Rakesh9100/Beautiify#412]
### What's the style idea?

We need to add icon to nav bar on every page as it's already on home page. In home page, home icon is beside home and components icon is beside components button etc.  And same i have to add to every page.
![Screenshot (8)](https://github.com/Rakesh9100/Beautiify/assets/118299098/18dfd0f9-4fc2-411e-8727-4ee86ac58f62)
![Screenshot (9)](https://github.com/Rakesh9100/Beautiify/assets/118299098/8a390a43-159c-4fa4-8268-01b0b7bf2aa0)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vishalkr10** [comment]
@Rakesh9100 pls do assign me under SWOC.

**Comment by Rakesh9100** [comment]
Proceed @Vishalkr10
