### ISSUE TITLE
[Feature] Adding Pulse Animated Navigation Bar

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/Beautiify#413]
### Description

we can add a new navigation bar which is pulse animated navigation bar in components 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/147225647/dd5ffb34-81c5-48a7-b123-e80d1b6e01a2

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by student-aditipaliwal** [comment]
PLEASE ASSSIGN THIS ISSUE TO ME

**Comment by Rakesh9100** [comment]
Pls complete the issues assigned to you first in my every projects @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
Ok, I will do it.

**Comment by Rakesh9100** [comment]
Do you want to get assigned @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
Yes, I would.

**Comment by student-aditipaliwal** [comment]
sir I have completed event form please check that

**Comment by Rakesh9100** [comment]
Assigning, proceed @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
work is done please check whose PR : #518

**Comment by Rakesh9100** [comment]
Check the comment on your PR pls @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
its done by me its my PR which was generated by me whose number is 518
