### ISSUE TITLE
[Feature] Adding Event Form

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/Beautiify#414]
### Description

Adding a new component in form an EVENT FORM 

### Screenshots

![Event Form with Vibrant Colors and Animations and 56 more pages - Personal - Microsoft​ Edge 24-01-2024 02_10_33](https://github.com/Rakesh9100/Beautiify/assets/147225647/7333e569-43cd-4ab5-b19d-df2d83b56ff6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by student-aditipaliwal** [comment]
please assign this issue to me

**Comment by Shubh484** [comment]
Please assign this issue to me. I will create an interactive one.

**Comment by student-aditipaliwal** [comment]
I can also enhance it sir ,it's just a proposal to add a new form ,please
assign this issue to me .

**Comment by Rakesh9100** [comment]
Proceed @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
thanku for assigning this task to me

**Comment by Rakesh9100** [comment]
Pls create your PR by today else you will be unassigned and issue will be closed @student-aditipaliwal

**Comment by Shubh484** [comment]
Kindly assign this to me.
Thankyou

**Comment by student-aditipaliwal** [comment]
ok sir I have done it it's PR is 517
