### ISSUE TITLE
[Bug] Copyright year missing in the footer section

### ISSUE THREAD

**Issue by gauravsingh1281** [Rakesh9100/Beautiify#417]
### Screenshots

<img width="960" alt="Screenshot 2024-01-24 145456" src="https://github.com/Rakesh9100/Beautiify/assets/85905403/f218dc8d-b9c2-4ea0-ae60-7f6452384b92">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by gauravsingh1281** [comment]
@Rakesh9100 Please assign this issue to me under the SWOC label.

**Comment by Rakesh9100** [comment]
Proceed @gauravsingh1281
