### ISSUE TITLE
[Feature] Adding a new button

### ISSUE THREAD

**Issue by Sakshamjain98** [Rakesh9100/Beautiify#419]
### Description

the button shows an animation on hover 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by vaishnavi192** [comment]
does this issue comes under DWOC'24? which category? I want to work on it

**Comment by Sakshamjain98** [comment]
Sir please assign me this issue
