### ISSUE TITLE
Adding icons to the nav bar components in contact page , like home page.

### ISSUE THREAD

**Issue by adi-exe** [Rakesh9100/Beautiify#421]
### Description

The components for navigation like home, contact , contributors have icons in the home page but it isn't there in contact page.
can you please assign this task to me under IWOC24.

### Screenshots

![Screenshot (121)](https://github.com/Rakesh9100/Beautiify/assets/134140404/d2b48ac3-e9e8-4100-aadc-932345c8b6a3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by adi-exe** [comment]
can you assign this to me please @Rakesh9100

**Comment by akarshi19** [comment]
Please assign me this task under 'JWOC'2024'

**Comment by Rakesh9100** [comment]
This is already completed in previous issue @adi-exe
