### ISSUE TITLE
[Feature] Adding Product Card

### ISSUE THREAD

**Issue by TanushreeBorase** [Rakesh9100/Beautiify#423]
### Description

I want to add a product card.

Screenshot
<img width="513" alt="image" src="https://github.com/Rakesh9100/Beautiify/assets/130696335/429264a6-19d6-4297-b096-ee7a4df24fde">
with hover effect

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @TanushreeBorase
