### ISSUE TITLE
[Feature] Adding Screensaver Background

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#426]
### Description

I would like to add Screensaver Background in Background section.Please assign this issue to me.I would like to work on it.

### Screenshots

Uploading Document - Profile 1 - Microsoft​ Edge 2024-01-25 00-08-26.mp4…

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by mansi1309** [comment]
https://github.com/Rakesh9100/Beautiify/assets/133951716/2129d5a3-41ba-4da0-bb35-11537c894dc0

![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/6581a4b8-bef0-4c60-bb1e-923cf07e8d3a)

**Comment by Rakesh9100** [comment]
Proceed @mansi1309

**Comment by mansi1309** [comment]
okay
