### ISSUE TITLE
[Feature] Adding Gliding Diagonals Background

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/Beautiify#428]
### Description

I want to add a Gliding Diagonals Background using CSS

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140608790/6da6a41a-94d7-4a7a-a3bb-444ed1b1f571

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Please assign me this under IWOC

**Comment by Rakesh9100** [comment]
Proceed @JiyaGupta-cs
