### ISSUE TITLE
[Style] Fixing CSS style for Neumorphic Accordion 

### ISSUE THREAD

**Issue by Prutha-Upadhyay** [Rakesh9100/Beautiify#429]
### What's the style idea?

I would like to fix CSS style  for Neumorphic Accordion!!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What style you want to add/fix @Prutha-Upadhyay

**Comment by Rakesh9100** [comment]
Proceed @Prutha-Upadhyay
