### ISSUE TITLE
[Feat]: Color combination can be improved 

### ISSUE THREAD

**Issue by Yatin12527** [Rakesh9100/Beautiify#43]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I think the color combination is very dull and it can be improved 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/134225415/36f9c4d3-fe9d-4923-8f66-10686a9af5b2)
I can work with different combination and try to improve the color and background. I will try to work on a darker theme to give the site a very aesthetic look

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Yatin12527** [comment]
> Enhancement of UI issue is already open. So pls wait and work on other issues @Yatin12527

yea if you feel unsatisfied with the design i can give it a try aswell.

**Comment by Rakesh9100** [comment]
Okay continue @Yatin12527

**Comment by Rakesh9100** [comment]
UI enhancement is already been done by someone. Pls work on other issues @Yatin12527
