### ISSUE TITLE
[Feature] Adding OTP Verification Form & Drag and Drop Form

### ISSUE THREAD

**Issue by ratnojitsaha** [Rakesh9100/Beautiify#430]
### What would you like to share?

I WANT TO ADD 4 FORMS IN THE [ Forms ] PAGE.
Here are the forms ---
1. OTP code verification form - Basic Otp enter and submit form using html css and js.
2. Drag and Drop form - Allow users to drag and drop elements (like files or options) into the form for submission..
3. Text To Voice Converter form - Contains a text area to write texts and later converts it into voice .
4. QR Code generator form - Just enter any url of a website and get a qr code .
5. Modal/ Popup login form - Create a form that pops up in a modal window when a button is clicked..

### Additional information

It is an add-on/enhancement issue raised to contribute under ******JWOC 2024********

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to add all these forms in this same issue @ratnojitsaha

**Comment by ratnojitsaha** [comment]
I want a hard issue to solve, if doing all these comes under hard, then I'm happy to do

**Comment by ratnojitsaha** [comment]
@Rakesh9100 IF U SAY U WILL GIVE ME MEDIUM/HARD FOR 2-3 OF THEM THEN I CAN DO IT IN 2 ISSUES, ELSE IN 1 GO

**Comment by ratnojitsaha** [comment]
@Rakesh9100 Please Assgn me under JWOC 2024

**Comment by Rakesh9100** [comment]
You can go for first 2 forms in this issue @ratnojitsaha

**Comment by Rakesh9100** [comment]
PR status pls @ratnojitsaha

**Comment by prakharsingh-74** [comment]
@Rakesh9100 I would like to contribute in this issue under JWOC

**Comment by ratnojitsaha** [comment]
@Rakesh9100 working in it, sry for delay

**Comment by Rakesh9100** [comment]
Provide your PR by today @ratnojitsaha
