### ISSUE TITLE
[Bug] Fix the links of social media icons

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#432]
### Description

Links of social media icons in footer of about section is not correct.
and for contect page it is not mentioned as shown in video.

Kindly assign this to me under IWOC2024.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/149922307/f4148789-8770-4ac7-bbb9-9de5a5c58b47

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Prince-kushwaha-2004

**Comment by Rakesh9100** [comment]
Merged 🎉 @Prince-kushwaha-2004
