### ISSUE TITLE
[Feature] Adding an animated Login/Signup form

### ISSUE THREAD

**Issue by JATIN0926** [Rakesh9100/Beautiify#433]
### Description

In this form firstly we will see login and before that there will be a signup form tilted and then when you click on signup the signup page will come in front with a animation , i am attaching a screenshot for reference

### Screenshots

<img width="960" alt="Login_Signup page_ss" src="https://github.com/Rakesh9100/Beautiify/assets/124780421/c59fbb69-47bf-45de-b8d0-4d4cdbb7f094">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @JATIN0926
