### ISSUE TITLE
[Feature] Adding Newton Cradle Loader

### ISSUE THREAD

**Issue by bera474** [Rakesh9100/Beautiify#435]
### Description

I want to add  Newtons Cradle Loader into the Loader Section. I am attaching the loader screenshot. Please assign me this issue under JWOC 2024.

### Screenshots

![Screenshot (74)](https://github.com/Rakesh9100/Beautiify/assets/118124036/878b5d12-2345-41a5-aa35-193eb732720c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @bera474
