### ISSUE TITLE
[Feature] Adding Pendulum Loader

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#437]
### Description

I want to add a new pendulum Loader into the loader components.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/e21f8114-11d3-4a49-a438-4644e1a8c935

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Abidsyed25
