### ISSUE TITLE
[Feature] Adding a Neumorphic Carousel

### ISSUE THREAD

**Issue by SoumyadevSaha** [Rakesh9100/Beautiify#438]
### Description

I want to add a neumorphic Carousel to the list of carousels under components. Please assign me this issue under IWOC

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SoumyadevSaha

**Comment by Rakesh9100** [comment]
PR status @SoumyadevSaha

**Comment by SoumyadevSaha** [comment]
> PR status @SoumyadevSaha

Extremely sorry for the delay, actually I was facing some serious health issues during the last week, and even now. I had my PR ad all ready, but was forgot to push.

**Comment by Rakesh9100** [comment]
Okay, no problem!!

Take care @SoumyadevSaha
