### ISSUE TITLE
[Style] Enhancement of Components card

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#441]
### Description

Enhancement of Components card with animation and new styling.
It will make website more beautiful.

Kindly watch the attached video and suggest any other changes in styling.

Kindly assign this to me under IWOC2024.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/149922307/52a1896f-5f6d-470a-aeb4-ef7f6d10160e

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Kindly check

**Comment by Prince-kushwaha-2004** [comment]
I will add it to both light and dark mode. 
Dark mode will have different styling which will match with dark them .

**Comment by Prince-kushwaha-2004** [comment]
This is how cards will appear in dark mode I am working on it I will do some more changes.
![Screenshot 2024-01-30 161441](https://github.com/Rakesh9100/Beautiify/assets/149922307/57eb9863-ec25-4ffc-a62a-07ca7eb71e53)

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
Kindly assign this to me under IWOC2024

**Comment by Rakesh9100** [comment]
Okay proceed @Prince-kushwaha-2004

**Comment by Prince-kushwaha-2004** [comment]
@Rakesh9100 
??

**Comment by Rakesh9100** [comment]
In the light theme, background is already purple and your cards are also most purple which is becoming dominant.

For now, you can go with changing the hover effects accordingly you have made but don't change the size of the cards or colors of it, you can also enhance the cards in the dark theme @Prince-kushwaha-2004
