### ISSUE TITLE
[Feature] FeedBack Page

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/Beautiify#448]
### Description

Hello @Rakesh9100, I did like to suggest you that we should add feedback page in website to take user response over experience they have over our website. We should have created an seperate email account for the website to receive those responses. Kindly look into this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need of this. Pls work on other issues @Yuvraj960
