### ISSUE TITLE
[Style] Enhance the Home page

### ISSUE THREAD

**Issue by Yuvraj960** [Rakesh9100/Beautiify#449]
### What's the style idea?

We need to improve the overall look and feel of the Landing page of the website. I want to improve the hover effects of the cards made, the navbar, etc.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Waht do you mean by overall look, as I need some screenshots or reference of your changes @Yuvraj960

**Comment by Yuvraj960** [comment]
Ok Rakesh.

Style 1:
![image](https://github.com/Rakesh9100/Beautiify/assets/146326636/6b480f9d-f8ab-4839-bb55-95c566fd9f55)
Please refer to below right corner, the positioning of your chatbot button with the back-to-top button seems weird. Either we have to shift the chatbot button or the back to top button on the below left corner of the website.

Style 2:
![Screenshot 2024-01-28 093924](https://github.com/Rakesh9100/Beautiify/assets/146326636/307a0f03-9973-40df-8d55-964c2ca2f24b)
We can add the Better UI for the Navbar, And Kinda add separation between the top page and rest scrolled website to add differentiation. Please see below the page reference:

https://github.com/Rakesh9100/Beautiify/assets/146326636/5c43445b-286c-46a1-a451-771eaa691bef

Style 3:
We can change the cards of the website.
Please refer to below attached video, I have 3 different designs to apply, the one you like I will apply it.

https://github.com/Rakesh9100/Beautiify/assets/146326636/dde3aeaa-8a3a-4852-ab31-40d99fe6cf96

Style 4: (Optional Change)
We can introduce the feedback system from users just like:

https://github.com/Rakesh9100/Beautiify/assets/146326636/ffdc9e5f-025b-4b65-9dcb-0b1fbe17e908

We can add this anywhere in the website, if want to.

Style 5:
We can change the social icon hover effects:

https://github.com/Rakesh9100/Beautiify/assets/146326636/6aaae420-2424-4b63-8fe9-87b0088f8824

This is all I think should be changed to enhance user experience. 
You can also suggest me some of the changes that you want in your website, I will try find the best alternative style to that.

**Comment by Yuvraj960** [comment]
I want to add the above enhancements to the website. 
@Rakesh9100, If you think something is wrong in my suggestion, please correct me.

**Comment by Rakesh9100** [comment]
Pls hold for now, will update you soon as one issue is already open before for enhancing the cards @Yuvraj960

**Comment by Rakesh9100** [comment]
Do you want to be assigned @Yuvraj960

**Comment by Yuvraj960** [comment]
Yes @Rakesh9100, I want to be get assigned, But can you please specify me the changes you want in the redesign of the website.

**Comment by Rakesh9100** [comment]
The website is already redesigned and looks good, so I don't have any specific idea for now. If you have, you can tell me @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, I did like to change the design of the navbar of the Website as it doesn't look aesthetic on the website. It doesn't differentiate it's presence on the website. Same goes through the footer. I did like to redesign Navbar and footer section of the website.

**Comment by Rakesh9100** [comment]
Okay proceed and give your best, will merge if it will look good @Yuvraj960

**Comment by Rakesh9100** [comment]
Status of your PR pls @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100 , my new page development is in very early stages  as my exams are there and I have fever also, but I assure you, that my pr will be there next week in the pr section😇. Sorry for being late for this particular issue🙏

**Comment by Rakesh9100** [comment]
No issues, take care of your health first @Yuvraj960

**Comment by Yuvraj960** [comment]
@Rakesh9100, due to fever I was not very active on this issue. 
Just updated my fork and seen that there are many design changes done for which I was developing code before fever, very sad to see this. 
But still, I have something to add in the website code:
1) I can add the smooth transition when dark-light mode toggles
2) I can alter the appearance of footer, as at present it seems like a normal part of website, but after the changes I will make it a highlighted part of the website by completely revamping its look.
3) I want to change the location of the chat bot button as it comes in way of the back-to-top button.
4) Add some missing hover effects in website (navbar items, get compo... button, etc.)
This is all, I can change on the website as of now, rest if you can suggest any major change, you think is to be done on the website, please tell.
And also, if you think that the above changes need not to be done necessarily, please close the issue.

**Comment by Rakesh9100** [comment]
I have updated the cards design 2 days back to which it was before the new design due to some issue. So you can update and revamp the cards design, its hover effects on the home page to give a good look.

Navbar slight update has been done, so make sure to update your forked repo.

Alignment of chatbot button is already open, so leave this for now.

And also go for the enhancements you mentioned!! @Yuvraj960
