### ISSUE TITLE
[Feature] Addition of voice command feature to searchbar

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#450]
### Description

Addition of voice command feature to search bar using web speech API
It will made website more user friendly and beautiful.

Kindly assign this to me under IWOC2024.

### Screenshots

![Screenshot 2024-01-27 215803](https://github.com/Rakesh9100/Beautiify/assets/149922307/6f6e9e51-c6bd-4e6c-b2fd-bc6eb0f1067d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Prince-kushwaha-2004
