### ISSUE TITLE
[Feature] Adding Gradient Stroke & Bounce Loader

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#453]
### Description

I would like to add Gradient Stroke & Bounce Loader in Loaders section.
Please assign this issue to me.

https://github.com/Rakesh9100/Beautiify/assets/133951716/3fdf81d0-5aba-4810-b367-c51f23bfb14d

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/133951716/b7b227e6-f37c-48dc-8f5b-ca7092ded04b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @mansi1309
