### ISSUE TITLE
[Feature] Buttons section change

### ISSUE THREAD

**Issue by JATIN0926** [Rakesh9100/Beautiify#456]
### Description

I think it is not a good way to put the buttons into card forms , buttons should be displayed on screen and on clicking it or after clicking on copy css button, it's css should be copied, that's a useful way to utilise buttons , user just want to come and see buttons and just copy them 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What are you trying to specify, pls mention clearly @JATIN0926

**Comment by JATIN0926** [comment]
![Screenshot_2024-01-28-06-08-57-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Rakesh9100/Beautiify/assets/124780421/151313b7-5f85-4a8a-bdef-7aa39fa034d3)


I want that buttons should be displayed like this and we can provide 2 icons below , one for copy css and other for GitHub may be , you suggest me if I will do this then how should be tha structure of the page ?

**Comment by Rakesh9100** [comment]
I suppose we don't need this. Anyone can directly go to the source code by clicking on GitHub logo and get the required files of that button component and copy and use those codes @JATIN0926
