### ISSUE TITLE
[Feature] Adding Cart Checkout Form

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/Beautiify#457]
### Description

I want to add a cart checkout  form

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/140608790/6aefa958-6c69-4dd7-aecb-db288ba6ebbf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @JiyaGupta-cs
