### ISSUE TITLE
[Bug] Redirection problem on about page

### ISSUE THREAD

**Issue by rajpootjyoti700** [Rakesh9100/Beautiify#458]
### Description

when we are on the about page and we click the about option again on the nav bar the whole page reloads this can be the major security issue as well becoz the content in about section is static so no need of refresh this page again nd again just like when we click HOME  page in 2nd or third time it is not refreshing .

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/133164017/782907da-cdb7-4ea8-98b7-882597df48df

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by rajpootjyoti700** [comment]
plz this issue to me i want to work on it

**Comment by Rakesh9100** [comment]
Proceed @rajpootjyoti700 

Fix for the Contributors and Contact as well!!

**Comment by rajpootjyoti700** [comment]
> Proceed @rajpootjyoti700
> 
> Fix for the Contributors and Contact as well!!

ok i will fix for contact nd other but in contributor every time we need to add new contributor So i think no need for contributor if u want i will fix it

**Comment by Rakesh9100** [comment]
Status of your PR pls @rajpootjyoti700

**Comment by Rakesh9100** [comment]
Issue will be closed if PR is not up by today @rajpootjyoti700

**Comment by rajpootjyoti700** [comment]
give me 1 or 2 days more will update u soon

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Rakesh9100** [comment]
Proceed @SohanRC
