### ISSUE TITLE
[Feature] Animated SignIn Form

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#459]
### Description

Wanna add a animated sign in form which has some animated background.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/c74ecc5c-7d32-40ed-a779-1bf3d8b8b892)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha
