### ISSUE TITLE
[Feature] Adding a coalesce background

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#462]
### Description

I want to add a coalesce background under backgrounds component.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Provide the demo video of your background pls @saurav2208

**Comment by saurav2208** [comment]
> Provide the demo video of your background pls @saurav2208


https://github.com/Rakesh9100/Beautiify/assets/125905089/2d93d257-9e7d-4095-b77c-75594574db60

**Comment by Rakesh9100** [comment]
Proceed @saurav2208
