### ISSUE TITLE
[Feature] Adding a Mouse-Responsive Web Background

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#463]
### Description

I would like to add a mouse-responsive Web Background under backgrounds component.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
PR Status @saurav2208

**Comment by Rakesh9100** [comment]
Do you want to get assigned @saurav2208

**Comment by saurav2208** [comment]
> Do you want to get assigned @saurav2208

Yes

**Comment by Rakesh9100** [comment]
Provide the demo screenshot of your component @saurav2208

**Comment by saurav2208** [comment]
https://github.com/Rakesh9100/Beautiify/assets/125905089/6be774b1-1d07-438c-82c6-2d9695223b57

**Comment by Rakesh9100** [comment]
Proceed @saurav2208
