### ISSUE TITLE
[Feature] Animated triangle loader

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/Beautiify#464]
### Description

Adding an animated triangle loader under loaders component

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the screenshot or demo video @bhavya-anand19

**Comment by bhavya-anand19** [comment]
> Pls provide the screenshot or demo video @bhavya-anand19


https://github.com/Rakesh9100/Beautiify/assets/133582773/2f3e3aff-4362-4fe0-b616-2430853d60c5

**Comment by Rakesh9100** [comment]
Go ahead @bhavya-anand19
