### ISSUE TITLE
[Feature] Adding Polygon Loader

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/Beautiify#465]
### Description

Adding a rebound animation polygon loader under loaders component.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by muskan42** [comment]
@Rakesh9100 kindly assign me the issue under SWOC.

**Comment by Rakesh9100** [comment]
Provide the demo video of your loader pls @bhavya-anand19

**Comment by bhavya-anand19** [comment]
> Provide the demo video of your loader pls @bhavya-anand19


https://github.com/Rakesh9100/Beautiify/assets/133582773/e5eee058-4533-4e34-8028-a4947477cd72

**Comment by Rakesh9100** [comment]
Do you want to get assigned @bhavya-anand19

**Comment by bhavya-anand19** [comment]
> Do you want to get assigned @bhavya-anand19

Yes

**Comment by Rakesh9100** [comment]
Proceed @bhavya-anand19
