### ISSUE TITLE
[Feature] Adding Clocks Components Category

### ISSUE THREAD

**Issue by muskan42** [Rakesh9100/Beautiify#466]
### Description

I would like to add a clock component to the project.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by muskan42** [comment]
@Rakesh9100 kindly assign me the issue under SWOC'24.

**Comment by Rakesh9100** [comment]
In which category you want to add this @muskan42

**Comment by muskan42** [comment]
@Rakesh9100 I want to make a separate category for different types of clocks and stopwatches.

**Comment by Rakesh9100** [comment]
Proceed @muskan42

**Comment by Rakesh9100** [comment]
Status of your PR @muskan42
