### ISSUE TITLE
Add logo to Header and fix title logo

### ISSUE THREAD

**Issue by rizkisepriadi** [Rakesh9100/Beautiify#47]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello @Rakesh9100  , I want to add a logo to the Header and fix the title logo to make it consistent, details you can check on the screenshot below. Thank you

### Screenshots

<img width="960" alt="Screenshot 2024-01-04 113240" src="https://github.com/Rakesh9100/Beautiify/assets/97104464/e7f7195f-d3e7-4c4f-92a4-b16b80aa40b9">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by kamalsritha** [comment]
can you please assign me this issue under SWOC.

**Comment by Rakesh9100** [comment]
Not needed. Pls work on other good issues @rizkisepriadi
