### ISSUE TITLE
[Feature] Adding scroll to top button in every component

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#471]
### Description

The scroll to top button is there in the home page but it is missing in the components page. I want to add scroll to top button in every component. I am attaching below screenshot for reference

### Screenshots

**After adding scroll to top button in every component**

![go_to_top](https://github.com/Rakesh9100/Beautiify/assets/116893970/bb7a0f29-2027-433a-a678-b3893d101e57)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abidsyed25** [comment]
@Rakesh9100 please assign me this issue. I am ready with a pull request.

**Comment by Rakesh9100** [comment]
Proceed @Abidsyed25
