### ISSUE TITLE
[Feature] Addition of Blob Button

### ISSUE THREAD

**Issue by ayusharyann** [Rakesh9100/Beautiify#473]
### Description

https://github.com/Rakesh9100/Beautiify/assets/144141216/0f1b928c-07b9-4dd2-b17e-c17173bdc8a9

I want to add a button with blob effect in buttons section . This is the demo of button 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @ayusharyann
