### ISSUE TITLE
[Feature] Adding Swipe Right Button

### ISSUE THREAD

**Issue by 12Indranil** [Rakesh9100/Beautiify#474]
### Description

I want to add a button in button section with button change feature. This is a demo of the button.

https://github.com/Rakesh9100/Beautiify/assets/134200046/11ea0f48-e2b3-4b64-9de9-454a8636e98e

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What name you will provide to this button @12Indranil

**Comment by 12Indranil** [comment]
@Rakesh9100 The name of the button will be given as: Swipe Right Button

**Comment by Rakesh9100** [comment]
Go ahead @12Indranil
