### ISSUE TITLE
[Feature] Addition of Thin button

### ISSUE THREAD

**Issue by Devanshu53** [Rakesh9100/Beautiify#475]
### Description

Want to add a Thin button with modern actions in Button component. 

https://github.com/Rakesh9100/Beautiify/assets/138321835/4d5de32e-5493-4a9b-bd31-d02b89c08081

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Devanshu53
