### ISSUE TITLE
[Feature] Adding Wiggle Button

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#477]
### Description

I would like to add wiggle button in button section.
I would like to work on it, Please assign this to me.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/133951716/01aa9f84-d6cd-447f-ba9b-1cd91abc63f4

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @mansi1309

**Comment by mansi1309** [comment]
okay..
