### ISSUE TITLE
[Feature] Adding a Maze Loader

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#478]
### Description

I would like to add a maze loader under loaders section
Please assign me under the IWOC 2024 
For further information refer to given video

https://github.com/Rakesh9100/Beautiify/assets/125133940/0f9aa8b1-7adf-492f-82ff-868a1d432618

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed and make sure loader should be in the center of the screen @Dhairya1Gupta
