### ISSUE TITLE
[Style] Enhance Glassmorphism Card

### ISSUE THREAD

**Issue by mschandana16** [Rakesh9100/Beautiify#479]
### Description

Pls assign this issue to me so that I can fix it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
It is just a component, what functional you want to fix @mschandana16

**Comment by mschandana16** [comment]
@Rakesh9100 I wanted to make it movable on hovering

**Comment by Rakesh9100** [comment]
Proceed @mschandana16

**Comment by Rakesh9100** [comment]
PR Status @mschandana16
