### ISSUE TITLE
[Feature] Adding Glow Up Button

### ISSUE THREAD

**Issue by SohanRC** [Rakesh9100/Beautiify#480]
### Description

Add a new animated button ! I am attaching a video here ! Please assign me under JWOC 2024.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/124901633/99b7e4dc-1e27-40c0-8549-f15bedbecbc1

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What name you will provide to this button @SohanRC

**Comment by SohanRC** [comment]
@Rakesh9100  Glow Up Button

**Comment by Rakesh9100** [comment]
Proceed @SohanRC
