### ISSUE TITLE
[Feature] Adding Playlist Carousel

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#482]
### Description

Playlist Carousel

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/7e0550f5-3b39-4a97-b12d-528ccd62fb28)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha
