### ISSUE TITLE
[Feature] Adding Animated Carousel

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#483]
### Description

Animated Carousel

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/620f62d9-0bf4-4583-b9c5-d7b9a4475a70)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha
