### ISSUE TITLE
[Feature] Adding Animated Genesis Login Form

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/Beautiify#484]
### Description

I want to add an Animated Opening and Closing Login Form

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140608790/5986766a-a14c-4b83-be60-f408947b202c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
In which category you want to add this and what name you will provide to this component @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100
Under forms category
With the name 'Animated Genesis Form'

**Comment by Rakesh9100** [comment]
Okay, will assign after you complete the assigned issue first @JiyaGupta-cs

**Comment by Rakesh9100** [comment]
Proceed @JiyaGupta-cs

**Comment by Rakesh9100** [comment]
PR status pls @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 Working on it

**Comment by Rakesh9100** [comment]
Provide your PR @JiyaGupta-cs

**Comment by Rakesh9100** [comment]
You will be unassigned if PR is not up by today @JiyaGupta-cs
