### ISSUE TITLE
[Feature] Adding Progression Form

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Rakesh9100/Beautiify#485]
### Description

I want to add a progression form which will be filled step by step and it will grew bigger as it proceeds

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/140608790/9b62f2d2-14ac-4da6-b1c7-87d2cc5db3d4

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @JiyaGupta-cs

**Comment by JiyaGupta-cs** [comment]
@Rakesh9100 I have opened a new PR for this as per the changes you said
