### ISSUE TITLE
[Feature] Adding Rainbow Animation Buttons

### ISSUE THREAD

**Issue by zul132** [Rakesh9100/Beautiify#487]
### Description

I would like to add a new Button component consisting of 5 animated buttons with Rainbow hover effects.

### Screenshots

Here's a sample screenshot of the buttons:
![Screenshot 2024-01-30 082028](https://github.com/Rakesh9100/Beautiify/assets/98112914/0597ff25-63db-4b8b-9e8e-0860381589d9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by zul132** [comment]
@Rakesh9100 I would like to work on this issue under JWOC, please assign it to me.

**Comment by Rakesh9100** [comment]
Proceed @zul132
