### ISSUE TITLE
[Feature] Adding Blog Post Card

### ISSUE THREAD

**Issue by Arushi-Kapkoti** [Rakesh9100/Beautiify#490]
### Description

I would like to add a new card called Blog Post Card. I have also attached the screenshot below. I would also like to ask if I should leave it like this (a single blog) or make a grid layout of multiple cards.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/114429172/3c702641-26c2-4ce9-beff-ada2440235e3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Arushi-Kapkoti 

You can add multiple cards using grid layout!!
