### ISSUE TITLE
[Feature] Adding Search Function into each Components

### ISSUE THREAD

**Issue by Surajit0573** [Rakesh9100/Beautiify#496]
### Description

The search function is only available on the home page to search components. I want to add a search function to every component page also, to specifically search any element into that component.

Assign me under JWOC 2024, if approved.

### Screenshots

Ex : I will add a search function here to search backgrounds...

![image](https://github.com/Rakesh9100/Beautiify/assets/111490250/71f67ce7-2867-4996-bb32-6f153c37dd01)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Surajit0573

**Comment by Rakesh9100** [comment]
Status of your PR @Surajit0573

**Comment by Surajit0573** [comment]
working on it...will PR before end of the day.
