### ISSUE TITLE
[Feature] Adding 3D Hover Effect Button

### ISSUE THREAD

**Issue by Dhairya1Gupta** [Rakesh9100/Beautiify#501]
### Description

I would like to add a 3D-hover effect button which will change after hovering on it.
Please refer to given video

https://github.com/Rakesh9100/Beautiify/assets/125133940/7f49d42c-675f-4c6b-8ec6-34932a9b65ab

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Status of your PR pls @Dhairya1Gupta
