### ISSUE TITLE
[Feature] Adding Product Preview Card

### ISSUE THREAD

**Issue by AlefiyaAbbas** [Rakesh9100/Beautiify#502]
### Description

I would like to add a card which displays the product image. When hovered the product name, details and ratings will be revealed and the the image will be blurred and animated behind.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/94435326/43a0929c-fe35-420f-8b5f-18c1f0178142

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What name you will provide to this card @AlefiyaAbbas

**Comment by AlefiyaAbbas** [comment]
Product Preview Card or OnHover Product Preview Card.

Do you have any suggestions? @Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed and name it `Product-Preview-Card` @AlefiyaAbbas

**Comment by Rakesh9100** [comment]
PR status pls @AlefiyaAbbas

**Comment by AlefiyaAbbas** [comment]
I will complete it by tonight. @Rakesh9100
