### ISSUE TITLE
[Feature] Adding User Attention Card

### ISSUE THREAD

**Issue by srshah27** [Rakesh9100/Beautiify#504]
### Description

I would like to add new cards to display various informative contents to the user. That are StyleBox, CodeBox, WarningBox, ErrorBox, InfoBox. I have used them on my portfolio site you can check them on this [example](https://www.srshah.me/example) page.

If you like my idea please assign it to me under SWOC'24.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/83776946/fbe51606-0e49-4f7b-98cd-6825107a0a76

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to add it in Cards category as a component @srshah27

**Comment by srshah27** [comment]
Yes sure

**Comment by Rakesh9100** [comment]
What name you will provide your card component @srshah27

**Comment by srshah27** [comment]
User-Attention-Cards seems fit to me. Do you have any other suggestions?

**Comment by Rakesh9100** [comment]
Okay, proceed and name it `User-Attention-Card` @srshah27

**Comment by Rakesh9100** [comment]
Status of your PR @srshah27

**Comment by srshah27** [comment]
Almost finished will submit a PR tonight
