### ISSUE TITLE
[Bug] Fix the movement of hovering effect on cards

### ISSUE THREAD

**Issue by ankit1576** [Rakesh9100/Beautiify#509]
### What's the style idea?

We need to improve this hover animation things like you can see while hovering of the component card it seems to be little  displaced from its original position this need to be fix 

:-this arrow in the screenshot displays that on hovering the card it slighty shifted(moved) which not looks good makes the page gittery and unprfessional
![image](https://github.com/Rakesh9100/Beautiify/assets/71921877/514e66d3-9781-46f6-a1fa-cd44e6bb81de)

+ we need to change the one more thing that for redirecting to the new page  to see the content preview we need to click specifically on link istead of that we can add link to card itselt to directly redirect to the page
![image](https://github.com/Rakesh9100/Beautiify/assets/71921877/5fb4799f-8562-4533-832f-f88dc15dc8b2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed only for fixing card hover effect and not to make the card itself a link @ankit1576

**Comment by ankit1576** [comment]
ok thanks
