### ISSUE TITLE
images overlapping

### ISSUE THREAD

**Issue by Nandini80** [Rakesh9100/Beautiify#510]
### Description

The overlap between the bot image and the redirect button is affecting the visual presentation, resulting in an unappealing appearance.

### Screenshots

<img width="104" alt="image" src="https://github.com/Rakesh9100/Beautiify/assets/121488571/5ff7fede-7610-4dd7-ba6c-720cf6041bdd">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need, Pls work on other good issues @Nandini80
