### ISSUE TITLE
[Feature] Adding Operating Search Bar

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#513]
### Description

Add a operating search bar , when we click on search button the suggest some operations 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/044e25d5-8404-4115-8371-e4f4aebc1a67)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
