### ISSUE TITLE
[Feature] Animated Stylish Footer

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#516]
### Description

Add a stylish footer where some animated objects are moving 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/c6ea345c-6365-4b85-a275-c105a4151466)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @AbhineshJha
