### ISSUE TITLE
Title: Dynamic Year in Copyright Notice

### ISSUE THREAD

**Issue by zahidgul107** [Rakesh9100/Beautiify#52]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The current copyright notice in the project's footer contains a static year (2023). To ensure it remains up-to-date, it would be beneficial to make the year dynamic, automatically updating to the current year. This helps maintain accuracy without manual intervention. Please assign this isssue to me under SWOC 24. Thank you

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @zahidgul107
