### ISSUE TITLE
[Style] Enhance navbar for small devices

### ISSUE THREAD

**Issue by Gauranshgoel123** [Rakesh9100/Beautiify#521]
### What's the style idea?

We need to improve the nav bar that pops up in case of smaller screens. 
The transparent background can be made better. 
When the cursor is on any of the other pages like home,about,components etc there is no indication or a proper CSS styling done for it. 
![Screenshot 2024-02-04 005449](https://github.com/Rakesh9100/Beautiify/assets/121503835/d294a650-3e92-4562-a658-b1a37b129f38)
I can contribute in that. This is my first open source contribution :)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Gauranshgoel123
