### ISSUE TITLE
[Feature] Adding Dropdown Category and some Components

### ISSUE THREAD

**Issue by AbhineshJha** [Rakesh9100/Beautiify#527]
### Description

I want to add a component -> Dropdown in your collection and add some dropdowns 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/142514166/1ff33466-11cb-4a44-bfe8-f9b3a9164f73)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @AbhineshJha
