### ISSUE TITLE
[Other] Redirecting to new tab issue

### ISSUE THREAD

**Issue by ankit1576** [Rakesh9100/Beautiify#528]
### What would you like to share?

like every time on click of the the component it will redirect to new tab 
![image](https://github.com/Rakesh9100/Beautiify/assets/71921877/0ff98332-0840-4054-b936-b859ea50f3bd)
it will ultimately increase the no of tabs and confusion so we need to make it single page 
i can add back button on component tab+footer in component tab
![image](https://github.com/Rakesh9100/Beautiify/assets/71921877/feb9a93e-6d9d-4255-9207-432f3285e39b)
as you can see in component tab no back button is not available 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Home button on the navbar is already present which can take us back to the home page @ankit1576
