### ISSUE TITLE
[Feature] Adding cookie consent box

### ISSUE THREAD

**Issue by Sneha6003** [Rakesh9100/Beautiify#529]
### Description

I would like to add a cookie consent box for enhanced user experience.
I would like to work on this issue under JWOC.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls elaborate your issue more as what exactly you want to add and where @Sneha6003

**Comment by Sneha6003** [comment]
something like this
![image](https://github.com/Rakesh9100/Beautiify/assets/147996970/dc672b74-cc9c-4fd4-a474-676a7429f641)

**Comment by Rakesh9100** [comment]
No need, pls work on other good issues @Sneha6003
