### ISSUE TITLE
Navbar text overlapping

### ISSUE THREAD

**Issue by Lavanya-Sathya** [Rakesh9100/Beautiify#53]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

When scrolling the home page, there is an undesirable overlap between the page headings and the content within the navbar.

### Screenshots

![Beautiify-issueSceenshot1](https://github.com/Rakesh9100/Beautiify/assets/83652986/5ae2e2a6-09f0-4e76-8863-c0d31c98e9c9)

![Beautiify-issueScreenShot2](https://github.com/Rakesh9100/Beautiify/assets/83652986/0b24f5a8-4e04-41cb-a5b5-299ba95db65b)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Akshatverma01** [comment]
HI @Lavanya-Sathya  I have successfully solved this issue and create a pull request . Kindly merge my pull request and add the tag of SWOC'24.

![Screenshot (71)](https://github.com/Rakesh9100/Beautiify/assets/121783296/ae82d586-df9c-493e-bd41-33c46c6776a8)
![Screenshot (72)](https://github.com/Rakesh9100/Beautiify/assets/121783296/e11985e2-f9b8-456b-b38a-b2305a9f6945)

**Comment by Rakesh9100** [comment]
UI has been changed now completely. Pls work on other issues @Lavanya-Sathya
