### ISSUE TITLE
[Bug] Typo error in About Us Page

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/Beautiify#533]
### Description

in ABOUT US page NAME OF WEBSITE "BEAUTIIFY" is  written as " BEAUTIFY" in some places which should be coreected , since it was the name of the website .

IN SCREENSHOT : defined wrong textby circle and 
correct text by line .

### Screenshots

![Beautiify _ About - Google Chrome 05-02-2024 22_35_16](https://github.com/Rakesh9100/Beautiify/assets/147225647/536e0108-f4c8-4568-89b5-af5347841945)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by student-aditipaliwal** [comment]
please assign this issue to me .

**Comment by Rakesh9100** [comment]
Proceed @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
thanku for assigning , I will do it by tomorrow
