### ISSUE TITLE
[Feature] Add Linear Gradient Animation Background

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/Beautiify#537]
### Description

Adding new linear-gradient animations background

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/125949765/53abe1d6-ace2-4c90-a248-7c4526611ec2

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
assign me

**Comment by Rakesh9100** [comment]
This [Background](https://beautiify.netlify.app/components/backgrounds/animated-triangles-background/) is already present @AftabMankapure
