### ISSUE TITLE
[Bug] About us page is not responsive

### ISSUE THREAD

**Issue by student-aditipaliwal** [Rakesh9100/Beautiify#539]
### Description

the about us page is not responsive when we open in cell phone text get overlaped 

### Screenshots

![(2) WhatsApp - Google Chrome 06-02-2024 13_40_39](https://github.com/Rakesh9100/Beautiify/assets/147225647/fe9ff35d-1539-4dab-95a5-81009016eef6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @student-aditipaliwal

**Comment by Rakesh9100** [comment]
Status of your PR pls @student-aditipaliwal

**Comment by student-aditipaliwal** [comment]
today i will provide u

**Comment by student-aditipaliwal** [comment]
Yes, it's done.

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Rakesh9100** [comment]
Go ahead @AftabMankapure
