### ISSUE TITLE
[Feature] Implement PR Title Checker workflow

### ISSUE THREAD

**Issue by praptisharma28** [Rakesh9100/Beautiify#541]
### Description

The project would benefit from a PR title checker that ensures conformity to conventional commit prefixes to help maintainer keep the track of PRs

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by praptisharma28** [comment]
Assign me @Rakesh9100

**Comment by Rakesh9100** [comment]
No need, please work on other issues @praptisharma28
