### ISSUE TITLE
[Feature] Addition of Type Writer Text Animation

### ISSUE THREAD

**Issue by JATIN0926** [Rakesh9100/Beautiify#542]
### Description

I want to add a typewrite text animation , yes i know it is there , but mine one is different , i am providing you the Link for that animation , now you can decide whether i should add it or not !

https://jatin0926.github.io/Typed-JS/

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @JATIN0926

**Comment by JATIN0926** [comment]
> Go ahead @JATIN0926 

@Rakesh9100 what will be the name for this animation? Because text-writer animation is there

**Comment by Rakesh9100** [comment]
`Typewriter-2-Text-Animation` @JATIN0926
