### ISSUE TITLE
[Feature] Adding GSAP Animations to the website

### ISSUE THREAD

**Issue by JATIN0926** [Rakesh9100/Beautiify#543]
### Description

I want to add some minimilistic or you can say cool animations , which will make the website attractive , you can refer to my this project :

https://elitecricketacademy.netlify.app/

### Screenshots

I have attached a small recording , you can refer above link for whole website

https://github.com/Rakesh9100/Beautiify/assets/124780421/d10832c2-7002-46d4-b759-7380132ee18e

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Asin-Junior-Honore** [comment]
@JATIN0926 please assign me this issue👨‍💻

**Comment by JATIN0926** [comment]
@Rakesh9100 why have to given me status standby, is there any issue ? 😅

**Comment by Rakesh9100** [comment]
You are assigned to one issue. After completion, you will be assigned to this @JATIN0926

**Comment by JATIN0926** [comment]
@Rakesh9100 previous issue is resolved 👍

**Comment by Rakesh9100** [comment]
Proceed @JATIN0926

**Comment by Rakesh9100** [comment]
PR status pls @JATIN0926

**Comment by JATIN0926** [comment]
@Rakesh9100  I am out of station for some days , I will update the PR in 1-2 days!
