### ISSUE TITLE
[Feature] Adding Inspiration Search Bar

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#544]
### Description

I would like to add inspiration search bar in search bar section.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/133951716/732da8e0-76ad-41b3-bb0f-5f2313bb166d

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by mansi1309** [comment]
@Rakesh9100 Please assign this issue to me .

**Comment by Rakesh9100** [comment]
Proceed @mansi1309
