### ISSUE TITLE
[Other] Components opening in new tab is not a good practice

### ISSUE THREAD

**Issue by akanshaBharti** [Rakesh9100/Beautiify#548]
### What would you like to share?

When user clicks on a component, everytime it uses a new tab to open(in Desktop). Cons for the same are: 
- Opening too many tabs can clutter the user's interface, leading to confusion and making it harder to find the original page.
- For some users, having multiple tabs or windows open can be confusing and disrupt their browsing flow.
- Users who rely on screen readers or keyboard navigation may have difficulty understanding or managing multiple tabs/windows opened without their consent.

![image](https://github.com/Rakesh9100/Beautiify/assets/112724805/e509506b-2023-4d1a-a3d0-1a5f948e7626)
![image](https://github.com/Rakesh9100/Beautiify/assets/112724805/e4ec7734-8dac-4389-8723-3df35200cc83)
![image](https://github.com/Rakesh9100/Beautiify/assets/112724805/07f3ac6a-8547-434a-9a4c-2490981fd5f5)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What is your approach to solve this? Do you want to open everything again in same tab @akanshaBharti

**Comment by akanshaBharti** [comment]
Yes, only the components. Demonstration of component can be in different tab.

**Comment by Rakesh9100** [comment]
No need, pls take over and work on other good issues @akanshaBharti
