### ISSUE TITLE
[Style] Dark mode background changes

### ISSUE THREAD

**Issue by SplinterSword** [Rakesh9100/Beautiify#549]
### What's the style idea?

We need to improve the dark mode. Unlike the light mode the dark mode has no wallpaper or design to it. It is just a grey background which doesn't look very good.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SplinterSword** [comment]
![image_2024-02-08_194808094](https://github.com/Rakesh9100/Beautiify/assets/57327315/ba357941-6cf5-4863-8903-4662feddb9ae)
Like we can add this image as a dark mode background

**Comment by Rakesh9100** [comment]
Dark mode cards is changed now, so can you pls tell what changes you want to do now after looking the new changes in the website again @SplinterSword

**Comment by Rakesh9100** [comment]
Okay proceed, let's see if it looks good @SplinterSword
