### ISSUE TITLE
[Style] Remove the border radius from the navbar

### ISSUE THREAD

**Issue by SplinterSword** [Rakesh9100/Beautiify#550]
### What's the style idea?

We need to improve the look of the nav bar in the website. I would like to remove the border radius and add some more box shadows on the nav bar to make seem like it is layered above the page and make it like this.
![image_2024-02-08_195355909](https://github.com/Rakesh9100/Beautiify/assets/57327315/96bc37b5-96cf-402c-bd76-cd8e13d78ffe)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by Rakesh9100** [comment]
Proceed @SplinterSword

**Comment by Rakesh9100** [comment]
Status of your PR pls @SplinterSword

**Comment by SplinterSword** [comment]
> Status of your PR pls @SplinterSword 

Sorry for the late reply. I had papers going on and also there is some family function that i needed to attend. I will complete it by today itself
