### ISSUE TITLE
[Feature] Adding Animated Border Login Form

### ISSUE THREAD

**Issue by SohanRC** [Rakesh9100/Beautiify#551]
### Description

Want to add a new Animated login form. I am attaching a ScreenShot below !! Please assign me under JWOC 2024.

Project Name = Animated Border Login Form.

### Screenshots

![Screenshot 2024-02-09 000551](https://github.com/Rakesh9100/Beautiify/assets/124901633/038daa40-a0a7-4766-a94d-715c4d782098)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @SohanRC
