### ISSUE TITLE
[Feature] Adding Magnifying Glass Search Bar

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#552]
### Description

I want to add a new Magnifying Glass Search bar in search-bar components. I am attaching a screenshot below for reference.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/b3930f0e-b79b-496b-a005-c086d9f80ecc

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abidsyed25** [comment]
@Rakesh9100 please assign me this under JWOC.

**Comment by Rakesh9100** [comment]
Go ahead @Abidsyed25
