### ISSUE TITLE
[Style] Change the coloring of navbar Home

### ISSUE THREAD

**Issue by SplinterSword** [Rakesh9100/Beautiify#553]
### What's the style idea?

I think we should change the text color of the home text in nav bar from this:
![image](https://github.com/Rakesh9100/Beautiify/assets/57327315/29c9b65a-4bcc-4969-be2c-a089d767bdea)
To this:
![image](https://github.com/Rakesh9100/Beautiify/assets/57327315/03328baa-827f-4e75-9050-92c0ef36e598)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kaif969** [comment]
please assign it to me under JWOC'2024.

**Comment by Rakesh9100** [comment]
No need, pls work on your assigned issues @SplinterSword
