### ISSUE TITLE
[Feature] Adding Card Carousel

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#554]
### Description

I would like to add Card Carousel in Carousel section.
Please assign this issue to me.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/133951716/ccdb4ccb-fea1-4c9c-abc9-b126a821e7d2

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @mansi1309

**Comment by mansi1309** [comment]
okay
