### ISSUE TITLE
[Feature]  we can add new animated  image  

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/Beautiify#558]
### Description

we can add new animation for images
 like rotation , flip, moving, new animation style
 

### Screenshots

.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Describe your issue more @AftabMankapure

**Comment by Rakesh9100** [comment]
Any update @AftabMankapure

**Comment by AftabMankapure** [comment]
working on it today i provide demo

**Comment by Rakesh9100** [comment]
Pls provide the status else I will close the issue @AftabMankapure
