### ISSUE TITLE
Enhancing UI and Centering the Contact Form

### ISSUE THREAD

**Issue by shivamm-verma** [Rakesh9100/Beautiify#56]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

- the Contact Form was not exactly in center of the page.
- now have adjusted this for smaller screens as well.
- added shadows in the Contact Form to Improve the UI for this page

*Screenshots and screen recordings are provided below*

### Screenshots

*Screenshots*

**before**

![before ss](https://github.com/Rakesh9100/Beautiify/assets/98605616/7bafc3c9-7bcb-4352-8914-131aecdbdd26)

**after**

![after ss](https://github.com/Rakesh9100/Beautiify/assets/98605616/70ddcb2e-af88-49e1-8600-fa4f81d173d1)

*Screen Recording (After)*

https://github.com/Rakesh9100/Beautiify/assets/98605616/8a9ce87a-995a-4eb2-99e6-158c34ba0598

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by shivamm-verma** [comment]
*Please assign this Issue to me for the SWOC'24, so that I can work on it.* @Rakesh9100

**Comment by PRITISH212121** [comment]
heyyy @Rakesh9100  can i work on this?

**Comment by Rakesh9100** [comment]
@shivamm-verma Start working. But make sure to pull the latest changes and then make your changes as UI is completely changed.

**Comment by shivamm-verma** [comment]
sure i will take care of that. Thankyou for assigning

**Comment by shivamm-verma** [comment]
it is now changed to in the latest version... (check screenshot below)
![image](https://github.com/Rakesh9100/Beautiify/assets/98605616/57db1f47-0827-4f77-bc0a-82b14e5f6815)

do you want me to Change and make the UI As Mentioned in the Issue Above??... (check screenshot below)
![image](https://github.com/Rakesh9100/Beautiify/assets/98605616/264edf42-8220-4033-8b5e-bb400d33db7d)

(includes resizing of this Card, change of the background color)

**Comment by Rakesh9100** [comment]
Do check the latest version again. It already have some different good background @shivamm-verma

**Comment by shivamm-verma** [comment]
checked...
![image](https://github.com/Rakesh9100/Beautiify/assets/98605616/89bbeaf4-16ba-49db-94e2-0410c1228573)

Can I Enhance the texts as depicted in the Issue & Add hover effects?

**Comment by Rakesh9100** [comment]
You can just add slight hover effect but do not change any text enhancement. Make it fully responsive @shivamm-verma
