### ISSUE TITLE
[Feature] Adding Raindrop Ripple Background

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/Beautiify#561]
### Description

Raindrop elements fall with CSS animations, creating a ripple effect.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/92045934/b79813c5-14f6-46df-bc0d-7befc74378d7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @kom-senapati
