### ISSUE TITLE
[Feature] Adding Interactive Particles Background

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#562]
### Description

I want to add a new Interactive Particles Background. I am attaching a screenshot below for reference.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/bb47da9b-bd65-4898-a7c1-ba5c28432aaf

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What name you will provide to this background @Abidsyed25

**Comment by Abidsyed25** [comment]
@Rakesh9100 I am thinking of Interactive Particles background or Interactive Balls background.

**Comment by Rakesh9100** [comment]
Proceed with second one @Abidsyed25
