### ISSUE TITLE
[Feature] Copy CSS Code

### ISSUE THREAD

**Issue by Surajit0573** [Rakesh9100/Beautiify#570]
### Description

I believe the main objective of this project is to offer a carefully selected range of elegantly designed components and animations that can be effortlessly integrated into any website, enhancing its overall user interface experience. 

In order to utilize a particular style, users should be provided with a "Copy Code" button. This will enable them to copy the CSS code directly and apply the desired style in their own projects.

Assign me under JWOC 2024, if approved.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Idea seems fine, but where you want to add this and how you will copy the code from GitHub @Surajit0573

**Comment by Surajit0573** [comment]
@Rakesh9100 , I can add it at each card between link and GitHub icon or I can add it on their own html file...please tell me where it will fine.
To copy at clipboard the whole CSS code I will use this JavaScript function >> "navigator.clipboard.writeText(value)"

**Comment by Rakesh9100** [comment]
I am not asking about the JS function that you will use rather asking that the Copy Code button will copy what?

`index.html file or style.css file or script.js file` as one needs everything for using the component in their project @Surajit0573

**Comment by Surajit0573** [comment]
Ok...I will add 3 different buttons for HTML, CSS and JavaScript Code and will add at their own html file.

**Comment by Rakesh9100** [comment]
No, this will not be good as new components keeps on adding and buttons will be missed out on those html files @Surajit0573

**Comment by Surajit0573** [comment]
@Rakesh9100, Can I add it at cards as everyone uses cards as templates and copy-paste the basic code then replace the destinations with his own files destinations...?!!

**Comment by Rakesh9100** [comment]
I didn't get what you are trying to say @Surajit0573
