### ISSUE TITLE
[Feature] Adding Interactive Hexagonal Background

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#571]
### Description

I want to add interactive hexagonal background in the background components. 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/19b06ed3-7586-4be7-b8c6-d370a1463d38

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abidsyed25** [comment]
@Rakesh9100 Please assign me this under JWOC.

**Comment by Rakesh9100** [comment]
Go ahead @Abidsyed25
