### ISSUE TITLE
[Bug] Search button in components page is not responsive

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#575]
### Description

While visiting components page on mobile screen, the search component button is not responsive

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/910875bc-498f-45bd-b307-9a8b6df9d87a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @pb0126
