### ISSUE TITLE
[Feature] Adding Gradient Waves Background

### ISSUE THREAD

**Issue by mansi1309** [Rakesh9100/Beautiify#578]
### Description

I would like to add gradient wave background in background section.
Please assign this issue to me.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/133951716/37c9301e-ba09-4446-989a-c605944996bf

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @mansi1309
