### ISSUE TITLE
[Feature] Adding Skeuomorphism Button

### ISSUE THREAD

**Issue by Shubh484** [Rakesh9100/Beautiify#579]
### Description

Will add a new "Skeuomorphism Button" in Button section

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/101503723/a76e81a3-eddc-426a-b6b4-41e1e469d310

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Shubh484** [comment]
Please assign this to me.

**Comment by Rakesh9100** [comment]
Proceed @Shubh484
