### ISSUE TITLE
[Feature] Adding Interactive Squares Background

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#580]
### Description

I want to add a new Interactive squares background in background components. 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/2f1ae16c-d1ac-4663-9cb6-a066a07f1cab

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Abidsyed25
