### ISSUE TITLE
[Feature] Add Text To Voice Form & QR Code Generator Form

### ISSUE THREAD

**Issue by ratnojitsaha** [Rakesh9100/Beautiify#584]
### What would you like to share?

Want to add these forms:
1. Text To Voice Converter form - Contains a text area to write texts and later converts it into voice.
2. QR Code generator form - Just enter any URL of a website and get a qr code.
3. Modal/ Popup login form - Create a form that pops up in a modal window when a button is clicked.

### Additional information

Please assign me under JWOC 2024

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead with the first two forms @ratnojitsaha

**Comment by Rakesh9100** [comment]
PR status pls @ratnojitsaha

**Comment by ratnojitsaha** [comment]
@Rakesh9100 will submit tommorow

**Comment by ratnojitsaha** [comment]
@Rakesh9100 what went wrong?
