### ISSUE TITLE
[Feature] Adding Reveal Loader

### ISSUE THREAD

**Issue by SohanRC** [Rakesh9100/Beautiify#585]
### Description

Add a new Loading Animation - "Reveal Loader" will be the loader name ! I am providing the screenshot below ! Please assign me this issue under JWOC 2024.

### Screenshots

![Screenshot 2024-02-18 013249](https://github.com/Rakesh9100/Beautiify/assets/124901633/942dc608-19dd-4541-bdc9-a1f936362f3b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SohanRC
