### ISSUE TITLE
[Feature] Adding Abstract Particle Swarm Background

### ISSUE THREAD

**Issue by kom-senapati** [Rakesh9100/Beautiify#586]
### Description

JavaScript and HTML canvas generate a vibrant particle swarm animation. Colorful particles move randomly, bouncing off canvas edges, creating dynamic visual effects.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/92045934/f922e51f-520a-4e71-b3bf-a4150ae7d71f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @kom-senapati
