### ISSUE TITLE
Hover effect on Logo in Landing page

### ISSUE THREAD

**Issue by Prachurya-Ray** [Rakesh9100/Beautiify#59]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

When someone hover over the logo image "B" it will slightly rotate sideways and appear little bit bigger in size giving enhanced UI effect.

### Screenshots

<img width="960" alt="image" src="https://github.com/Rakesh9100/Beautiify/assets/70370699/dab491a1-df9f-4587-ae31-40f013e43e30">

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Vipul-Harsh** [comment]
hey i can work on this issue please assign this task to me it would be great help.
thank you

**Comment by Ananyasiingh** [comment]
Yo! I have already fixed this issue. Can you review it? :)

**Comment by Ananyasiingh** [comment]
can I work on this issue if it is not resolved yet?

**Comment by Rakesh9100** [comment]
Not needed. Pls work on other good issues @Prachurya-Ray
