### ISSUE TITLE
[Feature] Add Torch Effect Login Form

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/Beautiify#590]
### Description

New animated **login form with torch effect**  in form section 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/125949765/bf330bec-18fb-49ea-ac57-65f30dbc6b51

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AftabMankapure** [comment]
Assign me under JWOC

**Comment by AftabMankapure** [comment]
@Rakesh9100  pls assign me under JWOC

**Comment by AftabMankapure** [comment]
@Rakesh9100  pls assign me

**Comment by Rakesh9100** [comment]
What name you will give to this form folder @AftabMankapure

**Comment by AftabMankapure** [comment]
@Rakesh9100  Animated login form with torch effect 

folder name  "   Animated-Login-Form-With-Torch-Effect "

**Comment by Rakesh9100** [comment]
This is too long name, just keep `Torch-Effect-Login-Form` @AftabMankapure

**Comment by AftabMankapure** [comment]
ok
