### ISSUE TITLE
[Bug] Navbar lists not inline on small devices

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#594]
### Description

When we visit website on small devices, the navbar lists are overflowing inline property which is pushing text in 2nd line and making navbar broad

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/2e3a69bf-5829-47c7-bbbd-026b6cd6e779)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to work @pb0126

**Comment by pb0126** [comment]
Yes assign it to me
I'll start working on this
Also, please check my previous PR's so that I can raise a new one
