### ISSUE TITLE
[Bug] Search Bar not responsive in Components Category pages

### ISSUE THREAD

**Issue by pb0126** [Rakesh9100/Beautiify#595]
### Description

The search bar is overflowing out of the main container on the Accordion page which is creating unresponsive website on small devices

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/33122840/07734a9c-cf06-406e-b2e3-8fee2989e8da)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
I suppose this issue is not just in Accordions page, it is for every category pages @pb0126

**Comment by pb0126** [comment]
I'll fix this for every page

**Comment by Rakesh9100** [comment]
Go ahead @pb0126
