### ISSUE TITLE
[Feature] Add Google Search Bar

### ISSUE THREAD

**Issue by Abidsyed25** [Rakesh9100/Beautiify#597]
### Description

I want to add a new Google style search bar in the search bar components. 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/116893970/b429a950-0cbe-4d19-90dc-9d1173b4d0da

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abidsyed25** [comment]
@Rakesh9100 Please assign me this issue under JWOC

**Comment by Rakesh9100** [comment]
Go ahead @Abidsyed25

**Comment by debrajrout** [comment]
Please assign the task to me. I will improve its attractiveness and appeal.

**Comment by debrajrout** [comment]
> ### Description
> I want to add a new Google style search bar in the search bar components.
> 
> ### Screenshots
>  Google-Search-Bar.-.Profile.1.-.Microsoft.Edge.2024-02-11.12-20-37.mp4 
> ### Checklist
> * [x]  I have checked the existing issues.
> * [x]  I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
> * [ ]  I am a IWOC'24 contributor.
> * [x]  I am a JWOC'24 contributor.
> * [ ]  I am a SWOC'24 contributor.
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

Please assign the task to me. I will improve its attractiveness and appeal.
