### ISSUE TITLE
[Feature]: Change the hover effect of components. 

### ISSUE THREAD

**Issue by Yatin12527** [Rakesh9100/Beautiify#6]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description
I think the hover effect for component cards should be changed to float or something more professional.

**Reproduce the bug**

1. Go to homepage
2. Click on "Get components"
3. Hover over all the cards

**Screenrecording**

https://github.com/Rakesh9100/Beautiify/assets/134225415/9a0872ff-5608-4be8-bfe3-6df9ff66c3c6

**Expected Behavior**
Float effect with smooth transition or some other appropirate effect would be better.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by krishnagitcontri** [comment]
hi @Yatin12527  I can do this task if you assign this to me. I request you to assign this task to me.

**Comment by PRITISH212121** [comment]
heyyy @Rakesh9100  I'm interested in solving this issue!

**Comment by Rakesh9100** [comment]
@Yatin12527 Proceed, Assigned!!
