### ISSUE TITLE
[Feature] Add 3D-2 Button

### ISSUE THREAD

**Issue by PranavBarthwal** [Rakesh9100/Beautiify#603]
### Description

Add 3D Button in buttons section

### Screenshots

![Screenshot 2024-02-23 120853](https://github.com/Rakesh9100/Beautiify/assets/110532770/f8b834de-1c6f-4b86-8679-0988d0f2ec1e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @PranavBarthwal
