### ISSUE TITLE
[Feature] Add Newsletter Subscription-2 Form

### ISSUE THREAD

**Issue by PranavBarthwal** [Rakesh9100/Beautiify#607]
### Description

Add a newsletter subscription form.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/110532770/5b721c4b-d821-48c2-8ee0-0291c3960f54)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by PranavBarthwal** [comment]
@Rakesh9100 please assign this issue.

**Comment by Rakesh9100** [comment]
Go ahead @PranavBarthwal
