### ISSUE TITLE
[Bug] Fix the alignment of headings

### ISSUE THREAD

**Issue by Anushkabh** [Rakesh9100/Beautiify#609]
### Description

i want to fix the alignment of below pages.. there are many such

### Screenshots

![Screenshot (115)](https://github.com/Rakesh9100/Beautiify/assets/99523033/b8ed4631-5a51-4b97-9fbc-312fc7a85562)
![Screenshot (117)](https://github.com/Rakesh9100/Beautiify/assets/99523033/5353be5b-a671-461d-8a24-ef093fbe5ec1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What alignment are you talking about, please mention the issue clearly @Anushkabh

**Comment by Anushkabh** [comment]
The screenshots above shows text animations search text animations are not aligned properly..
So i would fix those.

**Comment by Rakesh9100** [comment]
Do you want to just align the heading at center @Anushkabh

**Comment by Anushkabh** [comment]
Yes 
Kindly assign me this issue.. so i could reach top 10

**Comment by Rakesh9100** [comment]
Proceed and check whether heading is not aligned center or Search bar and Search text @Anushkabh

**Comment by Rakesh9100** [comment]
Provide your PR pls @Anushkabh

**Comment by Rakesh9100** [comment]
JWOC period is over now @Anushkabh
