### ISSUE TITLE
[Feature] Add Rotating Glow Effect Login Form

### ISSUE THREAD

**Issue by AftabMankapure** [Rakesh9100/Beautiify#611]
### Description

Add new login form with Rotating Glows.

Folder name
"Rotating Glows Login form"

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/125949765/35a749a1-487d-4516-9cbd-ec1285e5c7fb

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
JWOC period is going to end now, no new issue assignment will be done!! @AftabMankapure
