### ISSUE TITLE
[Feature] Add an animated background

### ISSUE THREAD

**Issue by rimidutta** [Rakesh9100/Beautiify#614]
### Description

using html css and javascript

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Are you JWOC or SWOC contributor @rimidutta

**Comment by rimidutta** [comment]
> Are you JWOC or SWOC contributor @rimidutta

JWOC

**Comment by Rakesh9100** [comment]
JWOC period is going to end now, no new issue assignment will be done!! @rimidutta
