### ISSUE TITLE
Enhancing the UI of the each of the components page

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#62]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The design of components page do not match with that of the home page. Also there is no footer section and logo on these pages. I would like to enhance the components page.

### Screenshots

![Screenshot (175)](https://github.com/Rakesh9100/Beautiify/assets/125905089/8bf0cc3b-4614-4e8f-b6d7-59aba5d1a66b)
![Screenshot (176)](https://github.com/Rakesh9100/Beautiify/assets/125905089/632486d0-67d7-446c-a171-2d66c1534917)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
UI enhancement issue is already open. Pls work on other issues @saurav2208
