### ISSUE TITLE
[Style] Enhance the hover effect of navbar buttons

### ISSUE THREAD

**Issue by Manishar55** [Rakesh9100/Beautiify#620]
### What's the style idea?

i would like to improve the hover effect of navbar buttons

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by udita-0707** [comment]
Hi @Abhishek0732 ,

I hope this message finds you well. I'm reaching out to express my interest in contributing to the project and to request assignment of this issue titled "[Style]".

I've reviewed the issue description and I believe I can make a meaningful contribution to address it. Please let me know if this issue is available for assignment.

Looking forward to contributing to the project!

Best regards,

**Comment by udita-0707** [comment]
Hi @Manishar55  ,

I hope this message finds you well. I'm reaching out to express my interest in contributing to the project and to request assignment of this issue titled "[Style]".

I've reviewed the issue description and I believe I can make a meaningful contribution to address it. Please let me know if this issue is available for assignment.

Looking forward to contributing to the project!

Best regards,

**Comment by Manishar55** [comment]
> Hi @Manishar55 ,
> 
> I hope this message finds you well. I'm reaching out to express my interest in contributing to the project and to request assignment of this issue titled "[Style]".
> 
> I've reviewed the issue description and I believe I can make a meaningful contribution to address it. Please let me know if this issue is available for assignment.
> 
> Looking forward to contributing to the project!
> 
> Best regards,

I am also a contributor

**Comment by Jithendranath8** [comment]
please assign this issue to me , i'll add hovering effects to navbar and i'll make it responsive

**Comment by Paromita-maji** [comment]
hey @Manishar55 I am a GSSoC Contributor can you please assign me this issue?

**Comment by officialhemant511** [comment]
hey @Manishar55 , can u pls assign the issue

**Comment by TechSenseiX** [comment]
Hii, With my background in front end development, I believe I'm well-equipped to tackle this issue effectively. I've also taken the time to thoroughly understand the problem and have some ideas on how to approach it.
Could you please consider assigning this issue to me? I'm excited about the opportunity to contribute.

**Comment by anushkapal28** [comment]
I hope you're doing well. I've been exploring ways to enhance the user experience on the website, particularly focusing on the navbar hover effect.

I have some ideas for improving it so can you assign me this.

**Comment by Shyambarua** [comment]
Please, Assign This Issue to me

**Comment by Harsh-Vardhan-Yadav-03** [comment]
Hi @Manishar55 , please assign this issue to  me

**Comment by ivarcodes** [comment]
Hi sir , i would love to contribute on this project and add the hover effect of nav buttons

**Comment by Ridhima10** [comment]
Hi, I hope this message fins you well. 
I will improve hover effect on button which will match the theme of the website. 
I love to  develop  beautiful designs and i am proficient in Front end development.
Very Excited to be a part of this project.

**Comment by Dev-AyushTrivedi** [comment]
I've been actively creating websites and I'm really interested in this issue. Could you please assign it to me? I'm participating in the GirlScript Summer of Code (GSSoC) 2024 and I believe this project would be a great opportunity for me to further enhance my skills.

**Comment by Yuvika-14** [comment]
Please assign me this issue

**Comment by Samaresh34** [comment]
Hii
I would like to be assigned to this issue and add this feature to the website. This contribution is for GSSoC'24.

**Comment by Prakhar-bansal1** [comment]
It will be my pleasure if you assign me for this issue. I'll try my best and give 100% to it..

**Comment by GarimaSingh0109** [comment]
HI I AM WILLING TO CONTRIBUTE TO THIS ISSUE PLEASE ASSIGN ME THIS TASK

**Comment by abhinav120304** [comment]
hey @Manishar55 I'd like to take on the task of refining the hover effect for the navigation buttons. A smooth and visually appealing hover effect can greatly enhance the interactivity and overall user experience of the website. I'll work on implementing a stylish hover effect that provides clear visual feedback to users when they interact with the navigation buttons. Please assign this task to me, and I'll ensure that the hover effect complements the website's design seamlessly. Thank you for considering my contribution!

**Comment by AshutoshVerma140404** [comment]
please assign me this issue under GSSoC'24 contribution

**Comment by Yuvika-14** [comment]
Hi  , please assign me this issue since I am very proficient in web development. I can easily resolve this issue of hover effect.

**Comment by paridhi1509** [comment]
Please assign this issue to me

**Comment by traptijindal** [comment]
please assign this issue to me..

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
This enhance button.

**Comment by Rakesh9100** [comment]
Proceed @Manishar55

**Comment by kavyachandarkar** [comment]
please assign me this issue under GSSoC'24 contribution

**Comment by nandani-goyal** [comment]
@Rakesh9100 please assign me this issue under GSSoC'24 contribution i can add a more attractive hovering effect to the website.
