### ISSUE TITLE
[Bug] Fix the chatbot close button

### ISSUE THREAD

**Issue by officialhemant511** [Rakesh9100/Beautiify#621]
### This chatbot section is not closed until we reload the website ....

![Screenshot (220)](https://github.com/Rakesh9100/Beautiify/assets/120431671/d475dca0-882e-48a4-978f-e3cb0c818424)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Shyambarua** [comment]
Please assign this issue to me because as a full stack developer i will write optimized code and i will resolve all other issues also

**Comment by officialhemant511** [comment]
hey @Rakesh9100 I found this issue so can you pls assign me this issue so that i can solve this....

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
This bug is present.
Assign them for removing.

**Comment by Rakesh9100** [comment]
Go ahead @officialhemant511

**Comment by Rakesh9100** [comment]
Status of your work @officialhemant511

**Comment by Ayushmaanagarwal1211** [comment]
Hii @Rakesh9100  i wanna work on that
please assign this to me

**Comment by Rakesh9100** [comment]
Do you want to work @r7projects-shayan

**Comment by r7projects-shayan** [comment]
sure @Rakesh9100
