### ISSUE TITLE
[Bug] Fix overlapping of footer in Contact page

### ISSUE THREAD

**Issue by Akshita-8** [Rakesh9100/Beautiify#622]
### Description

In Contact Us page the form is overlapping with footer and when we enter the email id the UI is not good. I can resolve this issue please assign me this issue.

### Screenshots

![Screenshot (426)](https://github.com/Rakesh9100/Beautiify/assets/111629390/6c771bb0-b535-48e0-8a37-29c0d3d35d0d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Akshar-Saxena** [comment]
Please assign me this task as I have worked on web for long time

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by PoojaGadagi08** [comment]
Hello @Rakesh9100 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by shnwz-solves** [comment]
Hi PA, please assign me this issue. I would like to contribute.

**Comment by traptijindal** [comment]
Hey! Please assign this task to me. I would like to contribute.

**Comment by Rakesh9100** [comment]
For which screen size are you facing this overlapping issue as I can see it is perfect on the website @Akshita-8

**Comment by Akshita-8** [comment]
> For which screen size are you facing this overlapping issue as I can see it is perfect on the website @Akshita-8

For 90 percent zoom in screen size it is perfect but for 100 percent is it overlapping you can see in the attached screenshot below.
![Screenshot (427)](https://github.com/Rakesh9100/Beautiify/assets/111629390/a20de1db-10a0-4cf7-b7bd-1f9701d93623)

**Comment by Rakesh9100** [comment]
Okay proceed @Akshita-8

**Comment by Akshita-8** [comment]
Thank you. Started working on it.

**Comment by sakshampurohitt** [comment]
pls assign me this under gssoc 2k24

**Comment by bhavanishanker-png** [comment]
please assign this issue to me, i can work on this, i have made the local setup as well, i can make the changes, and resolve this issue

**Comment by Rakesh9100** [comment]
Go ahead @bhavanishanker-png

**Comment by Rakesh9100** [comment]
This is resolved now, pls work on new issues @bhavanishanker-png
