### ISSUE TITLE
[Feature] Add Colour Changing Loader

### ISSUE THREAD

**Issue by BagchiShreya** [Rakesh9100/Beautiify#623]
### Description

This loader will show a new shiny colour while loading

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by PriyanshuShankar** [comment]
Hi,
I would like to be assigned to this issue. This contribution is for GSSoC'24

**Comment by Samaresh34** [comment]
Hi,
I would like to work on this project. Please assign it to me. This contribution is for GSSoC'24.

**Comment by Arpingh** [comment]
Hi ,  Please assign this issue to me.

**Comment by Rakesh9100** [comment]
Go ahead @BagchiShreya
