### ISSUE TITLE
[Style] Fix the alignment in the About page

### ISSUE THREAD

**Issue by aaryaparadkar** [Rakesh9100/Beautiify#625]
### What's the style idea?

The content in the About section, is a bit misaligned. Would like to resolve this, if it works with you.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Agrima11** [comment]
pls assign this issue to me...

**Comment by Divi-1026** [comment]
Please assign this issue to me as I created too clones ..so I am doing my best to resolve this issue

**Comment by Rakesh9100** [comment]
Can you pls describe that what is not aligned properly with the help of screenshot @aaryaparadkar
