### ISSUE TITLE
[Feature] Add contact details in the footer

### ISSUE THREAD

**Issue by AlaynaShaheen** [Rakesh9100/Beautiify#626]
### Description

Footer becomes more interactive to user by adding contact us along with social media links of Beautilify.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AlaynaShaheen** [comment]
Hello Rakesh,

I am Alayna Shaheen, a contributor participating in GSSoC'24. I want to add this contact us feature in footer to make it look more appealing to the users. I'm eager to tackle this challenge and contribute to the project. Looking forward on your guidance on how to proceed.

Regards,
Alayna Shaheen

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by Rakesh9100** [comment]
Do you have any supporting image for this issue @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
![Screenshot 2024-05-21 085620](https://github.com/Rakesh9100/Beautiify/assets/111679498/3901d8c8-2f54-46a0-8981-8ed01b7f9c3e)
In this way we can add contact details in footer

**Comment by Rakesh9100** [comment]
Do you want to be assigned @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
Yes I can do that @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay, proceed and make sure to match the UI @AlaynaShaheen

**Comment by AlaynaShaheen** [comment]
Thanks for assigning me @Rakesh9100.
