### ISSUE TITLE
[Feature] Implement smooth scrolling

### ISSUE THREAD

**Issue by suraj-9849** [Rakesh9100/Beautiify#627]
### What would you like to share?

So I saw that for this Beautiful website - Beautiify we need to include the smoothness in scrolling so I would like to add the Locomotive JS which can provide the smooth scrolling and best user experience. So I would like to work on this issue so please assign this to me @Rakesh9100  under the @GSSOC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by abhinav120304** [comment]
Hello! I'm eager to tackle the task of enhancing the smoothness of the website. Improving the overall user experience by adding smooth transitions and animations can significantly elevate the site's aesthetics and usability. I'll focus on refining transitions between pages, interactions with elements, and any other areas where smoothness can be enhanced. Please assign this task to me, and I'll work on bringing a polished and seamless feel to the website. Thank you for the opportunity to contribute!

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Check it

**Comment by Rakesh9100** [comment]
Go ahead @suraj-9849

**Comment by Rakesh9100** [comment]
Provide your PR @suraj-9849

**Comment by aditia1375** [comment]
Please assign this issue to me under GSSOC'24.
