### ISSUE TITLE
[Feature] Add Tables Category and several Components

### ISSUE THREAD

**Issue by Mahenoor0192** [Rakesh9100/Beautiify#628]
### What would you like to share?

Currently, the Components section lacks an option for tables. Tables are fundamental components in many web applications and are frequently used for presenting data in a structured format. I propose adding a Table component option to the Components section. I am willing to take ownership of this task and contribute to its implementation.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Agrima11** [comment]
pls assign me this issue

**Comment by saurabhsingh720** [comment]
@Mahenoor0192 
Can u give preview of that.

**Comment by Rakesh9100** [comment]
In Tables section, which all components can be included @saurabhsingh720

**Comment by Rakesh9100** [comment]
In Tables section, which all components can be included @Mahenoor0192

**Comment by Mahenoor0192** [comment]
@Rakesh9100 . In Tables Section, as components we can consider basic table structure, styling components like borders and shading, background color, interactive components like sorting, data filtering, pagination, search. Table designs can be made Responsive and also modals can be included.

**Comment by Rakesh9100** [comment]
Okay, proceed @Mahenoor0192

**Comment by Rakesh9100** [comment]
Pls provide your PR @Mahenoor0192

**Comment by ANGIRAVO** [comment]
I'm interested in working on issue #1208 #638 #638 . I've already reviewed the issue description and believe I have the necessary skills to contribute.

Please let me know if you're open to assigning this to me.

**Comment by aashlesha12** [comment]
I've created a video demonstrating my solution to the reported issue. I've added 2 types of tables.

https://github.com/user-attachments/assets/95599792-e07c-4c7b-9374-eefd5da940e2
