### ISSUE TITLE
Add swirl animated background

### ISSUE THREAD

**Issue by saurav2208** [Rakesh9100/Beautiify#63]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add an animated background under the background component.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @saurav2208
