### ISSUE TITLE
[Style]

### ISSUE THREAD

**Issue by Sathya-reddy1658** [Rakesh9100/Beautiify#631]
### What's the style idea?

We need to improve
adding few micro interactions
adding some animations where necessary
please assign me this issue and i'll add GSAP animations and locomotive.js and make it look   great!!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open to add locomotive, pls create new issues @Sathya-reddy1658
