### ISSUE TITLE
[Feature] Implementation of Docker Containerization for the Application

### ISSUE THREAD

**Issue by Sarthak027** [Rakesh9100/Beautiify#632]
### Description

**Proposal:**  Docker Containerization Implementation

**Objective:**

Implement Docker containerization to streamline deployment, enhance scalability, and improve portability across different environments.

**Benefits:**

- Streamlined Deployment: Consistent deployment across platforms reduces issues.

- Improved Portability: Facilitates migration between environments.

- Simplified Maintenance: Easier management and updates without system impact.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need of this, pls work on good and project related issues @Sarthak027
