### ISSUE TITLE
[Style] Enhance the color scheme of navbar

### ISSUE THREAD

**Issue by Leorasaharia** [Rakesh9100/Beautiify#636]
### What's the style idea?

The current UI design lacks coherence and balance in color scheme, particularly noticeable in the navigation bar. Additionally, the chatbot's appearance lacks responsiveness and the chat window doesn't close properly. To address these issues, the chatbot assistance should be redesigned to function as a pop-up feature for improved user interaction.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Leorasaharia** [comment]
Thankyou so much, would like to work on it!

**Comment by Rakesh9100** [comment]
Any update on this @Leorasaharia

**Comment by Rakesh9100** [comment]
Any update on this or should I close @Leorasaharia

**Comment by Leorasaharia** [comment]
I'll make the changes in a while. @Rakesh9100

**Comment by Rakesh9100** [comment]
> What would you like to address through this issue as issue is already opened before for fixing the closing of the chatbot @Leorasaharia

Which changes you will make, first provide your reply to this @Leorasaharia

**Comment by Leorasaharia** [comment]
@Rakesh9100 I've already designed the navigation layout and color scheme in the previous PR. Now, I'll focus on enhancing the navbar's color scheme, ensuring it stands out prominently in dark mode. This update aims to improve visibility and user experience by making the navbar area more vibrant.
