### ISSUE TITLE
[Style] Enhance the website with Chakra UI

### ISSUE THREAD

**Issue by Leorasaharia** [Rakesh9100/Beautiify#637]
### What's the style idea?

Buttons on the website appear dull and lack visual appeal. Implementing Chakra UI can breathe new life into button design, providing a sleeker and more modern appearance.
These changes will not only improve the overall aesthetics of the website but also enhance user experience and security.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide some supporting screenshots @Leorasaharia

**Comment by Leorasaharia** [comment]
@Rakesh9100 I'll certainly priovide the finalized project's screenshots after it's solved. will do it asap.

**Comment by Rakesh9100** [comment]
Okay proceed @Leorasaharia
