### ISSUE TITLE
Add a Glowing button in buttons section

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#64]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Right now there are only two types of buttons.
I can add a glow button.

Please assign it to me under SWOC'24

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/3047bf3b-ceb3-4d0d-b147-e9ae414e319d)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @rishicds
