### ISSUE TITLE
[Bug] Fix the space clicking between the cards

### ISSUE THREAD

**Issue by KhushiTiwarii** [Rakesh9100/Beautiify#645]
### Description

The page gets navigated to any of these 4 cards if clicked in the space between the cards.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/137861160/a489c600-14a7-457a-9793-08ef184c715f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Jithendranath8** [comment]
Please assign this issue to me , I have experience in doing it in responsive way

**Comment by saurabhsingh720** [comment]
@Rakesh9100 check it.

**Comment by Rakesh9100** [comment]
Proceed @KhushiTiwarii

**Comment by KhushiTiwarii** [comment]
hii @Rakesh9100  I have created a pull request 
kindly check it
