### ISSUE TITLE
[Feature] Add social media and feedback section in blog page 

### ISSUE THREAD

**Issue by rajlaxmi03** [Rakesh9100/Beautiify#649]
### Description

Add social media and feedback section in blog page 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sheshank-singh** [comment]
Hello @Rakesh9100 I am good at the adding the section on the website. i would love to work on this issue . Please assigned me this issue so i can start my contribution
Thank you

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by Rakesh9100** [comment]
We don't need any feedback section, pls create good issues @rajlaxmi03
