### ISSUE TITLE
[Style] Enhance font color for components heading in dark mode

### ISSUE THREAD

**Issue by KARTHIK174** [Rakesh9100/Beautiify#650]
### What's the style idea?

whenever we open any components section, when we change the theme to dark to bright then the word search followed by components are combining with the background black colour.so we need to improve by changing the colour for that particular text.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AMANVISHWAKARMA27** [comment]
Hey @KARTHIK174 , kindly assign me the issue.

**Comment by Anikketsingh** [comment]
well I am here to work on this please assign it to me @Rakesh9100

**Comment by Abdul-momin24** [comment]
Can you Please assignn this project to me

**Comment by Rakesh9100** [comment]
Provide the supporting screenshots for your issue @KARTHIK174

**Comment by KARTHIK174** [comment]
> Provide the supporting screenshots for your issue @KARTHIK174

![Screenshot 2024-05-30 100210](https://github.com/Rakesh9100/Beautiify/assets/107982190/afe946b0-961a-4e6d-adeb-19fd71bb695a)
![Screenshot 2024-05-30 100230](https://github.com/Rakesh9100/Beautiify/assets/107982190/3db29d3d-2728-4418-a784-2b21b0acd1cf)
here the font color should be changed in order to view properly.

**Comment by Rakesh9100** [comment]
Proceed @KARTHIK174
