### ISSUE TITLE
[Bug] Chatbox header is hiding behind navbar 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Rakesh9100/Beautiify#652]
### Description

When i open the chatbox that it opens but the header of the opened checkbox is hiding behind the navbar .
In my opinion the header should comes over navbar for better user experience .
I want to work on that .
If suitable assign this issue to me .

### Screenshots

![Screenshot 2024-05-10 231832](https://github.com/Rakesh9100/Beautiify/assets/118350936/af537f0d-fac0-42dd-8776-8b665e9fc788)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Agrima11** [comment]
hii...pls assign me this issue

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Assign this task.

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, you can comment there if you want to work @Ayushmaanagarwal1211
