### ISSUE TITLE
[Bug] Fix the chatbot close button

### ISSUE THREAD

**Issue by dakshsinghrathore** [Rakesh9100/Beautiify#653]
### Description

When accessing the website and engaging with the chatbot, there's currently no visible option to close the chat frame. To exit, users need to click on the chat frame and then press the Esc key. The exit option is obscured by the navbar, which can be resolved by adjusting the z-index of the navbar. Assigning this issue to me for resolution during GSSOC'24 would be highly beneficial.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/115932772/a1d30af4-3a1e-472f-9853-dd1fbf4bec8c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by dakshsinghrathore** [comment]
@Rakesh9100 Kindly assign me this issue under GSSOC24 would love to fix this in no time.

**Comment by AshutoshVerma140404** [comment]
@Rakesh9100 kindly assign me this issue

**Comment by sahiljarngal** [comment]
@Rakesh9100  please assign me this problem. I will fix it easily

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, you can comment there if you want to work @dakshsinghrathore
