### ISSUE TITLE
[Feature] Add Glassmorphism Dropdown

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [Rakesh9100/Beautiify#656]
### Description

I want to add a new Glassmorphism Dropdown in Dropdown component.
Kindly assign this to me under GSSOC"24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by AmrutaJayanti** [comment]
@Prince-kushwaha-2004 Can you please assign me this task .

**Comment by Rakesh9100** [comment]
Go ahead @Prince-kushwaha-2004

**Comment by Rakesh9100** [comment]
Provide your PR @Prince-kushwaha-2004
