### ISSUE TITLE
 Add a coffee cup loader 

### ISSUE THREAD

**Issue by divyansh2375** [Rakesh9100/Beautiify#66]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100  Can i please work on this issue?

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/130889408/d750c810-209b-43cf-9aee-b7fa841fc914)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Proceed @divyansh2375

**Comment by Rakesh9100** [comment]
@divyansh2375 Status of your PR

**Comment by DaSeeker67** [comment]
@Rakesh9100  i can work on this issue please assign

**Comment by Rakesh9100** [comment]
@divyansh2375 Are you working or not?

**Comment by divyansh2375** [comment]
i am working on this issue will be completing it within next two days

**Comment by divyansh2375** [comment]
![Screenshot (192)](https://github.com/Rakesh9100/Beautiify/assets/130889408/a9717d1f-8fcf-4565-b69a-3e704bc42772)


I have completed till this just going to finish it completely till tomorrow.
