### ISSUE TITLE
[Feature] Integrate links to open in the same tab

### ISSUE THREAD

**Issue by animex007** [Rakesh9100/Beautiify#661]
### Description

# Issue : Enhance User Experience by Integrating Links to Open in the Same Tab !

## Description:
-  Currently, when navigating through the website, every click on a button or link opens a new tab. While this might have been designed to prevent users from losing their place, it can lead to a cluttered browsing experience and disrupt the flow of navigation.

## Proposal:
- To enhance the user experience, I suggest integrating links and buttons to open in the same tab by default. This would streamline navigation and create a more cohesive browsing experience for users. Opening links in the same tab encourages users to stay focused on the content without unnecessary distractions from multiple tabs.

### Screenshots

- On every click on a button or link opens a new tab. 

![Screenshot 2024-05-11 043340](https://github.com/Rakesh9100/Beautiify/assets/93252366/f21bdc87-103a-4e77-963e-4c3a349e48bb)

- When I click on any button, it redirects me to a new tab.

![Screenshot 2024-05-11 043356](https://github.com/Rakesh9100/Beautiify/assets/93252366/93fe2bc2-4852-468f-ab0f-fac00c4c86e9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abhiiii-001** [comment]
Hey @animex007  ,
Plz assign this task to me as a GSSoC contributor;)

**Comment by AshutoshVerma140404** [comment]
please assign this issue to me

**Comment by animex007** [comment]
> Hey @animex007, Plz assign this task to me as a GSSoC contributor;)

Hii,
       @Abhiiii-001 I am also a contributor, not the project Admin or Mentor. I am waiting to get assigned to work on this issue!

**Comment by AshutoshVerma140404** [comment]
hey @animex007 please assign this issue to me under GSSoC'24, as i have already solved it please accept the pull request.

**Comment by animex007** [comment]
> hey, please assign this issue to me under GSSoC'24, as i have already solved it please accept the pull request.
Hey,
@AshutoshVerma140404  if you want contribute then open your own issue , what you are doing is stealing someone else  points !
You are solving someone else issue, while the issue is not been accepted .
Just read the code of conduct before contributing

**Comment by AshutoshVerma140404** [comment]
> > hey, please assign this issue to me under GSSoC'24, as i have already solved it please accept the pull request.
> > Hey,
> > @AshutoshVerma140404  if you want contribute then open your own issue , what you are doing is stealing someone else  points !
> > You are solving someone else issue, while the issue is not been accepted .
> > Just read the code of conduct before contributing

Sorry for the mistake , I didn't know about that. It won't happen again.

**Comment by AshutoshVerma140404** [comment]
> > hey, please assign this issue to me under GSSoC'24, as i have already solved it please accept the pull request.
> > Hey,
> > @AshutoshVerma140404  if you want contribute then open your own issue , what you are doing is stealing someone else  points !
> > You are solving someone else issue, while the issue is not been accepted .
> > Just read the code of conduct before contributing

I have removed my pull request

**Comment by Rakesh9100** [comment]
Pls provide your opinion on this @saurabhsingh720

**Comment by saurabhsingh720** [comment]
@animex007 
Your reason is right but this will make user experience difficult.
As user have to reach in different components. Then they will have to get back from current component.

**Comment by Rakesh9100** [comment]
Yes, absolutely @saurabhsingh720 

So pls work on other good issues @animex007
