### ISSUE TITLE
[login/register Button and My Favourites Button] <strore user's favourite any elements >

### ISSUE THREAD

**Issue by Vipullakum007** [Rakesh9100/Beautiify#663]
### Description

add **Login/Sigh Up** button.
so that user can store their favourite any elements in their ids. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by GauriBapat29** [comment]
Hi. I would like to sort the given issue. I request you to assign me this issue under GSSOC'24.

**Comment by Rakesh9100** [comment]
No need of login page, pls work on other issues @Vipullakum007
