### ISSUE TITLE
[Bug] Fix the chatbot close button

### ISSUE THREAD

**Issue by krishkh** [Rakesh9100/Beautiify#668]
### Description

The chatbot kinda crazy+ it doesnt fit completely in the screen (I am under gssoc'24)

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/51072063/a2188efa-0d93-48c2-8bce-90064a7869b9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Aishwarya2701** [comment]
I could help fix this issue @Rakesh9100

**Comment by Vaishnavigupta1312** [comment]
Please assign it to me @krishkh

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, pls create new issues @krishkh
