### ISSUE TITLE
[Style] Improve UI of the website

### ISSUE THREAD

**Issue by RazaAli313** [Rakesh9100/Beautiify#671]
### What's the style idea?

We need to improve the header and footer portion appealing and to adjust some more good colouring scheme 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open for this, you can open up new issues to maybe add some components @RazaAli313
