### ISSUE TITLE
[Style] Add strikethrough text effect to headers

### ISSUE THREAD

**Issue by Riddhi162** [Rakesh9100/Beautiify#673]
### What's the style idea?

We need to improve the header of pages like about us , contact us, search components to make it look more appealing and eyecatching.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you have any supporting screenshots @Riddhi162

**Comment by Riddhi162** [comment]
yes sure 
![Screenshot 2024-05-18 153835](https://github.com/Rakesh9100/Beautiify/assets/135015856/cc5c8992-25ee-4917-a499-8f552da0ab07)

**Comment by Rakesh9100** [comment]
Proceed @Riddhi162

**Comment by Riddhi162** [comment]
Thanks for assigning
