### ISSUE TITLE
[Style] Improve the font of the website

### ISSUE THREAD

**Issue by SrijaAdhya12** [Rakesh9100/Beautiify#676]
### What's the style idea?

I want to enhance the font face of this website using attractive fonts such as:
-  Roboto 
-  Montserrat
-  Helvetica 
and other fonts.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ankiiitagupta** [comment]
@Rakesh9100 Can you assign this issue to me under GSSOC'24 please? I would love to use my skills to provide you with desired and enhanced result.

**Comment by Rakesh9100** [comment]
Proceed @SrijaAdhya12

**Comment by SaurabhJha19** [comment]
Hi @Rakesh9100,
I have gone through the issue you mentioned about and have a solution  to it. I am a web developer and working on web development for last 7 year. Considering my knowlegde and experince in web dev, i belive i can handle this issue and get you things done.
I would request you to assign me this issue under GSSOC'24.
Looking forward for your approval.
Thank you

**Comment by SrijaAdhya12** [comment]
> Hi @Rakesh9100, I have gone through the issue you mentioned about and have a solution to it. I am a web developer and working on web development for last 7 year. Considering my knowlegde and experince in web dev, i belive i can handle this issue and get you things done. I would request you to assign me this issue under GSSOC'24. Looking forward for your approval. Thank you

This issue is already assigned to me. I am working on it
