### ISSUE TITLE
Enhancing the navbar UI

### ISSUE THREAD

**Issue by PRITISH212121** [Rakesh9100/Beautiify#68]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

i can make the navbar look better by adding material UI and better hover effects

### Screenshots

![swoc](https://github.com/Rakesh9100/Beautiify/assets/92733818/176be067-c4db-4d00-be0e-261e3dd6eb21)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by PRITISH212121** [comment]
@Rakesh9100  take a look,if yes then pls assign me

**Comment by Rakesh9100** [comment]
UI enhance issue is already open. Pls work on new other issues @PRITISH212121
