### ISSUE TITLE
[Style] Enhance header and font

### ISSUE THREAD

**Issue by chaanakyaaM** [Rakesh9100/Beautiify#681]
### What's the style idea?

i would like to change the font style and also improve the header including the buttons on the nav bar and their hover effects.

would you like to assign me this issue under GSSOC'24 ??

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a IWOC'24 contributor.
- [X] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by shnwz-solves** [comment]
Hi PA, please assign me this issue. I would like to Contribute.
