### ISSUE TITLE
Adding a Password Strength Calculator

### ISSUE THREAD

**Issue by cxde-Sujal** [Rakesh9100/Beautiify#682]
### Description

It will suggest whether a password is strong weak medium based on runtime of user input with different emojis use too describing strength to weakness

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

![Screenshot (142)](https://github.com/Rakesh9100/Beautiify/assets/137087363/99bd75da-9d80-4c3e-b0af-2ef89ad6c163)

**Comment by cxde-Sujal** [comment]
Assign it to me for GSSoc'24 sir

**Comment by Janani-m17** [comment]
Kindly assign this issue to me in GSSoC'24 sir.

**Comment by Yuvasri-b** [comment]
I like to work on this issue. Kindly assign it to me in GSSOC'24

**Comment by Rakesh9100** [comment]
Pls open project related relevant issues @cxde-Sujal
