### ISSUE TITLE
[Feature] Close button for chat bot

### ISSUE THREAD

**Issue by Ishaparte** [Rakesh9100/Beautiify#686]
### Description

the chat box is hiding under the navbar and the chat box is not closing, so I will add close button to it.
I am contributing under GSSOC'24.
@Rakesh9100 Plz assign me this issue.

### Screenshots

![chat bot](https://github.com/Rakesh9100/Beautiify/assets/113294672/b95835b5-6ce2-4a88-9bc0-e7d172fdcd59)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, pls create new issues @Ishaparte
