### ISSUE TITLE
[Style] Padding issue in navlinks hover box

### ISSUE THREAD

**Issue by Adeesh-bode** [Rakesh9100/Beautiify#689]
### What's the style idea?

We need to improve padding of hover box of navlinks

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [X] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Akshatakapare** [comment]
I'm interested in solving this issue, please assign me this issue, I am a GSsoc24 contributor.

**Comment by Utkarsh7368** [comment]
Please Assign this issue to me.

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls create new issues @Adeesh-bode
