### ISSUE TITLE
Adding a sliced text animation

### ISSUE THREAD

**Issue by bhavya-anand19** [Rakesh9100/Beautiify#69]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Under the text animation component, I would like to add a sliced text animation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @bhavya-anand19
