### ISSUE TITLE
[Style] Enhance the UI

### ISSUE THREAD

**Issue by Kumud14** [Rakesh9100/Beautiify#691]
### What's the style idea?

We need to improve the styles to make the page look more fascinating by :
Keeping the design balanced.
Compartmentalize the design by using grids.
Picking two or three base colors at most for the design Trying to make the graphics go well together Improving the website’s typography and Making elements stand out by adding white space around them and having all elements connected.
It will be my pleasure if you allow me to contribute to this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Kumud14** [comment]
I would like to work on this please assign it to me

**Comment by Rounit-Kumar** [comment]
I would like to work on this. Can you please assign it to me @Kumud14

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls create new issues such as adding components @Kumud14
