### ISSUE TITLE
[Bug] Chatbot Overlapping Issue

### ISSUE THREAD

**Issue by abhiperfect** [Rakesh9100/Beautiify#694]
### Description

The issue I'm facing is that the chatbot interface is overlapping with itself, causing visual clutter and difficulty in navigating the conversation. I've tried refreshing the page and restarting the chatbot, but the problem persists.

### Screenshots

![Screenshot 2024-05-12 031249](https://github.com/Rakesh9100/Beautiify/assets/114478676/fa640198-53b4-40d4-b309-971cbdab5963)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by gudia18** [comment]
i would love to work on this issue, plz assign me @Rakesh9100

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, you can create new issues or comment there if you want to work @abhiperfect
