### ISSUE TITLE
[Bug] Fix overlapping of scroll to top button with chatbot

### ISSUE THREAD

**Issue by SahilThakur02** [Rakesh9100/Beautiify#697]
### What would you like to share?

**Issue:**
The scroll-to-top button on the page is positioned unusually close to the chatbot open button, causing a potential usability concern.

**Details:**
Upon scrolling down the page, the scroll-to-top button becomes visible. However, its proximity to the chatbot open button is causing confusion for users. This close placement may lead to accidental clicks or hinder the ease of accessing the chatbot functionality.

**Expected Behavior:**
The scroll-to-top button should be positioned in a location that prevents overlap or confusion with other interactive elements, such as the chatbot open button. Users should be able to easily identify and interact with both buttons without interference.

**Steps to Reproduce:**

Scroll down the page to reveal the scroll-to-top button.
Observe its placement in relation to the chatbot open button

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SahilThakur02** [comment]
Please label it fir GSSOC'24 and /assign me the issue, I would like to work on it
@Rakesh9100

**Comment by Rakesh9100** [comment]
Proceed @SahilThakur02
