### ISSUE TITLE
Enhance the UI design

### ISSUE THREAD

**Issue by pankhuri92** [Rakesh9100/Beautiify#7]
### Prerequisites

- [x] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hi @Rakesh9100, I would like to suggest certain changes for the UI of the website:

- Eye catchy background
- Enhanced navbar
- Use of better fonts and highlights
- A more subtle color code for the website
- Compact footer

I have done the designing part for most of the projects I have worked in. And I am also skilled in Figma apart from front-end technologies. I would be glad to work for this project! 

Kindly assign me the issue.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Yatin12527** [comment]
> ### Prerequisites
> * [x]  I am an Open Source Contributor
> * [x]  I checked to make sure that this issue has not already been filed
> 
> ### Description
> Hi @Rakesh9100, I would like to suggest certain changes for the UI of the website:
> 
> * Eye catchy background
> * Enhanced navbar
> * Use of better fonts and highlights
> * A more subtle color code for the website
> * Compact footer
> 
> I have done the designing part for most of the projects I have worked in. And I am also skilled in Figma apart from front-end technologies. I would be glad to work for this project!
> 
> Kindly assign me the issue.
> 
> ### Code of Conduct
> * [x]  I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

As the whole UI design needs to be updated i'd love to share work with you and take the text part if possible. I'll try to put the best suiting eyecatching fonts on this.

**Comment by vishal0316** [comment]
> ### Prerequisites
> 
> - [x] I am an Open Source Contributor
> - [X] I checked to make sure that this issue has not already been filed
> 
> ### Description
> 
> Hi @Rakesh9100, I would like to suggest certain changes for the UI of the website:
> 
> - Eye catchy background
> - Enhanced navbar
> - Use of better fonts and highlights
> - A more subtle color code for the website
> - Compact footer
> 
> I have done the designing part for most of the projects I have worked in. And I am also skilled in Figma apart from front-end technologies. I would be glad to work for this project! 
> 
> Kindly assign me the issue.
> 
> ### Code of Conduct
> 
> - [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

 
Hey I SWOC contributor 
Please assign me I can do this.

**Comment by priyankaa-2004** [comment]
Hey @Rakesh9100 ,
 I can work on this issue and improve the UI of the entire web page and make it more minimalistic and more elegant by using better color pallets and fonts.
I would use better icons and transitions to make it more visually appealing.

**Comment by Rakesh9100** [comment]
@pankhuri92 Assigning, Start working!!

**Comment by pankhuri92** [comment]
Thanks @Rakesh9100, will keep you updated.

**Comment by Rakesh9100** [comment]
@pankhuri92 Status of your work pls

**Comment by pankhuri92** [comment]
Yes I am done with the main page. Just a few more changes for the component pages then i'll create pr.
![Screenshot 2024-01-04 015335](https://github.com/Rakesh9100/Beautiify/assets/138357063/6d3ddafe-c306-4e3e-bb2e-25154e982972)

**Comment by pankhuri92** [comment]
Hey @Rakesh9100, I'm done with work. Please review my pr.

**Comment by Rakesh9100** [comment]
Pls check the comment on the PR @pankhuri92

**Comment by Yatin12527** [comment]
hey @pankhuri92 i would request you to not change the card design i think current design look good 
(by card design i mean the one u get after opening individual components)
