### ISSUE TITLE
Adding Jelly Button to the website

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#70]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Right now there are only two types of buttons.
I can add a jelly button.

Please assign it to me under SWOC'24

### Screenshots

![beautify button](https://github.com/Rakesh9100/Beautiify/assets/144611267/5c9c6007-2338-4436-b5f4-a37e56d20607)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @GhoshAditi
