### ISSUE TITLE
[Feature] Add Popups Category and several Components

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/Beautiify#703]
### Description

Types of modal I thought to do:

- [ ] success
- [ ] warn
- [ ] danger
- [ ] with scrolling body
- [ ] with animation
- [ ] with a image
- [ ] with a form
- [ ] even more

Can you assign this issue to me? I am sure that i can provide this feature in best level.

Please assign this issue to me under GSSOC'24. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TejasAror** [comment]
Plz assign me this I can solve this in optimize form

**Comment by Rakesh9100** [comment]
Where do you want to add these feature @DharshiBalasubramaniyam

**Comment by Rakesh9100** [comment]
Okay go ahead @DharshiBalasubramaniyam
