### ISSUE TITLE
[Style]  update link , with good animations 

### ISSUE THREAD

**Issue by yogeshpatidar88** [Rakesh9100/Beautiify#709]
### What's the style idea?

We need to improve icons , time to jumble , improve hover effect

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sobithav18** [comment]
I would like to focus on enhancing the navbar, hover effects, grids, and other elements of our website.I have strong web development skills and experience in creating websites. Please assign me to this project.
