### ISSUE TITLE
[Bug] Remove unwanted margins for small screen

### ISSUE THREAD

**Issue by kushalkumar1362** [Rakesh9100/Beautiify#713]
### What's the style idea?

We need to remove extra space 
![Screenshot (342)](https://github.com/Rakesh9100/Beautiify/assets/140513098/d7579fe9-3bf1-4789-96b5-0832d56a2198)
![Screenshot (343)](https://github.com/Rakesh9100/Beautiify/assets/140513098/96857dfe-519f-4e14-94a7-655149f47e7d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @kushalkumar1362

**Comment by Rakesh9100** [comment]
Label will be added after the PR is up @kushalkumar1362
