### ISSUE TITLE
Add a back to the top button 

### ISSUE THREAD

**Issue by Ramben0909** [Rakesh9100/Beautiify#727]
### Description

In the bottom I can add a back to the top button so that you don't have to scroll up 
Hey @Rakesh9100 please assign this issue to me as a GSSoC '24 contributor 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Rakesh9100** [comment]
We already have scroll to top button, pls create new issues @Ramben0909
