### ISSUE TITLE
[Bug] Wanted to Change the Frontend Appearance of the website

### ISSUE THREAD

**Issue by nishasingh-git** [Rakesh9100/Beautiify#729]
### Description

I wanna make visually looking much better website by changing the colors and text style and so on

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by sammyyyyy12** [comment]
hey! can this issue be assigned to me under GSSoc'24? I am eager to work in beautifying the beautiify app and my tech stack involves html, css, java, c, c++, python.

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls create new issues @nishasingh-git
