### ISSUE TITLE
[Feature] Add Port ID Card

### ISSUE THREAD

**Issue by codewithganeshhh** [Rakesh9100/Beautiify#730]
### Description

It was  a mini ID card like structure , That have a About , Experience and contact section with Photograph

### Screenshots

![Screenshot 2024-05-14 221316](https://github.com/Rakesh9100/Beautiify/assets/139307139/a9e56d3e-777d-4446-b1e3-47b23bb39ae1)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by codewithganeshhh** [comment]
dear @Rakesh9100 please assign me for  this project

**Comment by Rakesh9100** [comment]
Do you want to add this as a component and in which category @codewithganeshhh

**Comment by codewithganeshhh** [comment]
In Card Component @Rakesh9100

**Comment by codewithganeshhh** [comment]
Assign me @Rakesh9100

**Comment by Rakesh9100** [comment]
What will be the name of your card @codewithganeshhh

**Comment by Rakesh9100** [comment]
Any update or should I close this issue @codewithganeshhh

**Comment by codewithganeshhh** [comment]
PORT ID Card @Rakesh9100

**Comment by Rakesh9100** [comment]
Okay proceed @codewithganeshhh

**Comment by codewithganeshhh** [comment]
@Rakesh9100 add level for Issue otherwise i don’t give point in gssoc leader board

**Comment by Rakesh9100** [comment]
No, it will not be any problem @codewithganeshhh
