### ISSUE TITLE
[Style] Align the 3D Rotating Text Animation component

### ISSUE THREAD

**Issue by Shashanktriathi1703** [Rakesh9100/Beautiify#734]
### Description

# Adjusting Panel Position
* In the text-animation folder, there is a 3D Rotating Text Animation. When I clicked on the link for the 3D rotating text 
animation, it appeared at the top of the webpage, causing the text to not display perfectly and look a bit awkward.
* Adjust the width, left, and angle values in the panel definitions to ensure they are properly spaced and displayed within 
the scene without overlapping or going out of bounds.

### Screenshots

![3d-rotating](https://github.com/Rakesh9100/Beautiify/assets/105815482/2e508f00-1021-4317-915f-ff3b6ed3bca7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Shashanktriathi1703** [comment]
Allow me to work on this issue under GSSOC' 2024.

**Comment by Rakesh9100** [comment]
Proceed and also align it properly at the center of the screen @Shashanktriathi1703

**Comment by thecloudcode** [comment]
Hi @Rakesh9100, I have a brief understanding of the code base, and I can work on this issue pretty well, kindly assign me this issue. I would love to work on it.

**Comment by thecloudcode** [comment]
Hi, @Rakesh9100 , I have **solved** the issue.

##Screenshot
![Screenshot 2024-06-08 202645](https://github.com/Rakesh9100/Beautiify/assets/114615639/341cabfd-ffdf-4407-8e69-2aaa6ebd8480)

Kindly **assign** me this issue under GSSoC'24, so that I can send you a **pull request** to merge the code.

**Comment by Shashanktriathi1703** [comment]
Sorry, I have lost time because of me, I had my university exam, now I am free. @Rakesh9100 I am now working on this issue.
