### ISSUE TITLE
[Feature] <Adding About Us Page>

### ISSUE THREAD

**Issue by meghana9044** [Rakesh9100/Beautiify#735]
### Description

A About Us page is important for any website to tell users what the website is about in 3-4 lines.
I'm interested in contributing to this project under GSSOC'24. Please assign this issue to me. 
My About Us page will be attractive and elegant.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by PSTabaswiniSivamorthy** [comment]
Please assign me with this issue. I am interested to perform this task.

**Comment by Rakesh9100** [comment]
We already have About Us page, pls create new issues @meghana9044
