### ISSUE TITLE
[Feature] Add Dot Wave Background

### ISSUE THREAD

**Issue by nilamkumari11** [Rakesh9100/Beautiify#740]
### Description

The background will consist of dots, and hovering over any dot will generate an enchanting wave-like pattern, adding an intriguing dynamic to the visual experience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by maniranjan2023** [comment]
Kindly assign me this issue to me......

**Comment by Rakesh9100** [comment]
Do you want to add it as a component in the Backgrounds category @nilamkumari11

**Comment by nilamkumari11** [comment]
yes

**Comment by Rakesh9100** [comment]
Go ahead @nilamkumari11

**Comment by Rakesh9100** [comment]
Pls provide your PR @nilamkumari11
