### ISSUE TITLE
[Feature] Add Abstract Background

### ISSUE THREAD

**Issue by Dsmita03** [Rakesh9100/Beautiify#742]
### Description

Addition of abstract background in components [background]

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.\
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot @Dsmita03

**Comment by Dsmita03** [comment]
1) screenshot of the background:
<img width="1162" alt=" abstract background 1" src="https://github.com/Rakesh9100/Beautiify/assets/123728188/cc938c6a-b14a-46ee-9f99-49060f4a4960">


2)Screenshot (after applying js)

<img width="1162" alt=" abstract (moving)" src="https://github.com/Rakesh9100/Beautiify/assets/123728188/6e175142-ab06-4943-be66-885275d7075c">

**Comment by Rakesh9100** [comment]
Okay go ahead @Dsmita03
