### ISSUE TITLE
[Feature] Add Product Order Validation Card

### ISSUE THREAD

**Issue by Piyushkharapkar** [Rakesh9100/Beautiify#743]
### Description

 The focus of the product order validation card should be on providing a clear and user-friendly interface for users to review and confirm their order details. Used simple and crisp design and animations on buttons. 

https://github.com/Rakesh9100/Beautiify/assets/155226533/f7ca63af-d058-4a11-b712-94fa4810e5b6

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Piyushkharapkar
