### ISSUE TITLE
in navigation bar section 2nd heading  text is no proper visible in dark mode

### ISSUE THREAD

**Issue by kartikmehta18** [Rakesh9100/Beautiify#744]
### What's the style idea?

We need to improve in dark mode black color change in to white
![image](https://github.com/Rakesh9100/Beautiify/assets/125860170/5665158e-53c5-49e3-aeb6-766c032ee126)
@

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kartikmehta18** [comment]
i am gssoc24 contributor 
plz assigm me this issue

**Comment by GnanariddhikaRavikumar** [comment]
Hi, could you assign me this issue under GSSOC'24

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls create new issues @kartikmehta18
