### ISSUE TITLE
[Style] Enhance the components category in home page

### ISSUE THREAD

**Issue by Mdazar123** [Rakesh9100/Beautiify#747]
### What's the style idea?

We need to improve 
by adding new color components to make the user feel good and attract them to use the website again and again, leading to a better user experience. 
Making the components transparent doesn't look good. Colors like white and black are mandatory to give a classic look to the website.
I have a good grasp of CSS styling. I have created many clones and developed my own website, OvenOasis. I have a good command of coloring ratios and I am confident that I can make this website more attractive.
 Please assign this project to me under GSSOC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Mdazar123** [comment]
please assign this to me

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

**Comment by Rakesh9100** [comment]
Do you want to be assigned @Mdazar123

**Comment by Mdazar123** [comment]
@Rakesh9100,

I am very proficient in the design aspect of projects and always give my 100% effort. I am eagerly waiting to be assigned a task and am ready to contribute

**Comment by Rakesh9100** [comment]
Go ahead @Mdazar123

**Comment by Mdazar123** [comment]
Thank you, @Rakesh9100, for assigning this task to me. I truly appreciate the opportunity and am eager to contribute my best efforts.

**Comment by Rakesh9100** [comment]
Pls provide your PR @Mdazar123

**Comment by Mdazar123** [comment]
Hi @Rakesh9100,

I apologize for the delay in submitting my PR. My semester mid Exams are currently underway, which has occupied most of my time. However, my exams will be over by Saturday evening, and I will make sure to submit the PR by then.

**Comment by Rakesh9100** [comment]
Are you ready with your PR @Mdazar123

**Comment by Mdazar123** [comment]
Hi @Rakesh9100,

I apologize for the delay; it was due to the Bakrid celebrations.

I have created a pull request for this issue : #1078

Thank you for your understanding and patience.
