### ISSUE TITLE
Add UI to blank backgrounds of the components

### ISSUE THREAD

**Issue by muskan42** [Rakesh9100/Beautiify#75]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Some of the components are with blank backgrounds.
I wish to add UI to these pages or enhance the existing ones.

### Screenshots

![Screenshot 2024-01-06 004445](https://github.com/Rakesh9100/Beautiify/assets/141642724/7b915af6-f869-4b61-ba2f-916020cddbb3)
![Screenshot (66)](https://github.com/Rakesh9100/Beautiify/assets/141642724/512a5789-0c7c-4635-b1a7-7eeaf97dbbbe)
![Screenshot (65)](https://github.com/Rakesh9100/Beautiify/assets/141642724/542fa684-5fa7-43f7-a3c8-654670db13f5)
![Screenshot (64)](https://github.com/Rakesh9100/Beautiify/assets/141642724/83c9af98-e572-4b96-a082-d66dcdc842fa)
![Screenshot (63)](https://github.com/Rakesh9100/Beautiify/assets/141642724/db715b8a-3edd-46de-9b83-7370ad3322ba)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by muskan42** [comment]
@Rakesh9100 Kindly assign me the issue under SWOC'24.

**Comment by Rakesh9100** [comment]
Proceed @muskan42

**Comment by muskan42** [comment]
Thank you!

**Comment by Aditi-Dahiya** [comment]
What's the update on your work @muskan42   ?
