### ISSUE TITLE
[Feature] Add a review page

### ISSUE THREAD

**Issue by kanishka-parmar** [Rakesh9100/Beautiify#753]
### Description

Add a review page that will have experience and reviews about this site by the people who have used this. 
As this site is for helping the developers enhance their site; to make new people trust I suggest the review page where everyone who is part of this community can give their reviews which helps the new ﻿individuals to trust this site. 

I want to work on this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by kanishka-parmar** [comment]
@Rakesh9100 Please assign me this under GSSOC'24

**Comment by Sooraj002** [comment]
Hey I would like to resolve this issue

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@Rakesh9100  Sir, I would really like to work on this issue under Gssoc'24, so please assign it to me.

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

**Comment by 143divya** [comment]
Please assign this to me

**Comment by Rakesh9100** [comment]
What that review page will contain and where reviews will be sent, pls elaborate @kanishka-parmar

**Comment by kanishka-parmar** [comment]
From review page I mean like testimonials where people will share their experiences and how it helped them or any doubt they have they can share that. It will help the new people to trust the site and use it .

**Comment by Rakesh9100** [comment]
Okay go ahead @kanishka-parmar

**Comment by kanishka-parmar** [comment]
Thanks @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls provide your PR @kanishka-parmar

**Comment by kanishka-parmar** [comment]
@Rakesh9100 yeah I am working on it. Sorry for the delay I was lil busy with exams so

**Comment by Rakesh9100** [comment]
Are you still working @kanishka-parmar

**Comment by kanishka-parmar** [comment]
It will take some time due to exams, in first week of July I will complete it for sure .

**Comment by Rakesh9100** [comment]
Provide your PR now @kanishka-parmar

**Comment by kanishka-parmar** [comment]
> Provide your PR now @kanishka-parmar

Yes
