### ISSUE TITLE
[Style] Want to style the navbar differently

### ISSUE THREAD

**Issue by ayush-848** [Rakesh9100/Beautiify#757]
### What's the style idea?

![image](https://github.com/Rakesh9100/Beautiify/assets/126975547/c0996ce3-a86c-4ce3-ba2c-3c7361ef9f08)

1. The navbar will remain transparent until a certain vertical scroll.
2. On hover the font will change its color.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ayush-848** [comment]
@Rakesh9100 Please assign this issue to me. I am a GSSoC'24 contributor.

**Comment by SHANMUGAPRIYA-1** [comment]
Please do assign this task to me

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.
