### ISSUE TITLE
[Style] Enhance the navbar

### ISSUE THREAD

**Issue by anshika-gupta21** [Rakesh9100/Beautiify#759]
Hello @Rakesh9100 , I am GSSoC'24 contributor. I would like to contribute to this project to make it much more better. Currently, the hover function on Navbar has a little less margin and also the color scheme is not looking as beautiful as the project. It is wonderful project and can be made much better just by a little changes. 

Kindly assign me this issue and I'll work on it right now. 
![Screenshot 2024-05-17 171155](https://github.com/Rakesh9100/Beautiify/assets/124676798/e0edd2fb-4cf2-4875-8c96-fb6bf5a55076)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by sxnkush** [comment]
Kindly assign this project to me.

**Comment by Rakesh9100** [comment]
What changes do you want to make @anshika-gupta21

**Comment by anshika-gupta21** [comment]
I would like to improve the color scheme and margin and padding of the website. It would beautify the Beutiify website even more. Like you can see in the screenshot there is very less padding, this can be improved. Also, color scheme needs to be improved so that all components of navbar are visible clearly. @Rakesh9100

**Comment by bhavanishanker-png** [comment]
please assign this issue to me, i can work on this, i have made the local setup as well, i can make the changes, and resolve this issue

**Comment by Rakesh9100** [comment]
Go ahead @anshika-gupta21

**Comment by anshika-gupta21** [comment]
Thank you @Rakesh9100
