### ISSUE TITLE
ChatBot feature not closing.

### ISSUE THREAD

**Issue by saketh-05** [Rakesh9100/Beautiify#760]
### Description

If we click on chatbot icon, then it opens. But if we want to close it, is not possible. I want to fix this issue. I will make the chatbot feature to be able to close/open easily. Please assign this issue to me under GSSoC'24

### Screenshots

![Screenshot 2024-05-17 190437](https://github.com/Rakesh9100/Beautiify/assets/134281589/6389e15d-0a7e-4d87-9d69-cd4346dc3c04)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by adityakishore25** [comment]
Hey @saketh-05 could assign this issue to me. I want to work on this issue.

**Comment by abhishek7673** [comment]
It is closing well. No need to worry. I did it several times. Instead, you can decrease the box length for better.

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, pls create new issues @saketh-05
