### ISSUE TITLE
Modify the buttons on the Contact form

### ISSUE THREAD

**Issue by navyamalhotra78** [Rakesh9100/Beautiify#761]
### What's the style idea?

The send message button on the form on the contact me page is not aligned and is conflicting with the footer. It would look great if I could change this alignment. Please assign this to me under GSSoC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by arpit4521** [comment]
Please assign me this issue so that I can show and add unique features producing better illustration.

**Comment by Rakesh9100** [comment]
This is already fixed, pls work on other issues @navyamalhotra78
