### ISSUE TITLE
[Feature] Add Smoke Background

### ISSUE THREAD

**Issue by pavitraag** [Rakesh9100/Beautiify#765]
### Description

I would like to add a Smoke Animation Background and Rainfall Animation Background,can you @Rakesh9100 assign me .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Provide your PR @pavitraag

**Comment by pavitraag** [comment]
I am almost done but unable to link in the final html code.Please give me some time.
