### ISSUE TITLE
[Style] Enhance the About page

### ISSUE THREAD

**Issue by syannam-12** [Rakesh9100/Beautiify#766]
### What's the style idea?

In my opinion. the about page is not styled properly. It looks like a plain text with black background. If given a chance I will try to enhance its appearance to the best of my ability

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by syannam-12** [comment]
Thanks, I will.

**Comment by Rakesh9100** [comment]
What enhancements you want to make @syannam-12

**Comment by syannam-12** [comment]
The overall background of the website is very colourful and I feel that the
dark background of the about page does not go well with the theme. I would
also like to improve the font style and the navbar hover effect. I would
really appreciate it if you could assign this issue to me.
Thank you

**Comment by Rakesh9100** [comment]
Go ahead @syannam-12

**Comment by syannam-12** [comment]
@Rakesh9100/Beautiify ***@***.***>  Please mention the
level for this issue #766

**Comment by Rakesh9100** [comment]
Pls provide your PR @syannam-12
