### ISSUE TITLE
[Style] : change in the component section

### ISSUE THREAD

**Issue by thekirti02** [Rakesh9100/Beautiify#769]
### What's the style idea?

Hello PA,
We need to improve the component section,  removing the "search component" will be good for the user experience as there is a "get component" option. So it looks disorganized or messy. we can take one of them.
I am a GSSoc'24 contributor.
Thank you _.
<img width="944" alt="beautiigy" src="https://github.com/Rakesh9100/Beautiify/assets/105008820/f8bbfb29-7e67-424b-948a-1454b927691b">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No, it is fine, and we will keep both of them. Pls create good issues @thekirti02
