### ISSUE TITLE
[Style] Enhance the Beautiify heading

### ISSUE THREAD

**Issue by sheetal-81** [Rakesh9100/Beautiify#770]
### What's the style idea?

We need to improve { Beautiify } heading in animation form like text color animation effect 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by 90firoj** [comment]
Hello sir , please add the label.
I want to work on it .

**Comment by Stut26** [comment]
Hey please assign the label.
I want to work on this. Please assign this to me.

**Comment by HareRamDwivedi** [comment]
I am a GSSOC contributor , I have a good experience in UI designing I can make it more visually appealing please assign me this issue under GSSOC 2024

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot of your issue @sheetal-81

**Comment by sheetal-81** [comment]
okay 
The changes i want to do in Beatify heading 
I am writing it here according to priority wise -{1} Text logo animation {2} Loading Style CSS Text Animation {3} Text color animation 
for **Text color  animation** i have sample video of its 
https://github.com/Rakesh9100/Beautiify/assets/134307985/0af87202-0d08-4189-86d6-d47e080e6951

for Loading Style CSS Text Animation here is the code 
<svg viewBox="0 0 960 300">
	<symbol id="s-text">
		<text text-anchor="middle" x="50%" y="80%">Beautify  </text>
    <text text-anchor="middle" x="52%" y="80%">Beautify   </text>
    
	</symbol>

	<g class = "g-ants">
		<use xlink:href="#s-text" class="text-copy"></use>
		<use xlink:href="#s-text" class="text-copy"></use>
		<use xlink:href="#s-text" class="text-copy"></use>
		<use xlink:href="#s-text" class="text-copy"></use>
		<use xlink:href="#s-text" class="text-copy"></use>
	</g>
</svg>

.css file 
@import url(https://fonts.googleapis.com/css?family=Montserrat);

html, body{
  height: 100%;
  font-weight: 800;
}

body{
  background: yellow;
  font-family: Arial;
}

svg {
    display: block;
    font: 10.5em 'Montserrat';
    width: 960px;
    height: 300px;
    margin: 0 auto;
}

.text-copy {
    fill: none;
    stroke: white;
    stroke-dasharray: 6% 29%;
    stroke-width: 5px;
    stroke-dashoffset: 0%;
    animation: stroke-offset 5.5s infinite linear;
}

.text-copy:nth-child(1){
	stroke: #4D163D;
	animation-delay: -1;
}

.text-copy:nth-child(2){
	stroke: #840037;
	animation-delay: -2s;
}

.text-copy:nth-child(3){
	stroke: #BD0034;
	animation-delay: -3s;
}

.text-copy:nth-child(4){
	stroke: #BD0034;
	animation-delay: -4s;
}

.text-copy:nth-child(5){
	stroke: #FDB731;
	animation-delay: -5s;
}

@keyframes stroke-offset{
	100% {stroke-dashoffset: -35%;}
}


**and for text logo animation** 

<div class="logo-container">
  <h1 id="page-logo">LOGO</h1>
</div>

.css
*, *:before, *:after { box-sizing: border-box; }
html { height: 100%; }
body {
	display:          flex;
	align-items:      center;
	justify-content:  center;
	min-height:       100%;
	background-color: #f5f6f9;
}

.logo-container {
	position: relative;
	
	&:before {
		content:  "";
		position: absolute;
		top:      calc( 100% - 2px );
		width:    100%;
		height:   4px;
		background-color: #cf0000;
		transform-origin: center center;
		transform: scaleX( 0 );
		
		animation: line-animation 3s ease infinite alternate;
	}
	
	h1#page-logo {
		font: bold 6rem 'Arial', sans-serif;
		
		animation: clip-path-reveal-1 3s ease infinite alternate;
	}
}

@keyframes line-animation {
	0% { transform: scaleX( 0 ); }
	15% { transform: scaleX( 0 ); }
	20%, 25% { transform: scaleX( 1 ); top: calc( 100% - 2px ); }
	50% { transform: scaleX( 1 ); top: 0px; }
	70% { transform: scaleX( 0.2 ); top: 0px; }
	80%, 100% { transform: scaleX( 0.2 ); top: 0px; }
}

@keyframes clip-path-reveal-1 {
	0%, 25% { clip-path: polygon(0 100%, 100% 100%, 100% 100%, 0% 100%); }
	50% { clip-path: polygon(0 0, 100% 0, 100% 100%, 0% 100%); }
}

**Comment by Rakesh9100** [comment]
Go ahead @sheetal-81
