### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by aditi9402** [Rakesh9100/Beautiify#771]
### Category of documentation update

Want to add a well defined code of conduct document for the repository under GsSoc 24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have Code of conduct, pls check properly before creating any issue @aditi9402
