### ISSUE TITLE
[Bug] Fix the scroll to top icon for small devices

### ISSUE THREAD

**Issue by sharmi4590** [Rakesh9100/Beautiify#772]
### Description

Hey @Rakesh9100 
There's a overlapping in the message button and top up button . There's the icon also missing for the top up button.

### Screenshots

![Screenshot_20240518-224814](https://github.com/Rakesh9100/Beautiify/assets/102676949/304dcc23-13a4-43fd-9f5b-927829c1af16)
At the bottom right you can see the overlapping , I will make it responsive and add the icon to the top up button
I am a GSSOC'24 contributor 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Sowmyatiwari** [comment]
Heyy , the buttons of this project is not looking attractive ,and also the footer is not properly aligned , I will fix this issue , please consider assigning  it to me.

**Comment by 143divya** [comment]
Please assign this to me

**Comment by Deepthi-Ramineni** [comment]
I would like to work on this. Can you please assign it to me?

**Comment by anushreenair** [comment]
I have reviewed the current state of the interface and have a clear understanding of the required adjustments. Additionally, I have experience with responsive design and CSS, which I believe will help me effectively tackle this issue.
Could you please assign this issue to me? I am eager to contribute to the project and help enhance the user experience of the Beautiify app.

**Comment by Rakesh9100** [comment]
Proceed @sharmi4590
