### ISSUE TITLE
[Style] Improve About Us page UI

### ISSUE THREAD

**Issue by nagalakshmi08** [Rakesh9100/Beautiify#773]
### What's the style idea?

We need to improve the UI of about us page in mobile phones.
![Screenshot_20240518_231415](https://github.com/Rakesh9100/Beautiify/assets/121669832/7c245329-3dce-4626-96be-19642c9365d4)
The text is taking too much height leaving empty space on left side.
This can be improved by changing the style.
Please assign me this issue, I would like to contribute to this project under GSSoC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rishitatripathi** [comment]
Please assign me this issue, I would like to contribute to this project under GSSoC'24.

**Comment by akarshi19** [comment]
Please assign this issue to me under GSSoC'24

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls create new issues @nagalakshmi08
