### ISSUE TITLE
[Style] Enhance the components category symbols

### ISSUE THREAD

**Issue by Akshitha-reddy-13** [Rakesh9100/Beautiify#774]
### What's the style idea?

We could give previews of each 
![image](https://github.com/Rakesh9100/Beautiify/assets/122172211/ef25ff11-c342-4518-8196-aee43401247e)

and can also enhance the symbols in the below image 
![image](https://github.com/Rakesh9100/Beautiify/assets/122172211/4176ee50-cddc-43f8-8d67-e19982c65ded)

Can you assign it to me? @ra
Full name: Akshitha Reddy
GitHub profile link: [Akshitha-reddy-13](https://github.com/Akshitha-reddy-13)
Email ID: akshithajagan13@gmail.com
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Akshitha-reddy-13** [comment]
The icons are looking ordinary, and the user interface is not attractive, so i would like to change the user interface in a more efficient way.

**Comment by Rakesh9100** [comment]
Go ahead @Akshitha-reddy-13

**Comment by Rakesh9100** [comment]
Pls provide your PR @Akshitha-reddy-13

**Comment by Akshitha-reddy-13** [comment]
Please excuse me for 2 days I will provide PR by Saturday night.

**Comment by Akshitha-reddy-13** [comment]
Sorry
