### ISSUE TITLE
[Bug] Fix the card content overflowing in Contact page

### ISSUE THREAD

**Issue by usharani222** [Rakesh9100/Beautiify#777]
### Description
The card content in contact page is overflowing 

### Screenshots

<img width="960" alt="Screenshot 2024-05-19 191852" src="https://github.com/Rakesh9100/Beautiify/assets/126246565/7aef192e-1c87-4508-9156-0be18a36d4b7">

I want to fix this issue under gssoc 
Can you assign it to me? 
Full name: Usha Rani
GitHub profile link: https://github.com/usharani222
Email ID: usha78633@gmail.com
LinkedIn: https://www.linkedin.com/in/usha-rani-a26098264/
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by usharani222** [comment]
I am a proficient front-end developer with expertise in HTML, CSS, JavaScript, and React. **Assign me this issue**

Thanks

**Comment by usharani222** [comment]
Please assign me this issue @Rakesh9100

**Comment by Rakesh9100** [comment]
For which screen are you facing this issue @usharani222

**Comment by usharani222** [comment]
On laptop 
Assign me this issue @Rakesh9100
