### ISSUE TITLE
[Style] Enhance the About us page

### ISSUE THREAD

**Issue by Bhavishya2601** [Rakesh9100/Beautiify#779]
### What's the style idea?

The current UI of about us page isn't upto standards of the rest of the webpage
I wanna change it and make it professional and at the same time match your webpage

Hope you would assign this task to me under gssoc

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Komalpreet-Kaur112** [comment]
Hi @Rakesh9100
I am a participant in the GirlScript Summer of Code. I came across this issue regarding the enhancement of the "About Us" page and I would love to work on it. I have some ideas to add more styling and make the page look more attractive.
 I am excited to contribute and look forward to your response.
Could you please assign this issue to me? 
<img width="1280" alt="Screenshot 2024-05-30 at 11 04 01 PM" src="https://github.com/Rakesh9100/Beautiify/assets/143227316/c18997b7-5c38-45b4-aa5e-e4f38b3d7c42">

**Comment by Rakesh9100** [comment]
Go ahead @Bhavishya2601

**Comment by Rakesh9100** [comment]
What ideas do you have to make it attractive, provide the before and after styling screenshots of your idea @Komalpreet-Kaur112
