### ISSUE TITLE
Glowing Text Animation

### ISSUE THREAD

**Issue by GhoshAditi** [Rakesh9100/Beautiify#78]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to add Glowing Text Animation to the website.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @GhoshAditi
