### ISSUE TITLE
[Docs] Improve Readme

### ISSUE THREAD

**Issue by srivaniganji** [Rakesh9100/Beautiify#782]
### What's the style idea?

I have been exploring the project and noticed that the documentation of the environment could be improved. The current instructions are somewhat sparse and could benefit from more detailed steps, especially for newcomers who may not be as familiar with the required tools and dependencies.

So, could you give me an opportunity to use my skill to improve the project.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rishitatripathi** [comment]
Please assign me this issue under GSSoc'24.

**Comment by meenakshiiyer2531** [comment]
Hello,
Can you please assign me this issue for Gssoc 24. I ensure to work and complete the assignment on time.
Regards,
V Meenakshi Iyer
