### ISSUE TITLE
[Style] Enhance footer

### ISSUE THREAD

**Issue by srivaniganji** [Rakesh9100/Beautiify#783]
### What's the style idea?

Looking forward for a chance to update the footer bar in the website as it looks quite nasty..

So, could you please assign this project to me!

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by BhumikaRahwani** [comment]
Hi!! @srivaniganji , Plz do assign me the issue, as i am very eager to address it.

**Comment by Rishitatripathi** [comment]
Please assign me this issue under GSSoc'24.

**Comment by HareRamDwivedi** [comment]
I am a GSSOC contributor , I have a good experience in UI designing I can make it more visually appealing please assign me this issue under GSSOC 2024

**Comment by srivaniganji** [comment]
Done with the enhancement.. Thank you all.. I am closing this issue.
