### ISSUE TITLE
[Feature] Adding animation effects on scroll

### ISSUE THREAD

**Issue by ShaikArshidBanu** [Rakesh9100/Beautiify#786]
### Description

I would like to add the animation effects on scroll as shown in the following video to the website. Please assign this issue to me.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/112767165/7a2db889-84da-4489-b992-888d766bb6a8

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by ShaikArshidBanu** [comment]
Please assign this issue to me.

**Comment by Rakesh9100** [comment]
No need of these animations, pls work on other issues @ShaikArshidBanu
