### ISSUE TITLE
[Feature] Add Loading Text Animation & Gradient Background

### ISSUE THREAD

**Issue by amandollar** [Rakesh9100/Beautiify#787]
### Description

I would like to suggest adding two new components to enhance the visual appeal and user experience of the website: a loading text animation in the text animation section and a gradient background in the background section.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by meenakshiiyer2531** [comment]
hey @Rakesh9100 
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer

**Comment by Rakesh9100** [comment]
Go ahead @amandollar

**Comment by amandollar** [comment]
Sure,i am working on it

**Comment by Rakesh9100** [comment]
Pls provide your PR @amandollar

**Comment by amandollar** [comment]
#Issue Number 787

I have already created a pr
