### ISSUE TITLE
[Feature] Add theme changing option

### ISSUE THREAD

**Issue by priyaladesara** [Rakesh9100/Beautiify#794]
### Description

Adding theme chnaging option to nav-bar panel to turn it in bright and dark mode.

I can help to add this feature and  enhace this under GSSoC'24. Please assign me this . @Rakesh9100 

Also can you add labels for GSSoc and levels .
Thank you.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Shravani246** [comment]
Can you assign this issue to me. I can do it

**Comment by Rakesh9100** [comment]
We already have this on the navbar, pls create new issues @priyaladesara
