### ISSUE TITLE
[Docs] contributing.md file is missing

### ISSUE THREAD

**Issue by priyaladesara** [Rakesh9100/Beautiify#795]
### Category of documentation update

In code section documentation for contribution can be made easier via adding contributing file separately.
please assign this task to me  under GSSoC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Contributing_Guidelines.md file is already present, pls check properly before creating an issue @priyaladesara
