### ISSUE TITLE
[Style] Align the contributors section

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/Beautiify#796]
The contributor's profile image in not correctly aligned.

![Screenshot 2024-05-22 195802](https://github.com/Rakesh9100/Beautiify/assets/142779809/25dc2c9a-6eb0-4158-9010-269370ca7b9a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by priyaladesara** [comment]
I can fix this under GSSoC'24. please assign it to me . @Rakesh9100 .

**Comment by Varsha010101** [comment]
This issue is because the image link at the empty location is redirecting to a blank site with no avatar. I can fix this issue under GSSoC'24. Please assign it to me. @Rakesh9100.

**Comment by soniya-malviy** [comment]
I would like to solve this issue please assign me this issue. @Rakesh9100 .

**Comment by Rakesh9100** [comment]
Go ahead @root-0101

**Comment by Rakesh9100** [comment]
Provide your PR @root-0101

**Comment by root-0101** [comment]
I will do it by today
