### ISSUE TITLE
[Style] Enhance the text color in Contact Page

### ISSUE THREAD

**Issue by Anshika-Gochar** [Rakesh9100/Beautiify#799]
### What's the style idea?

We need to change the color of text in contact page to improve visibility of the heading for a good interactive experience.
![issue 2](https://github.com/Rakesh9100/Beautiify/assets/148606019/0a57b59b-91e9-46f4-9f6a-b7f6c8046488)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anshika-Gochar** [comment]
please assign this  issue to me under GSSOC'24.

**Comment by Anshika-Gochar** [comment]
please assign this to me under GSSoc'24

**Comment by HareRamDwivedi** [comment]
I am a GSSOC contributor , I have a good experience in UI designing I can make it more visually appealing please assign me this issue under GSSOC 2024

**Comment by Rakesh9100** [comment]
Proceed @Anshika-Gochar

**Comment by Henin-6024** [comment]
I would like to contribute for this project. Please assign this task to me under GSSoC'24 with required labels.

**Comment by Meghana-n10** [comment]
I want to enchance the text colour. Please allow me to contribute to it. Please assign me this issue under ggsoc'24

**Comment by Rakesh9100** [comment]
Pls provide your PR @Anshika-Gochar
