### ISSUE TITLE
[Style] Increase the hover size on navbar

### ISSUE THREAD

**Issue by Anshika-Gochar** [Rakesh9100/Beautiify#800]
### What's the style idea?

We need to improve the hover box's size and color in order to make it more appealing and match with the page's vibe
![beautify](https://github.com/Rakesh9100/Beautiify/assets/148606019/d7b91ba6-494f-4f17-9c7a-3e07b395ee72)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anshika-Gochar** [comment]
i can fix this and make it more attractive, so please assign this to me under GSSOC'24 ...

**Comment by Rakesh9100** [comment]
Do you want to work on this @Anshika-Gochar

**Comment by Anshika-Gochar** [comment]
Yessss please assign this to me

**Comment by Rakesh9100** [comment]
Go ahead @Anshika-Gochar
