### ISSUE TITLE
[Style] Align the close button in Overlay Navigation Bar

### ISSUE THREAD

**Issue by shreya-paul-17** [Rakesh9100/Beautiify#802]
### What's the style idea?

We need to improve the placing of the close button to the top. It will result in better enhancement 

Below is an attached screenshot:
![beautiify](https://github.com/Rakesh9100/Beautiify/assets/135226069/9bbfdbae-4027-4ee3-b76b-8a2f7296c64a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
For which component are you talking about @shreya-paul-17

**Comment by shreya-paul-17** [comment]
@Rakesh9100  This has occurred in the overlay navigation bar of navigation bar component

**Comment by Shweta-281** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me?

**Comment by Rakesh9100** [comment]
Okay go ahead @shreya-paul-17

**Comment by Rakesh9100** [comment]
Pls provide your PR @shreya-paul-17
