### ISSUE TITLE
[Feature] Add Black Red Signup Form

### ISSUE THREAD

**Issue by Vaishnavi1047** [Rakesh9100/Beautiify#804]
### Description

**Elegant and pleasing black and red design** 

(GSSOC contribution)

### Screenshots

![Screenshot 2024-05-25 143443](https://github.com/Rakesh9100/Beautiify/assets/149894552/3db07177-ab83-47bb-b719-9bc89021f912)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to add it as a component in the Forms category @Vaishnavi1047

**Comment by Vaishnavi1047** [comment]
yes sir in the form section

**Comment by Vaishnavi1047** [comment]
yes in that form component sir

**Comment by Rakesh9100** [comment]
Go ahead @Vaishnavi1047

**Comment by Vaishnavi1047** [comment]
https://github.com/Rakesh9100/Beautiify/pull/803
heres the pull request pls merge it
