### ISSUE TITLE
Improper alignment of send message button with the rest of the contact Information window in the Contact Section 

### ISSUE THREAD

**Issue by Meghanadh1337** [Rakesh9100/Beautiify#805]
### Description

Hello Sir  ,I have noticed that  send message button is forced down and not aligned properly with the rest of the contact Information window in the Contact Section.
(Observed using the Windows Edge Browser).
Please assign the issue so I can resolve it.

### Screenshots

<img width="1440" alt="Screenshot 2024-05-26 at 12 08 16 AM" src="https://github.com/Rakesh9100/Beautiify/assets/116261133/a53293d7-a15c-409d-8b82-dcebd0a6d4d4">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue is already open for this, pls create new issues @Meghanadh1337
