### ISSUE TITLE
[Feature] :Unable to close chatbot 

### ISSUE THREAD

**Issue by Garima-149** [Rakesh9100/Beautiify#810]
### Description

There is no option for closing the opened chatbot which creates a bad user experience. @Rakesh9100 please assign this issue to me.

### Screenshots

![Screenshot (41)](https://github.com/Rakesh9100/Beautiify/assets/143211271/342da01f-71f1-408a-a386-8395ae7efc6f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, pls create new issues @Garima-149
