### ISSUE TITLE
[Style] Enhance the color of text in Get Components button

### ISSUE THREAD

**Issue by shuhaki** [Rakesh9100/Beautiify#811]
### Description

Improve the hover effect and font color of the button ... because it's beauty website and font color looks like dark... so I want to change the color....for best looking for user.

<img width="446" alt="Screenshot 2024-05-27 at 1 53 00 AM" src="https://github.com/Rakesh9100/Beautiify/assets/145912232/1d154eca-f835-45e1-8235-38e389b0059e">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @shuhaki
