### ISSUE TITLE
[Bug] Fix the chatbot close button

### ISSUE THREAD

**Issue by Anupsimha** [Rakesh9100/Beautiify#812]
### Description

The Head Section Of Chat Bot Is behind The Navigation Bar, and There Is No Option For Cancelling The Chat Bot Field If The User Wants To.
Please Assign This Task Under Me For GSSOC'24!!!

### Screenshots

![Screenshot 2024-05-27 055947](https://github.com/Rakesh9100/Beautiify/assets/144825137/b9b8eebd-f720-4201-8aaa-99f70f0c0431)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by tanvi1110** [comment]
Hey I would love to fix this

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, pls create new issues @Anupsimha
