### ISSUE TITLE
[Style] Enhance the navbar

### ISSUE THREAD

**Issue by DrishtiRai777** [Rakesh9100/Beautiify#818]
### What's the style idea?

We can improve the styling of the navigation bar to enhance the overall aesthetics of the website. Some suggestions we can incorporate for improvement are:

- Icon alignment and size
- Spacing
- Color scheme
- Font consistency and size
- Hover effects

I would like to make these changes. Could you please assign this issue to me under GSSOC 2024 ?
Thank you.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by RahaneSayali** [comment]
I am gssoc'24 contributor and I follow Contributing guidelines. Please assign this issue to me

**Comment by PratikMane0112** [comment]
I would like to work on this issue.

**Comment by Rakesh9100** [comment]
Go ahead @DrishtiRai777

**Comment by DrishtiRai777** [comment]
Thank you @Rakesh9100
