### ISSUE TITLE
[Bug] Fix the chatbot close button

### ISSUE THREAD

**Issue by kaushal8582** [Rakesh9100/Beautiify#819]
### Description

 Chatbot have not close button and chatbot heading is not show . so plz assign me this project to solve this issue .

### Screenshots

![Screenshot Capture - 2024-05-29 - 07-19-19](https://github.com/Rakesh9100/Beautiify/assets/137991463/56f94c17-d0a6-4aa8-a0a5-d124e449de8e)
![Screenshot Capture - 2024-05-29 - 07-19-19](https://github.com/Rakesh9100/Beautiify/assets/137991463/59bf186b-538f-4646-b435-3b7fe664fafb)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Issue 621 is already open for this, pls create new issues or you can comment there if you want to work @kaushal8582
