### ISSUE TITLE
[Feature] Add search icon in every search bar

### ISSUE THREAD

**Issue by soniya-malviy** [Rakesh9100/Beautiify#820]
### What would you like to share?

We can add search icon in every search bar which enhance user experience, and it will look good.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot properly @soniya-malviy

**Comment by soniya-malviy** [comment]
Before :
![Uploading Image 30-05-24 at 6.25 PM.jpeg…]()
After:
![Uploading Image 30-05-24 at 6.25 PM (1).jpeg…]()

**Comment by soniya-malviy** [comment]
before:
![without](https://github.com/Rakesh9100/Beautiify/assets/151515611/28783140-f657-45bc-afad-94a78187e278)
After:
![Uploading with.jpeg…]()

**Comment by Rakesh9100** [comment]
Do you want to work @thecloudcode

**Comment by thecloudcode** [comment]
yeah sure @Rakesh9100

**Comment by Rakesh9100** [comment]
Go ahead @thecloudcode

**Comment by thecloudcode** [comment]
@Rakesh9100 Kindly assign me this issue, before merging I am a GSSoC'24 Contributor. Thank you.

**Comment by aashlesha12** [comment]
I'm interested in working on issue #820. I've already reviewed the issue description and believe I have the necessary skills to contribute.

Please let me know if you're open to assigning this to me."

**Comment by Rakesh9100** [comment]
Do you want to work on this @aashlesha12

**Comment by Atharvverma1234** [comment]
Hi, I would like to work on this issue. Please assign it to me. Thank you!

**Comment by Rakesh9100** [comment]
Proceed @Atharvverma1234
