### ISSUE TITLE
[Feature] Disable the text selection on the website

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Rakesh9100/Beautiify#823]
### Description

Text is getting selected.. It should be turned off..

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/153417476/fc594bfe-1777-4dd4-8484-faccef9c12ab)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 Please assign me this issue under GSSoC 2024 ..

**Comment by Rakesh9100** [comment]
Go ahead @SuhainaFathimaM
