### ISSUE TITLE
[Feature] Add more footer components

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Rakesh9100/Beautiify#824]
### Description

1. Parallax Footer
2. Split Footer
3. Interactive Footer
4.  Sticky Footer
Adding these footers

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 Please assign me this issue under GSSoC 2024 ..

**Comment by Komalpreet-Kaur112** [comment]
Hey @Rakesh9100 
I would like to work on this issue. Please assign it to me.

**Comment by Rakesh9100** [comment]
Do you want to add these as components in the Footer category @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 Yes, I would like to add footers to the footers category

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 Please assign this issue

**Comment by thecloudcode** [comment]
Hi, @Rakesh9100, tell me what kind of footer you need, and in case, you are satisfied by the issue description, tell me. I can handle this pretty well. Would love to work on it.

Kindly, assign me this issue.

**Comment by Rakesh9100** [comment]
Pls provide your PR @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@Rakesh9100 I will submit the PR by today
