### ISSUE TITLE
[Feature] Add Circular Navigation Bar

### ISSUE THREAD

**Issue by itssarvani394** [Rakesh9100/Beautiify#827]
### Description

I would like to add other navigation bars like Flip-Navigation bar, Off-Canvas Navigation bar, Circular Navigation bar and Progress bar Navigation in the Navigation-bars section to enhance the features of the website.
Could you please add gssoc labels and assign it to me

### Screenshots

![Screenshot 2024-05-30 170452](https://github.com/Rakesh9100/Beautiify/assets/129776752/63cdc1ca-d1bb-4325-9932-2fc488874ea5)
![Screenshot 2024-05-30 171239](https://github.com/Rakesh9100/Beautiify/assets/129776752/0d86f9ba-f7a7-4730-930f-5f2b958ab1ab)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
You can add one by one in each issue, so which navigation bar you want to add for this issue @itssarvani394

**Comment by itssarvani394** [comment]
> You can add one by one in each issue, so which navigation bar you want to add for this issue @itssarvani394

I'd like to add circular navigation bar for this issue, so you'd want me to create an issue for each navigation bar?

**Comment by B8indu** [comment]
Please assign this issue

**Comment by Rakesh9100** [comment]
Yes, you can create separate issues for each one of them @itssarvani394

**Comment by Rakesh9100** [comment]
Yes, you can create separate issues for each one of them one by one @itssarvani394
