### ISSUE TITLE
Add Box Loader

### ISSUE THREAD

**Issue by chanda-04** [Rakesh9100/Beautiify#83]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Wanted to add a new loader in component as it has only 2 loading component and i wanna add one more to it .
 I have attached the image of loader.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/123861834/2c23cc77-8632-475f-8be1-5283680f74fe)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
What name you will provide to this loader? @chanda-04

**Comment by chanda-04** [comment]
Box Loader

**Comment by SohanRC** [comment]
Want to add a new Loader in the Loader Components Section. Please assign me under JWOC 2024.

**Comment by Rakesh9100** [comment]
@chanda-04 Status of your PR

@SohanRC You can open up new issues if you want to but you will be assigned from 15th Jan, 2024!!

**Comment by SohanRC** [comment]
Want to add a new Loader in the Loader Components Section. Please assign me under JWOC 2024.

**Comment by Rakesh9100** [comment]
You should open up new issue if you want to add a new component @SohanRC
