### ISSUE TITLE
[Feature] Add Profile Card

### ISSUE THREAD

**Issue by Vaishnavi1047** [Rakesh9100/Beautiify#835]
### Description

Adding a profile card in the card component of the website, just like an instagram or twitter profile card.

### Screenshots

![Screenshot 2024-03-13 002056](https://github.com/Rakesh9100/Beautiify/assets/149894552/c1520fa8-5c28-4182-9629-fa3d0cbbcafa)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Vaishnavi1047

**Comment by Vaishnavi1047** [comment]
https://github.com/Rakesh9100/Beautiify/pull/803/commits
pls look at these commits

**Comment by B8indu** [comment]
Please assign this issue
