### ISSUE TITLE
[Style] Enhance the home page

### ISSUE THREAD

**Issue by diyaaa19** [Rakesh9100/Beautiify#840]
### What would you like to share?

The selected feature on the navbar turns to bright red which is too flashy and the background of the footer featuring social media handles and your name should have a crisp solid background, which would enhance the overall look of the web app. @Rakesh9100 please assign me these issues under gssoc'24.
thanks

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the supporting screenshot of your issue @diyaaa19

**Comment by Rakesh9100** [comment]
Any update on this or should I close @diyaaa19

**Comment by diyaaa19** [comment]
somebody already addressed that issue, i can enhance the component pane though
![image](https://github.com/Rakesh9100/Beautiify/assets/151644762/015196be-f221-46f2-917d-5e8e0de756fb)
![image](https://github.com/Rakesh9100/Beautiify/assets/151644762/d07a8ebf-8a96-448b-8e74-0c78553f84c5)

**Comment by Rakesh9100** [comment]
Review this @saurabhsingh720

**Comment by saurabhsingh720** [comment]
> somebody already addressed that issue, i can enhance the component pane though ![image](https://private-user-images.githubusercontent.com/151644762/341375934-015196be-f221-46f2-917d-5e8e0de756fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTMwOTgsIm5iZiI6MTcxOTQ5Mjc5OCwicGF0aCI6Ii8xNTE2NDQ3NjIvMzQxMzc1OTM0LTAxNTE5NmJlLWYyMjEtNDZmMi05MTdkLTVlOGUwZGU3NTZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMjUzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDQwYjRhMWVhYWQ5ZWRmNTdiM2MzOTcxNzVjN2FiNjAzNzVmMDkzMWE1MDVjNDVhMDc1MDgyZTQyMzc0Y2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TJgZwOOIHk8zF_h7FidZ1aqgF8e4KD-gZyiB3xmbdrI) ![image](https://private-user-images.githubusercontent.com/151644762/341376071-d07a8ebf-8a96-448b-8e74-0c78553f84c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTMwOTgsIm5iZiI6MTcxOTQ5Mjc5OCwicGF0aCI6Ii8xNTE2NDQ3NjIvMzQxMzc2MDcxLWQwN2E4ZWJmLThhOTYtNDQ4Yi04ZTc0LTBjNzg1NTNmODRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxMjUzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzIwMDUwOGUyZWJiNmRmN2IxODFiMWNhOTY2N2M1NWQ1ZGVmNTgyYjRkYzA3MDljYjBjZWZkMDMyNWE2YWE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qRjywckG7N_SLLoRFsXidhCsDLp68Laod9NFkI3999A)

Its is not looking good.

**Comment by saurabhsingh720** [comment]
@diyaaa19 
Do something better so that UI matches the components style.

**Comment by Rakesh9100** [comment]
You can work on other good issues, this enhancement is not required as it is not matching with the UI @diyaaa19
