### ISSUE TITLE
[Bug] Fix the visibility of heading text in Contact page

### ISSUE THREAD

**Issue by aursh24** [Rakesh9100/Beautiify#843]
### Description

Text in Contact Us "Send us a Message" isn't very visible. I would like to change the styling of it to make it look more clear and visible.

### Screenshots

![Screenshot 2024-05-31 085440](https://github.com/Rakesh9100/Beautiify/assets/121930064/52f155d7-71d7-4c01-84ff-486bb0462ba5)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by aursh24** [comment]
@Rakesh9100 
please assign me this issue under GSSoC24.

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Assign them to make them visible

**Comment by Rakesh9100** [comment]
Go ahead @aursh24
