### ISSUE TITLE
[Style] Improve the animation on social icons in footer

### ISSUE THREAD

**Issue by Riddhi162** [Rakesh9100/Beautiify#845]
### What's the style idea?

We can improve the style/animation for the socials in footer. We can make something like this.

https://github.com/Rakesh9100/Beautiify/assets/135015856/1e7ffd48-d5f7-4aff-a85f-ec73b9bc2c83

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 it is good

**Comment by Rakesh9100** [comment]
Go ahead @Riddhi162
