### ISSUE TITLE
[Feature] Add Minecraft Button

### ISSUE THREAD

**Issue by Dsmita03** [Rakesh9100/Beautiify#850]
### Description

I want to add a new button under Component section.

Please assign me this issue under GSSOC'24

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/123728188/8853e677-5f9d-4431-8e52-0a3c5123f229

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Assign them

**Comment by Rakesh9100** [comment]
Proceed @Dsmita03
