### ISSUE TITLE
[Feature] Add Slide Login Register Form

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#855]
### Description

I want to add a new login form to the forms section.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/338e6dc6-590c-4f00-ab22-2bba01706d47

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Praneeth-2602 
Login and sign up not required

**Comment by Rakesh9100** [comment]
What will be the name of your form component @Praneeth-2602 

It is the component that he wants to add, he don't want to implement on the main website. So it is fine to add @Praneeth-2602

**Comment by Praneeth-2602** [comment]
SlideForm - Animated Login/Signup

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @Praneeth-2602

**Comment by Praneeth-2602** [comment]
@Rakesh9100 Please assign the issue now

**Comment by Rakesh9100** [comment]
Go ahead @Praneeth-2602
