### ISSUE TITLE
[Feature] Add proper message when no search results found

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/Beautiify#857]
### Description

In the components section, when i search for any invalid key, it displays nothing. It is better to display proper message like in the screenshot for best user experience.

### Screenshots

current situation:
![Screenshot 2024-05-31 193434](https://github.com/Rakesh9100/Beautiify/assets/139672976/185a4fa5-f722-45b1-b7ef-93e39d675a9c)

expected one:
![image](https://github.com/Rakesh9100/Beautiify/assets/139672976/66c1f959-2530-4fde-a050-5df2c77a7634)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Adding this make the project better

**Comment by Rakesh9100** [comment]
Go ahead @DharshiBalasubramaniyam
