### ISSUE TITLE
Add a Shooting Star Background

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#86]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hello, I want to add an animated shooting star background, please assign it to me under SWOC'24

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/67752e0b-b1b8-45fd-970a-e1a7e44eed82)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @rishicds
