### ISSUE TITLE
[Feature] Add dynamic code for year in footer section

### ISSUE THREAD

**Issue by tarushi29** [Rakesh9100/Beautiify#860]
### Description

Dynamic code using js function can be coded to enhance dynamic feature for year in the footer section.

### Screenshots

![Screenshot 2024-06-01 000652](https://github.com/Rakesh9100/Beautiify/assets/128239884/b0faeb59-e2a9-4f31-83b3-378f19d73be2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @tarushi29
