### ISSUE TITLE
[Feature] Add Zoom And Fade Background

### ISSUE THREAD

**Issue by sandy-queen** [Rakesh9100/Beautiify#862]
### Description

I want to add a background that will zoom in and out. It also has a fading effect. It works something like this: 

*Please assign the issue to me. I want to work on it for GSSOC'24*

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/147652780/8cee7a0e-4623-4e51-bfd7-fde8ac8b885b

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What will be the name of your background @sandy-queen

**Comment by sandy-queen** [comment]
> What will be the name of your background @sandy-queen

I think "Zoom and Fade" should be a suitable name
