### ISSUE TITLE
[Feature] Add Morphing Button

### ISSUE THREAD

**Issue by Mubashir2611** [Rakesh9100/Beautiify#863]
### Description
**I want to add a Morphing Button** 
**Assign me @Rakesh9100** 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/108177382/3c68d935-c656-4507-bdd1-feaa813d9396)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New addition, assign them

**Comment by Rakesh9100** [comment]
Go ahead @Mubashir2611
