### ISSUE TITLE
[Feature] Add custom cursor to the website

### ISSUE THREAD

**Issue by Anjaliavv51** [Rakesh9100/Beautiify#864]
### Description

Addition of Custom Cursor.
Which gives enhancement to the cursor pointer.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/154777864/eddea792-6f42-4d16-a2bb-7f6b6a1ab301)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Anjaliavv51** [comment]
@Rakesh9100

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please assign me this issue under GSSOC

**Comment by Rakesh9100** [comment]
Do you want to add it as a component or implement on the main website @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Rakesh9100 implement on main website

**Comment by Rakesh9100** [comment]
Go ahead and make sure to match the color with UI @Anjaliavv51

**Comment by Anjaliavv51** [comment]
https://github.com/Rakesh9100/Beautiify/assets/154777864/be375570-267b-4e3b-8dd7-1142b90a977b


@Rakesh9100 please view the output in the above screen recording

**Comment by Anjaliavv51** [comment]
@Rakesh9100 please view the Changes

**Comment by Anjaliavv51** [comment]
@Rakesh9100 if the changes are okay i will create the PR.

**Comment by Anjaliavv51** [comment]
@Rakesh9100 if the changes are okay i will create the PR.

**Comment by Rakesh9100** [comment]
Proceed and create your PR @Anjaliavv51
