### ISSUE TITLE
[Feature] Add error 404 page

### ISSUE THREAD

**Issue by PratikMane0112** [Rakesh9100/Beautiify#865]
### Description

Missing 404 error page  -

![Screenshot 2024-06-02 112501](https://github.com/Rakesh9100/Beautiify/assets/153143167/d65026fb-fa2c-48a1-8c19-f976beea7d06)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @PratikMane0112
