### ISSUE TITLE
[Style] Enhance the About Us page

### ISSUE THREAD

**Issue by BhavyaV05** [Rakesh9100/Beautiify#866]
### What's the style idea?

I have seen a similar issue raised previously, but, I wanted to add a few more styling changes like:

- change in background colour
- Increasing font size
- Changing the font colour accordingly
- Adding a few more transitions to make the user experience better.

I have attached an example of my idea below.
![Screenshot from 2024-06-02 14-19-00](https://github.com/Rakesh9100/Beautiify/assets/156503307/ff69afd1-cd66-42bc-b4b4-8bb7166f8521)
This page would look like this in night mode.
![image](https://github.com/Rakesh9100/Beautiify/assets/156503307/fd622e53-518d-4e06-9a4a-c7bc5c46c55c)
This is just a simple demonstration of my idea. The final outlook would include more and better changes.
Please assign this issue to me under gssoc'24.
Thank you !

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SohaFarhana** [comment]
Hey I would like to work on this issue

**Comment by Rakesh9100** [comment]
Okay, proceed @BhavyaV05 

Make sure to match the UI and responsive as well!

**Comment by Rakesh9100** [comment]
Pls provide your PR @BhavyaV05

**Comment by BhavyaV05** [comment]
sorry for the delay, was updating to the latest version 
will provide PR soon

**Comment by Rakesh9100** [comment]
You will be unassigned if PR is not up by today EOD @BhavyaV05

**Comment by BhavyaV05** [comment]
have provided the PR now, I apologise for the delay
