### ISSUE TITLE
[Feature] Add Falling Leaf Background

### ISSUE THREAD

**Issue by samarsajad** [Rakesh9100/Beautiify#867]
### Description

Adding a falling leaf animation background

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by samarsajad** [comment]
Please assign me this issue @Rakesh9100

**Comment by saurabhsingh720** [comment]
@samarsajad

**Comment by samarsajad** [comment]
yeah sure.
![image](https://github.com/Rakesh9100/Beautiify/assets/142666229/46ff9a22-9931-4d52-b9a0-b1461686bea9)
@saurabhsingh720

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New background addition.
Kindly assign them

**Comment by Rakesh9100** [comment]
Go ahead @samarsajad

**Comment by heypriyak** [comment]
please assign me the issue @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls provide your PR @samarsajad

**Comment by samarsajad** [comment]
> Pls provide your PR @samarsajad 

I'll send by tonight.. I'm working on it.
