### ISSUE TITLE
[Feature] Add Hotel Reservation Form

### ISSUE THREAD

**Issue by Nayanika1402** [Rakesh9100/Beautiify#868]
### Description

Collects details like check-in/check-out dates, room type, and guest information.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100 new addition 
Assign her.

**Comment by Rakesh9100** [comment]
Go ahead @Nayanika1402
