### ISSUE TITLE
I would like to add slider 

### ISSUE THREAD

**Issue by Sonaliparte** [Rakesh9100/Beautiify#87]
### Description

I would like to add a slider. @Rakesh9100 I want to work on this issue can you please assign it to me.

### Screenshots
![Screenshot 2024-01-06 171549](https://github.com/Rakesh9100/Beautiify/assets/114504015/6746f1f1-bbf4-40d1-aff4-f2f6da4f917a)

**Comment by Rakesh9100** [comment]
Screenshot is not properly added @Sonaliparte Pls fix and then will assign you

**Comment by Sonaliparte** [comment]
yes I have updated

**Comment by Rakesh9100** [comment]
Proceed @Sonaliparte

**Comment by Sonaliparte** [comment]
Thank you

**Comment by Rakesh9100** [comment]
@Sonaliparte Status of your PR pls
