### ISSUE TITLE
[Feature] Add Apple Themed Dropdown

### ISSUE THREAD

**Issue by VesperAkshay** [Rakesh9100/Beautiify#870]
### Description

**Add Apple-inspired Dropdown Menu**

## Description
As part of the new feature development, I would like to add an Apple-inspired dropdown menu to the GitHub repository. The dropdown menu should have the following characteristics:

- Visually similar to the dropdown menus used in Apple's user interfaces
- Responsive and interactive, allowing users to easily navigate and select options
- Consistent with the overall design and branding of the project

## Expected Behavior
When the user clicks on the "Menu" button, a dropdown menu should appear, displaying a list of options. The dropdown menu should have the following features:

- Smooth transition when opening and closing the menu
- Hover effect on the menu options to indicate interactivity
- Ability to close the menu by clicking outside of it

## Assigned To
- [Vesper Akshay]

### Screenshots

![Repo](https://github.com/Rakesh9100/Beautiify/assets/118452811/041e3860-7bf6-40b9-bf68-3ab46ca072d7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by VesperAkshay** [comment]
Assign me this Issue

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
Addition of new drop down.
Assign them

**Comment by Rakesh9100** [comment]
Go ahead @VesperAkshay

**Comment by VesperAkshay** [comment]
Please provide the level label for this Issue
