### ISSUE TITLE
[Docs] Improve the Readme file

### ISSUE THREAD

**Issue by shruti110503** [Rakesh9100/Beautiify#873]
### Category of documentation update

The README file gives very less information about the website.
![Screenshot 2024-06-03 010609](https://github.com/Rakesh9100/Beautiify/assets/118251562/c6446235-1eeb-4639-afa4-e94b07bcd211)

### Describe the change you think might work

I will write it in a better way such as to attract more people.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What improvements do you want to do @shruti110503

**Comment by shruti110503** [comment]
@Rakesh9100 The beautiify app has so many different features but the readme file gives its full description in just one sentence. As a user i think i would want some more explanation on the different features on what the app offers. I just want to improve and elaborate the features, write them well and overall enhance the readme file.

**Comment by Rakesh9100** [comment]
Okay proceed @shruti110503
