### ISSUE TITLE
[Feature] Add Slider Card

### ISSUE THREAD

**Issue by Abhigna-arsam** [Rakesh9100/Beautiify#874]
### Description

I proposed to add a slider card

### Screenshots

Expected output:

![Screenshot 2024-06-03 115550](https://github.com/Rakesh9100/Beautiify/assets/125258286/4b0ae898-e1e3-4f83-b7c0-2a5758cc5c02)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Abhigna-arsam** [comment]
@Rakesh9100 please assign the above work to me

**Comment by saurabhsingh720** [comment]
@Rakesh9100 
New card addition.
Kindly assign them

**Comment by Rakesh9100** [comment]
Go ahead @Abhigna-arsam
