### ISSUE TITLE
[Bug] Remove the extra space in About page

### ISSUE THREAD

**Issue by Vibhu315** [Rakesh9100/Beautiify#876]
### Description

In About Us page when we scroll down there is a extra space below the footer which can be removed.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/93249125/8ee03297-f17e-4a0c-8f7d-8f7ddc21480c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vibhu315** [comment]
hey @Rakesh9100 ,
please assign this issue to me, I can solve this issue

**Comment by Aashka19** [comment]
please assign this issue to me under gssoc 24

**Comment by Rakesh9100** [comment]
But I can't see any extra space, can you show through a recorded video @Vibhu315

**Comment by Rakesh9100** [comment]
I can't see any extra space, can you pls show through a recorded video @Vibhu315

**Comment by Vibhu315** [comment]
The **About** page of the website contains extra space below footer.

Here is the video:-

https://github.com/Rakesh9100/Beautiify/assets/93249125/75cb6876-943d-495a-ab16-bcae17abdba5

**Comment by Rakesh9100** [comment]
I can't see any extra space, pls show with the help of recorded video @Vibhu315

**Comment by Rakesh9100** [comment]
Can you tell me the screen size for which this extra space is showing as I can't see it on the website @Vibhu315

**Comment by Vibhu315** [comment]
My laptop screen size is 14 inch. In my laptop the extra space is visble and also when I inspect the website the extra space is visible in all type of screen size.

https://github.com/Rakesh9100/Beautiify/assets/93249125/2812bc04-1f59-41cc-9152-00b1e25979e6

**Comment by Rakesh9100** [comment]
Okay, go ahead @Vibhu315
