### ISSUE TITLE
[Feature] Add Draggable Carousel

### ISSUE THREAD

**Issue by Archiesachin** [Rakesh9100/Beautiify#877]
### Description

Adding a draggable carousel which will move when dragged with the mouse. It can move forward or backward. 

### Screenshots

Preview

https://github.com/Rakesh9100/Beautiify/assets/103347688/f601ce8a-15ef-453d-bc93-6e8e1305d81c

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Archiesachin
