### ISSUE TITLE
[Style] Changing font-style under dark mode

### ISSUE THREAD

**Issue by HJ2207** [Rakesh9100/Beautiify#880]
### What's the style idea?

We can change the font color and style of headings above search bar under different sections while in Dark Mode to make it clearly visible. 
![accordions](https://github.com/Rakesh9100/Beautiify/assets/146331595/15726952-46a1-4f6b-986c-45123b52f289)
for example, in Accordions page, the "Search Accordion" is not clearly visible in dark mode.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Aashka19** [comment]
please assign this issue to me under gssoc 24

**Comment by Rakesh9100** [comment]
### It is already visible clearly, pls create new issues @HJ2207 

![image](https://github.com/Rakesh9100/Beautiify/assets/73993775/be9c75fa-62a9-4dbf-b185-e1732a2e33fc)
