### ISSUE TITLE
[Feature] Add Truck Delivery Loader

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/Beautiify#883]
### Description

I want to add the new truck delivery order loader which will more attractive 
you can go throw this image for refence 
![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/897e2404-a6ae-4fb3-a703-1bfd4c6a588a)

Assign me this issue under gssoc2024
 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/017e66fd-61d3-449e-8eeb-9c437c958fd6)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
you haven't assign me the label level1 ,2 ,3
