### ISSUE TITLE
[Feature] Add Color Palette Card

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/Beautiify#884]
### Description

Want to contribute the color Patel card for the card sectio0n as it is attractive and looking good after hover 

![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/143d7e6a-9439-4ad3-bf5f-f8ca94d50c01)
 **After Hover** 

![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/e0f2e079-35d8-4f92-b611-3339631f3aa3)

It will change the color accordingly it will helpful for many websites  

Assign me this issue under the **gssoc 2024** 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue @SaiyamTuteja

**Comment by Rakesh9100** [comment]
Is this Color Palette Card @SaiyamTuteja

**Comment by Rakesh9100** [comment]
Any update for this that I have asked or should I close this issue @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
i am submitting this Issue today positively
