### ISSUE TITLE
[Feature] Add Mouse Hover Particle Background

### ISSUE THREAD

**Issue by Skb08** [Rakesh9100/Beautiify#885]
### Description

I want to enhance the user experience on our website by adding a visually appealing background effect that reacts to mouse movements. Particle.js is a popular JavaScript library that can help us achieve this by creating a particle system that follows the user's cursor.
here the demo video (it's only the demo in final background will be replace)
 ### Video
https://github.com/Rakesh9100/Beautiify/assets/113046759/4387b723-e66b-4462-aeb5-376e442de4e4

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do yOu want to implement this background for the home page @Skb08

**Comment by Skb08** [comment]
No , I want to add this in the background component

**Comment by Rakesh9100** [comment]
Go ahead @Skb08
