### ISSUE TITLE
[Feature] Add Order Cancellation Form

### ISSUE THREAD

**Issue by Pujan-sarkar** [Rakesh9100/Beautiify#886]
## Description 
An Order Cancellation Form is a document used by customers to formally request the cancellation of an order they have previously placed. This form helps both the customer and the seller to clearly document and process the cancellation request, ensuring that all necessary details are captured for the transaction to be terminated efficiently.

## About
The Order Cancellation Form typically includes the following sections:

1. Customer Information:
2. Order Details:
3. Cancellation Details:
4. Confirmation:

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @Pujan-sarkar

**Comment by pallabisneha** [comment]
I want to work on this issue for gssoc 2024. Please assign it to me😊
