### ISSUE TITLE
[Feature] Add Terms And Conditions Form

### ISSUE THREAD

**Issue by Pujan-sarkar** [Rakesh9100/Beautiify#887]
### Description

A Terms & Conditions Form is a legal document outlining the rules, regulations, and guidelines that users or customers must agree to in order to use a service, purchase a product, or participate in an activity. This form sets clear expectations and responsibilities for both the service provider and the user, helping to protect both parties' rights and interests.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Complete your assigned issue first @Pujan-sarkar

**Comment by Rakesh9100** [comment]
Proceed @Pujan-sarkar
