### ISSUE TITLE
[Bug] Fix the email validation

### ISSUE THREAD

**Issue by P-lavanya16** [Rakesh9100/Beautiify#889]
### Description

i want to add email validation using js if its a wrong email like anything its shows please enter a valid address
### Screenshots

![Screenshot (118)](https://github.com/Rakesh9100/Beautiify/assets/145569662/f024e4ec-bbb9-447f-95a3-69b3af660ac2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls write in the description clearly about your issue @P-lavanya16

**Comment by P-lavanya16** [comment]
@Rakesh9100 could you please review it!!
