### ISSUE TITLE
[Feature] Add an about us section

### ISSUE THREAD

**Issue by Komal73** [Rakesh9100/Beautiify#89]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

to add a about us page for providing better info about the website and its uses

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
What infos you will provide in about us page for this website? @Komal73

**Comment by DaSeeker67** [comment]
@Rakesh9100  can this be assigned to me  I can provide a aboutus page having 
1. Introduction
2. Mission and vision
3. Tech stack
4. Contributors
5. community involvement and Roadmap,
I can do the changes if you want

**Comment by Rakesh9100** [comment]
Do you want to work or should I assign this to other contributor @Komal73 ?

**Comment by DaSeeker67** [comment]
I would love to work on it please assign

**Comment by Komal73** [comment]
@Rakesh9100 I want to work ont this... the page will contain info about profile, history, mission, motto, founders and important links

**Comment by praptisharma28** [comment]
Assign me @Rakesh9100 , I can easily add seeing the project in depth.

**Comment by Shiv10122003** [comment]
Please add iwoc symbol

**Comment by Shiv10122003** [comment]
As this repo is under iwoc also

**Comment by praptisharma28** [comment]
Though it is in standby but I started working on it early. You can have a look at the PR #166 . Thankyou @Rakesh9100

**Comment by Rakesh9100** [comment]
Do you want to work under SWOC @Komal73

**Comment by Sidd2806** [comment]
please assign this task  to me  i will add Team,Overview ,Mission and Vision ,Achievement and Contributions

**Comment by Komal73** [comment]
@Rakesh9100 I'm willing to work on this under swoc

**Comment by Rakesh9100** [comment]
Okay go ahead @Komal73

**Comment by divyansh2375** [comment]
I can work on this issue if you want @Rakesh9100  and will complete it in within 2 or 3 days

**Comment by Paarisha1** [comment]
can i contribute in this under swoc

**Comment by Rakesh9100** [comment]
Are you working @Komal73

**Comment by Komal73** [comment]
@Rakesh9100 Yes I am working, assign me and I will complete it very soon.

**Comment by Rakesh9100** [comment]
@Komal73 You are unassigned as enough time is taken now!

@praptisharma28 Do you want to get assigned

**Comment by Sidd2806** [comment]
@Rakesh9100 i will be happy to contribute in this please assign me this issue

**Comment by Rakesh9100** [comment]
Go ahead @Sidd2806

**Comment by Rakesh9100** [comment]
You want to work for which open source program @Sidd2806

**Comment by praptisharma28** [comment]
@Rakesh9100 assign me, I did PR too for this before assign and it was closed. I can change the text for it and will do it.

**Comment by Rakesh9100** [comment]
Proceed @praptisharma28

**Comment by praptisharma28** [comment]
![Screenshot (520)](https://github.com/Rakesh9100/Beautiify/assets/123169861/4fc98a8c-6728-4aa0-8987-1216d23f3851)
@Rakesh9100 , you like it?

**Comment by Rakesh9100** [comment]
Pls work on these: @praptisharma28 

1. Keep the content same but design of the box should be same as your previously closed PR.
2. Background should be the same as Contributors or Contact Page.
3. Keep the footer same as home page @praptisharma28

**Comment by Rakesh9100** [comment]
Pls work on these: @praptisharma28 

1. Keep the content same but design of the box should be same as your previously closed PR.
2. Background should be the same as Contributors or Contact Page.
3. Keep the footer same as home page.

**Comment by praptisharma28** [comment]
@Rakesh9100 , the design of the box is almost the same, I didn't change it I just managed the content in the box. I am doing the other 2 things!

**Comment by Rakesh9100** [comment]
Spacing of the character and contents should be proper not too congested @praptisharma28

**Comment by Rakesh9100** [comment]
Spacing of the character and contents should be proper not too congested, you can reduce the content if needed @praptisharma28

**Comment by praptisharma28** [comment]
ok got it @Rakesh9100

**Comment by praptisharma28** [comment]
![Screenshot (536)](https://github.com/Rakesh9100/Beautiify/assets/123169861/ba4b83d1-45ae-4438-87c1-8efcc7eb2c05)
done @Rakesh9100 please add the ""difficulty label"" here before merging. Thanks.

**Comment by praptisharma28** [comment]
> ![Screenshot (536)](https://private-user-images.githubusercontent.com/123169861/299091920-ba4b83d1-45ae-4438-87c1-8efcc7eb2c05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjQ4MzcsIm5iZiI6MTcwNjEyNDUzNywicGF0aCI6Ii8xMjMxNjk4NjEvMjk5MDkxOTIwLWJhNGI4M2QxLTQ1YWUtNDQzOC04N2MxLThlZmNjN2ViMmMwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxOTI4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTE2MTQyNzYxOGEzMzdhMDhhZDcyMmFhYTMxZTAyNDgzN2FmN2ZlNTZiNzBkYjllOGYyMTdmM2JkZGIyZWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.StHWhTGjcjlaG9nDzHkro2Bo7Lz2IBRV9sSWfuH-KVY) done @Rakesh9100 please add the ""difficulty label"" here before merging. Thanks.

Add the tag on issue before merging @Rakesh9100
