### ISSUE TITLE
[Bug] Fix the email validation in Contact page

### ISSUE THREAD

**Issue by NidhiTornekar** [Rakesh9100/Beautiify#891]
### Description

The contact section does not have correct validation for the email field.
In below example, even an incorrect email such as "test@gmail" was accepted.

I wish to fix the regex for correct validation.

Please assign me this issue under gssoc.

### Screenshots

![ss1](https://github.com/Rakesh9100/Beautiify/assets/121748841/5a22354c-3459-441f-a650-1f2fbc23fab1)
![image](https://github.com/Rakesh9100/Beautiify/assets/121748841/8c542600-3670-49d2-8205-cc518c872662)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by NidhiTornekar** [comment]
@Rakesh9100  Please could you assign me this issue?

**Comment by Rakesh9100** [comment]
Go ahead @NidhiTornekar
