### ISSUE TITLE
[Feature] Add Crazy Arch Loader

### ISSUE THREAD

**Issue by patelkiran185** [Rakesh9100/Beautiify#892]
### Description

To add few components
    Crazy Arch Loaders
    Cuboid Loader
    Minimalist Loader
    Drag and Drop Loader
    Animated moon background
Please assign me this work.

### Screenshots

[Screencast from 2024-06-05 01-51-01.webm](https://github.com/Rakesh9100/Beautiify/assets/138752385/ed8b19df-aa4a-4980-97ab-9bcdd25d45bb)

[Screencast from 2024-06-05 01-51-39.webm](https://github.com/Rakesh9100/Beautiify/assets/138752385/b1e736f5-40f5-4faf-9ed1-c2c1803ca433)

[Screencast from 2024-06-05 01-55-24.webm](https://github.com/Rakesh9100/Beautiify/assets/138752385/7e57f5a8-91f7-4d59-8b2a-0bd1cec57f81)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by patelkiran185** [comment]
@Rakesh9100 can you assign me this?

**Comment by Rakesh9100** [comment]
You can add one component in this issue, so which one do you want to, and then open new issues for every component on by one @patelkiran185

**Comment by patelkiran185** [comment]
@Rakesh9100 I will add the arch loader.
