### ISSUE TITLE
[Style] Enhance the home page with gradients

### ISSUE THREAD

**Issue by nainika0305** [Rakesh9100/Beautiify#896]
### What's the style idea?

We need to improve the aesthetic appeal of the site. Currently, the boxes have a standard background and text style. I want to add a gradient background , to add a touch of elegance ,  and complementary text for the component boxes. 
![enhanced_image](https://github.com/Rakesh9100/Beautiify/assets/149311472/9cb8fd7c-0908-4a1b-b56f-69c4d76dc473)
Removing shadow from text will make it more legible.

please assign me this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls show the before and after improvements properly with the supporting screenshot @nainika0305

**Comment by diyaaa19** [comment]
@Rakesh9100 Here's my take on this, please assign me this issue under gssoc'25
![image](https://github.com/Rakesh9100/Beautiify/assets/151644762/09e294d9-b89c-459e-9c58-e02bc8e3874a)
With gradients and no text shadow the site looks much more appealing:
![image](https://github.com/Rakesh9100/Beautiify/assets/151644762/4fdc46f9-0f1d-4f07-98f3-aa2888f27872)

**Comment by nainika0305** [comment]
Hi this is what i thought of 
before: 
![image](https://github.com/Rakesh9100/Beautiify/assets/149311472/b8fe650c-6224-43e4-aa26-e3832cddf78a)
after: 
![Screenshot 2024-06-08 171002](https://github.com/Rakesh9100/Beautiify/assets/149311472/9a2b16e3-bb97-4305-9da5-c4f102bdf5ef)

i will also change for dark mode ..

also it would look better if in the nav bar it turns blue when selected rather than red. 

please assign me this under gssoc 24'

**Comment by Rakesh9100** [comment]
Go ahead @nainika0305
