### ISSUE TITLE
[Bug] Improvement in header and footer part

### ISSUE THREAD

**Issue by SadiyaTahsin29** [Rakesh9100/Beautiify#898]
### Description

I would like to improve the footer and header part of the website as there are some adjustments that need to be done

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
What kind of adjustments, pls show properly with the screenshots @SadiyaTahsin29

**Comment by SadiyaTahsin29** [comment]
Background and Visuals: The linear-gradient in the body tag ensures a vibrant but non-distracting background. You can replace 'your-background-image.jpg' with the actual path of your background image in the .hero class.
Navbar: The .navbar class includes fixed positioning, ensuring it stays at the top during scrolling. Tooltips are added using the ::after pseudo-element.
Hero Section: Contains a prominent heading, a brief introduction, and a clear call-to-action (CTA) button.
Introduction Section: Provides a welcoming message and an overview of what the site offers.
Features Section: Uses cards to highlight key features. The transform property adds a hover effect for interactivity.
Footer: Contains contact information, ensuring users can reach out.
Additional Tips:
Test Responsiveness: Ensure the page looks good on various devices by testing and adjusting media queries if necessary.
Load Time Optimization: Optimize images and other resources to improve load times.
Accessibility: Ensure all interactive elements are keyboard accessible and provide alt text for images to improve accessibility.

**Comment by Rakesh9100** [comment]
No need, pls work on other issues @SadiyaTahsin29
