### ISSUE TITLE
[Feature] Add Toggle Button-2

### ISSUE THREAD

**Issue by Vikashchou-dhary** [Rakesh9100/Beautiify#899]
### Description

adding the source code for dark/light mode toggle button in the navigation bars componets

### Screenshots

![toggle button](https://github.com/Rakesh9100/Beautiify/assets/158028747/dba58b94-e9a7-418e-a8ab-339d77365a51)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Vikashchou-dhary** [comment]
@Rakesh9100 I would like to add the feature. Plz assign the issue to me

**Comment by Rakesh9100** [comment]
Do you want to add this as a component and in which category @Vikashchou-dhary

**Comment by Vikashchou-dhary** [comment]
In BACKGROUNDS CATEGORY

**Comment by Rakesh9100** [comment]
What will be the name of your component @Vikashchou-dhary

**Comment by Vikashchou-dhary** [comment]
background toggle

**Comment by Rakesh9100** [comment]
Okay proceed @Vikashchou-dhary

**Comment by Vikashchou-dhary** [comment]
@Rakesh9100 i will complete the task by today evening as i was engaged in some other work so i was not able to complete it
