### ISSUE TITLE
Navigation on each component page 

### ISSUE THREAD

**Issue by kanishka-parmar** [Rakesh9100/Beautiify#9]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As we click on components its opening in new tab and if we want to return to home again there is no option other than clicking the previous tab. So according to me we can add either the back button or the navigation bar itself to each component page to make website more interactive from user end.
I would like to contribute this under SWOC 2024 

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/114792553/d2b0191c-6e50-4505-9dcd-ab1b4756698b

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by PRITISH212121** [comment]
hey @Rakesh9100  I'm interested in solving this issue!

**Comment by Rakesh9100** [comment]
@kanishka-parmar Proceed!!

**Comment by kanishka-parmar** [comment]
Thanks @Rakesh9100 !!!

**Comment by Rakesh9100** [comment]
@kanishka-parmar Status of your PR pls

**Comment by Rakesh9100** [comment]
@kanishka-parmar Are you working?

**Comment by PRITISH212121** [comment]
@Rakesh9100  if its open,can i work on it?,incase u dont get an update

**Comment by Rakesh9100** [comment]
@PRITISH212121 Go ahead and Start working

**Comment by kanishka-parmar** [comment]
@Rakesh9100  i have started doing it and it's about to complete how you can unassign  me

**Comment by Rakesh9100** [comment]
Okay fine @kanishka-parmar Continue but keep providing updates when you are working on any issue

**Comment by kanishka-parmar** [comment]
Ok sorry now I will take care to update and thanks  for re-assigning
@Rakesh9100

**Comment by Rakesh9100** [comment]
Do update your local repo as UI is changed completely and then make your changes accordingly @kanishka-parmar

**Comment by kanishka-parmar** [comment]
Ok @Rakesh9100 i will update it

**Comment by kanishka-parmar** [comment]
@Rakesh9100 Hey i wanna ask that as a home page and component page background is different now so i should keep same nav bar design as at home page or it should differ according to page ui ?

**Comment by Rakesh9100** [comment]
Are you implementing navbar or back button or both to every component page? @kanishka-parmar

**Comment by kanishka-parmar** [comment]
I thought of navbar but if you say we can have only back button also you suggest
@Rakesh9100 
But according to me nav bar would be good option

**Comment by Rakesh9100** [comment]
Then go for the navbar only and keep its design similar to component pages UI, not the home page UI @kanishka-parmar

**Comment by kanishka-parmar** [comment]
Ok @Rakesh9100

**Comment by Aditi-Dahiya** [comment]
What's the update of your work @kanishka-parmar ?

**Comment by kanishka-parmar** [comment]
@Aditi-Dahiya just the designing is left i will complete it by today or tomorrow.

**Comment by Aditi-Dahiya** [comment]
> @Aditi-Dahiya just the designing is left i will complete it by today or tomorrow.

Ok, go ahead 👍🏻
