### ISSUE TITLE
Implement some changes for mobile navigation menu

### ISSUE THREAD

**Issue by yashi-15** [Rakesh9100/Beautiify#90]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Changes needed

- The navigation bar for mobile devices has a background color of pink, I would like to change it to an appropriate color which would be more suitable according to the color scheme of website.
- I want to make the background (outside of nav menu) blurred once the nav icon is expanded.

Kindly assign this issue to me under SWOC .

### Screenshots

![Screenshot (199)](https://github.com/Rakesh9100/Beautiify/assets/132138302/e57b11a6-9df6-4724-b9cd-e1b04e67c453)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @yashi-15
