### ISSUE TITLE
[Style] Make Cart Checkout Form responsive

### ISSUE THREAD

**Issue by agastya3636** [Rakesh9100/Beautiify#900]
### What would you like to share?

I will make changes in the css of that form and make it responsive

### Additional information

![image](https://github.com/Rakesh9100/Beautiify/assets/124435030/b5c7f5cd-3f2b-4bea-abd8-d90544a8820b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide your PR @agastya3636
