### ISSUE TITLE
[Feature] Add Classic Footer

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/Beautiify#902]
### Description

A classic footer with minimalist look. 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/118552563/579206b6-00e3-45a7-b405-43530f49bf0a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by divyansh-2005** [comment]
please assign me this issue

**Comment by Rakesh9100** [comment]
Do you want to add this as a component @divyansh-2005

**Comment by divyansh-2005** [comment]
Yes

**Comment by Rakesh9100** [comment]
Go ahead @divyansh-2005

**Comment by divyansh-2005** [comment]
In Pull request #916 component has been added
