### ISSUE TITLE
Add a Liquid button

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#91]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add a liquid button, please assign it to me under SWOC'24

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/38d523eb-58c9-41a7-b533-17692561076f)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Go ahead @rishicds
