### ISSUE TITLE
[Style] Change the theme toggle button position for small devices

### ISSUE THREAD

**Issue by PratikMane0112** [Rakesh9100/Beautiify#912]
### Description

Currently when website is seen in mobile the toggle button appears in hamburger -

![Screenshot 2024-06-08 105853](https://github.com/Rakesh9100/Beautiify/assets/153143167/bac84d0e-84ff-43e2-b544-16bc0df74e9a)

It should be in navbar instead of hamburger component like below(a rough idea) - 

![Untitled design (1)](https://github.com/Rakesh9100/Beautiify/assets/153143167/96ecdf11-71f9-4539-9f76-8ca6d4914912)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your assigned issue first @PratikMane0112
