### ISSUE TITLE
[Style] Enhance the theme toggle icon

### ISSUE THREAD

**Issue by PratikMane0112** [Rakesh9100/Beautiify#913]
### What's the style idea?

Current toggle icon look bit unstyled - 

![Screenshot 2024-06-08 105334](https://github.com/Rakesh9100/Beautiify/assets/153143167/f32775c1-6f7a-40bf-a52d-cca76daec3cb)

I will make it more attractive like below - 

Dark Mode -
![Screenshot 2024-06-08 111924](https://github.com/Rakesh9100/Beautiify/assets/153143167/e8e17aee-11a3-4e34-af9c-4b0169c05cf9)

Light Mode -
![Screenshot 2024-06-08 111804](https://github.com/Rakesh9100/Beautiify/assets/153143167/92e4ac66-9694-40a6-b088-c84e147f5f26)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Trevisx07** [comment]
Please assign me this issue.

**Comment by Rakesh9100** [comment]
Do you want to work @PratikMane0112

**Comment by PratikMane0112** [comment]
> Do you want to work @PratikMane0112
Yes.

**Comment by PratikMane0112** [comment]
> Go ahead and implement some good-looking icon @PratikMane0112

Sure !!!
