### ISSUE TITLE
[Feature] Add Dice Loader

### ISSUE THREAD

**Issue by DiwareNamrata23** [Rakesh9100/Beautiify#917]
### Description

 Add the animated dice loader in loader section. Like the dice has 6 section so it will come one by one . For reference the video is given below

https://github.com/Rakesh9100/Beautiify/assets/142529986/c392ae1a-3246-4cad-b699-32deb38560fd

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DiwareNamrata23
