### ISSUE TITLE
 [Feature] Add Mesmerizing Loader

### ISSUE THREAD

**Issue by DiwareNamrata23** [Rakesh9100/Beautiify#918]
### Description

Add the mesmerizing loader in loader section. For reference the video is attached below

https://github.com/Rakesh9100/Beautiify/assets/142529986/d100c02d-01bc-4526-92b7-822a1f5efb66

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls complete your previous assigned issue first @DiwareNamrata23

**Comment by DiwareNamrata23** [comment]
please assign this issue as previous one is completed @Rakesh9100
