### ISSUE TITLE
[Feature] Add Animated Login Register Form

### ISSUE THREAD

**Issue by DiwareNamrata23** [Rakesh9100/Beautiify#919]
### Description

Here are the images for reference
<img width="1440" alt="Screenshot 2024-06-07 at 4 55 38 PM" src="https://github.com/Rakesh9100/Beautiify/assets/142529986/0f08fb29-47c2-4b2d-9af3-71c9ef80b7bd">
<img width="1440" alt="Screenshot 2024-06-07 at 5 09 16 PM" src="https://github.com/Rakesh9100/Beautiify/assets/142529986/33d720d8-6dd4-4e72-81af-32aaf2b2ca85">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@DiwareNamrata23 
Can u tell the name of the form??

**Comment by DiwareNamrata23** [comment]
@Rakesh9100 please assign this issue to me.
thank you!

**Comment by Rakesh9100** [comment]
Go ahead @DiwareNamrata23
