### ISSUE TITLE
[Style] Increase navbar height for improved usability

### ISSUE THREAD

**Issue by NAVYA260** [Rakesh9100/Beautiify#923]
### Description

I've observed that the height of our current navbar is too low, which makes it appear compressed and can affect the ease of navigation. A taller navbar would provide more space for the navigation links and elements, improving both the visual appeal and user experience.

### Screenshots

![Screenshot 2024-06-08 163315](https://github.com/Rakesh9100/Beautiify/assets/141401827/492e6909-2fc7-462d-97de-1faa89ff0342)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by NAVYA260** [comment]
I am interested in addressing this issue and would like to be assigned to make the necessary changes. Please assign this issue to me, and I will ensure that the navbar is adjusted for better usability and aesthetics.

**Comment by Rakesh9100** [comment]
Pls provide the screenshot of how it will look after your changes @NAVYA260

**Comment by NAVYA260** [comment]
![Screenshot 2024-06-13 200023](https://github.com/Rakesh9100/Beautiify/assets/141401827/f74f36bb-1981-4b6e-9bef-c54382f78aae)
I’ve increased the height of the navbar, making it easier to navigate and visually more appealing.
Hope you will assign me to this task.

**Comment by NAVYA260** [comment]
![Screenshot 2024-06-13 201317](https://github.com/Rakesh9100/Beautiify/assets/141401827/07326761-ea52-408a-b4bd-27256a796001)
@Rakesh9100  I’ve increased the height of the navbar, which now makes it easier to navigate and visually more appealing.
Hope you will assign me to this task.

**Comment by Rakesh9100** [comment]
Go ahead @NAVYA260
