### ISSUE TITLE
[Feature] Add Heros Category and several Components

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/Beautiify#925]
### Description

Create a new category specifically for hero sections in the repository. Design and implement several hero section, ensuring each component is customizable to fit different design requirements and brand aesthetics.
- Full-Screen Image hero 
- Video Background Hero
- Minimalist Hero
- Split-Screen Hero
- Carousel Hero
- Text-Only Hero
- even more

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DharshiBalasubramaniyam
