### ISSUE TITLE
[Feature] Add Water Text Animation

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Rakesh9100/Beautiify#927]
### Description

I have made a water text animation component in html css and js. I want to add it under text animation section. 

### Screenshots

![Screenshot 2024-06-08 171817](https://github.com/Rakesh9100/Beautiify/assets/123104247/fdb41739-0022-428e-8afc-4988445f9f2a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @ParnaRoyChowdhury777

**Comment by Rakesh9100** [comment]
Pls provide your PR @ParnaRoyChowdhury777

**Comment by ParnaRoyChowdhury777** [comment]
> Pls provide your PR @ParnaRoyChowdhury777 

Done
