### ISSUE TITLE
Animated Login Form

### ISSUE THREAD

**Issue by rishicds** [Rakesh9100/Beautiify#93]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I want to add an animated Login form.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/124495375/37f09436-d364-4321-ae36-1decb817e3e9)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Carry on @rishicds
