### ISSUE TITLE
[Feature] Add Login Form

### ISSUE THREAD

**Issue by Vaishnavi1047** [Rakesh9100/Beautiify#944]
### Description

Create a stunning webpage with a sleek, gradient background and elegant styling using Tailwind CSS. This example leverages Tailwind's utility-first approach for a sophisticated, modern design.

### Screenshots

![Screenshot 2024-06-08 204124](https://github.com/Rakesh9100/Beautiify/assets/149894552/093fe06d-f90d-4fed-abb6-0537719e5e9d)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Where do you want to add this @Vaishnavi1047

**Comment by Vaishnavi1047** [comment]
In forms section sir

**Comment by Vaishnavi1047** [comment]
@Rakesh9100 sir?

**Comment by Rakesh9100** [comment]
Go ahead @Vaishnavi1047
