### ISSUE TITLE
[Feature] Add Sign Up Form

### ISSUE THREAD

**Issue by Vaishnavi1047** [Rakesh9100/Beautiify#945]
### Description

Create a stunning webpage with a sleek, gradient background and elegant styling using Tailwind CSS. This example leverages Tailwind's utility-first approach for a sophisticated, modern design.

### Screenshots

![Screenshot 2024-06-08 204553](https://github.com/Rakesh9100/Beautiify/assets/149894552/a01e8ad6-d973-48a8-a187-b6e10753be52)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Tanishka023** [comment]
Hey @Rakesh9100  Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this. I agree to follow the code of conduct of GSSoC'24.

Regards,
Tanishka Bhalla

**Comment by Vaishnavi1047** [comment]
@Rakesh9100 pls assign this

**Comment by Vaishnavi1047** [comment]
Pls assign the same

**Comment by Rakesh9100** [comment]
Go ahead @Vaishnavi1047
