### ISSUE TITLE
[Feature] Add Collapsible Navigation Bar

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/Beautiify#952]
It would be great if we add a responsive sidebar with a search-bar to the navbar sections which helps user to explore more options

https://github.com/Rakesh9100/Beautiify/assets/142779809/69568e91-24f4-4c59-887a-666a9acf261f

**Comment by Rakesh9100** [comment]
What will be the name of your navigation bar @root-0101

**Comment by Rakesh9100** [comment]
Okay proceed, keep it as `Collapsible-Navigation-Bar` @root-0101
