### ISSUE TITLE
[Feature] Add Hacker Login Form

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/Beautiify#953]
It would be great if we add an animated login form to the forms section which improves the UI experience of a web page

https://github.com/Rakesh9100/Beautiify/assets/142779809/1b4e2ebb-2f0f-4bf7-9792-18146f2649bc

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.

**Comment by Rakesh9100** [comment]
Go ahead @root-0101

**Comment by Rakesh9100** [comment]
Provide your PR @root-0101
