### ISSUE TITLE
[Feature] Add Bike Loader

### ISSUE THREAD

**Issue by root-0101** [Rakesh9100/Beautiify#954]
### Description

As I have made a cool bike CSS pre-loader so, it would be great if we could add this to the pre-loader sections so, user can use this amazing loader into the web page

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/142779809/196494bd-9d09-4f82-8e85-f8474b001b87

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.

**Comment by Rakesh9100** [comment]
Proceed @root-0101

**Comment by root-0101** [comment]
Hey @Rakesh9100 Please review the PR

**Comment by root-0101** [comment]
@Rakesh9100 I have completed the task please review the PR
