### ISSUE TITLE
[Feature] Add Testimonial Card

### ISSUE THREAD

**Issue by ananya-dhiman** [Rakesh9100/Beautiify#955]
### Description

Adding Testimonial Card with drop down animation and profile images

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Do you want to add it as a component in Cards category @ananya-dhiman

**Comment by ananya-dhiman** [comment]
Yes, or do I need to add it as testimonials for website in the other webpages?

**Comment by Rakesh9100** [comment]
No, you can only add it as a component in the cards category @ananya-dhiman
