### ISSUE TITLE
[Feature] Add Feedback Form-2

### ISSUE THREAD

**Issue by divyansh-2005** [Rakesh9100/Beautiify#957]
### Description

A simple and elegant Feedback-Form  

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/118552563/e67db713-aad2-4c8d-ac2e-126e07e491f2)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by divyansh-2005** [comment]
@Rakesh9100 , Please assign me this issue I have the component ready.

**Comment by Tanishka023** [comment]
Hey @Rakesh9100  Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this. I agree to follow the code of conduct of GSSoC'24.

Regards,
Tanishka Bhalla

**Comment by Rakesh9100** [comment]
Go ahead @divyansh-2005
