### ISSUE TITLE
[Style] Make the contact form responsive

### ISSUE THREAD

**Issue by ishap11** [Rakesh9100/Beautiify#961]
### Description

Hello, This is Isha Prajapati. I hope you're doing well. I'm interested in improving our website's functionality and user experience.

The footer and contact form on the Beautiify website have the following main issues:
1. Not Mobile-Friendly: The layout is cramped and hard to use on small screens.
2. Overlapping Elements: Social media icons overlap the "Send Message" button.
These problems make the contact form and footer difficult to use, especially on mobile devices.

I am eager to contribute under GSSoC'24 and help enhance our website’s functionality and user experience. Please assign this task to me.
Thank you!

### Screenshots

![Screenshot 2024-06-09 231003](https://github.com/Rakesh9100/Beautiify/assets/128213933/80a23913-92b0-4e7b-8e9f-1f23b188dac3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls show the issue that you are facing with the help of recorded video @ishap11

**Comment by ishap11** [comment]
Hello ,
 I hope this message finds you well. I have recorded a video highlighting issues with the Beautiify website's footer and contact form. You can view the video here: (https://github.com/Rakesh9100/Beautiify/assets/128213933/9c7a3e55-336d-4d6e-bc86-847585e7428c)

Main issues identified :
1. Not a friendly layout
2. Overlapping elements like social media icons, text and "Send Message" button.
 Please consider assigning this task to me for GSSoC'24.
Thank you!

**Comment by Rakesh9100** [comment]
I can't see any unresponsiveness on the website, pls check again now if it still exists @ishap11
