### ISSUE TITLE
[Style] Enhance the home page

### ISSUE THREAD

**Issue by kritzxd8** [Rakesh9100/Beautiify#963]
### What's the style idea?

hey @Rakesh9100 I'm kritika a fellow gssoc24 contributor. 
these components boxes don't go well with the page . I am willing to change the style of this .  

![Screenshot 2024-06-10 123515](https://github.com/Rakesh9100/Beautiify/assets/162461631/19f2024b-9b67-4c97-a196-8ffb57a83d94)

a kind request to assign level while assigning this issue to me

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Pls provide the screenshots of before and after your changes @kritzxd8

**Comment by kritzxd8** [comment]
hey @Rakesh9100 !!!

before
![Screenshot 2024-06-10 123515](https://github.com/Rakesh9100/Beautiify/assets/162461631/d93fa38e-fd6b-4ffc-98fb-216a0ada6029)

after :
![Screenshot 2024-06-21 155105](https://github.com/Rakesh9100/Beautiify/assets/162461631/7e107de3-7d38-4254-b0b8-3262a6b830ce)
![Screenshot 2024-06-21 155125](https://github.com/Rakesh9100/Beautiify/assets/162461631/bc8419fc-19a8-4e4c-bac5-3888d3acf5b2)

i also have a footer idea 
![footer](https://github.com/Rakesh9100/Beautiify/assets/162461631/9e533c4c-e7f9-44a3-9b12-15a030f0ce87)


i have the code ready for both . 

----footer----

As the bottom of your **footer has your name** in it I will  keep that **included** .
The colour won't be the same as above image . 
I will follow the **same background** as u have in your project.

_It would be great if u assigned this to me !!_

**Comment by Rakesh9100** [comment]
No need to make the boxes so small, pls work on other issues @kritzxd8
