### ISSUE TITLE
[Feature] Add Reviews Category and a Component

### ISSUE THREAD

**Issue by avireet** [Rakesh9100/Beautiify#965]
### Description

We can make a component where we have templates for the reviews section in a website
Reviews are customer/users feedback of the website that will be displayed on  home page

### Screenshots
here is a example of review sections that I intend to add
![Screenshot (338)](https://github.com/Rakesh9100/Beautiify/assets/123054965/3124f26f-92ae-43e5-9561-c803d9833007)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by avireet** [comment]
Hi, please assign me this issue

**Comment by Rakesh9100** [comment]
Issue is already open to Add a review page @avireet

**Comment by avireet** [comment]
I didn't knew that, but it is still not done so if you assign me this issue, I can get it done in an hour
![Screenshot 2024-06-10 220042](https://github.com/Rakesh9100/Beautiify/assets/123054965/f1436c36-d1c3-4ee6-aab1-4e83b57fc3ab)
![Screenshot 2024-06-10 220002](https://github.com/Rakesh9100/Beautiify/assets/123054965/f73ab402-6d7b-46bc-8cfd-3c19549a08bd)

**Comment by Rakesh9100** [comment]
Okay, so you want to add a Review Category and component inside that. Issue is not opened previously for this, so you can work. But first tell me at least 4-5 components types or names which can come under Reviews category @avireet

**Comment by avireet** [comment]
i have 4 types of reviews to add under reviews category
1) Scroll review
![Screenshot (338)](https://github.com/Rakesh9100/Beautiify/assets/123054965/bb26f63d-b0d3-4747-9803-653a057093fd)

2)Card Carousel Review
![Screenshot 2024-06-15 125828](https://github.com/Rakesh9100/Beautiify/assets/123054965/1b1244f3-235d-4dad-8002-35642699e578)

3)Star carousel review
![Screenshot 2024-06-15 125842](https://github.com/Rakesh9100/Beautiify/assets/123054965/4175462c-030b-4a83-b9c9-df00851dcb9d)

4) Highlighted carousel review
![Screenshot 2024-06-15 153011](https://github.com/Rakesh9100/Beautiify/assets/123054965/a3e010a2-1ba1-42ba-a636-dd7d1ec685f2)

**Comment by Rakesh9100** [comment]
But these all can come under Carousels category itself @avireet
