### ISSUE TITLE
[Style] Enhance the Contact page with borders

### ISSUE THREAD

**Issue by agrwal697** [Rakesh9100/Beautiify#967]
### Description

I think if the Contact section had  border-bottom in every text item so it would have better UI and also it is not aligned properly. I would also like to make it responsive.
Please Assign me this issue with the label of GSSOC.

### Screenshots

before:

![image](https://github.com/Rakesh9100/Beautiify/assets/128716726/df6dfac0-933b-415e-a2e9-f36fee296490)

After:

![image](https://github.com/Rakesh9100/Beautiify/assets/128716726/81a47eaa-f2a2-4646-899f-6d4047a3e702)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.

**Comment by Rakesh9100** [comment]
Go ahead @agrwal697
