### ISSUE TITLE
[Feature] Add Cube Color Card

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/Beautiify#969]
### Description

I want to add the attractive cube card when we hover on it will show the different colors 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/6661ff57-15d6-4c5e-98a3-c9472bf92672)

[8e66824f-e4a8-4757-bdbb-9689e1a099c1.webm](https://github.com/Rakesh9100/Beautiify/assets/119167105/58d6f180-bea8-4273-93ef-d79784807d32)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@SaiyamTuteja @pb0126 @Rakesh9100 @NaveenChandraAdhikari @Nemesis-AS @SplinterSword

**Comment by Rakesh9100** [comment]
Go ahead @SaiyamTuteja

**Comment by Rakesh9100** [comment]
Provide your PR @SaiyamTuteja

**Comment by SaiyamTuteja** [comment]
As its making lots of puzzled i can recreate new PR and I can add it into the loader section as described by you @Rakesh9100
