### ISSUE TITLE
Homepage UI Bug - 'Get Components' Button Overlapping with 'Background' Div

### ISSUE THREAD

**Issue by DaSeeker67** [Rakesh9100/Beautiify#97]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

In the homepage of the Beautiify Website the Get "Components button" gets overlapped by the "Background" div,

Browser Brave, OS windows 11

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/65525769/2d619ea0-e957-42cc-a403-7837a4b5330c)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Website responsiveness issue is already open. Pls work on other issues @DaSeeker67

**Comment by DaSeeker67** [comment]
ohk sorry sir @Rakesh9100  , Can you assign me some issue or tell me in which part should I start finding issues or enhancements

**Comment by Rakesh9100** [comment]
You can open up new issues on your own to add some components and get it assigned @DaSeeker67 

I will open up some issues in few time, just keep checking to grab that.

**Comment by DaSeeker67** [comment]
@Rakesh9100  i had made an issue for adding a gradient dynamic background please assign that to me
