### ISSUE TITLE
[Feature] Add Heart Beat Loader

### ISSUE THREAD

**Issue by SaiyamTuteja** [Rakesh9100/Beautiify#970]
### Description

I want to add the Heart Pulse Loader which will load the pulse in red color 

![image](https://github.com/Rakesh9100/Beautiify/assets/119167105/505ad98d-e589-4b91-b787-1fba3b225c05)

Assign me this issue under GSSOC2024

### Screenshots

[1d91bd97-7475-4171-bc81-3ab61623ebde.webm](https://github.com/Rakesh9100/Beautiify/assets/119167105/80e4786e-50f4-44a4-9752-e4fd01bcc861)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me. 
@SaiyamTuteja @pb0126 @Rakesh9100 @NaveenChandraAdhikari @Nemesis-AS @SplinterSword

**Comment by Rakesh9100** [comment]
Proceed @SaiyamTuteja
