### ISSUE TITLE
#adding a take to previous page button

### ISSUE THREAD

**Issue by nandani-goyal** [Rakesh9100/Beautiify#971]
### Description

we can add a "button" on each of the components page. For eg: when we go to the 3d accordions in the accordions section we don't have any button which takes us back to the "accordions page" from the "3D accordions page".
I can add these buttons to each of the page.
please assign me this work under gssoc'24.

### Screenshots

![Screenshot 2024-06-11 163957](https://github.com/Rakesh9100/Beautiify/assets/152094228/be11a1b7-d64c-47fe-84d1-114762c1f6e9)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
No need for this as new components are getting added every day, so it will be hectic to add back button to every component. Pls work on good issues @nandani-goyal
