### ISSUE TITLE
[Style] Enhance the home page

### ISSUE THREAD

**Issue by Arushi009** [Rakesh9100/Beautiify#973]
### What's the style idea?

We need to enhance the web page background by giving it a more modern and refreshing look. Bright and pastel colors can infuse the web page with vibrancy and evoke a sense of liveliness. Additionally, they can create a visually appealing and cheerful ambiance that engages users and leaves a lasting impression. I believe that this update will enhance the overall user experience and make our website more visually appealing. Changing the font type of the website and updating the icon designs for Instagram, Twitter, etc., will enhance the overall visual appeal. Additionally, we need to create a little more space between these icons (i.e. insta, twitter,github) and "created by Rakesh" line to avoid a congested appearance. 
![Screenshot 2024-06-12 113711](https://github.com/Rakesh9100/Beautiify/assets/151595150/1ccbe3d4-cea7-4cdb-8d2d-9694c8969f76)
![Screenshot 2024-06-12 113726](https://github.com/Rakesh9100/Beautiify/assets/151595150/686d4a89-c8e9-4684-8c39-becf2c66c0cf)
![Screenshot 2024-06-12 113840](https://github.com/Rakesh9100/Beautiify/assets/151595150/368d5683-7a7b-427a-b8a0-09b4f04d9dca)
  

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Hi Arushi, Sorry for the late response. But, it is still not clear that what UI changes you want to make. If possible, provide me the example screenshot of how the website will look after your changes. Make sure to check the current website and the latest repo @Arushi009

**Comment by Arushi009** [comment]
Hello Rakesh,
This is what I wanted to convey to you -

   1. We need to enhance the web page background by giving it a more modern
   and refreshing look. Bright and pastel colors can infuse the web page with
   vibrancy and evoke a sense of liveliness. Additionally, they can create a
   visually appealing and cheerful ambiance that engages users and leaves a
   lasting impression
   2. Change the blobs in the background in Image 1
   <https://drive.google.com/file/d/1iaCl1wksiuBpIwpvNqoeDFNpwRlQToBN/view?usp=drive_link>
   into 3d meta blobs to make it realistic.
   3. Improve the visual appeal by changing the font type and color of the
   button options in Image 2
   <https://drive.google.com/file/d/1kWvv9KP3M_Y-OcaknPcTAcbi1Hhnoey_/view?usp=drive_link>
   .
   4. We need to create more space between these icons (i.e. Instagram,
   Twitter, GitHub) and the "created by Rakesh" line to avoid a cluttered
   appearance. I have made the necessary adjustments in Image 3
   <https://drive.google.com/file/d/1sca0sU3bKvJkzzklGdJ-Y4kEJBFV-Gud/view?usp=drive_link>
to
   create Image 4
   <https://drive.google.com/file/d/1bA5VyLxFUdLhpRychOhXDNog1DERa5_E/view?usp=drive_link>
to
   make it simple and ensuring that there is sufficient space between them.


Yours sincerely
Arushi Mahapatra
GSSoc Contributor 2024

**Comment by Arushi009** [comment]
Since this is my first and also my last project and I haven't gotten any
projects in gssoc ,kindly allow me to showcase my skills here as gssoc is
nearing its end.

**Comment by Rakesh9100** [comment]
The drive link is showing me no access, can you provide the access to my email to view your drive files @Arushi009

**Comment by Arushi009** [comment]
Can you try it now sir?

**Comment by Rakesh9100** [comment]
Pls check the present website as many new changes has been added, and then if you want to make any proper modifications, let me know @Arushi009

**Comment by Arushi009** [comment]
Sir,Can you please send me the link to the modified website

**Comment by Rakesh9100** [comment]
[Check](https://beautiify.netlify.app/) here @Arushi009

**Comment by Rakesh9100** [comment]
[Check](https://beautiify.netlify.app/) here!!

And pls don't say to make changes to the footer as issue is already open for that @Arushi009

**Comment by Arushi009** [comment]
Hello Rakesh,
This is what I wanted to convey to you -

   1. We need to enhance the web page background by giving it a more modern
   and refreshing look. Bright and pastel colors can infuse the web page with
   vibrancy and evoke a sense of liveliness. Additionally, they can create a
   visually appealing and cheerful ambiance that engages users and leaves a
   lasting impression
   2. Improve the visual appeal by changing the font type and color of the
   button options in Image 2
   <https://drive.google.com/file/d/1kWvv9KP3M_Y-OcaknPcTAcbi1Hhnoey_/view?usp=drive_link>
   .



Thanks
Arushi

**Comment by Arushi009** [comment]
Hello Rakesh,

Could you kindly reply back so that i can work on it?

Thanks
Arushi

**Comment by Rakesh9100** [comment]
Hi Arushi,

You can go ahead and start your work. Make sure to update your forked repo
with the latest updates to avoid merge conflicts.

Regards
Rakesh

**Comment by Arushi009** [comment]
please assign the gssoc label to me.

**Comment by Rakesh9100** [comment]
Level label will be added after PR is merged successfully @Arushi009

**Comment by Arushi009** [comment]
Hello sir,
Today is the last day of gssoc so could kindly merge my pr
