### ISSUE TITLE
[Feature] Add Snowball Background

### ISSUE THREAD

**Issue by Skb08** [Rakesh9100/Beautiify#977]
### Description

Implement a Particle.js background that simulates snowballs falling from the top of the screen. Additionally, add an interactive mouse hover effect that disperses the snowballs when the mouse moves over them.

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/113046759/ce967d1f-7a30-4a23-a545-aa962a114500

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @Skb08
