### ISSUE TITLE
[Style] Improve Our Valuable Contributors title

### ISSUE THREAD

**Issue by SahilThakur02** [Rakesh9100/Beautiify#979]
### Description

The current title, "Our Valuable Contributors," is a good starting point, but it could be more engaging and capture the essence of our contributor community.

I would like to improve it, want to make a label ( A colored rectangle with text inside ) and also write something creative replacing "Our Valuable Contributors", example: ⭐️ Contributors Spotlight

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by SahilThakur02** [comment]
Please /assign me the issue
@Rakesh9100

**Comment by Anupama-du** [comment]
Hi, I would like to solve this issue, please assign me

**Comment by SahilThakur02** [comment]
> Hi, I would like to solve this issue, please assign me 

I am already working it 😄 have pulled a PR , waiting for it to be reviewed.
