### ISSUE TITLE
Add Dynamic Gradient Background

### ISSUE THREAD

**Issue by DaSeeker67** [Rakesh9100/Beautiify#98]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Implement a visually appealing background enhancement - a seamless, moving gradient effect. This feature aims to introduce a dynamic touch to website backgrounds without requiring customization. The gradient will smoothly transition across the background, contributing to an engaging user experience.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/65525769/a7ebf51d-7d5c-47d3-a10a-83e825176c8b)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Do you want to change the current UI background and implement a new one? @DaSeeker67

**Comment by DaSeeker67** [comment]
sir im proposing a feature update in the background section of beautiify

**Comment by Rakesh9100** [comment]
I am not getting the clarification. Background section of Beautiify means do you want to add a background component in Backgrounds category? @DaSeeker67

**Comment by DaSeeker67** [comment]
yes

**Comment by Rakesh9100** [comment]
Okay then continue @DaSeeker67
