### ISSUE TITLE
[Feature] Automatically Comment on Pull Request Raise

### ISSUE THREAD

**Issue by thevijayshankersharma** [Rakesh9100/Beautiify#980]
### Description

I would like to implement a feature that automatically comments on a PR when it is raised. This comment will serve as an acknowledgment to the contributor for their contribution and provide any necessary instructions or next steps.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
We already have this https://github.com/Rakesh9100/Beautiify/blob/main/.github/workflows/greetings.yml, pls work on new issues @thevijayshankersharma
