### ISSUE TITLE
[Feature] Add Multilevel Dropdown

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [Rakesh9100/Beautiify#985]
### Description

I would like to add multilevel dropdown under dropdowns.

Please kindly assign this issue to me.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/139672976/6420a6b7-85e1-4d5f-951b-edf5e5d852ee)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Go ahead @DharshiBalasubramaniyam

**Comment by Anupama-du** [comment]
Hi, I would like to solve this issue, please assign me
