### ISSUE TITLE
Bug Report: Contact Page Form Div Not Responsive

### ISSUE THREAD

**Issue by DaSeeker67** [Rakesh9100/Beautiify#99]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The contact page on Beautiify currently exhibits a responsiveness issue with the form div, impacting the user experience. The form div is not adapting appropriately to various screen sizes, leading to a compromised layout and functionality.

Browser Brave , OS windows 11 

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/65525769/ff983dc0-9ac7-401d-98d2-9dd30896a61a)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by vrun1208** [comment]
Hi, @Rakesh9100 I want to work on this issue, Can you assign me

**Comment by Rakesh9100** [comment]
Do you want to work on this @DaSeeker67

**Comment by Rakesh9100** [comment]
Do you want to work on this @vrun1208

**Comment by vrun1208** [comment]
> Do you want to work on this @vrun1208

Sure! Assign me @Rakesh9100

**Comment by Rakesh9100** [comment]
@vrun1208 Okay go ahead

**Comment by Rakesh9100** [comment]
Status of your PR @vrun1208

**Comment by vrun1208** [comment]
> Status of your PR @vrun1208

working on it!!! @Rakesh9100
