### ISSUE TITLE
[Feature] Add Game Signup Form

### ISSUE THREAD

**Issue by TexZ-GenZ** [Rakesh9100/Beautiify#995]
### Description

This pull request introduces a redesigned signup form for a game. The new form features a modern and visually appealing design, enhancing user experience and accessibility. Key highlights include:

1. **Background Video**: A looping, muted background video for a dynamic and engaging user interface.
2. **Responsive Layout**: The form is designed to be fully responsive, ensuring optimal display on various devices and screen sizes.
3. **Custom Fonts and Styling**: Incorporates 'Norse Bold' and 'Courier New' fonts for a distinctive look. The styling includes intuitive box-sizing, margin resets, and improved media defaults for consistency.
4. **Form Validation**: Enhanced form validation for passwords, ensuring strong security by requiring an uppercase letter, lowercase letter, number, and special character.
5. **Interactive Elements**: Input fields and buttons with interactive styles such as hover effects and box shadows to improve user feedback and interaction.
6. **Animation**: Subtle border color animation on the container for a dynamic and modern touch.
7. **Accessibility**: Improved line-height for readability and text rendering for better accessibility.

### Features
1. Added a background video (`bgv`) with autoplay and loop functionalities.
2. Implemented a responsive container with a blur effect and border animation.
3. Styled the logo and header for the game signup form.
4. Created form groups for input fields, with improved styling for hover and focus states.
5. Added validation patterns and hover effects for the password fields.
6. Styled the submit button and added hover effects.
7. Provided a login prompt with interactive link styling.

### Screenshots

![image](https://github.com/Rakesh9100/Beautiify/assets/90178250/f618a26f-2e4b-4dbc-9468-31978044fb08)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [x] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by Rakesh9100** [comment]
Proceed @TexZ-GenZ

**Comment by Anupama-du** [comment]
Hi, I would like to solve this issue, please assign me
