### ISSUE TITLE
[Feature] Add Toggle Switches Category and several Components

### ISSUE THREAD

**Issue by Praneeth-2602** [Rakesh9100/Beautiify#999]
### Description

I want to add the new component section named as Toggle Switches which shall contain all the toggle type buttons like dark mode light mode toggle, on off toggle etc. Below attached are few example

### Screenshots

https://github.com/Rakesh9100/Beautiify/assets/137754636/ac024c57-138e-41eb-a790-0520f837b5c4

https://github.com/Rakesh9100/Beautiify/assets/137754636/e008311c-1320-48a8-9f9f-f7f2c24973a4

https://github.com/Rakesh9100/Beautiify/assets/137754636/ce3fd45b-e619-4c76-a23c-0e98e81d44a8

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a GSSOC'24 contributor.
- [ ] I am a IWOC'24 contributor.
- [ ] I am a JWOC'24 contributor.
- [ ] I am a SWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Rakesh9100/Beautiify/blob/main/.github/CODE_OF_CONDUCT.md)".

**Comment by saurabhsingh720** [comment]
@Rakesh9100  I think it is good what do u think?

**Comment by Praneeth-2602** [comment]
@Rakesh9100 please assign me this issue

**Comment by Rakesh9100** [comment]
You can put these components in Buttons category itself @Praneeth-2602

**Comment by Praneeth-2602** [comment]
That section would contain all the elements made using button tag...
Here we can include those made using the checkboxes and etc...

**Comment by Praneeth-2602** [comment]
It would be better to separate these two categories and will be easier for the user to access them as well

**Comment by Praneeth-2602** [comment]
@Rakesh9100 please assign me this one

**Comment by Rakesh9100** [comment]
Okay, proceed @Praneeth-2602

**Comment by Praneeth-2602** [comment]
How many components do you expect me to add?

**Comment by Rakesh9100** [comment]
You can add 2-3 components @Praneeth-2602

**Comment by Praneeth-2602** [comment]
Ok I will add two components. one dark mode toggle and one switch
